# -*- coding: utf-8 -*-
"""Branş kitabı başlığı -> bot arşivindeki mevzuat öneki. Elle kurulmuş, tahmin yok."""
ALIAS = {
 'Kamulaştırma Kanunu':'2942 Kamulaştırma',
 'Taşınmaz Mal Zilyedliğine Yapılan Tecavüzlerin Önlenmesi Hakkında Kanun':'Zilyetlik 3091',
 'Kamu İhale Kanunu':'4734 Kamu İhale',
 'Kamu İhale Sözleşmeleri Kanunu':'4735 Kamu İhale Sözleşmeleri',
 'Karayolu Taşıma Kanunu':'4925 Karayolu Taşıma',
 '5018 sayılı Kamu Malî Yönetimi ve Kontrol Kanunu':'5018 Kamu Malî Yönetimi',
 'TSK, Jandarma ve Sahil Güvenlik Besleme Kanunu':'5668 Besleme',
 'Gıda Hijyeni Yönetmeliği':'Gıda Hijyeni Yön',
 'Hazine Taşınmazlarının İdaresi Hakkında Yönetmelik':'Hazine Taşınmazları Yön',
 'Hekimlik Meslek Etiği Kuralları':'Hekimlik Etiği',
 'Kamu İdarelerine Ait Taşınmazların Kaydına İlişkin Yönetmelik':'Kamu Taşınmazları Kaydı Yön',
 'Kamu Konutları Yönetmeliği':'Kamu Konutları Yön',
 'Kamu Zararlarının Tahsiline İlişkin Usul ve Esaslar Hakkında Yönetmelik':'Kamu Zararları Tahsili Yön',
 'Karayolu Taşıma Yönetmeliği':'Karayolu Taşıma Yön',
 'Kazandan Beslemesi Olanaksız Erbaş/Erlere Tayın Bedeli Yönetmeliği':'Tayın Bedeli Kullanımı Yön',
 'Mal Alımı İhaleleri Uygulama Yönetmeliği':'Mal Alımı İhaleleri Uygulama Yön',
 'Mal Alımları Denetim Muayene ve Kabul İşlemlerine Dair Yönetmelik':'Mal Alımları Muayene Kabul Yön',
 'Merkezî Yönetim Harcama Belgeleri Yönetmeliği':'Harcama Belgeleri Yön',
 'Ön Ödeme Usul ve Esasları Hakkında Yönetmelik':'Ön Ödeme Yön',
 'Şehitlik Yönetmeliği':'Şehitlik Yön',
 'Ses ve Gaz Fişeği Atabilen Silahlar Hakkında Yönetmelik':'Ses/Gaz Fişeği Yön',
 'TSK Beslenme Bedellerinin Uygulanmasına Dair Yönetmelik':'Beslenme Bedelleri Yön',
 "TSK, Jandarma Gn.K.lığı ve Sahil Güvenlik K.lığı Besleme Kanunu Uygulama Yönetmeliği":'Besleme Kanunu Uygulama Yön',
 'TSK, MİT, EGM, JGK ve SGK Taşınır Mal Yönetmeliği':'Taşınır Mal Yön',
 'TSK, MİT, EGM, Jandarma ve Sahil Güvenlik Taşınır Mal Yönetmeliği':'Taşınır Mal Yön',
 'Yapım İşleri İhaleleri Uygulama Yönetmeliği':'Yapım İşleri İhaleleri Uygulama Yön',
 'Yapım İşleri Muayene ve Kabul Yönetmeliği':'Yapım İşleri Muayene Kabul Yön',
 "1219 sayılı Tababet ve Şuabatı San'atlarının Tarzı İcrasına Dair Kanun":'1219 Tababet Şuabatı',
 'Nakdi Tazminat ve Aylık Bağlanması Hakkında Kanun':'2330 Nakdi Tazminat',
 'Çevre Kanunu':'Çevre 2872',
 'Türk Ceza Kanunu — Mal veya Hizmet Satımından Kaçınma (m.240)':'TCK 5237',
 '5510 Sayılı Sosyal Sigortalar ve Genel Sağlık Sigortası Kanunu (MALİYE Tam Kapsam)':'5510 Sosyal Sigortalar SGK',
 '5996 Sayılı Veteriner Hizmetleri, Bitki Sağlığı, Gıda ve Yem Kanunu':'5996 Veteriner Gıda Yem',
 'İlkyardım Yönetmeliği':'İlkyardım Yön',
 'Yataklı Sağlık Tesislerinde Acil Servis Hizmetleri Tebliği':'Acil Servis Tebliğ',
 '2629 sayılı Uçuş, Paraşüt, Denizaltı, Dalgıç ve Kurbağa Adam Hizmetleri Tazminat Kanunu':'2629 Uçuş Paraşüt Tazminat',
 'Türk Sivil Havacılık Kanunu':'2920 Sivil Havacılık',
 'TSK, Jandarma ve Sahil Güvenlik Sağlık Yeteneği Yönetmeliği (Uçucular)':'Sağlık Yeteneği Yön',
 'Jandarma Teşkilat, Görev ve Yetkileri Kanunu (Mali Hükümler)':'Jandarma Kanunu',
 "TSK'da İstihdam Edilecek Sözleşmeli Subay ve Astsubaylar Hakkında Kanun (Mali Hükümler)":'Sözleşmeli Sb/Asb 4678',
 'Cari Yıl Merkezî Yönetim Bütçe Kanunu (H · K · E Cetvelleri)':'Bütçe Kanunu',
 'Fazla veya Yersiz Ödemelerin Tahsili Yönetmeliği':'Fazla Yersiz Ödemeler Yön',
 'Jandarma Genel Komutanlığı Kıyafet Yönetmeliği':'JGK Kıyafet Yön',
 'Jandarma Genel Komutanlığı Subay, Astsubay ve Uzman Jandarma Atama Yönetmeliği':'Atama Yön',
 'Ordu Evleri, Askerî Gazinolar, Kışla Gazinoları ve Vardiya Yatakhaneleri ile Eğitim Merkezleri Yönetmeliği':'Ordu Evleri Yön',
 'Telsiz İşlemlerine İlişkin Usul ve Esaslar Hakkında Yönetmelik':'Telsiz İşlemleri Yön',
 'Elektronik Haberleşme Sektörüne İlişkin Yetkilendirme Yönetmeliği':'Elektronik Haberleşme Yetkilendirme Yön',
 '5809 Sayılı Elektronik Haberleşme Kanunu':'5809 Elektronik Haberleşme',
 'Kodlu veya Kriptolu Haberleşme Yapma Usul ve Esasları Hakkında Yönetmelik':'Kriptolu Haberleşme Yön',
 'Cumhurbaşkanlığı 2019/12 Bilgi ve İletişim Güvenliği Tedbirleri Genelgesi':'CB Genelge 2019-12',
 'Cumhurbaşkanlığı 2024/7 Tasarruf Tedbirleri Genelgesi (Haberleşme Giderleri)':'Tasarruf Genelgesi 2024-7',
 'Bilgi ve İletişim Güvenliği Rehberi':'Bilgi Güvenliği Rehberi',
}

ALIAS.update({
  'Tayın Bedeli Kanunu':'2155 Tayın Bedeli',
  '257 Sayılı Er ve Erbaş Harçlıkları Kanunu':'257 Er Erbaş Harçlık',
  'Silahlı Kuvvetler İhtiyaç Fazlası Mal ve Hizmetler Kanunu':'3212 Silahlı Kuvvetler İhtiyaç Fazlası Mal',
  'Uzman Erbaş Kanunu (Mali Hükümler)':'3269 Uzman Erbaş',
  'Uzman Jandarma Kanunu — Mali Hükümler':'3466 Uzman Jandarma',
  'Damga Vergisi Kanunu':'488 Damga Vergisi',
  'Kamu Malî Yönetimi ve Kontrol Kanunu (Tam Kapsam)':'5018 Kamu Malî Yönetimi',
  'Sayıştay Kanunu':'6085 Sayıştay',
  '6191 Sayılı Sözleşmeli Erbaş ve Er Kanunu (Mali Hükümler)':'6191 Sözleşmeli Erbaş Er',
  'Harcırah Kanunu':'6245 Harcırah',
  '926 Sayılı Türk Silahlı Kuvvetleri Personel Kanunu (Mali Hükümler)':'926 TSK Personel',
  'Er ve Erbaş Harçlıkları Yönetmeliği':'Er Erbaş Harçlıkları Yön',
  'İç Kontrol ve Ön Malî Kontrole İlişkin Usul ve Esaslar':'İç Kontrol Ön Malî Kontrol',
  'Jandarma Kantin Yönetmeliği':'Jandarma Kantin Yön',
  'Askeri Yasak Bölgeler ve Güvenlik Bölgeleri Kanunu':'2565 Askeri Yasak Bölgeler',
  '3194 Sayılı İmar Kanunu':'3194 İmar',
  'Kadastro Kanunu':'3402 Kadastro',
  '5543 Sayılı İskân Kanunu':'5543 İskân',
  'Uzman Erbaş Kanunu (Personel Hükümleri)':'3269 Uzman Erbaş',
  'Uzman Jandarma Kanunu (Personel Hükümleri)':'3466 Uzman Jandarma',
  '657 Sayılı Devlet Memurları Kanunu':'657 Devlet Memurları',
  'Askeralma Kanunu':'7179 Askeralma',
  'TSK Personel Kanunu (Personel Hükümleri)':'926 TSK Personel',
  'Astsubay Sicil Yönetmeliği':'Astsubay Sicil Yön',
  'JGK ve SGK Kurum Kimlik Kartı Yönetmeliği':'Kurum Kimlik Kartı Yön',
  'Subay Sicil Yönetmeliği':'Subay Sicil Yön',
  'Bilgi ve İletişim Güvenliği Tedbirleri Genelgesi (2019/12)':'CB Genelge 2019-12',
  'Tasarruf Tedbirleri Genelgesi (2024/7) — Haberleşme Giderleri':'Tasarruf Genelgesi 2024-7',
  'Kodlu/Kriptolu Haberleşme Yapma Usul ve Esasları Yönetmeliği':'Kriptolu Haberleşme Yön',
})
