# 5237 TCK (müşterek kapsam) — kelime → cevap. Yalnız resmî metindeki bilgi; sayılar metindeki gibi yazıyla.
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 # madde, tip, KELİME, CEVAP, kanıt başı, kanıt sonu, karıştırılan[(madde, fark)], not
 ('2','yasak','düzenleyici işlemleriyle','suç ve ceza konulamaz','(2) İdarenin','konulamaz.',[],'yönetmelik, genelge ile suç olmaz'),
 ('2','yasak','kıyas','yapılamaz; geniş yorum da yasak','(3) Kanunların suç','geniş yorumlanamaz.',[],''),
 ('4','kosul','bilmemek','mazeret sayılmaz','(1) Ceza kanunlarını bilmemek','mazeret sayılmaz.',[],'ceza kanunlarını bilmemek'),
 ('5','kosul','özel ceza kanunları','TCK genel hükümleri orada da uygulanır','(1) Bu Kanunun genel hükümleri','uygulanır.',[],''),
 ('8','kosul','sabit platformlarda','Türkiye\'de işlenmiş sayılır','d) Türkiye\'nin kıt\'a','Türkiye\'de işlenmiş sayılır.',[],'kıt\'a sahanlığı, münhasır ekonomik bölge; neticenin Türkiye\'de gerçekleşmesi de yeter'),
 ('20','istisna','Tüzel kişiler hakkında','ceza yok; güvenlik tedbiri var','(2) Tüzel kişiler hakkında','saklıdır.',
  [('253','rüşvetle menfaat sağlanan tüzel kişiye güvenlik tedbiri')],'ceza sorumluluğu şahsidir'),
 ('21','suc_adi','öngörmesine rağmen','olası kast','(2) Kişinin, suçun kanuni','indirilir.',[],'ceza üçte birden yarısına kadar İNDİRİLİR; müebbet yerine yirmi–yirmibeş yıl'),
 ('22','suc_adi','istememesine karşın','bilinçli taksir','(3) Kişinin öngördüğü','artırılır.',[],'ceza üçte birden yarısına kadar ARTIRILIR'),
 ('22','istisna','kişisel ve ailevi durumu','ceza verilmez','(6) Taksirli hareket','indirilebilir.',[],'taksirle kendi yakınına zarar; bilinçli taksirde yarıdan altıda bire indirilebilir'),
 ('23','kosul','en azından taksirle','netice sebebiyle ağırlaşmış suçta sorumluluk şartı','(1) Bir fiilin','hareket etmesi gerekir.',[],'kastedilenden daha ağır netice'),
 ('35','suc_adi','elinde olmayan nedenlerle','teşebbüs','(1) Kişi, işlemeyi','sorumlu tutulur.',[],'elverişli hareketlerle doğrudan icraya başlamış olmalı'),
 ('35','ceza','Suça teşebbüs halinde','dörtte birinden dörtte üçüne kadar İNDİRİM','(2) Suça teşebbüs halinde','indirilir.',
  [('43','zincirleme suçta aynı oran ARTIRIM')],'zincirleme suçta aynı oran artırım; ağırlaştırılmış müebbet yerine ondört–yirmibir, müebbet yerine on–onsekiz yıl'),
 ('36','istisna','gönüllü vazgeçer','teşebbüsten ceza yok','(1) Fail, suçun icra','cezalandırılır.',[],'tamamlanan kısım suçsa yalnız ondan ceza'),
 ('37','suc_adi','araç olarak kullanan','dolaylı fail; fail gibi sorumlu','(2) Suçun işlenmesinde bir başkasını','artırılır.',[],'kusur yeteneği olmayanı kullanırsa üçte birden yarısına artırım'),
 ('38','ceza','azmettiren kişi','işlenen suçun cezası ile cezalandırılır','(1) Başkasını suç işlemeye','cezalandırılır.',[],'fail ile aynı ceza'),
 ('38','ceza','Üstsoy ve altsoy','azmettirmede üçte birden yarısına artırım','(2) Üstsoy ve altsoy','varlığı aranmaz.',[],'çocuğu azmettirmede üstsoy-altsoy aranmaz'),
 ('38','ceza','Azmettirenin belli olmaması','ortaya çıkaran faile indirim','(3) Azmettirenin belli','indirim yapılabilir.',[],'diğer hallerde üçte bir; ağırlaştırılmış müebbet yerine yirmi–yirmibeş yıl'),
 ('39','ceza','sekiz yılı geçemez','yardım eden; cezanın yarısı indirilir','Diğer hallerde cezanın yarısı','sekiz yılı geçemez.',[],'ağırlaştırılmış müebbet yerine onbeş–yirmi, müebbet yerine on–onbeş yıl'),
 ('39','suc_adi','kararını kuvvetlendirmek','yardım eden (azmettirme değil)','a) Suç işlemeye teşvik','vaat etmek.',
  [('38','azmettirme: suç kararı olmayan kişide karar oluşturmak')],'teşvik, sonradan yardım vaadi, yol gösterme, araç sağlama da yardım etmedir'),
 ('40','kosul','Özgü suçlarda','yalnız özel sıfatlı kişi fail olur','(2) Özgü suçlarda','sorumlu tutulur.',[],'diğerleri azmettiren ya da yardım eden'),
 ('41','istisna','sadece gönüllü vazgeçen','yalnız vazgeçen ortak yararlanır','(1) İştirak halinde','yararlanır.',[],'diğer ortaklar yararlanmaz'),
 ('42','suc_adi','bileşik suç','içtima hükümleri uygulanmaz','(1) Biri diğerinin','uygulanmaz.',[],'biri diğerinin unsuru ya da ağırlaştırıcı nedeni'),
 ('43','suc_adi','değişik zamanlarda','zincirleme suç; tek ceza, dörtte birden dörtte üçe ARTIRIM','(1) Bir suç işleme kararının','artırılır.',
  [('35','teşebbüste aynı oran indirim')],'aynı kişiye karşı aynı suç; mağduru belirsiz suçlarda da'),
 ('43','kosul','tek bir fiille','birden fazla kişiye karşı aynı suç: zincirleme hükmü','(2) Aynı suçun birden fazla kişiye','uygulanır.',[],''),
 ('43','istisna','işkence ve yağma','zincirleme suç uygulanmaz','(3) Kasten öldürme','uygulanmaz.',[],'kasten öldürme ve kasten yaralamada da uygulanmaz'),
 ('44','suc_adi','farklı suçun','fikri içtima; en ağır cezayı gerektiren suçtan','(1) İşlediği bir fiil','cezalandırılır.',[],'tek fiil, birden fazla farklı suç'),
 ('247','ceza','zimmetine geçiren','beş yıldan oniki yıla kadar hapis','(1) Görevi nedeniyle','cezalandırılır.',[],'görevi nedeniyle zilyetliği devredilmiş mal; kamu görevlisi'),
 ('247','ceza','açığa çıkmamasını','nitelikli zimmet; ceza yarı oranında artırılır','(2) Suçun, zimmetin','artırılır.',[],'hileli davranışla gizleme'),
 ('247','ceza','iade edilmek üzere','kullanma zimmeti; yarı oranına kadar indirilebilir','(3) Zimmet suçunun','indirilebilir.',[],'geçici kullanıp geri koyma'),
 ('248','ceza','Soruşturma başlamadan önce','zimmette etkin pişmanlık: üçte ikisi indirilir','(1) Soruşturma başlamadan','üçte biri indirilir.',[],'soruşturma öncesi üçte iki → kovuşturma öncesi yarısı → hükümden önce üçte bir'),
 ('248','ceza','Kovuşturma başlamadan önce','cezanın yarısı indirilir','(1) Soruşturma başlamadan','üçte biri indirilir.',[],''),
 ('248','ceza','hükümden önce','cezanın üçte biri indirilir','(1) Soruşturma başlamadan','üçte biri indirilir.',[],''),
 ('249','ceza','değerinin azlığı','üçte birden yarıya kadar indirilir','(1) Zimmet suçunun konusunu','indirilir.',[],'zimmette'),
 ('250','suc_adi','icbar eden','irtikâp; beş yıldan on yıla kadar hapis','Görevinin sağladığı nüfuzu','cezalandırılır.',
  [('252','rüşvet: anlaşma var, iki taraf da suçlu')],'ZORLA = İRTİKÂP, ANLAŞMA = RÜŞVET'),
 ('250','kosul','kendisini mecbur hissederek','icbar sayılır','Kamu görevlisinin haksız tutum','icbarın varlığı kabul edilir.',[],'haklı işinin görülmeyeceği endişesiyle menfaat vermişse'),
 ('250','suc_adi','ikna eden','ikna suretiyle irtikâp; üç yıldan beş yıla','(2) Görevinin sağladığı güveni','cezalandırılır.',[],'hileli davranışla kandırma'),
 ('250','suc_adi','hatasından yararlanarak','irtikâp; bir yıldan üç yıla','(3) İkinci fıkrada','hükmolunur.',[],'ZORLA beş–on, KANDIR üç–beş, HATA bir–üç yıl'),
 ('251','kosul','göz yuman','denetim görevlisi müşterek fail','(1) Zimmet veya irtikap','sorumlu tutulur.',[],'kasten göz yumma'),
 ('251','ceza','Denetim görevini ihmal','üç aydan üç yıla kadar hapis','(2) Denetim görevini','cezalandırılır.',[],'zimmet ya da irtikâba imkân sağlama'),
 ('252','ceza','Görevinin ifasıyla ilgili bir işi','rüşvet; dört yıldan oniki yıla kadar hapis','(1) Görevinin ifasıyla','cezalandırılır.',[],'veren de alan da aynı ceza'),
 ('252','kosul','Rüşvet konusunda anlaşmaya','suç tamamlanmış sayılır','(3) Rüşvet konusunda','hükmolunur.',[],'para el değiştirmese de'),
 ('252','ceza','rüşvet talebinde bulunması','kabul edilmezse ceza yarı oranında indirilir','(4) Kamu görevlisinin rüşvet talebinde','indirilir.',[],'teklif reddedilirse de aynı'),
 ('252','kosul','rüşvetin temini hususlarında aracılık','aracı müşterek fail; kamu görevlisi olmasa da','(5) Rüşvet teklif','cezalandırılır.',[],''),
 ('252','ceza','yeminli mali müşavir','rüşvette üçte birden yarısına artırım','(7) Rüşvet alan veya','artırılır.',[],'yargı görevi yapan, hakem, bilirkişi, noter de'),
 ('254','istisna','aynen teslim etmesi','rüşvet alan: ceza yok (etkin pişmanlık)','(1) (Değişik: 2/7/2012-6352/88 md.) Rüşvet alan kişinin','cezaya hükmolunmaz.',[],'resmî makamlar öğrenmeden önce; veren pişmanlıkla haber verirse de ceza yok'),
 ('255','suc_adi','nüfuz sahibi olduğundan bahisle','nüfuz ticareti; iki–beş yıl + beşbin güne kadar adli para','(1) Kamu görevlisi üzerinde','cezalandırılır.',[],'kamu görevlisiyse hapis yarı artar; menfaat veren bir–üç yıl'),
 ('256','suc_adi','ölçünün dışında kuvvet','kasten yaralama hükümleri uygulanır','(1) Zor kullanma','uygulanır.',[],'zor kullanma yetkisinin aşılması'),
 ('257','ceza','gereklerine aykırı hareket','altı aydan iki yıla kadar hapis','(1) Kanunda ayrıca','cezalandırılır.',[],'görevi kötüye kullanma, yaparak'),
 ('257','ceza','ihmal veya gecikme','üç aydan bir yıla kadar hapis','(2) Kanunda ayrıca','cezalandırılır.',[],'YAPARAK altı ay–iki yıl, YAPMAYARAK üç ay–bir yıl'),
 ('258','ceza','gizli kalması gereken','göreve ilişkin sırrın açıklanması; bir yıldan dört yıla','(1) Görevi nedeniyle kendisine','verilir.',[],''),
 ('258','kosul','sıfatı sona erdikten sonra','aynı ceza','(2) Kamu görevlisi sıfatı','aynı ceza verilir.',[],'görevden ayrılsa da'),
 ('259','ceza','mal veya hizmet satmaya','altı aya kadar hapis veya adlî para','(1) Yürüttüğü görevin','cezalandırılır.',[],'kamu görevlisinin ticareti'),
 ('260','istisna','üçten fazla olmaması','toplu görev terkinde ceza yok','(1) Hukuka aykırı olarak','cezaya hükmolunmaz.',[],'en az dört kamu görevlisi olmalı; ceza üç aydan bir yıla'),
 ('260','istisna','mesleki ve sosyal hakları','kısa süreli iş bırakma: indirim ya da ceza yok','(2) Kamu görevlilerinin mesleki','verilmeyebilir.',[],'hizmeti aksatmayacak biçimde'),
 ('261','ceza','karşılık ödenmek suretiyle de olsa','kişilerin malları üzerinde usulsüz tasarruf; altı ay–iki yıl','(1) İlgili kanunlarda','cezalandırılır.',[],''),
 ('262','ceza','terk emri','görevi sürdüren; üç aydan iki yıla','(1) Bir kamu görevini','verilir.',[],'kamu görevinin usulsüz üstlenilmesi'),
 ('264','ceza','nişan veya madalyaları','üç aydan bir yıla kadar hapis','(1) Bir rütbe','verilir.',[],'yetkisiz resmî elbise giymek de'),
 ('264','ceza','Elbisenin sağlayacağı kolaylık','üniformayla işlenen suçta üçte bir artırım','(2) Elbisenin','hükmolunur.',[],''),
 ('265','ceza','görevini yapmasını engellemek','görevi yaptırmamak için direnme; altı aydan üç yıla','(1) Kamu görevlisine karşı','cezalandırılır.',[],'cebir veya tehdit'),
 ('265','ceza','yargı görevi yapan kişilere','iki yıldan dört yıla','(2) Suçun yargı görevi','hükmolunur.',[],''),
 ('265','ceza','tanınmayacak bir hale','üçte bir artırım','(3) Suçun, kişinin','artırılır.',[],'birden fazla kişiyle birlikte de üçte bir'),
 ('265','ceza','korkutucu güçten','yarı oranında artırım','(4) Suçun, silahla','artırılır.',[],'silahla da yarı; MASKE/KALABALIK üçte bir, SİLAH/ÖRGÜT yarı'),
 ('266','ceza','araç ve gereçleri','üçte biri oranında artırılır','(1) Görevi gereği','artırılır.',[],'görev araçlarıyla suç'),
 ('317','ceza','komutasını alanlara','müebbet hapis','(1) Kanunen yetkili','müebbet hapis cezası verilir.',[],'yetkisiz komuta; terk emrine uymayan komutana da'),
 ('318','ceza','firara sevk edecek','halkı askerlikten soğutma; altı aydan iki yıla','Askerlik hizmetini yapanları','verilir.',[],'basın yayın yoluyla yarı artırım'),
 ('319','ceza','itaatsizliğe','askerleri itaatsizliğe teşvik; bir yıldan üç yıla','(1) Askerleri veya askerî idareye','hapis cezası verilir.',[],'aleni ise iki–beş yıl; savaş zamanında bir kat artar'),
 ('320','ceza','vatandaşlardan asker yazan','yabancı hizmetine asker toplama; üç yıldan altı yıla','(1) Hükûmetin izni','verilir.',[],'hizmeti kabul eden bir–üç yıl'),
 ('321','ceza','bilerek aykırı harekette','savaşta emirlere aykırılık; bir yıldan altı yıla','(1) Savaş zamanında','verilir.',[],''),
 ('322','ceza','sözleşmedeki yükümlülükleri','savaşta yerine getirmeme; üç–on yıl + onbin gün adlî para','(1) Savaş zamanında, Devletin','verilir.',[],'hile yapılırsa on–onbeş yıl; taksirle ise dörtte üçe kadar indirim'),
 ('323','ceza','asılsız veya abartılmış','savaşta yalan haber; beş yıldan on yıla','(1) Savaş sırasında','verilir.',[],'propaganda, askerlere yönelik, yabancıyla anlaşma: on–yirmi yıl'),
 ('323','ceza','düşmanla anlaşma neticesi','müebbet hapis','(3) Fiil, düşmanla','verilir.',[],''),
 ('324','ceza','seferberlikle','sulh zamanında ihmal; altı aydan üç yıla','(1) Sulh zamanında','verilir.',[],''),
 ('325','ceza','akademik derece','savaş hâlindeki devletten kabul; bir yıldan üç yıla','(1) Türkiye ile savaş','verilir.',[],'şeref, unvan, nişan, maaş da'),
 ('1', 'tanim', 'suç işlenmesini önlemektir', 'amaç listesi: hak-özgürlük, kamu düzeni, hukuk devleti, sağlık-çevre, toplum barışı', '(1) Ceza Kanununun amacı', 'suç işlenmesini önlemektir.', [], 'sınav: "amaçları arasında sayılmayan" sorusu'),
 ('1', 'tanim', 'türleri düzenlenmiştir', 'düzenlenenler: ceza sorumluluğu esasları, suçlar, ceza ve güvenlik tedbirleri', 'Kanunda, bu amacın gerçekleştirilmesi', 'türleri düzenlenmiştir.', [], '"suça iten sebepler" listede yok'),
 ('2', 'tanim', 'açıkça suç saymadığı', 'suçta ve cezada kanunîlik ilkesi; idarenin düzenleyici işlemiyle suç konulamaz', '(1) Kanunun açıkça suç saymadığı', 'suç ve ceza konulamaz.', [], ''),
 ('37', 'kosul', 'fiili birlikte gerçekleştiren', 'her biri fail olarak sorumlu (müşterek faillik)', '(1) Suçun kanuni tanımında yer alan fiili birlikte', 'fail olarak sorumlu olur.', [], ''),
 ('40', 'kosul', 'en azından teşebbüs aşamasına', 'iştirakten sorumluluk için suçun varmış olması gerekir', '(3) Suça iştirakten dolayı', 'varmış olması gerekir.', [], ''),
 ('39', 'tanim', 'hususunda yol göstermek', 'yardım eden; araçları sağlamak da (azmettirme değil)', 'b) Suçun nasıl işleneceği hususunda', 'araçları sağlamak.', [], ''),
 ('42', 'tanim', 'ağırlaştırıcı nedenini oluşturması', 'bileşik suç (tanım): biri diğerinin unsuru; tek fiil sayılır', '(1) Biri diğerinin unsurunu', 'bileşik suç denir.', [], ''),
]
yaz(1, '5237 sayılı Türk Ceza Kanunu', K)
