# 5237 Türk Ceza Kanunu (müşterek kapsam) — kelime → cevap
# KURAL (başkan, 4 Eki 2026): SOL = soru KÖKÜNDE göreceğin ifade, SAĞ = doğru ŞIKTA arayacağın kelime.
# Sorulardan geriye doğru yazıldı (219 cevaplı soru + kitapçık kökleri); kanıt resmî metin.
# Yazım: süreler kısa yazılır ("beş yıldan oniki yıla kadar hapis" → "beş-oniki yıl hapis").
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 # m.1-5 — amaç, kanunilik, eşitlik, bağlayıcılık, genel hükümler
 ('1','tanim','Kanununun amacı','hak-özgürlük/kamu düzen-güvenliği/hukuk devleti/kamu sağlığı-çevre/toplum barışı/suç önleme; milli ekonomi-kamusal etki YOK','(1) Ceza Kanununun amacı','suç işlenmesini önlemektir.',[],'2026 Uzman sınavında soruldu (cevap: suçun kamusal etkisini incelemek amaç değil)'),
 ('1','tanim','amacın gerçekleştirilmesi için','sorumluluk esasları, suçlar, ceza, güvenlik tedbirleri; suça iten sebepler YOK','Kanunda, bu amacın gerçekleştirilmesi','türleri düzenlenmiştir.',[],'2026 Uzman sınavında soruldu'),
 ('2','tanim','Kanunun açıkça suç saymadığı','ceza verilemez, tedbir uygulanamaz; kanunilik ilkesi','(1) Kanunun açıkça suç saymadığı','başka bir ceza ve güvenlik tedbirine hükmolunamaz.',[],'kanunda yazılı olmayan ceza ve tedbire de hükmolunamaz'),
 ('2','yasak','İdarenin düzenleyici işlemleriyle','suç ve ceza konulamaz','(2) İdarenin','konulamaz.',[],'yönetmelik, genelge ile suç olmaz'),
 ('2','yasak','suç ve ceza içeren hükümler','kıyas yapılamaz, geniş yorumlanamaz','(3) Kanunların suç','geniş yorumlanamaz.',[],''),
 ('3','kosul','ceza ve güvenlik tedbiri','işlenen fiilin ağırlığıyla orantılı','(1) Suç işleyen kişi hakkında','tedbirine hükmolunur.',[],'ceza ve güvenlik tedbiri'),
 ('3','yasak','ayrım yapılamaz','ırk/dil/din/mezhep/milliyet/renk/cinsiyet/siyasi fikir/felsefi inanç/milli-sosyal köken/doğum/ekonomik-toplumsal konum; meslek-sendika YOK','(2) Ceza Kanununun uygulamasında','ayrıcalık tanınamaz.',[],'hiçbir kimseye ayrıcalık da tanınamaz'),
 ('4','kosul','Ceza kanunlarını','bilmemek mazeret sayılmaz','(1) Ceza kanunlarını bilmemek','mazeret sayılmaz.',[],'2026 Uzman sınavında soruldu'),
 ('5','kosul','Kanunun genel hükümleri','özel ceza kanunlarında da uygulanır','(1) Bu Kanunun genel hükümleri','uygulanır.',[],'ceza içeren kanunlardaki suçlarda da'),
 # m.8 — yer bakımından
 ('8','kosul',"Türkiye'de işlenmiş",'sayılır: fiil kısmen ya da netice Türkiye’de; yabancı gemi DEĞİL','Fiilin kısmen veya tamamen','işlenmiş sayılır.',[],'Türk kara-hava-karasuları, açık denizde Türk araçları, Türk savaş araçları, kıta sahanlığındaki sabit platformlar sayılır; yabancı karasuyundaki yabancı gemi sayılmaz'),
 # m.20-23 — sorumluluk, kast, taksir
 ('20','kosul','Ceza sorumluluğu','şahsidir: başkasının fiilinden sorumlu tutulmaz; tüzel kişiye ceza yok','(1) Ceza sorumluluğu şahsidir','saklıdır.',[('1', 'm.1: ceza sorumluluğunun temel esasları Kanunda düzenlenir')],'tüzel kişiye yalnız güvenlik tedbiri uygulanabilir'),
 ('20','kosul','fiilinden dolayı sorumlu tutulamaz','kimse başkasının (ceza sorumluluğu şahsidir)','(1) Ceza sorumluluğu şahsidir','sorumlu tutulamaz.',[],''),
 ('20','istisna','Tüzel kişiler','ceza yok, güvenlik tedbiri var','(2) Tüzel kişiler hakkında','saklıdır.',[('253','rüşvetle menfaat sağlanan tüzel kişiye güvenlik tedbiri')],'adli para cezası da verilmez'),
 ('21','tanim','Kast,','bilerek ve istenerek; pişmanlık unsur DEĞİL','(1) Suçun oluşması kastın','gerçekleştirilmesidir.',[],'suçun kanuni tanımındaki unsurların; suçun oluşması kastın varlığına bağlı'),
 ('21','suc_adi','gerçekleşebileceğini öngörmesine rağmen','olası kast','(2) Kişinin, suçun kanuni','indirilir.',[],'gerçekleşebileceğini öngörüp yine de işlemek'),
 ('21','ceza','olası kast','müebbete iner; müebbette yirmi-yirmibeş yıl; diğerinde üçte bir-yarı indirim','(2) Kişinin, suçun kanuni','indirilir.',[],'ağırlaştırılmış müebbet yerine müebbet'),
 ('22','kosul','Taksirle işlenen fiiller','kanunun açıkça belirttiği hallerde','(1) Taksirle işlenen fiiller','hallerde cezalandırılır.',[],'her hâlde cezalandırılmaz'),
 ('22','tanim','dikkat ve özen yükümlülüğüne aykırılık','taksir','(2) Taksir, dikkat ve özen','gerçekleştirilmesidir.',[],'netice öngörülmeden gerçekleşir'),
 ('22','suc_adi','neticeyi istememesine karşın','bilinçli taksir','(3) Kişinin öngördüğü','artırılır.',[],'öngörür ama istemez'),
 ('22','ceza','bilinçli taksir','üçte bir-yarı ARTIRILIR','(3) Kişinin öngördüğü','artırılır.',[],'indirim DEĞİL'),
 ('22','kosul','herkes kendi kusurundan dolayı','kusuruna göre ayrı ayrı','(5) Birden fazla kişinin taksirle','ayrı ayrı belirlenir.',[],'her failin cezası'),
 ('22','istisna','failin kişisel ve ailevi durumu','ceza verilmez; bilinçli taksirde yarı-altıda bir indirim','(6) Taksirli hareket','indirilebilir.',[],'taksirle kendi yakınına zarar'),
 ('23','kosul','ağır veya başka bir netice','en azından taksir','(1) Bir fiilin','hareket etmesi gerekir.',[],'kastedilenden ağır netice; kusursuz ceza olmaz'),
 # m.35-41 — teşebbüs, gönüllü vazgeçme, iştirak
 ('35','suc_adi','elinde olmayan nedenlerle','teşebbüs','(1) Kişi, işlemeyi','sorumlu tutulur.',[],'elverişli hareketlerle doğrudan icraya başlamış olmalı'),
 ('35','kosul','teşebbüs','unsuru: kast, elverişli hareketle icraya başlama, tamamlanamama; gönüllü vazgeçme DEĞİL','(1) Kişi, işlemeyi','sorumlu tutulur.',[('36', 'gönüllü vazgeçende teşebbüsten ceza yok'), ('40', 'm.40: iştirak için suç en azından teşebbüs aşamasına varmalı'), ('262', 'm.262: kamu görevini usulsüz üstlenmeye teşebbüs bile yeter')],'elinde olmayan nedenle tamamlanamama'),
 ('35','ceza','Suça teşebbüs','dörtte bir-dörtte üç indirim','(2) Suça teşebbüs halinde','indirilir.',[('43','zincirleme suçta aynı oran ARTIRIM')],'ağırlaştırılmış müebbet yerine ondört-yirmibir, müebbet yerine on-onsekiz yıl; yarısı DEĞİL'),
 ('36','istisna','gönüllü vazgeçer','teşebbüsten dolayı cezalandırılmaz','(1) Fail, suçun icra','cezalandırılır.',[('41', 'm.41: iştirakte gönüllü vazgeçen yalnız kendisi yararlanır'), ('248', 'm.248: zimmette gönüllü iade etkin pişmanlıktır')],'tamam olan kısım suçsa yalnız ondan ceza'),
 ('36','istisna','neticenin gerçekleşmesini önlerse','teşebbüsten dolayı cezalandırılmaz','(1) Fail, suçun icra','cezalandırılır.',[],'kendi çabasıyla'),
 ('37','kosul','fiili birlikte gerçekleştiren','her biri fail','(1) Suçun kanuni tanımında yer alan fiili birlikte','fail olarak sorumlu olur.',[],'müşterek faillik'),
 ('37','suc_adi','araç olarak kullanan','fail; kusur yeteneği olmayanda üçte bir-yarı artırım','(2) Suçun işlenmesinde bir başkasını','artırılır.',[],'dolaylı faillik'),
 ('38','ceza','suç işlemeye azmettiren','işlenen suçun cezası','(1) Başkasını suç işlemeye','cezalandırılır.',[('40', 'özgü suçta özel sıfatı olmayan azmettiren ya da yardım eden olur')],'fail ile aynı ceza'),
 ('38','ceza','altsoy ilişkisinden doğan nüfuz','üçte bir-yarı artırım; çocukta aranmaz','(2) Üstsoy ve altsoy','varlığı aranmaz.',[],'azmettirenin cezası'),
 ('38','ceza','Azmettirenin belli olmaması','müebbette onbeş-yirmi yıl; diğerinde üçte bir indirim','(3) Azmettirenin belli','indirim yapılabilir.',[],'azmettireni ortaya çıkaran fail ya da ortak; ağırlaştırılmış müebbet yerine yirmi-yirmibeş yıl'),
 ('39','ceza','yardım eden','müebbette on-onbeş yıl; diğerinde yarı indirim, sekiz yılı geçemez','(1) Suçun işlenmesine yardım eden kişiye','sekiz yılı geçemez.',[('40', 'özgü suçta özel sıfatı olmayan azmettiren ya da yardım eden olur')],'ağırlaştırılmış müebbette onbeş-yirmi yıl'),
 ('39','suc_adi','yol göstermek','yardım eden; teşvik, karar kuvvetlendirme, araç sağlama, kolaylaştırma da','(2) Aşağıdaki hallerde kişi','icrasını kolaylaştırmak.',[],'azmettiren DEĞİL; fiili bizzat icra eden fail olur'),
 ('40','kosul','Suça iştirak için','kasten ve hukuka aykırı fiil yeterli','(1) Suça iştirak için','kendi kusurlu fiiline göre cezalandırılır.',[],'taksirli fiile iştirak olmaz; herkes kendi kusuruna göre'),
 ('40','kosul','Özgü suçlarda','özel faillik niteliği olan fail; diğerleri azmettiren-yardım eden','(2) Özgü suçlarda','sorumlu tutulur.',[],'zimmete katkı veren sivil fail olamaz'),
 ('40','kosul','Suça iştirakten','en azından teşebbüs aşaması','(3) Suça iştirakten dolayı','varmış olması gerekir.',[],'2026 Subay sınavında soruldu'),
 ('41','istisna','İştirak halinde','sadece gönüllü vazgeçen ortak yararlanır','(1) İştirak halinde','yararlanır.',[],'suç başka sebeple işlenmez ya da bütün gayretine rağmen işlenirse de uygulanır; sadece olay yerinden ayrılmak yetmez'),
 # m.42-45 — içtima, cezalar
 ('42','suc_adi','tek fiil sayılan','bileşik suç','(1) Biri diğerinin','bileşik suç denir.',[],'biri diğerinin unsuru ya da ağırlaştırıcı nedeni'),
 ('42','kosul','bileşik suç','içtima hükümleri uygulanmaz','(1) Biri diğerinin','uygulanmaz.',[],''),
 ('43','suc_adi','değişik zamanlarda bir kişiye karşı','zincirleme suç: tek ceza, dörtte bir-dörtte üç artırım','(1) Bir suç işleme kararının','artırılır.',[('35', 'teşebbüste aynı oran indirim')],'temel ve nitelikli şekiller aynı suç; mağduru belirsiz suçlarda da'),
 ('43','kosul','tek bir fiille','birden fazla kişiye: zincirleme hükmü uygulanır','(2) Aynı suçun birden fazla kişiye','uygulanır.',[],''),
 ('43','istisna','kasten yaralama, işkence ve yağma','zincirleme uygulanmaz; hırsızlıkta uygulanır','(3) Kasten öldürme','uygulanmaz.',[],'kasten öldürme, kasten yaralamada da uygulanmaz'),
 ('44','suc_adi','birden fazla farklı suçun oluşmasına','en ağır cezayı gerektiren suçtan','(1) İşlediği bir fiil','cezalandırılır.',[],'fikri içtima: tek fiil, birden fazla farklı suç'),
 ('45','tanim','Suç karşılığında uygulanan yaptırım','hapis ve adlî para','(1) Suç karşılığında uygulanan','adlî para cezalarıdır.',[],'güvenlik tedbiri ceza DEĞİL'),
 # m.247-249 — zimmet
 ('247','suc_adi','Görevi nedeniyle zilyedliği kendisine devredilmiş','zimmet','(1) Görevi nedeniyle','cezalandırılır.',[('258', 'görevi nedeniyle öğrendiği gizli belgeyi açıklama: bir-dört yıl')],'zilyetliği kendisine devredilmiş ya da koruma-gözetimiyle yükümlü olduğu mal'),
 ('247','ceza','zimmet','beş-oniki yıl; para dışı mallar da (yalnız para DEĞİL)','(1) Görevi nedeniyle','cezalandırılır.',[('248', 'm.248: zimmette etkin pişmanlık indirimi'), ('249', 'm.249: değeri az zimmette üçte bir-yarı indirim'), ('251', 'm.251: zimmete göz yuman denetçi müşterek fail')],'kamu görevlisi'),
 ('247','ceza','zimmetin açığa çıkmamasını sağlamaya yönelik','yarı oranında artırılır','(2) Suçun, zimmetin','artırılır.',[],'hileli davranışla gizleme'),
 ('247','ceza','kullanıldıktan sonra iade edilmek üzere','yarı oranına kadar indirilebilir','(3) Zimmet suçunun','indirilebilir.',[],'geçici kullanıp geri koyma'),
 ('248','ceza','Soruşturma başlamadan önce','aynen iade ya da tazmin: cezanın üçte ikisi indirilir','(1) Soruşturma başlamadan','üçte ikisi indirilir.',[],'zimmette etkin pişmanlık: aynen iade ya da tam tazmin; dörtte üç oranı YOK'),
 ('248','ceza','Kovuşturma başlamadan önce','gönüllü aynen iade-tazmin: cezanın yarısı indirilir','(2) Kovuşturma başlamadan','yarısı indirilir.',[],'gönüllü olarak'),
 ('248','ceza','Etkin pişmanlığın hükümden önce gerçekleşmesi','üçte biri indirilir','Etkin pişmanlığın hükümden','üçte biri indirilir.',[],''),
 ('249','ceza','malın değerinin azlığı','üçte bir-yarı indirim','(1) Zimmet suçunun konusunu','indirilir.',[],'zimmette'),
 # m.250-251 — irtikâp, denetim
 ('250','suc_adi','icbar eden kamu görevlisi','irtikâp; beş-on yıl hapis','Görevinin sağladığı nüfuzu','cezalandırılır.',[('252', 'rüşvet: anlaşma var, iki taraf da suçlu')],'ZORLA = İRTİKÂP, ANLAŞMA = RÜŞVET'),
 ('250','kosul','kendisini mecbur hissederek','icbar sayılır','Kamu görevlisinin haksız tutum','icbarın varlığı kabul edilir.',[],'haklı işinin görülmeyeceği endişesiyle'),
 ('250','suc_adi','ikna eden kamu görevlisi','hileli irtikâp; üç-beş yıl','(2) Görevinin sağladığı güveni','cezalandırılır.',[],'hileli davranışla kandırma'),
 ('250','ceza','kişinin hatasından','yararlanarak işlenirse bir-üç yıl hapis','(3) İkinci fıkrada','hükmolunur.',[],'ZORLA beş-on, KANDIR üç-beş, HATA bir-üç; rüşvet irtikâbın biçimi DEĞİL'),
 ('250','suc_adi','İrtikap','icbar, ikna (hile), hatadan yararlanma; rüşvet DEĞİL','(1) (Değişik: 2/7/2012-6352/86 md.) Görevinin','indirilebilir.',[('251', 'm.251: irtikâba göz yuman denetçi müşterek fail')],''),
 ('250','ceza','mağdurun ekonomik durumu','yarısına kadar indirilebilir','(4) (Ek: 2/7/2012-6352/86 md.) İrtikap','indirilebilir.',[],'irtikâp edilen menfaatin değeri de'),
 ('251','kosul','işlenmesine kasten göz yuman','müşterek fail','(1) Zimmet veya irtikap','sorumlu tutulur.',[],'denetimle yükümlü kamu görevlisi, kasten'),
 ('251','ceza','Denetim görevini ihmal','üç ay-üç yıl hapis','(2) Denetim görevini','cezalandırılır.',[],'zimmet ya da irtikâba imkân sağlama'),
 # m.252-254 — rüşvet
 ('252','ceza','Görevinin ifasıyla ilgili bir işi','rüşvet; dört-oniki yıl hapis','(1) Görevinin ifasıyla','cezalandırılır.',[],'veren de alan da aynı ceza'),
 ('252','kosul','Rüşvet konusunda anlaşma','suç tamamlanmış sayılır; teşebbüs DEĞİL','(3) Rüşvet konusunda','hükmolunur.',[('255', 'nüfuz ticaretinde de anlaşma tamamlanmış suç sayılır'), ('254', 'm.254: anlaşan kişi pişmanlıkla haber verirse ceza yok')],'para el değiştirmese de'),
 ('252','ceza','Kamu görevlisinin rüşvet talebinde bulunması','kabul edilmezse yarı indirim','(4) Kamu görevlisinin rüşvet talebinde','indirilir.',[],'teklif reddedilirse de'),
 ('252','kosul','aracılık eden kişi','müşterek fail','(5) Rüşvet teklif','cezalandırılır.',[('255', 'nüfuz ticaretine aracılık eden de müşterek fail')],'kamu görevlisi olmasa da; dolaylı menfaat sağlanan kişi de müşterek fail'),
 ('252','ceza','Rüşvet alan','üçte bir-yarı artar: yargı, hakem, bilirkişi, noter, YMM; avukat YOK','(7) Rüşvet alan veya','artırılır.',[('254', 'rüşvet alan resmî makamlar öğrenmeden teslim ederse ceza yok')],'YMM = yeminli mali müşavir'),
 ('253','istisna','haksız menfaat sağlanan tüzel kişiler','tüzel kişiye özgü güvenlik tedbiri','(1) Rüşvet suçunun işlenmesi','hükmolunur.',[],'ceza DEĞİL'),
 ('254','istisna','yetkili makamlara aynen teslim','makamlarca öğrenilmeden önce: rüşvet alana ceza yok','(1) (Değişik: 2/7/2012-6352/88 md.) Rüşvet alan kişinin','cezaya hükmolunmaz.',[],'anlaşan kamu görevlisi haber verirse de'),
 ('254','istisna','Rüşvet veren','pişmanlıkla haber verirse ceza yok','Rüşvet veren veya bu konuda','cezaya hükmolunmaz.',[('252','rüşvet veren de dört-oniki yıl hapis')],'resmî makamlar öğrenmeden önce; yabancı kamu görevlisine rüşvette uygulanmaz'),
 # m.255-266 — nüfuz ticareti ve diğer kamu görevlisi suçları
 ('255','suc_adi','nüfuz sahibi olduğundan bahisle','nüfuz ticareti; iki-beş yıl hapis','(1) Kamu görevlisi üzerinde','cezalandırılır.',[],'beşbin güne kadar adli para da'),
 ('255','suc_adi','haksız bir işin gördürülmesi amacıyla','nüfuz ticareti','(1) Kamu görevlisi üzerinde','cezalandırılır.',[],'haksız bir işin gördürülmesi için menfaat'),
 ('255','ceza','Kişinin kamu görevlisi olması','hapis yarı oranında artırılır','Kişinin kamu görevlisi olması','yarı oranında artırılır.',[],''),
 ('255','ceza','İşinin gördürülmesi karşılığında','menfaat sağlayana bir-üç yıl','İşinin gördürülmesi karşılığında','cezalandırılır.',[],'gördürüleceği beklentisiyle de'),
 ('255','ceza','Nüfuz ticareti','gerçek nüfuz şart değil; teklif reddedilse de yarı indirimli ceza','(1) Kamu görevlisi üzerinde','birinci fıkrada belirtilen ceza ile cezalandırılır.',[],'aracı ve dolaylı menfaat sağlanan müşterek fail'),
 ('256','suc_adi','ölçünün dışında kuvvet','kasten yaralama hükümleri','(1) Zor kullanma','uygulanır.',[],'zor kullanma yetkisinin aşılması'),
 ('257','ceza','görevinin gereklerine aykırı hareket','görevi kötüye kullanma; altı ay-iki yıl','(1) Kanunda ayrıca','cezalandırılır.',[],'ayrıca suç değilse; idari para cezası DEĞİL'),
 ('257','ceza','ihmal veya gecikme','üç ay-bir yıl hapis','(2) Kanunda ayrıca','cezalandırılır.',[],'YAPARAK altı ay-iki yıl, YAPMAYARAK üç ay-bir yıl'),
 ('258','ceza','gizli kalması gereken belgeleri','sır açıklama; bir-dört yıl hapis','(1) Görevi nedeniyle kendisine','verilir.',[],'göreve ilişkin sırrın açıklanması'),
 ('258','kosul','görevlisi sıfatı sona erdikten sonra','aynı ceza','(2) Kamu görevlisi sıfatı','aynı ceza verilir.',[],'görevden ayrılsa da'),
 ('259','ceza','mal veya hizmet satmaya','nüfuzdan yararlanarak: altı aya kadar hapis ya da adlî para','(1) Yürüttüğü görevin','cezalandırılır.',[],''),
 ('260','ceza','toplu biçimde, görevlerini terk','üç ay-bir yıl; üçten fazla değilse ceza yok; devretme YOK','(1) Hukuka aykırı olarak','cezaya hükmolunmaz.',[],'terk eden, gelmeyen, yapmayan, yavaşlatan kamu görevlileri'),
 ('260','istisna','hizmeti aksatmayacak biçimde','geçici, kısa süreli iş bırakma: indirim ya da ceza yok','(2) Kamu görevlilerinin mesleki','verilmeyebilir.',[],'mesleki-sosyal haklar için'),
 ('261','ceza','zorla tasarrufta bulunan kamu görevlisi','altı ay-iki yıl; karşılık ödense de','(1) İlgili kanunlarda','cezalandırılır.',[],'kişilerin malları üzerinde, koşullara aykırı olduğunu bilerek'),
 ('262','ceza','görevi sürdüren kimseye','terk emrine rağmen: üç ay-iki yıl hapis','(1) Bir kamu görevini','verilir.',[],'kamu görevinin usulsüz üstlenilmesi'),
 ('262','suc_adi','Bir kamu görevini','kanun-nizama aykırı üstlenmeye teşebbüs bile yeter; üç ay-iki yıl','(1) Bir kamu görevini, kanun','hapis cezası verilir.',[],'yerine getirmeye teşebbüs etmek yeterli'),
 ('264','ceza','resmi elbise','yetkisiz alenen giyene üç ay-bir yıl hapis','(1) Bir rütbe','verilir.',[],'yetkisiz, alenen ve yanıltacak şekilde giymek; hakkı olmayan nişan-madalya takmak da'),
 ('264','ceza','Elbisenin sağlayacağı kolaylık','ile suç işlenirse ceza üçte biri artar','(2) Elbisenin','hükmolunur.',[],'elbisenin kolaylığıyla suç işlenirse'),
 ('265','ceza','görevini yapmasını engellemek','amacıyla cebir-tehdit: direnme suçu; altı ay-üç yıl','(1) Kamu görevlisine karşı','cezalandırılır.',[],''),
 ('265','ceza','yargı görevi yapan kişiler','iki-dört yıl hapis','(2) Suçun yargı görevi','hükmolunur.',[('252', 'rüşvet alan yargı görevlisinin cezası üçte bir-yarı artar')],''),
 ('265','ceza','kendisini tanınmayacak bir hale','üçte bir artırım','(3) Suçun, kişinin','artırılır.',[],'birden fazla kişiyle birlikte işlenirse de'),
 ('265','ceza','korkutucu güçten yararlanılarak','yarı oranında artırım','(4) Suçun, silahla','artırılır.',[],'silahla da; MASKE/KALABALIK üçte bir, SİLAH/ÖRGÜT GÜCÜ yarı; örgüte yarar sağlama maksadı artırım sebebi DEĞİL'),
 ('266','ceza','elinde bulundurduğu araç ve gereçleri','üçte biri oranında artırılır','(1) Görevi gereği','artırılır.',[],'suç tanımında kamu görevlisi sıfatı esas alınmamışsa'),
 # m.317-325 — askeri ve savaş suçları
 ('317','ceza','komutasını alan','müebbet: kıta/donanma/gemi/filo/kale/üs/liman/şehir; savaş şartı, okul-hastane YOK','(1) Kanunen yetkili','müebbet hapis cezası verilir.',[],'yetkisiz komuta'),
 ('317','ceza','emirlere uymayanlara','komutanlığı terk emrine uymayana aynı ceza (müebbet)','(1) Kanunen yetkili olmadıkları','aynı ceza verilir.',[],''),
 ('318','ceza','firara sevk','altı ay-iki yıl; basın-yayınla yarı artar (bir kat DEĞİL)','Askerlik hizmetini yapanları firara','yarısı oranında artırılır.',[],'askerlikten soğutma'),
 ('318','ceza','basın ve yayın yolu','yarısı oranında artırılır','Askerlik hizmetini yapanları firara','yarısı oranında artırılır.',[],'askerlikten soğutmada'),
 ('319','ceza','kanunlara karşı itaatsizliğe','bir-üç yıl; aleni iki-beş; savaşta bir kat; basın-yayın YOK','(1) Askerleri veya askerî idareye','artırılır.',[],''),
 ('320','ceza','asker yazan','üç-altı yıl hapis','(1) Hükûmetin izni','verilir.',[],'yabancı hizmetine asker toplama'),
 ('320','ceza','askerlik çağında olanlar','üçte biri oranında artırılır','(1) Hükûmetin izni olmaksızın','üçte biri oranında artırılır.',[],''),
 ('320','ceza','hizmeti kabul eden kimseye','bir-üç yıl hapis','(3) Birinci fıkradaki hizmeti','hapis cezası verilir.',[],''),
 ('321','ceza','kararlarına bilerek aykırı hareket','bir-altı yıl hapis','(1) Savaş zamanında','verilir.',[],'savaşta yetkili makamın emirlerine aykırılık'),
 ('322','ceza','sözleşmedeki yükümlülükleri','üç-on yıl hapis, onbin güne adlî para','(1) Savaş zamanında, Devletin','verilir.',[],'savaşta yükümlülüğü yerine getirmeme'),
 ('322','ceza','taksirden ileri gelmişse','dörtte üçüne kadarı indirilebilir','(2) Yükümlülüklerin kısmen veya tamamen','dörtte üçüne kadarı indirilebilir.',[],''),
 ('322','ceza','yerine getirilmesinde hile yapan','on-onbeş yıl hapis','(4) Savaş zamanında yükümlülüklerin','adlî para cezası verilir.',[],'onbin güne kadar adlî para da'),
 ('323','ceza','asılsız veya abartılmış','haber yayma: beş-on yıl; propaganda/askerlere/yabancıyla on-yirmi; kin-düşmanlık/basın YOK','(1) Savaş sırasında','hapistir.',[],''),
 ('323','ceza','düşmanla anlaşma','müebbet hapis','(3) Fiil, düşmanla','verilir.',[],''),
 ('324','ceza','seferberlikle ilgili görevlerini ihmal','sulh zamanı; altı ay-üç yıl','(1) Sulh zamanında','verilir.',[],'ihmal eden ya da geciktiren kamu görevlisi'),
 ('325','ceza','akademik derece','savaştaki devletten; bir-üç yıl','(1) Türkiye ile savaş','verilir.',[],'şeref, unvan, nişan, maaş da'),
]
yaz(1, '5237 sayılı Türk Ceza Kanunu (müşterek kapsam)', K)
