# 6284 Ailenin Korunması ve Kadına Karşı Şiddetin Önlenmesine Dair Kanun — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('2','tanim','Aile mahkemesi hâkimini','Kanundaki hâkim','c) Hâkim','Aile mahkemesi hâkimini,',[],''),
 ('2','tanim','yedi gün yirmidört saat','Şiddet önleme ve izleme merkezleri (ŞÖNİM)','f) Şiddet önleme ve izleme merkezleri','yürüten merkezleri,',[],''),
 ('2','tanim','aynı haneyi paylaşmasa da','ev içi şiddet; aile mensubu sayılanlar arasında da','b) Ev içi şiddet','ekonomik şiddeti,',[],'fiziksel, cinsel, psikolojik, ekonomik'),
 ('3','makam','geçici maddi yardım','mülkî amirin koruyucu tedbiri','(1) Bu Kanun kapsamında korunan kişilerle ilgili olarak aşağıdaki tedbirlerden','geçici maddi yardım yapılması.',[],'barınma, rehberlik-danışmanlık, geçici koruma, kreş de mülkî amir'),
 ('3','makam','Hayatî tehlikesinin bulunması hâlinde','mülkî amir geçici koruma; kolluk da gecikmede alabilir','ç) Hayatî tehlikesinin','geçici koruma altına alınması.',[],'talep üzerine ya da resen'),
 ('3','sure','kreş imkânının','mülkî amir; çocuklu korunan kişiye dört ay, çalışıyorsa iki ay','d) Gerekli olması hâlinde, korunan kişinin çocukları','kreş imkânının sağlanması.',[],'aylık net asgari ücretin yarısını geçmemek üzere'),
 ('3','sure','kırksekiz saat içinde onaylanmayan','kolluğun aldığı koruyucu tedbir kalkar; mülkî amir onayı','(2) Gecikmesinde sakınca bulunan hâllerde birinci fıkranın (a) ve (ç)','kendiliğinden kalkar.',[('5','önleyici tedbirde hâkim onayı yirmidört saat')],'MÜLKİ AMİR KIRK SEKİZ, HÂKİM YİRMİ DÖRT; evrak ilk işgünü onaya'),
 ('4','makam','İşyerinin değiştirilmesi','hâkimin koruyucu tedbiri','(1) Bu Kanun kapsamında korunan kişilerle ilgili olarak aşağıdaki koruyucu','ayrı yerleşim yeri belirlenmesi.',[('10','işyeri değişikliği kararını kişinin tabi olduğu mevzuata göre yetkili merci uygular')],'ayrı yerleşim yeri de hâkim'),
 ('4','makam','aile konutu şerhi','hâkim; TMK şartları ve korunan kişinin talebi','c) 22/11/2001','aile konutu şerhi konulması.',[],''),
 ('4','makam','Tanık Koruma Kanunu','hâkim; kimlik değişikliği, aydınlatılmış rıza','ç) Korunan kişi bakımından hayatî','değiştirilmesi.',[],'diğer tedbirler yetersizse'),
 ('5','makam','derhâl uzaklaştırılması','hâkimin önleyici tedbiri; konut korunan kişiye tahsis','b) Müşterek konuttan','tahsis edilmesi.',[],'EVİ TERK EDEN MAĞDUR DEĞİL, ŞİDDET UYGULAYAN'),
 ('5','kosul','zimmetinde bulunan silahı','kamu görevlisi de kurumuna teslim eder (önleyici tedbir)','ğ) Silah taşıması zorunlu','kurumuna teslim etmesi.',[],'ruhsatlı silahlar kolluğa teslim'),
 ('5','sure','yirmidört saat içinde onaylanmayan','kolluğun aldığı önleyici tedbir kalkar; hâkim onayı','(2) Gecikmesinde sakınca bulunan hâllerde birinci fıkranın (a), (b), (c) ve (d)','kendiliğinden kalkar.',[('3','koruyucu tedbirde mülkî amir onayı kırksekiz saat')],''),
 ('5','kosul','talep edilmese dahi tedbir nafakasına','hâkim hükmedebilir; şiddet uygulayan geçimi sağlıyorsa','(4) Şiddet uygulayan, aynı zamanda','tedbir nafakasına hükmedebilir.',[],'TMK nafakası yoksa'),
 ('7','kosul','herkes bu durumu','ihbar edebilir; kamu görevlisi gecikmeksizin işlem yapar','(1) Şiddet veya şiddet uygulanma tehlikesinin varlığı','ihbar edebilir.',[],''),
 ('8','sure','en çok altı ay için','tedbir kararı süresi; uzatılabilir, değiştirilebilir','(2) Tedbir kararı ilk defasında','en çok altı ay için verilebilir.',[],'talep: ilgili, Bakanlık, kolluk, Cumhuriyet savcısı'),
 ('8','kosul','delil veya belge aranmaz','koruyucu tedbir kararı için','(3) Koruyucu tedbir kararı verilebilmesi','delil veya belge aranmaz.',[],'önleyici tedbir geciktirilmeksizin verilir'),
 ('8','sira_usul','sadece korunan kişiye tebliğ','tedbir talebinin reddi kararı','Tedbir talebinin reddine','sadece korunan kişiye tebliğ edilir.',[],'tedbir kararı iki tarafa da'),
 ('8','sira_usul','zorlama hapsinin uygulanacağı ihtarı','tebliğ ve tefhimde yapılır','(5) Tedbir kararının tefhim','ihtarı yapılır.',[],''),
 ('9','sure','aile mahkemesine itiraz edilebilir','tedbir kararına; tefhim/tebliğden iki hafta','(1) Bu Kanun hükümlerine göre verilen kararlara','aile mahkemesine itiraz edilebilir.',[],''),
 ('9','sure','İtiraz mercii kararını bir hafta','verir; itiraz üzerine karar kesin','(3) İtiraz mercii','kesindir.',[],'İTİRAZ İKİ HAFTA, KARAR BİR HAFTA'),
 ('10','kosul','engel teşkil etmez','tedbir kararının tebliğ edilmemesi uygulamayı engellemez','(5) Tedbir kararının ilgililere','engel teşkil etmez.',[],''),
 ('10','makam','kolluk birimi görevli ve yetkilidir','tedbirin uygulanması; yerleşim yeri ya da tedbirin uygulanacağı yer','(3) Korunan kişinin geçici koruma','kolluk birimi görevli ve yetkilidir.',[],''),
 ('12','yasak','ses ve görüntüleri dinlenemez','teknik takipte yasak; hâkim kararıyla teknik araç kullanılabilir','(1) Bu Kanun hükümlerine göre verilen tedbir kararlarının uygulanmasında','kayda alınamaz.',[],''),
 ('13','ceza','fiili bir suç oluştursa bile','zorlama hapsi üç günden on güne; hâkim kararıyla','(1) Bu Kanun hükümlerine göre hakkında tedbir','zorlama hapsine tabi tutulur.',[],'tedbire aykırılık'),
 ('13','ceza','onbeş günden otuz güne','tekrarında zorlama hapsi; toplam altı ayı geçemez','(2) Tedbir kararının gereklerine','altı ayı geçemez.',[],'İLK 3-10 GÜN, TEKRAR 15-30, TOPLAM 6 AY'),
 ('13','makam','Zorlama hapsine ilişkin kararlar','Cumhuriyet başsavcılığınca yerine getirilir','(3) Zorlama hapsine','yerine getirilir.',[],''),
 ('3', 'sure', 'ilk işgünü içinde mülkî amirin', 'kolluk amirinin koruyucu tedbir evrakı; kırksekiz saatte onaylanmazsa kalkar', 'Kolluk amiri evrakı en geç', 'kendiliğinden kalkar.', [], ''),
 ('8', 'sira_usul', 'Cumhuriyet savcısının başvurusu üzerine', 'tedbir kararı: ilgilinin talebi, Bakanlık, kolluk ya da savcı başvurusuyla', '(1) Tedbir kararı, ilgilinin talebi', 'kolluk biriminden talep edilebilir.', [], 'muhtar, sivil toplum örgütü YOK'),
 ('8', 'sira_usul', 'en çabuk ve en kolay', 'ulaşılabilecek yer hâkimi, mülkî amir ya da kolluk biriminden talep', '(1) Tedbir kararı, ilgilinin talebi', 'kolluk biriminden talep edilebilir.', [], ''),
 ('8', 'sure', 'Tedbir kararı ilk defasında', 'en çok altı ay; sonra süre/şekil değiştirilebilir, kaldırılabilir, devam eder', '(2) Tedbir kararı ilk defasında', 'aynen devam etmesine karar verilebilir.', [], ''),
 ('8', 'sure', 'geciktirilmeksizin verilir', 'önleyici tedbir kararı; koruyucu tedbirde delil aranmaz', '(3) Koruyucu tedbir kararı verilebilmesi', 'geciktirilmeksizin verilir.', [], ''),
 ('8', 'kosul', 'tüm resmi kayıtlarda gizli tutulur', 'kimlik, adres ve koruma için önemli bilgiler; tebligata ayrı adres', '(6) Gerekli bulunması hâlinde, tedbir kararı ile birlikte', 'ayrı bir adres tespit edilir.', [], 'ifşa edene TCK; şiddet uygulayanın adli sicili gizlilik kapsamında YOK'),
 ('1', 'tanim', 'tek taraflı ısrarlı takip', 'korunanlar: kadınlar, çocuklar, aile bireyleri, ısrarlı takip mağdurları', '(1) Bu Kanunun amacı; şiddete uğrayan', 'usul ve esasları düzenlemektir.', [], 'şiddete uğrama tehlikesi bulunanlar da'),
 ('1', 'kosul', 'ayrımcılık olarak yorumlanamaz', 'kadınları cinsiyete dayalı şiddetten koruyan özel tedbirler', 'ç) Bu Kanun kapsamında kadınlara yönelik cinsiyete', 'ayrımcılık olarak yorumlanamaz.', [], ''),
 ('1', 'kosul', 'kadın erkek eşitliğine duyarlı', 'temel ilke: insan haklarına dayalı, sosyal devlet, adil, etkili, süratli', 'b) Şiddet mağdurlarına verilecek destek', 'süratli bir usul izlenir.', [], ''),
 ('1', 'kosul', 'Avrupa Konseyi Sözleşmesi', 'Anayasa ve taraf olunan uluslararası sözleşmeler esas alınır', 'a) Türkiye Cumhuriyeti Anayasası ile', 'esas alınır.', [], 'yalnız Anayasa değil'),
 ('2', 'tanim', 'Aile ve Sosyal Politikalar Bakanlığını', 'Bakanlık tanımı; Aile ve Sosyal Politikalar', 'a) Bakanlık', 'Sosyal Politikalar Bakanlığını,', [], ''),
 ('2', 'tanim', 'özgürlüğün keyfî engellenmesini', 'şiddet tanımı: fiziksel, cinsel, psikolojik, sözlü, ekonomik; tehdit-baskı dahil', 'd) Şiddet: Kişinin', 'her türlü tutum ve davranışı,', [], 'dinî şiddet, mesleki başarı azalması tanımda YOK'),
 ('2', 'tanim', 'kolluk görevlileri ve mülkî amirler', 'tedbir kararı tanımı: hâkim de verir; istem üzerine veya resen', 'ğ) Tedbir kararı', 'tedbir kararlarını,', [], ''),
 ('2', 'tanim', 'kalma tehlikesi bulunan kişiyi', 'şiddet mağduru tanımı; dolaylı maruz kalan ve etkilenen de', 'e) Şiddet mağduru', 'etkilenme tehlikesi bulunan kişileri,', [], 'tanımlar: Bakanlık, ev içi şiddet, hâkim, kadına yönelik şiddet, şiddet, mağdur, ŞÖNİM, uygulayan, tedbir kararı; Cumhuriyet başsavcılığı YOK'),
 ('5', 'makam', 'önleyici tedbirlerden birine', 'hâkim karar verir (şiddet uygulayana); kolluk amiri gecikmede a,b,c,d', '(1) Şiddet uygulayanlarla ilgili olarak', 'hâkim tarafından karar verilebilir:', [], 'mülkî amir önleyici tedbir VEREMEZ'),
 ('5', 'makam', 'söz ve davranışlarda bulunmaması', 'önleyici tedbir (a): şiddet tehdidi, hakaret, aşağılama, küçük düşürme', 'a) Şiddet mağduruna yönelik olarak şiddet tehdidi', 'söz ve davranışlarda bulunmaması.', [], ''),
 ('5', 'makam', 'konuta, okula ve işyerine yaklaşmaması', 'hâkimin önleyici tedbiri; korunan kişilere ve bulundukları yerlere', 'c) Korunan kişilere, bu kişilerin bulundukları', 'işyerine yaklaşmaması.', [], 'yakınlarına, tanıklarına, çocuklarına yaklaşmama da (d)'),
 ('5', 'makam', 'alkol ya da uyuşturucu', 'korunan kişilerin bulunduğu yerlerde kullanmama; bağımlıysa tedavi (hastane dahil)', 'h) Korunan kişilerin bulundukları yerlerde alkol', 'muayene ve tedavisinin sağlanması.', [], ''),
 ('13', 'ceza', 'üç günden on güne kadar', 'ilk aykırılıkta zorlama hapsi; hâkim kararıyla', '(1) Bu Kanun hükümlerine göre hakkında tedbir', 'zorlama hapsine tabi tutulur.', [], ''),
 ('13', 'ceza', 'aykırılığın her tekrarında', 'zorlama hapsi onbeş günden otuz güne; toplam altı ay', '(2) Tedbir kararının gereklerine', 'altı ayı geçemez.', [], ''),
 ('13', 'ceza', 'toplam süresi altı ayı geçemez', 'zorlama hapsi; tekrarında onbeş günden otuz güne', '(2) Tedbir kararının gereklerine', 'altı ayı geçemez.', [], ''),
 ('13', 'makam', 'il ve ilçe müdürlüklerine bildirilir', 'zorlama hapsi kararları Bakanlığın müdürlüklerine; başsavcılık yerine getirir', '(3) Zorlama hapsine', 'müdürlüklerine bildirilir.', [], ''),
 ('9', 'sure', 'iki hafta içinde', 'tedbir kararına itiraz; tefhim/tebliğden itibaren; aile mahkemesine', '(1) Bu Kanun hükümlerine göre verilen kararlara', 'aile mahkemesine itiraz edilebilir.', [], ''),
 ('9', 'kosul', 'İtiraz üzerine verilen kararlar', 'kesindir; itiraz mercii bir hafta içinde karar verir', '(3) İtiraz mercii', 'kesindir.', [], 'temyiz, istinaf YOK'),
 ('9', 'makam', 'tek dairesi bulunması hâlinde', 'itiraz dosyası asliye hukuk mahkemesine; çok daireliyse izleyen daireye', '(2) Hâkim tarafından verilen tedbir kararlarına itiraz', 'gecikmeksizin gönderilir.', [], 'aynı hâkimse en yakın asliye hukuk'),
 ('3', 'makam', 'uygun görülecek benzer tedbirlere', 'mülkî amir koruyucu tedbirde; hâkim koruyucu ve önleyicide de', '(1) Bu Kanun kapsamında korunan kişilerle ilgili olarak aşağıdaki tedbirlerden', 'mülkî amir tarafından karar verilebilir:', [('4', 'hâkimin koruyucu tedbirleri: işyeri, ayrı yerleşim yeri, aile konutu şerhi, kimlik değişikliği'), ('5', 'hâkimin önleyici tedbirleri: uzaklaştırma, yaklaşmama, silah teslimi, nafaka')], ''),
 ('3', 'makam', 'rehberlik ve danışmanlık hizmeti', 'psikolojik, meslekî, hukukî ve sosyal; mülkî amir tedbiri', 'c) Psikolojik, meslekî, hukukî', 'danışmanlık hizmeti verilmesi.', [], ''),
 ('4', 'makam', 'ayrı yerleşim yeri belirlenmesi', 'hâkimin koruyucu tedbiri; evli korunan kişi için', '(1) Bu Kanun kapsamında korunan kişilerle ilgili olarak aşağıdaki koruyucu', 'ayrı yerleşim yeri belirlenmesi.', [], ''),
 ('11', 'kosul', 'kadın erkek eşitliği konusunda eğitim', 'kolluk görevlerini bu eğitimi almış, belirlenmiş yeterli personel yapar', '(1) Kolluk görevleri, kolluğun merkez', 'personel tarafından yerine getirilir.', [], 'yalnız kadın personel şartı YOK'),
]
yaz(10, '6284 sayılı Ailenin Korunması ve Kadına Karşı Şiddetin Önlenmesine Dair Kanun', K)
