# 7068 Genel Kolluk Disiplin Hükümleri — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('4','kosul','ağır olan disiplin cezası verilir','bir fiil birden fazla disiplinsizlikse','(3) Bir fiilin birden fazla','ağır olan disiplin cezası verilir.',[],'disiplinsizlik kasten de taksirle de olur'),
 ('4','kosul','birden fazlası verilemez','aynı fiile iki disiplin cezası yok','(2) Aynı fiil nedeniyle','birden fazlası verilemez.',[],''),
 ('4','kosul','idari yaptırıma bağlanmış olması','ayrıca disiplin cezasına engel değil','(4) Bir fiilin diğer kanunlar','engel teşkil etmez.',[],''),
 ('5','kosul','aynı fiilden dolayı ayrıca disiplin','adli soruşturma/kovuşturma disiplin cezasını engellemez','(1) Herhangi bir fiilden','engellemez.',[],''),
 ('6','kosul','mutlaka gerekçeli','takdir hakkı; ölçülü, adaletli, hakkaniyetli','(2) Takdir hakkı mutlaka','gerekçeli olarak kullanılır.',[],''),
 ('6','kosul','samimi ikrarı ve gösterdiği pişmanlık','takdirde göz önüne alınır','f) Disiplinsizlik yapan personelin samimi','gözönüne alınır.',[],'işleniş biçimi, zaman-yer, hizmete etki, zarar, kusur, önceki disiplin durumu da'),
 ('7','tanim','daha dikkatli olması gerektiğinin','uyarma cezası (yazı ile)','a) Uyarma cezası','yazı ile bildirilmesidir.',[('7','kınama: kusurlu olduğunun yazıyla bildirilmesi')],''),
 ('7','tanim','kusurlu olduğunun yazı ile','kınama cezası','b) Kınama cezası','yazı ile bildirilmesidir.',[],'UYARMA = DİKKATLİ OL, KINAMA = KUSURLUSUN'),
 ('7','sayi_oran','onbeş günlüğe kadar kesinti','aylıktan kesme; brüt aylıktan, zam ve tazminat hariç','c) Aylıktan kesme cezası','kuruşlar dikkate alınmaz.',[],'tam lira üzerinden'),
 ('7','sure','dört, altı veya on ay','kısa süreli durdurma','ç) Kısa süreli durdurma','durdurulmasıdır.',[],''),
 ('7','sure','oniki, onaltı, yirmi veya yirmidört','uzun süreli durdurma','d) Uzun süreli durdurma','durdurulmasıdır.',[],'KISA 4-6-10, UZUN 12-16-20-24'),
 ('7','tanim','bir daha çalıştırılmamak üzere','meslekten çıkarma (emniyet, jandarma, sahil güvenlik)','e) Meslekten çıkarma','meslekten çıkarılmasıdır.',[],'Devlet memurluğundan çıkarma: bir daha memurluğa atanmamak üzere'),
 ('7','kosul','bir derece hafif olanı','iyi/çok iyi değerlendirme puanı alana uygulanabilir','(2) Kurumda geçmiş','uygulanabilir.',[],''),
 ('7','sure','özlük dosyasından silinmesini','uyarma-kınama beş, diğerleri on yıl sonra; atamaya yetkili amire','(5) Devlet memurluğundan çıkarma ya da','özlük dosyasından silinir.',[],''),
 ('8','ceza','alenen eleştirmek','uyarma; amiri alenen eleştirmek, itiraz','g) Usulüne uygun olarak kendisine','disiplinsizlik teşkil etmez.).',[],'karar verilene kadar fikrini savunmak disiplinsizlik değil'),
 ('8','ceza','Nezaket kurallarına aykırı','uyarma; nezaket kurallarına aykırılık','e) Nezaket','davranışlarda bulunmak.',[],''),
 ('8','ceza','mesaiye geç gelmek','uyarma; özürsüz mesaiye geç gelmek, erken ayrılmak','d) Özürsüz veya izinsiz olarak mesaiye','riayet etmemek.',[],''),
 ('8','ceza','yüzük, bilezik, kolye','kınama; yüzük, bilezik, kolye takmak','d) Mevzuat veya talimatlarla taşınmasına','benzeri şeyleri takmak.',[],''),
 ('8','ceza','Nöbeti teslimden sonra','kınama; nöbet sonrası görev yerine geç dönmek','c) Nöbeti teslimden','geç dönmek.',[],''),
 ('8','ceza','demirbaş tabancanın üzerinde','kınama; demirbaş tabancayı boyamak, gravür','ğ) Zati demirbaş','değişiklikler yapmak.',[],''),
 ('8','ceza','eksik kuşam ve teçhizatla','üç güne kadar aylıktan kesme; eksik kuşam','(3) Aylıktan kesme cezasını gerektiren','eksik kuşam ve teçhizatla göreve çıkmak.',[],''),
 ('8','ceza','yirmidört saate kadar göreve gelmemek','üç güne kadar aylıktan kesme; göreve gelmemek','4) İzinsiz veya kurumunca kabul edilebilir bir özrü','göreve gelmemek.',[],''),
 ('8','ceza','kahvehane, kıraathane','resmi kıyafetle oturmak: üç güne kadar aylıktan kesme','7) Görevli bulunduğu sırada','benzeri yerlerde oturmak.',[],''),
 ('8','ceza','il sınırları dışına çıkmak','amirinden izin almadan: üç güne kadar aylıktan kesme','8) Amirinden izin almaksızın','dışına çıkmak.',[],''),
 ('8','ceza','personel kimlik kartını','kaybetmek: üç güne kadar aylıktan kesme','10) Kendisine verilmiş olan personel','kaybetmek.',[],''),
 ('8','ceza','hastalığını abartmak','hastalığı abartmak: üç güne kadar aylıktan kesme','11) Bazı isteklerini','alışkanlık haline getirmek.',[],''),
 ('8','ceza','Selamlama ile ilgili','kurallara uymama: üç güne kadar aylıktan kesme','15) Selamlama','riayet etmemek.',[],'protokol kuralları, kılık kıyafet de'),
 ('8','ceza','onur kırıcı söz','dört ila on gün aylıktan kesme; onur kırıcı söz','b) Dört ila on günlüğe','onur kırıcı söz söylemek',[],'aynı rütbedekilere, astlara, mesai arkadaşlarına'),
 ('9','ceza','İşkence yapmak','Devlet memurluğundan çıkarma','(1) Devlet memurluğundan çıkarma cezası uygulanacak','İşkence yapmak.',[],'bölücü faaliyet de; diğer haller 657'),
 ('10','ceza','Silahla ölüme sebebiyet','meslekten çıkarma verilebilir (ağırlaştırıcı)','(5) Silahla ölüme','meslekten çıkarma cezası verilebilir.',[],''),
 ('10','ceza','Görevde uyumak','Devlet/kişi zarar görmüşse meslekten çıkarma','(8) Görevde uyumak','uygulanabilir.',[],''),
 ('10','ceza','Denetleme ve soruşturma görevlerini savsaklamak','zarar varsa dört ay kısa süreli durdurma','(12) Denetleme ve soruşturma','uygulanabilir.',[],''),
 ('10','ceza','yurtdışı liman ziyaretlerinde','sahil güvenlik personeli: bir üst ceza türü','(13) Bu Kanunda belirlenmiş','meslekten çıkarma cezası verilebilir.',[],'Türk karasuları dışında da'),
 ('11','gorev_yetki','geçici olarak kontrol altına almaya','operasyon komutanı, gemi komutanı; zarar, disiplin bozulması, sarhoşluk','(1) Jandarma Genel Komutanlığının terörle','yetkilidir.',[],''),
 ('11','sure','yirmidört saati geçmeyecek','kontrol altında bulundurma süresi','(2) Kontrol altında bulundurma','en kısa sürede bilgi verilir.',[],''),
 ('11','sure','oniki saati geçmesi','yakınlarına ve komutanın üstüne bilgi','(2) Kontrol altında bulundurma','en kısa sürede bilgi verilir.',[],'KONTROL EN ÇOK 24 SAAT, 12 SAATTE HABER'),
 ('12','sayi_oran','yirmi disiplin cezası puanı','son bir yılda; ya da iki amirden oniki ceza','a) En son alınan disiplin cezasının kesinleştiği tarihten geriye doğru son bir yıl','disiplin cezası almak.',[],'meslekten çıkarma; disiplin kurulu verir'),
 ('12','sayi_oran','kırk disiplin cezası puanı','son beş yılda; ya da yirmibeş ceza: meslekten çıkarma','b) En son alınan','disiplin cezası almak.',[],'BİR YIL: 20 PUAN / 12 CEZA · BEŞ YIL: 40 PUAN / 25 CEZA'),
 ('13','makam','en üst disiplin amiridir','kaymakam ilçede, vali ilde','(3) Kaymakamlar ilçe','bir üst disiplin amiridir.',[],''),
 ('13','makam','bir üst disiplin amiridir','vali kaymakama; Bakan EGM, JGK, SGK ve valilere','(3) Kaymakamlar ilçe','bir üst disiplin amiridir.',[],''),
 ('13','sira_usul','fiilen görevli olduğu teşkilat bünyesinde','teşkilat dışında görevlendirilenin soruşturması; dosya kendi teşkilatına','(6) Bakanlık merkez','kurullarına gönderilir.',[],''),
 ('14','sira_usul','heyet başkanı hariç olmak üzere','soruşturma heyetine ast üye konabilir','Ancak gerek görülmesi halinde','görevlendirilebilir.',[],'soruşturmacı kural olarak üst konumunda ya da müfettiş'),
 ('14','gorev_yetki','kriminal inceleme yaptırma','soruşturmacının yetkisi (hâkim/savcı kararı gerektirmeyen)','(3) Disiplin soruşturmacıları ve heyeti','yazışma yetkisini haizdir.',[],'ifade alma, tanık, bilirkişi, keşif de'),
 ('15','kosul','bu sıfatlarından doğan yetkilerini kullanamazlar','disiplin amiri yetki kullanamaz; üst amir kullanır','(3) Disiplin amirleri boşanmış','tarafından kullanılır.',[],'eş (boşanmış olsa da), ikinci dereceye kadar hısım'),
 ('15','yasak','yetkisi devredilemez','disiplin amirliği','(4) Disiplin amirliği','devredilemez.',[],'vekâleten, ikinci ve geçici görevle yürütenler kullanabilir'),
 ('19','makam','vali yardımcısının başkanlığında','il jandarma disiplin kurulu','a) İl jandarma disiplin kurulu, vali','vali yardımcısının başkanlığında,',[],'hukuk işleri müdürü, il jandarma komutanı, personel ve asayiş şube müdürleri'),
 ('19','makam','en az tuğgeneral rütbesini','JGK Merkez Disiplin Kurulu başkanı','ç) (Değişik:18/10/2018-7148/39 md.) Jandarma Genel Komutanlığı Merkez','başmüfettişten oluşur.',[],''),
 ('19','makam','jandarma genel komutan yardımcısının başkanlığında','JGK Yüksek Disiplin Kurulu; Personel, Teftiş, Hukuk başkanları','d) (Değişik:18/10/2018-7148/39 md.) Jandarma Genel Komutanlığı Yüksek','bir başkandan oluşur.',[],'Jandarma Genel Komutanı da başkanlık edebilir'),
 ('19','kosul','en kıdemli astsubay üye olarak','astsubayın disiplin işinde kıdemli astsubay üye bulunur (Yüksek DK hariç)','Hakkında disiplin soruşturması yapılandan daha kıdemli bir astsubay yok ise','üye olarak görevlendirilir.',[],''),
 ('20','gorev_yetki','Yüzbaşı ve altı rütbelerdeki','il/kurum disiplin kurulları: çıkarma cezaları dışındakiler','a) İl jandarma disiplin kurulu il jandarma','diğer disiplin cezalarını,',[],'uzman erbaş, sözleşmeli erbaş-ere memurluktan çıkarma dışındakiler'),
 ('20','gorev_yetki','albay rütbesinde bulunanlara','JGK Yüksek Disiplin Kurulu: çıkarma cezaları dışındaki cezalar','2) Genel Komutanlık merkez teşkilatı, asayiş kolordu','dışında kalan disiplin cezalarını,',[],'binbaşı-yarbaya meslekten çıkarma da YDK'),
 ('20','gorev_yetki','Generaller hakkında tüm disiplin cezalarını','Bakanlık Yüksek Disiplin Kurulu; albaya meslekten çıkarma da','a) Albay rütbesindeki personele','Bakanlık Yüksek Disiplin Kurulu yetkilidir.',[],''),
 ('21','makam','valinin onayıyla','il jandarma disiplin kurulunun meslekten çıkarma dışındaki kararları kesinleşir','a) İl jandarma disiplin kurulunun','Bakanın onayıyla,',[],''),
 ('21','makam','valinin önerisi','il JDK meslekten çıkarma: YDK uygun görüşü + Bakan onayı','a) İl jandarma disiplin kurulunun','Bakanın onayıyla,',[],''),
 ('21','makam','Jandarma Genel Komutanının onayıyla','kurum, kolordu, Merkez DK kararları (meslekten çıkarma dışı)','b) Asayiş kolordu komutanlıkları, komando tugay komutanlıkları, komando alay komutanlıkları, Jandarma Komando Özel Asayiş ve Kurtarma Tugay Komutanlığı, eğitim tugay ve birlik komutanlıkları disiplin kurulu, Genel','Bakanın onayıyla,',[],'meslekten çıkarma: YDK uygun görüşü + Bakan onayı; YDK kararları Bakan onayıyla'),
 ('21','makam','Kurulunca kesin karara','Bakan/JGK/YDK\'nın uygun görmediği dosyalar','(2) Birinci fıkra kapsamında','kesin karara bağlanır.',[],''),
 ('27','sira_usul','kurulun yetkisizliğine','disiplin kurulu karar türlerinden; gerekçeli yazılır','(1) Disiplin kurulu, soruşturma','karar verebilir.',[],'ceza yok, karar yok, ceza, yetkisizlik'),
 ('28','kosul','görevden uzaklaştırma önlemi derhal kaldırılır','meslekten çıkarma hafif cezaya indirilince','(2) Disiplin kurullarınca haklarında','derhal kaldırılır.',[],'uzaklaştırmada 657 uygulanır'),
 ('29','sure','bir ay içinde','uyarma–durdurma cezalarında soruşturmaya başlama (öğrenmeden)','a) Uyarma, kınama, aylıktan kesme','zamanaşımına uğrar.',[],'ÖĞRENMEDEN: HAFİF BİR AY, ÇIKARMA ALTI AY'),
 ('29','sure','altı ay içinde','çıkarma cezalarında soruşturmaya başlama; mahkeme iptalinde yeniden değerlendirme de','a) Uyarma, kınama, aylıktan kesme','zamanaşımına uğrar.',[],''),
 ('29','sure','iki yıl içinde disiplin cezası','ceza verme yetkisi zamanaşımına uğrar (fiil tarihinden)','(2) Disiplin cezasını gerektiren fiillerin','zamanaşımına uğrar.',[],'kesintisizde kesinti, zincirlemede son suç tarihinden'),
 ('30','sure','on gün içinde itiraz','disiplin amiri cezasına; bir üst amire yazılı','(1) Disiplin amirleri tarafından verilen','Süresi içinde itiraz edilmeyen cezalar kesinleşir.',[],''),
 ('30','makam','Kaymakamın doğrudan verdiği','valiye itiraz','(1) Disiplin amirleri tarafından verilen','Süresi içinde itiraz edilmeyen cezalar kesinleşir.',[],'KAYMAKAMDAN VALİYE'),
 ('30','makam','Bakanlık Yüksek Disiplin Kuruluna itiraz','vali, EGM, JGK, SGK doğrudan cezaları; karar kesin','(1) Disiplin amirleri tarafından verilen','Süresi içinde itiraz edilmeyen cezalar kesinleşir.',[],''),
 ('30','sure','otuz gün içinde karara','itiraz mercii karar süresi','(2) İtiraz, yetkili merci','karara bağlanır.',[],'İTİRAZ ON GÜN, KARAR OTUZ GÜN'),
 ('30','yasak','daha ağır ceza verilemez','itiraz üzerine','(4) İtiraz üzerine','ceza verilemez.',[],'hafifletebilir ya da kaldırabilir'),
 ('30','kosul','ancak idari yargı yoluna','Bakan ve disiplin kurulu cezalarına itiraz yok','(5) Bakan ile disiplin','başvurulabilir.',[],''),
 ('31','sure','yedi günden az olamaz','savunma süresi','Savunma için verilen süre','vazgeçmiş sayılır.',[],'savunmasız ceza verilemez; süresinde yapmayan vazgeçmiş sayılır'),
 ('31','kosul','tanık dinletmeye','çıkarma cezası istenen personelin hakkı; vekille savunma','(4) Hakkında meslekten çıkarma','savunma yapma hakkına sahiptir.',[],''),
 ('32','sure','üsse veya limana dönmesiyle','seyirdeki gemide verilen cezada dava süresi başlar','Ancak Sahil Güvenlik Komutanlığının seyir','dönmesiyle başlar.',[],'normalde tebliğden'),
 ('33','sure','takip eden aybaşında','aylıktan kesme uygulanır (kesinleşme sonrası)','(2) Aylıktan kesme cezası, kesinleşme','aybaşında uygulanır.',[],''),
 ('33','makam','Devlet Personel Başkanlığına','meslekten/memurluktan çıkarma cezaları ayrıca bildirilir','(3) Verilen disiplin cezaları','Devlet Personel Başkanlığına bildirilir.',[],''),
 ('34','kosul','uzun süreli durdurma cezası gibi','657\'deki kademe ilerlemesinin durdurulması','(2) 657 sayılı Kanundaki','telakki edilir ve uygulanır.',[],'boşlukta 657 disiplin hükümleri'),
 ('8', 'ceza', 'usul ve kurallara riayet etmeden', 'kınama; usulsüz sözlü, yazılı veya elektronik müracaat/şikâyet', '(2) Kınama cezasını gerektiren fiiller', 'müracaat veya şikâyette bulunmak.', [], ''),
]
yaz(12, "7068 sayılı Genel Kolluk Disiplin Hükümleri Hakkında KHK'nın Kabul Edilmesine Dair Kanun", K)
