# 7068 Genel Kolluk Disiplin Hükümleri — kelime → cevap
# KURAL (başkan, 4 Eki 2026): SOL = soru KÖKÜNDE göreceğin ifade, SAĞ = doğru ŞIKTA arayacağın kelime.
# Sorulardan geriye doğru yazıldı (210 cevaplı soru + kitapçık kökleri); kanıt resmî metin.
# m.8: "soruda bu fiil geçerse → şıkta bu ceza". Kanıt her zaman fıkra başlığından başlar (cezanın adı kanıtta görünsün).
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
# m.8 fıkra başlıkları (kanıt başlangıcı)
U, KN = 'MADDE 8- (1) Uyarma cezasını', 'MADDE 8- (2) Kınama cezasını'
A3, A10, A15 = 'MADDE 8- (3) a) Üç günlüğe', 'MADDE 8- (3) b) Dört ila on', 'MADDE 8- (3) c) Onbir ila onbeş'
D4, D6, D10 = 'MADDE 8- (4) a) Dört ay', 'MADDE 8- (4) b) Altı ay', 'MADDE 8- (4) c) On ay'
U12, U16, U20, U24 = 'MADDE 8- (5) a) Oniki ay', 'MADDE 8- (5) b) Onaltı ay', 'MADDE 8- (5) c) Yirmi ay', 'MADDE 8- (5) ç) Yirmidört ay'
MC = 'MADDE 8- (6) Meslekten çıkarma'
# cezalar (sağ taraf)
uy, kn = 'uyarma', 'kınama'
k3, k10, k15 = 'üç güne kadar aylıktan kesme', 'dört-on gün aylıktan kesme', 'onbir-onbeş gün aylıktan kesme'
d4, d6, d10 = 'dört ay kısa süreli durdurma', 'altı ay kısa süreli durdurma', 'on ay kısa süreli durdurma'
u12, u16, u20, u24 = 'oniki ay uzun süreli durdurma', 'onaltı ay uzun süreli durdurma', 'yirmi ay uzun süreli durdurma', 'yirmidört ay uzun süreli durdurma'
mc = 'meslekten çıkarma'
GELMEME = 'GÖREVE GELMEME: 24 saate kadar üç gün kesme; 2 güne kadar dört-on gün; 3 güne kadar onbir-onbeş gün; 5 güne kadar dört ay; 9 güne kadar yirmi ay'
K = [
 # m.4-6 — genel esaslar, adli soruşturmadan bağımsızlık, takdir hakkı
 ('4','kosul','oluşabilir','kasten veya taksirle','(1) Disiplinsizlik kasten','taksirle oluşabilir.',[],'yalnız kasten DEĞİL'),
 ('4','kosul','Aynı fiil nedeniyle','birden fazla ceza verilemez','(2) Aynı fiil nedeniyle','birden fazlası verilemez.',[],''),
 ('4','kosul','birden fazla disiplinsizlik','ağır olan ceza verilir','(3) Bir fiilin birden fazla','ağır olan disiplin cezası verilir.',[],''),
 ('4','kosul','idari yaptırıma','disiplin cezasına engel değil','(4) Bir fiilin diğer kanunlar','engel teşkil etmez.',[],'başka kanunda idari yaptırım olsa da'),
 ('5','kosul','adli soruşturma','disiplin soruşturması ve cezasını engellemez','(1) Herhangi bir fiilden','engellemez.',[('4','m.4 metninin sonunda bu maddenin başlığı yer alır')],'aynı fiilden dolayı ayrıca disiplin cezası verilebilir'),
 ('6','kosul','takdir hak','ölçülü-adil-hakkaniyetli-gerekçeli; işleniş/zaman-yer/hizmete etki/zarar/kusur/önceki disiplin/pişmanlık; medeni hal/sosyal medya/sicil amiri görüşü YOK','(1) Bu Kanun ile disiplin cezası','pişmanlık, gözönüne alınır.',[('5', 'm.5 metninin sonunda bu maddenin başlığı yer alır')],''),
 ('6','yasak','takdir hakkının kaldırılması','hiçbir idari makam karar veremez','(4) İtiraz üzerine yetkili makamlar','uygulama yapılamaz.',[],'itiraz kararları hariç'),
 # m.7 — disiplin cezaları
 ('7','tanim','Personele verilecek','yedi: uyarma/kınama/aylıktan kesme/kısa-uzun durdurma/meslekten-memurluktan çıkarma; görevden uzaklaştırma-oda hapsi-kademe YOK','(1) Personele verilecek disiplin cezaları','memurluktan çıkarılmasıdır.',[],'görevden uzaklaştırma ceza değil, tedbir (m.28)'),
 ('7','tanim','daha dikkatli olması','uyarma','a) Uyarma cezası:','yazı ile bildirilmesidir.',[],'yazıyla'),
 ('7','tanim','kusurlu olduğunun','kınama','b) Kınama cezası:','yazı ile bildirilmesidir.',[],'UYARMA = DİKKATLİ OL, KINAMA = KUSURLUSUN'),
 ('7','sayi_oran','Aylıktan kesme cezası:','brüt aylıktan onbeş güne kadar; zam-tazminat hariç','c) Aylıktan kesme cezası:','kuruşlar dikkate alınmaz.',[],'tam lira üzerinden; otuz gün DEĞİL'),
 ('7','sure','Kısa süreli durdurma:','dört, altı veya on ay','ç) Kısa süreli durdurma:','süre ile durdurulmasıdır.',[],'kademe ilerlemesi durur'),
 ('7','sure','Uzun süreli durdurma:','oniki, onaltı, yirmi, yirmidört ay; onsekiz YOK','d) Uzun süreli durdurma:','süre ile durdurulmasıdır.',[],''),
 ('7','tanim','Meslekten çıkarma:','Emniyet, Jandarma, Sahil Güvenlikte bir daha çalışamaz','e) Meslekten çıkarma:','meslekten çıkarılmasıdır.',[],'memurluktan çıkarma: bir daha Devlet memuru olamaz'),
 ('7','tanim','Devlet memurluğundan çıkarma:','bir daha memurluğa atanamaz','f) Devlet memurluğundan çıkarma:','memurluktan çıkarılmasıdır.',[],''),
 ('7','kosul','iyi veya çok iyi','bir derece hafif ceza uygulanabilir','(2) Kurumda geçmiş','hafif olanı uygulanabilir.',[],'geçmiş hizmeti olumlu personel'),
 ('7','kosul','üst ve alt kademeleri','ağır ya da hafif ceza sayılmaz','(3) Birinci fıkranın','ceza sayılmaz.',[],'aylıktan kesme ve durdurmalarda'),
 ('7','sure','özlük dosyasından','silinme: uyarma-kınama beş yıl, diğerleri on yıl sonra','(5) Devlet memurluğundan çıkarma ya da','özlük dosyasından silinir.',[],'atamaya yetkili amire başvurur; çıkarma cezaları silinmez'),
 # m.8 — liste satırları
 ('8','tanim','Uyarma cezasını','gerektiren: temizlik/tasarruf/mesaiye gecikme/nezaket/bilgi vermeme/alenen eleştiri; nöbet dönüşü-il dışına çıkma DEĞİL','MADDE 8- (1) Uyarma cezasını','bu kapsamda disiplinsizlik teşkil etmez.).',[],'faaliyete-mesaiye geç kalma, amire bilgi vermemek de; il dışına izinsiz çıkmak üç gün kesme'),
 ('8','tanim','Kınama cezasını','gerektiren: usulsüz şikâyet/nöbet dönüşü gecikme/takı/arkadaşa saygısızlık/imtina/hitap','MADDE 8- (2) Kınama cezasını','müsamaha ve savsaklama göstermek.',[],'yasak davranış, bildirim gecikmesi, arkadaşı kötüleme, tabanca süsleme, savsaklama da'),
 # m.8 (1) uyarma
 ('8','ceza','giyim ve kuşamını temiz tutmamak',uy,U,'temizliğine özen göstermemek.',[],''),
 ('8','ceza','tasarruf tedbirlerine',uy,U,'makul seviyedeki özeni göstermemek.',[],''),
 ('8','ceza','faaliyetlere geç kalmak',uy,U,'faaliyetlere geç kalmak.',[],''),
 ('8','ceza','mesaiye geç gelmek',uy,U,'mesai saatlerine riayet etmemek.',[],'erken ayrılmak da'),
 ('8','ceza','Nezaket kurallarına aykırı',uy,U,'aykırı tavır ve davranışlarda bulunmak.',[],''),
 ('8','ceza','amire bilgi vermemek',uy,U,'amire bilgi vermemek.',[],'emrin sonucu, katılınan toplantı hakkında'),
 ('8','ceza','alenen eleştirmek',uy,U,'bu kapsamda disiplinsizlik teşkil etmez.).',[],'karar verilene kadar fikrini savunmak ya da kanunsuz emre itiraz disiplinsizlik DEĞİL'),
 # m.8 (2) kınama
 ('8','ceza','talimatlarla yasaklanan davranışlarda',kn,KN,'yasaklanan davranışlarda bulunmak.',[],'görev sırasında'),
 ('8','ceza','usul ve kurallara riayet etmeden','şikâyette bulunmak: kınama','MADDE 8- (2) Kınama cezasını','müracaat veya şikâyette bulunmak.',[],'toplu şikâyet dört ay kısa durdurma'),
 ('8','ceza','Nöbeti teslimden sonra',kn,KN,'özürsüz olarak geç dönmek.',[],''),
 ('8','ceza','Bildirimleri süresi içerisinde',kn,KN,'yerine ulaştırmamak.',[],''),
 ('8','ceza','yüzük, bilezik, kolye',kn,KN,'benzeri şeyleri takmak.',[],''),
 ('8','ceza','mesai arkadaşlarına karşı saygısız',kn,KN,'saygısız davranmak.',[],'aynı rütbedekilere de; görev sırasında amire saygısızlık dört ay, görev dışında üç gün kesme'),
 ('8','ceza','sorumluluğu üstlenmekten imtina',kn,KN,'imtina ettiğini gösterecek tavır ve davranışlarda bulunmak.',[],''),
 ('8','ceza','onların bulunmadığı ortamlarda','arkadaşı kötüleme: kınama','MADDE 8- (2) Kınama cezasını','olumsuz sözler söylemek.',[],'kişiliği hakkında kötüleyici söz'),
 ('8','ceza','demirbaş tabanca',kn,KN,'gibi değişiklikler yapmak.',[],'boya, kaplama, gravür'),
 ('8','ceza','teamüllere aykırı hitap',kn,KN,'aykırı hitaplarda bulunmak.',[],''),
 ('8','ceza','müsamaha ve savsaklama',kn,KN,'müsamaha ve savsaklama göstermek.',[('10','zarar doğurursa daha ağır ceza verilebilir')],''),
 # m.8 (3) a) üç güne kadar aylıktan kesme
 ('8','ceza','eksik kuşam',k3,A3,'teçhizatla göreve çıkmak.',[],''),
 ('8','ceza','uyarılarına uymamak',k3,A3,'gereken süre içinde yanıtlamamak.',[],'amir ve üstlerin uyarısına'),
 ('8','ceza','başkalarını aracı koyup','öncelik-ayrıcalık istemek: üç güne kadar aylıktan kesme','MADDE 8- (3) a) Üç günlüğe','öncelik ve ayrıcalık talep etmek.',[],''),
 ('8','ceza','yirmidört saate kadar göreve','gelmemek: üç güne kadar aylıktan kesme','MADDE 8- (3) a) Üç günlüğe','yirmidört saate kadar göreve gelmemek.',[],'GÖREVE GELMEME: 24 saate kadar üç gün kesme; 2 güne kadar dört-on gün; 3 güne kadar onbir-onbeş gün; 5 güne kadar dört ay; 9 güne kadar yirmi ay'),
 ('8','ceza','Görev dışında amir',k3,A3,'üstlerine saygısız davranmak.',[],'görev SIRASINDA amire saygısızlık dört ay kısa durdurma'),
 ('8','ceza','Nöbet görevine gelmemek',k3,A3,'kurallara aykırı hareket etmek.',[('10','zarar doğurursa meslekten çıkarma uygulanabilir')],''),
 ('8','ceza','resmi kıyafet ile kahvehane',k3,A3,'benzeri yerlerde oturmak.',[],'görev gereği değilse'),
 ('8','ceza','il sınırları dışına',k3,A3,'il sınırları dışına çıkmak.',[],'amirinden izinsiz; uyarma DEĞİL'),
 ('8','ceza','özel işlerinde kullanmak',k3,A3,'özel işlerinde kullanmak.',[],'emrindekileri ya da Devlet araçlarını'),
 ('8','ceza','personel kimlik kartını',k3,A3,'bir neden olmaksızın kaybetmek.',[],'kimlik kartını başkasına vermek meslekten çıkarma'),
 ('8','ceza','hastalığını abartmak',k3,A3,'alışkanlık haline getirmek.',[],''),
 ('8','ceza','arayıp soranlara',k3,A3,'cevap vermemek, baştan savmak.',[],''),
 ('8','ceza','Görevde kayıtsızlık',k3,A3,'belirtilen sürede bitirmemek.',[],''),
 ('8','ceza','kişileri bekletmek',k3,A3,'kişileri bekletmek.',[],'haklı neden olmadan'),
 ('8','ceza','Selamlama',k3,A3,'kurallara riayet etmemek.',[],''),
 ('8','ceza','protokol kurallarına',k3,A3,'aykırı tavır ve davranışlarda bulunmak.',[],''),
 ('8','ceza','ilgisi olmayan işlerle',k3,A3,'işlerle uğraşmak.',[],'görevdeyken'),
 ('8','ceza','Kılık ve kıyafet',k3,A3,'kurallara uymamak.',[],'üniforma giymemek dört-on gün'),
 # m.8 (3) b) dört-on gün aylıktan kesme
 ('8','ceza','astlarına veya mesai arkadaşlarına',k10,A10,'eylemle hakaret etmek.',[],'aynı rütbedekilere onur kırıcı söz, hakaret; KİŞİLERE onur kırıcı söz onbir-onbeş gün'),
 ('8','ceza','göreve ilişkin evrakı',k10,A10,'evrakı kaybetmek.',[],'resmi belge kaybı; üç gün kesme DEĞİL'),
 ('8','ceza','Devlet malı eşyanın hasar',k10,A10,'kaybolmasına neden olmak.',[],'önlem almamak yüzünden'),
 ('8','ceza','oyun oynamak',k10,A10,'yerlerde oyun oynamak.',[],'izin verilmeyen kahvehane, lokal, kulüpte'),
 ('8','ceza','iki güne kadar','göreve gelmemek: dört-on gün aylıktan kesme','MADDE 8- (3) b) Dört ila on','göreve gelmemek.',[],'GÖREVE GELMEME: 24 saate kadar üç gün kesme; 2 güne kadar dört-on gün; 3 güne kadar onbir-onbeş gün; 5 güne kadar dört ay; 9 güne kadar yirmi ay'),
 ('8','ceza','Mühür veya beratını',k10,A10,'neden olmaksızın kaybetmek.',[],''),
 ('8','ceza','devir ve teslim',k10,A10,'görev yerinden ayrılmak.',[],'tamamlamadan ayrılmak'),
 ('8','ceza','geri vermemek',k10,A10,'geri vermemek.',[],'resmi belge, araç, gereç'),
 ('8','ceza','üniforma giymemek',k10,A10,'üniforma giymemek.',[],'onbir-onbeş gün DEĞİL'),
 # m.8 (3) c) onbir-onbeş gün aylıktan kesme
 ('8','ceza','üç güne kadar','göreve gelmemek: onbir-onbeş gün aylıktan kesme','MADDE 8- (3) c) Onbir ila onbeş','görevine gelmemek.',[],'GÖREVE GELMEME: 24 saate kadar üç gün kesme; 2 güne kadar dört-on gün; 3 güne kadar onbir-onbeş gün; 5 güne kadar dört ay; 9 güne kadar yirmi ay'),
 ('8','ceza','derhal dönmesi','bildirildiği halde dönmemek: onbir-onbeş gün aylıktan kesme','MADDE 8- (3) c) Onbir ila onbeş','makul sürede dönmemek.',[],'izinden çağrılınca'),
 ('8','ceza','zamanında iletmemek',k15,A15,'zamanında iletmemek.',[],'olay, bilgi, emri; GİZLEMEK on ay kısa durdurma'),
 ('8','ceza','kişilere karşı onur kırıcı',k15,A15,'davranışta bulunmak.',[],'görev sırasında'),
 ('8','ceza','soruşturmaları uzatmak',k15,A15,'soruşturmayı eksik bırakmak.',[],'raporu süresinde vermemek'),
 # m.8 (4) a) dört ay kısa süreli durdurma
 ('8','ceza','yalan söylemek',d4,D4,'yalan söylemek.',[],'amir ve memurlara görevle ilgili'),
 ('8','ceza','Denetim görevini yerine getirmemek',d4,D4,'Denetim görevini yerine getirmemek.',[],''),
 ('8','ceza','beş güne kadar','göreve gelmemek: dört ay kısa süreli durdurma','MADDE 8- (4) a) Dört ay','göreve gelmemek.',[],'GÖREVE GELMEME: 24 saate kadar üç gün kesme; 2 güne kadar dört-on gün; 3 güne kadar onbir-onbeş gün; 5 güne kadar dört ay; 9 güne kadar yirmi ay'),
 ('8','ceza','haksız yere şikâyet',d4,D4,'haksız yere şikâyet etmek.',[],''),
 ('8','ceza','dövme girişimi','dört ay kısa süreli durdurma','MADDE 8- (4) a) Dört ay','dövme girişiminde bulunmak.',[],'ast, aynı rütbe, mesai arkadaşı; AMİRİ dövmeye teşebbüs yirmidört ay'),
 ('8','ceza','Toplu olarak','şikâyet: dört ay kısa süreli durdurma','MADDE 8- (4) a) Dört ay','şikâyette bulunmak.',[],'sözlü veya yazılı'),
 ('8','ceza','sırasında amir veya üstlerine saygısız',d4,D4,'saygısız davranmak.',[],'görev DIŞINDA üç gün kesme'),
 ('8','ceza','baskı ve taciz',d4,D4,'baskı ve taciz uygulamak.',[],'sürekli ve sistemli'),
 # m.8 (4) b) altı ay kısa süreli durdurma
 ('8','ceza','hediye veya borç',d6,D6,'hediye veya borç almak.',[],'astlarından ya da iş sahiplerinden'),
 ('8','ceza','borçlanıp ödememeyi',d6,D6,'alışkanlık haline getirmek.',[],''),
 ('8','ceza','saygısızca konuşmalar',d6,D6,'anlaşılmaz sesler çıkarmak.',[],'telsizde; telsizde AMİRİ eleştirmek meslekten çıkarma'),
 ('8','ceza','motorlu araç, makine',d6,D6,'hasara sebep olmak.',[],'ağır kusurla'),
 ('8','ceza','otoritesini zedeleyecek','şekilde amiri eleştirmek: altı ay kısa süreli durdurma','MADDE 8- (4) b) Altı ay','söz söylemek ya da yazı yazmak.',[],'amiri olumsuz eleştirmek'),
 ('8','ceza','Hizmet dışında resmi sıfatının',d6,D6,'eylem ve davranışlarda bulunmak.',[],'hizmet İÇİNDE onaltı ay uzun'),
 ('8','ceza','göreve başlamayı geciktirmek',d6,D6,'göreve başlamayı geciktirmek.',[],'mazeret ileri sürerek'),
 # m.8 (4) c) on ay kısa süreli durdurma
 ('8','ceza','olayları ve bunlarla ilgili bilgileri',d10,D10,'kuruluş ve kişilerden gizlemek.',[],'amirden gizlemek'),
 ('8','ceza','Yetkili olmadığı halde basın',d10,D10,'bilgi ya da demeç vermek.',[],'onur zedeleyici bildiri-demeç meslekten çıkarma'),
 ('8','ceza','ihmal sonucu yaralamaya',d10,D10,'işlenmesine neden olmak.',[('10','silahla ihmalen yaralamada meslekten çıkarma verilebilir')],'silahla; ölümde yirmidört ay'),
 ('8','ceza','trafik kazası sonucu yaralamaya',d10,D10,'trafik kazası sonucu yaralamaya sebebiyet vermek.',[],'hizmet aracıyla ağır kusur; ölümde yirmidört ay'),
 ('8','ceza','arkadaşlarını tehdit',d10,D10,'arkadaşlarını tehdit etmek.',[],'AMİRİ tehdit yirmidört ay'),
 # m.8 (5) uzun süreli durdurma
 ('8','ceza','mal bildiriminde',u12,U12,'gerçeğe aykırı bildirimde bulunmak.',[],''),
 ('8','ceza','kurum binalarına gelen','kişilere hakaret: oniki ay uzun süreli durdurma','MADDE 8- (5) a) Oniki ay','getirilenlere hakaret etmek.',[],'görev sırasında kişilere hakaret'),
 ('8','ceza','ihmal nedeniyle kaybetmek',u16,U16,'ihmal nedeniyle kaybetmek.',[],'motorlu araç, muhabere, silah, mühimmat'),
 ('8','ceza','Hizmet içinde resmi sıfatının',u16,U16,'eylem ve davranışlarda bulunmak.',[],'hizmet DIŞINDA altı ay kısa'),
 ('8','ceza','uyumak veya uyuklamak',u16,U16,'uyumak veya uyuklamak.',[],'meslekten çıkarma DEĞİL (zarar doğarsa olabilir)'),
 ('8','ceza','dokuz güne kadar','göreve gelmemek: yirmi ay uzun süreli durdurma','MADDE 8- (5) c) Yirmi ay','görevine gelmemek.',[],'GÖREVE GELMEME: 24 saate kadar üç gün kesme; 2 güne kadar dört-on gün; 3 güne kadar onbir-onbeş gün; 5 güne kadar dört ay; 9 güne kadar yirmi ay'),
 ('8','ceza','kaçmasına neden olmak',u20,U20,'yakalama görevini savsaklamak.',[],'dikkatsizlikle; BİLEREK kaçmasına imkân meslekten çıkarma'),
 ('8','ceza','müşterek bahis',u20,U20,'şans oyunlarını oynamak.',[],'yetkisiz'),
 ('8','ceza','ihmal sonucu ölüme',u24,U24,'işlenmesine neden olmak.',[],'silahla; meslekten çıkarmaya ağırlaşabilir (m.10)'),
 ('8','ceza','Silahla yaralama suçunu kasten işlemek','yirmidört ay uzun süreli durdurma','MADDE 8- (5) ç) Yirmidört ay','kasten işlemek.',[],''),
 ('8','ceza','silah atmak',u24,U24,'silah atmak.',[('10','zarar doğurursa meslekten çıkarma uygulanabilir')],'meskûn yerde'),
 ('8','ceza','Amirin usulüne göre verdiği emri','yerine getirmemek: yirmidört ay uzun süreli durdurma','MADDE 8- (5) ç) Yirmidört ay','yerine getirmemek.',[],'zarar doğarsa meslekten çıkarma'),
 ('8','ceza','görev yerini terk',u24,U24,'görev yerini terk etmek.',[],'amirin izni olmadan'),
 ('8','ceza','Kişinin iffetine yönelik','söz-fiil: yirmidört ay uzun süreli durdurma','MADDE 8- (5) ç) Yirmidört ay','harekette bulunmak.',[],''),
 ('8','ceza','Amir veya üste hakaret',u24,U24,'üste hakaret etmek.',[],'ARKADAŞA hakaret dört-on gün kesme'),
 ('8','ceza','küçümsemek',u24,U24,'küçümsemek.',[],'amir ya da üstü'),
 ('8','ceza','dövmeye teşebbüs',u24,U24,'dövmeye teşebbüs etmek.',[],'amiri; arkadaşı dövme girişimi dört ay'),
 ('8','ceza','fiili olarak tehdit',u24,U24,'fiili olarak tehdit etmek.',[],'amiri; arkadaşı tehdit on ay'),
 ('8','ceza','kasıtlı olarak yok etmek',u24,U24,'yanlış biçimde işlemesini sağlamak.',[],'göreve ilişkin belge, bilgisayar verisi'),
 ('8','ceza','kriptolu cihaz',u24,U24,'ilgili birime derhal bildirmemek.',[],'kaybını, çalındığını; 2026 Subay sınavında soruldu'),
 ('8','ceza','trafik kazası sonucu ölüme',u24,U24,'sonucu ölüme sebebiyet vermek.',[],'hizmet aracıyla ağır kusur'),
 # m.8 (6) meslekten çıkarma
 ('8','ceza','ayrımı yapmak',mc,MC,'ayrım yapıcı tutum ve davranışlarda bulunmak.',[],'dil, ırk, cinsiyet, din'),
 ('8','ceza','Göreve çıkılmaması için','propaganda-kışkırtma: meslekten çıkarma','MADDE 8- (6) Meslekten çıkarma','karar uyarınca göreve çıkmamak.',[],''),
 ('8','ceza','toplu hale dönüştürerek',mc,MC,'tahrik ya da teşvik etmek.',[],''),
 ('8','ceza','Yetkisini veya nüfuzunu','meslekten çıkarma','MADDE 8- (6) Meslekten çıkarma','nedenlerle kötüye kullanmak.',[],'kin ve dostlukla da'),
 ('8','ceza','yetkisiz kişilere vermek',mc,MC,'verilmesine göz yummak.',[],'dosya, kayıt, evrak'),
 ('8','ceza','Gizli tutulması zorunlu',mc,MC,'kişilere açıklamak.',[],''),
 ('8','ceza','hükümlünün kaçmasına bilerek ve isteyerek','meslekten çıkarma','MADDE 8- (6) Meslekten çıkarma','imkân vermek.',[],'dikkatsizlikle kaçma yirmi ay'),
 ('8','ceza','suç kanıtlarını',mc,MC,'bu fiillere yardımcı olmak.',[],''),
 ('8','ceza','mühimmatı satmak',mc,MC,'başkalarının kullanımına vermek.',[],'kimlik kartını başkasına vermek de'),
 ('8','ceza','gerçek dışı rapor',mc,MC,'imza etmek veya ettirmek.',[],''),
 ('8','ceza','yardımdan kaçınmak',mc,MC,'gerekli girişimde bulunmamak.',[],'güvenlik görevlisine'),
 ('8','ceza','uygunsuz yerlere',mc,MC,'uygunsuz yerlere gitmek.',[],''),
 ('8','ceza','görevli bulunduğu sırada alkollü',mc,MC,'içilmesine göz yummak.',[],''),
 ('8','ceza','belli olacak biçimde',mc,MC,'belli olacak biçimde gelmek.',[],'göreve sarhoş ya da alkollü gelmek'),
 ('8','ceza','gizlenemeyecek derecede sarhoş',mc,MC,'sarhoş görünmek.',[],'resmi kıyafetle umuma açık yerde içki'),
 ('8','ceza','Uyuşturucu',mc,MC,'kolaylaştırmak ya da özendirmek.',[],''),
 ('8','ceza','Kumar oynamak',mc,MC,'kumar oynatanlarla ilişki kurmak.',[],'yetkisiz bahis yirmi ay'),
 ('8','ceza','Kaçakçılık',mc,MC,'kaçakçılarla ilişki kurmak.',[],''),
 ('8','ceza','Geliri ile uygun',mc,MC,'haklı kaynağını gösterememek.',[],''),
 ('8','ceza','grev yasağı',mc,MC,'eylemlerde bulunmak.',[],''),
 ('8','ceza','kazanç getirici faaliyetlerde',mc,MC,'faaliyetlerde bulunmak.',[],''),
 ('8','ceza','Siyasi partilerin yararına',mc,MC,'gösteri yürüyüşlerine katılmak.',[],''),
 ('8','ceza','sendikalara üye olmak',mc,MC,'düzenlemek veya bunlara katılmak.',[],''),
 ('8','ceza','bildiri dağıtmak',mc,MC,'bilgi, yazı ve demeç vermek.',[],'yetkisiz demeç on ay kısa'),
 ('8','ceza','itaatsizliğe, mukavemete',mc,MC,'taarruza tahrik ya da teşvik etmek.',[],''),
 ('8','ceza','Menşei belli olmayan',mc,MC,'benzerlerini bulundurmak.',[],'silah, mühimmat'),
 ('8','ceza','bilgisayar loglarında','meslekten çıkarma; yetkisiz sorgulama','aa) Yetkili olmadığı halde','log kayıtlarını değiştirmek veya silmek.',[],'haberleşmenin gizliliğini ihlal, kişisel veriyi yaymak da meslekten çıkarma'),
 ('8','ceza','fiili tecavüz','meslekten çıkarma; üstlerine de','dd) Üstlerine, aynı rütbedeki','fiili tecavüzde bulunmak.',[],'meslektaşlara da'),
 ('8','ceza','telsiz haberleşme araçlarıyla amir','meslekten çıkarma; olumsuz eleştiri','ee) Görevde kullanılan telsiz','eleştirici nitelikte konuşmalar yapmak.',[],'telsizde saygısızlık altı ay'),
 ('8','ceza','Dernek kurmak','meslekten çıkarma; spor dernekleri hariç','ff) Dernek kurmak','derneklere üye olmak.',[],''),
 ('8','ceza','Vakıf kurmak','meslekten çıkarma; Bakanlıkça belirlenmiş hariç','gg) Vakıf kurmak','organlarında görev almak.',[],''),
 ('8','ceza','Fuhşa teşvik','meslekten çıkarma; bilerek ilişki','hh) Fuhşa teşvik','bilerek ilişki kurmak.',[],''),
 ('8','sayi_oran','verilmesini gerektiren hallerde','kısada 1/5-1/4, uzunda 1/3-1/2 brüt aylık kesilir','a) Kısa süreli durdurma cezası verilmesini',"1/2'si, kesilir.",[],'terfisi 926-3466-3269-6191’e tabi Jandarma ve Sahil Güvenlik personeli; durdurma yerine'),
 ('8','makam','Yedinci fıkrada','yetkili disiplin kurulları verir','(8) Yedinci fıkrada','kurullarınca verilir.',[],'brüt aylık kesintisi'),
 # m.9 — Devlet memurluğundan çıkarma
 ('9','kosul','bu cezayı verme yetkisi','657 sayılı Kanuna göre; ek: milli güvenlik-bölücü yapı, işkence','(1) Devlet memurluğundan çıkarma cezası uygulanacak','657 sayılı Kanun hükümleri uygulanır.',[],''),
 ('9','ceza','milli güvenliği tehlikeye','Devlet memurluğundan çıkarma','(1) Devlet memurluğundan çıkarma cezası uygulanacak','ilişki içerisinde bulunmak.',[],'bölücü yapıya katılmak, yardım'),
 ('9','ceza','İşkence','Devlet memurluğundan çıkarma','(1) Devlet memurluğundan çıkarma cezası uygulanacak','İşkence yapmak.',[],'meslekten çıkarma DEĞİL'),
 # m.10 — ağırlaştırıcı nedenler
 ('10','ceza','emrinin yapılmaması','zarar varsa meslekten çıkarma uygulanabilir','(1) Amirin emrinin yapılmaması','meslekten çıkarma cezası uygulanabilir.',[],'hizmet gecikir ya da durursa'),
 ('10','ceza','Görev yerinden ayrılmak','uzun ya da zararlıysa meslekten çıkarma','(2) Görev yerinden ayrılmak','meslekten çıkarma cezası uygulanabilir.',[('8','devir-teslimi tamamlamadan ayrılmak dört-on gün kesme')],''),
 ('10','ceza','Yazılı kağıt, belge','zarar varsa meslekten çıkarma','(3) Yazılı kağıt, belge','meslekten çıkarma cezası verilebilir.',[('8','belgeyi kasten yok etmek yirmidört ay uzun durdurma')],''),
 ('10','ceza','nöbet talimatına aykırı','zarar varsa meslekten çıkarma','(4) Nöbet görevine gelmemek','meslekten çıkarma cezası uygulanabilir.',[('8','nöbete gelmemek temelde üç gün kesme')],''),
 ('10','ceza','Silahla ölüme','meslekten çıkarma verilebilir','(5) Silahla ölüme','meslekten çıkarma cezası verilebilir.',[],''),
 ('10','ceza','Silahla dikkatsizlik','yaralamada meslekten çıkarma verilebilir','(6) Silahla dikkatsizlik','meslekten çıkarma cezası verilebilir.',[('8','temelde on ay kısa (yaralama), yirmidört ay (ölüm)')],''),
 ('10','ceza','Meskûn yerlerde silah atmak fiili','zarar varsa meslekten çıkarma','(7) Meskûn yerlerde','meslekten çıkarma cezası uygulanabilir.',[],''),
 ('10','ceza','Görevde uyumak','zarar varsa meslekten çıkarma','(8) Görevde uyumak','meslekten çıkarma cezası uygulanabilir.',[],'temelde onaltı ay uzun'),
 ('10','ceza','Muhtelif mazeretler','aksama-zarar varsa meslekten çıkarma','(9) Muhtelif mazeretler','meslekten çıkarma cezası verilebilir.',[],''),
 ('10','ceza','müsamaha veya savsaklama','zarar varsa daha ağır ceza','(10) Görevin takdir','daha ağır cezalardan birisi verilebilir.',[],'temelde kınama'),
 ('10','ceza','yaralamaya kasten sebebiyet','meslekten çıkarma verilebilir','(11) Silahla yaralamaya kasten','meslekten çıkarma cezası verilebilir.',[],''),
 ('10','ceza','soruşturma görevlerini savsaklamak','zarar varsa dört ay kısa süreli durdurma','(12) Denetleme ve soruşturma','kısa süreli durdurma cezası uygulanabilir.',[],''),
 ('10','ceza','liman ziyaretlerinde','bir üst ceza: uyarma-kınamada kesme-durdurma; diğerinde meslekten çıkarma','(13) Bu Kanunda belirlenmiş','meslekten çıkarma cezası verilebilir.',[],'SG personeli, Türk karasuları dışında da'),
 # m.11 — geçici kontrol altına alma
 ('11','gorev_yetki','emri altındakileri','zarar, disiplin bozulması, sarhoşluk; operasyon-gemi komutanı','(1) Jandarma Genel Komutanlığının terörle','yetkilidir.',[],'terörle mücadele operasyonu, seyirdeki gemi ve bot'),
 ('11','sure','kontrol altına','alma: en çok yirmidört saat; oniki saati geçerse yakınlara-üste bilgi','(1) Jandarma Genel Komutanlığının terörle','en kısa sürede bilgi verilir.',[('10', 'm.10 metninin sonunda m.11 başlığı yer alır')],'altı saat DEĞİL'),
 ('11','sure','Kontrol altında bulundurma','yirmidört saati geçmez; operasyon komutanının uygun gördüğü yerde','(2) Kontrol altında bulundurma','geçmeyecek şekilde uygulanır.',[],'operasyon komutanının uygun gördüğü yerde'),
 ('11','sure','oniki saati','geçerse yakınlarına ve komutanın üstüne bilgi','(2) Kontrol altında bulundurma','en kısa sürede bilgi verilir.',[],''),
 ('11','ceza','cezanın üst sınırı','üst sınırdaysa ya da sınır yoksa bir üst ceza','(3) Kontrol altına alınanlarla','bir üst ceza uygulanır.',[],'kontrol altına alınanlara'),
 # m.12 — alışkanlık haline getirme
 ('12','sayi_oran','son bir yıl','yirmi puan ya da iki amirden oniki ceza: meslekten çıkarma','a) En son alınan disiplin cezasının','toplam oniki defa veya daha fazla disiplin cezası almak.',[],'BİR YIL: 20 PUAN / 12 CEZA'),
 ('12','sayi_oran','son beş yıl','kırk puan ya da iki amirden yirmibeş ceza','b) En son alınan disiplin cezasının','yirmibeş defa veya daha fazla disiplin cezası almak.',[],'BEŞ YIL: 40 PUAN / 25 CEZA'),
 ('12','makam','alışkanlık haline getirme','yetkili disiplin kurulu meslekten çıkarma verir','(1) Aşağıda belirtilen durumlar','yetkili disiplin kurullarınca verilir:',[('8','hastalığı abartmayı ya da borç ödememeyi alışkanlık edinmek ayrı fiiller')],''),
 ('12','kosul','Aynı disiplin dosyası','en yüksek cezanın puanı esas','(2) Aynı disiplin dosyası','değerlendirmeye esas alınır.',[],''),
 ('12','kosul','ceza puanlarının hesaplanması','Jandarma-Sahil Güvenlik (2), Emniyet (1) sayılı çizelge','(3) Birinci fıkra kapsamında','çizelgede gösterilmiştir.',[],''),
 ('12','kosul','sözleşmelerinin feshine','özel kanun hükümleri saklı','(4) Sözleşmeli personelin','hükümler saklıdır.',[],''),
 # m.13-15 — disiplin amirleri
 ('13','kosul','makam, rütbe veya kıdemce','büyük ve amir konumunda olmalı','(1) Disiplin amirinin, disiplin','amir konumunda bulunması gerekir.',[],'disiplin amirinin iki şartı'),
 ('13','makam','en üst disiplin amiri','kaymakam: ilçe, vali: il','(3) Kaymakamlar ilçe','en üst disiplin amiridir.',[],''),
 ('13','makam','bir üst disiplin amiri','vali kaymakama; Bakan valilere, Emniyet-Jandarma-Sahil Güvenlik başlarına','(3) Kaymakamlar ilçe','bir üst disiplin amiridir.',[('30', 'itiraz bir üst disiplin amirine yazılı yapılır')],''),
 ('13','makam','her rütbe ve derecedeki','disiplin amiri soruşturma açabilir','(4) Disiplin amirleri','soruşturması açabilir.',[],''),
 ('13','makam','cezası verme görev ve yetkisi','üst disiplin amirleri de kullanabilir','(5) Disiplin soruşturması yapma','tarafından da kullanılabilir.',[],''),
 ('13','sira_usul','teşkilat dışında görev','soruşturma görevli olduğu teşkilatta; dosya kendi teşkilatına','(6) Bakanlık merkez','kurullarına gönderilir.',[],''),
 ('14','sira_usul','Maiyetinde','öğrenen amir bizzat ya da yazılı görevlendireceği soruşturmacıyla soruşturur','(1) Maiyetinden birinin','disiplin soruşturması yapar.',[],'olayın araştırılması gerektiğine kanaat getirirse'),
 ('14','sira_usul','Disiplin soruşturmacısı olarak','üst/müfettiş; ast yalnız heyet üyesi; eş-hısım (boşanmış da) olamaz','(2) Disiplin soruşturmacısı olarak','soruşturmalarda görevlendirilemez.',[],'heyet başkanı ast OLAMAZ; mülki idare, emniyet sınıfı, JGK-SGK personeli dışından olmaz'),
 ('14','gorev_yetki','soruşturmacıları ve heyeti','ifade, tanık, bilirkişi, keşif; kriminal yalnız hâkim kararı gerekmezse','(3) Disiplin soruşturmacıları ve heyeti','yazışma yetkisini haizdir.',[('26','disiplin kurullarına da aynı inceleme yetkisi')],''),
 ('14','yasak','boşanmış','eş (boşanmış da), ikinci dereceye kadar kan-kayın hısım görevlendirilemez','(4) Disiplin soruşturmacısı olarak görevlendirilebileceği','soruşturmalarda görevlendirilemez.',[('15', 'disiplin amiri de eş-hısım hakkında yetki kullanamaz, üst amir kullanır')],''),
 ('15','makam','ikinci derece','disiplin amiri yetki kullanamaz, üst amir kullanır; soruşturmacı da olamaz','(3) Disiplin amirleri boşanmış','tarafından kullanılır.',[('14','soruşturmacı da eş-hısım hakkında görevlendirilemez')],'eş (boşanmış olsa da), kan ve kayın hısmı'),
 ('15','yasak','Disiplin amirliği yetkisi','devredilemez','(4) Disiplin amirliği yetkisi','devredilemez.',[],''),
 ('15','makam','vekâleten','disiplin amiri yetkilerini kullanabilir','(2) Disiplin amiri olarak tayin','yetkileri kullanabilirler.',[],'ikinci ya da geçici görevle yürüten de'),
 # m.19-21 — jandarma disiplin kurulları
 ('19','makam','İl jandarma disiplin kurulu','vali yardımcısı başkan; hukuk, jandarma komutanı, personel-asayiş şube; tuğgeneral YOK','a) İl jandarma disiplin kurulu','şube müdüründen, oluşur.',[('20', 'il kurulu yüzbaşı ve altına çıkarma dışı ceza verir'), ('21', 'il kurulu kararını vali onaylar')],'il jandarma komutanı ya da yardımcısı; Merkez kurulunun başkanı tuğgeneral'),
 ('19','makam','Merkez Disiplin Kurulu','en az tuğgeneral başkan','ç) (Değişik:18/10/2018-7148/39 md.) Jandarma Genel Komutanlığı Merkez','başmüfettişten oluşur.',[('20','Merkez kurulu binbaşı-yarbaya çıkarma dışı ceza verir'),('21','Merkez kurulu kararını Genel Komutan onaylar')],'Tayin Daire Başkanı, bir daire başkanı, şube müdürü, başmüfettiş'),
 ('19','makam','Jandarma Genel Komutanlığı Yüksek','Genel Komutan ya da yardımcısı başkan','d) (Değişik:18/10/2018-7148/39 md.) Jandarma Genel Komutanlığı Yüksek','bir başkandan oluşur.',[('20','Yüksek kurul binbaşı-yarbaya meslekten çıkarma verir'),('21','Yüksek kurul kararlarını Bakan onaylar')],'Personel, Teftiş Kurulu, Hukuk Hizmetleri başkanları'),
 ('19','kosul','Astsubayların disiplin işleri','kıdemli astsubay üye; yoksa sonraki en kıdemli; Yüksek kurullar hariç','(2) Astsubayların disiplin işlerinin','üye olarak görevlendirilir.',[],'Bakanlık Yüksek DK ve JGK Yüksek DK’da aranmaz'),
 ('19','makam','Akademisi Disiplin Kurulu','çıkarma dışı Müsteşar, çıkarma Bakan onayı','Jandarma ve Sahil Güvenlik Akademisi Disiplin Kurulunun','Bakanın onayıyla kesinleşir.',[],''),
 ('20','gorev_yetki','yüzbaşı','meslekten ve memurluktan çıkarma dışı cezalar','a) İl jandarma disiplin kurulu il jandarma','dışında kalan diğer disiplin cezalarını,',[],'il kurulu; uzman erbaş-sözleşmeli ere memurluktan çıkarma dışı hepsi'),
 ('20','gorev_yetki','binbaşı ve yarbay','meslekten çıkarmayı Jandarma Genel Komutanlığı Yüksek Disiplin Kurulu verir','d) Jandarma Genel Komutanlığı Yüksek Disiplin Kurulu;','subaylara meslekten çıkarma cezasını,',[],'diğer cezaları Merkez kurulu'),
 ('20','gorev_yetki','Albay rütbesindeki','meslekten çıkarmayı Bakanlık Yüksek Disiplin Kurulu verir','(2) Genel Komutanlık merkez teşkilatı','vermeye Bakanlık Yüksek Disiplin Kurulu yetkilidir.',[],''),
 ('20','gorev_yetki','Generaller','tüm cezaları Bakanlık Yüksek Disiplin Kurulu verir','(2) Genel Komutanlık merkez teşkilatı','vermeye Bakanlık Yüksek Disiplin Kurulu yetkilidir.',[],''),
 ('21','makam','dışındaki kararları','il kurulu: valinin; diğer kurullar: Genel Komutanın onayı','(1) Jandarma teşkilatı disiplin kurullarınca','meslekten çıkarma cezası dışındaki kararları Jandarma Genel Komutanının onayıyla,',[('19','Akademi kurulunun çıkarma dışı kararı Müsteşar onayıyla')],'meslekten çıkarmada: Yüksek DK uygun görüşü + Bakan onayı'),
 ('21','makam','Yüksek Disiplin Kurulunun kararları','Bakan onayıyla kesinleşir','c) Genel Komutanlık Yüksek Disiplin Kurulunun','Bakanın onayıyla, kesinleşir.',[],''),
 ('21','makam','uygun görülmeyen','kararlar: Bakanlık Yüksek Disiplin Kurulu kesin karar verir','(3) İl jandarma disiplin kurulunca','kesin karara bağlanır.',[('19', 'm.19 dipnotunda da: Bakanın uygun görmediği kararlar')],'valinin uygun görmediği il kurulu kararı JGK Yüksek DK’ya'),
 # m.26-28 — kurul usulü, kararlar, görevden uzaklaştırma
 ('26','kosul','disiplin kurulunun saptanmasında','fiili işlediği tarihte çalıştığı yer','MADDE 26- (1) (Değişik:18/10/2018-7148/42 md.) Disiplin','çalıştığı yer esas alınır.',[],''),
 ('26','kosul','Ast memur ile üst memurun','üst memura yetkili kurul','Ast memur ile üst memurun','yetkili disiplin kuruludur.',[],''),
 ('26','sira_usul','salt çoğunluk','oy çokluğu; çekimser yok; eşitlikte başkanın oyu','(8) Disiplin kurulları salt','karar alınmış sayılır.',[],''),
 ('26','sira_usul','Oyların eşit','başkanın oyu yönünde','(8) Disiplin kurulları salt','karar alınmış sayılır.',[],''),
 ('27','kosul','soruşturma sonucunda','ceza, ceza yok, karar yok, yetkisizlik; görevden uzaklaştırma DEĞİL','(1) Disiplin kurulu, soruşturma','karar verebilir.',[],'başka disiplinsizlik çıkarsa ona uygun ceza'),
 ('27','sira_usul','gerekçeli olarak yazılır','başkan-üyeler imzalar, tebliğ edilir','(3) Disiplin kurulu kararları','ilgililere tebliğ edilir.',[],''),
 ('28','kosul','görevden uzaklaştırma','657 uygulanır; ceza hafifleyince derhal kaldırılır','(1) Disiplin soruşturması nedeniyle','derhal kaldırılır.',[('27','m.27 metninin sonunda bu maddenin başlığı yer alır')],'çıkarma cezası alan, onaylanana kadar uzaklaştırılabilir'),
 # m.29 — zamanaşımı
 ('29','sure','öğrenildiği tarihten','itibaren uyarma-durdurma bir ay, çıkarmalar altı ay içinde soruşturma','(1) Bu Kanunda sayılan fiilleri','zamanaşımına uğrar.',[],'ÖĞRENMEDEN: HAFİF BİR AY, ÇIKARMA ALTI AY'),
 ('29','sure','işlendiği tarihten itibaren','iki yıl içinde ceza verilmeli','(2) Disiplin cezasını gerektiren','zamanaşımına uğrar.',[],'fiilden itibaren'),
 ('29','kosul','işlemeye başlar','tamamlanmış: işlendiği; kesintisiz: kesinti; zincirleme: son suç','(3) Zamanaşımı, tamamlanmış','işlemeye başlar.',[],'zincirlemede ilk suç DEĞİL'),
 ('29','sure','şekil noksanlığı','nedeniyle iptalde tebliğden itibaren altı ay içinde yeniden değerlendirme','(Yeniden Düzenleme:21/11/2024-7533/40 md.) Fiilin','yeniden değerlendirme yapar.',[],'hatalı vasıflandırma ya da şekil noksanlığıyla iptal'),
 # m.30 — itiraz
 ('30','sure','itiraz','tebliğden on gün içinde bir üst amire, yazılı','(1) Disiplin amirleri tarafından verilen','bir üst disiplin amirine yazılı olarak yapılır.',[('6','itiraz kararları takdir hakkını kaldırabilir'),('8','amire itiraz uyarma; fikrini savunmak disiplinsizlik değil'),('29','m.29 metninin sonunda bu maddenin başlığı yer alır')],'süresinde itiraz edilmeyen kesinleşir'),
 ('30','makam','kaymakam','doğrudan verdiği cezaya valiye itiraz','Kaymakamın doğrudan verdiği','valiye itiraz edilir.',[('13','kaymakam ilçede en üst disiplin amiri')],''),
 ('30','makam','doğrudan verdikleri','Bakanlık Yüksek Disiplin Kuruluna; karar kesin','Ancak vali, Emniyet Genel Müdürü','Kurulun verdiği karar kesindir.',[],'vali, EGM, Genel Komutan, SG Komutanı'),
 ('30','sure','yetkili merci tarafından','otuz gün içinde karara bağlanır','(2) İtiraz, yetkili merci','karara bağlanır.',[],'İTİRAZ ON GÜN, KARAR OTUZ GÜN'),
 ('30','yasak','İtiraz üzerine','önceki cezadan ağır ceza verilemez; hafifletilebilir, kaldırılabilir','(3) İtiraz haklı görülürse','daha ağır ceza verilemez.',[('6','itiraz kararları takdir hakkını kaldırabilir')],''),
 ('30','kosul','Bakan ile disiplin kurullarının','yalnız idari yargı','(5) Bakan ile disiplin','başvurulabilir.',[],''),
 # m.31 — savunma
 ('31','sure','savunma','alınmadan ceza verilemez; en az yedi gün süre; yapmayan vazgeçmiş','(1) Disiplin amirleri veya disiplin kurulları tarafından savunma','vazgeçmiş sayılır.',[('8', 'emre itirazda fikrini savunmak disiplinsizlik değil'), ('30', 'm.30 metninin sonunda bu maddenin başlığı yer alır')],''),
 ('31','makam','savunma istenir','disiplin amiri, kurul başkanı ya da görevlendirdiği üye','(2) Disiplin amirince','ilgiliden savunma istenir.',[],''),
 ('31','kosul','soruşturma evrakını inceleme','savunma istenmesinden itibaren','(3) Hakkında disiplin soruşturması','inceleme hakkına sahiptir.',[],''),
 ('31','kosul','istenen personel','evrak inceleme, tanık dinletme, vekille sözlü-yazılı savunma','(4) Hakkında meslekten çıkarma','savunma yapma hakkına sahiptir.',[],'çıkarma cezası istenen'),
 # m.32-34 — yargı denetimi, infaz, uygulanacak hükümler
 ('32','kosul','Kesinleşen disiplin cezalarına','iptal davası; süre tebliğden başlar','(1) Kesinleşen disiplin','tebliğinden itibaren başlar.',[],''),
 ('32','sure','açma süresi','kesinleşen cezanın personele tebliğinden başlar','(2) Dava açma süresi','tebliğinden itibaren başlar.',[],'gemi-botta verilen cezada üsse-limana dönüşle'),
 ('32','sure','seyir halindeki gemi','dava süresi üsse-limana dönüşle başlar','Ancak Sahil Güvenlik Komutanlığının seyir','dönmesiyle başlar.',[('11','seyirdeki gemide komutan geçici kontrol altına alabilir')],''),
 ('33','sure','Disiplin cezaları,','kesinleşmesini müteakip','(1) Disiplin cezaları, kesinleşmesini','yerine getirilir.',[('34','657’deki kademe durdurma JGK-SGK’da m.8/7’ye göre yerine getirilir')],'kesinleşmeden önce DEĞİL'),
 ('33','sure','Aylıktan kesme cezası,','kesinleşmeyi takip eden aybaşında','(2) Aylıktan kesme cezası,','aybaşında uygulanır.',[],''),
 ('33','makam','üst disiplin amirine','çıkarma cezaları ayrıca Devlet Personel Başkanlığına','(3) Verilen disiplin cezaları','Devlet Personel Başkanlığına bildirilir.',[('30','itiraz bir üst disiplin amirine yazılı yapılır')],'tüm cezalar üst disiplin amirine'),
 ('34','kosul','kademe ilerlemesinin durdurulması','uzun süreli durdurma sayılır','(2) 657 sayılı Kanundaki','telakki edilir ve uygulanır.',[],''),
 ('34','kosul','hüküm bulunmayan hallerde','657’nin disiplin hükümleri','(1) Bu Kanunda hüküm','hükümleri uygulanır.',[],''),
]
yaz(12, "7068 sayılı Genel Kolluk Disiplin Hükümleri Hakkında KHK'nın Kabul Edilmesine Dair Kanun", K)
