# 7068 Genel Kolluk Disiplin Hükümleri — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('4','kosul','ağır olan disiplin cezası verilir','bir fiil birden fazla disiplinsizlikse','(3) Bir fiilin birden fazla','ağır olan disiplin cezası verilir.',[],'disiplinsizlik kasten de taksirle de olur'),
 ('4','kosul','birden fazlası verilemez','aynı fiile iki disiplin cezası yok','(2) Aynı fiil nedeniyle','birden fazlası verilemez.',[],''),
 ('4','kosul','idari yaptırıma bağlanmış olması','ayrıca disiplin cezasına engel değil','(4) Bir fiilin diğer kanunlar','engel teşkil etmez.',[],''),
 ('5','kosul','aynı fiilden dolayı ayrıca disiplin','adli soruşturma/kovuşturma disiplin cezasını engellemez','(1) Herhangi bir fiilden','engellemez.',[],''),
 ('6','kosul','mutlaka gerekçeli','takdir hakkı; ölçülü, adaletli, hakkaniyetli','(2) Takdir hakkı mutlaka','gerekçeli olarak kullanılır.',[],''),
 ('6','kosul','samimi ikrarı ve gösterdiği pişmanlık','takdirde göz önüne alınır','f) Disiplinsizlik yapan personelin samimi','gözönüne alınır.',[],'işleniş biçimi, zaman-yer, hizmete etki, zarar, kusur, önceki disiplin durumu da'),
 ('7','tanim','daha dikkatli olması gerektiğinin','uyarma cezası (yazı ile)','a) Uyarma cezası','yazı ile bildirilmesidir.',[('7','kınama: kusurlu olduğunun yazıyla bildirilmesi')],''),
 ('7','tanim','kusurlu olduğunun yazı ile','kınama cezası','b) Kınama cezası','yazı ile bildirilmesidir.',[],'UYARMA = DİKKATLİ OL, KINAMA = KUSURLUSUN'),
 ('7','sayi_oran','onbeş günlüğe kadar kesinti','aylıktan kesme; brüt aylıktan, zam ve tazminat hariç','c) Aylıktan kesme cezası','kuruşlar dikkate alınmaz.',[],'tam lira üzerinden'),
 ('7','sure','dört, altı veya on ay','kısa süreli durdurma','ç) Kısa süreli durdurma','durdurulmasıdır.',[],''),
 ('7','sure','oniki, onaltı, yirmi veya yirmidört','uzun süreli durdurma','d) Uzun süreli durdurma','durdurulmasıdır.',[],'KISA 4-6-10, UZUN 12-16-20-24'),
 ('7','tanim','bir daha çalıştırılmamak üzere','meslekten çıkarma (emniyet, jandarma, sahil güvenlik)','e) Meslekten çıkarma','meslekten çıkarılmasıdır.',[],'Devlet memurluğundan çıkarma: bir daha memurluğa atanmamak üzere'),
 ('7','kosul','bir derece hafif olanı','iyi/çok iyi değerlendirme puanı alana uygulanabilir','(2) Kurumda geçmiş','uygulanabilir.',[],''),
 ('7','sure','özlük dosyasından silinmesini','uyarma-kınama beş, diğerleri on yıl sonra; atamaya yetkili amire','(5) Devlet memurluğundan çıkarma ya da','özlük dosyasından silinir.',[],''),
 ('8','ceza','alenen eleştirmek','uyarma; amiri alenen eleştirmek, itiraz','g) Usulüne uygun olarak kendisine','disiplinsizlik teşkil etmez.).',[],'karar verilene kadar fikrini savunmak disiplinsizlik değil'),
 ('8','ceza','Nezaket kurallarına aykırı','uyarma; nezaket kurallarına aykırılık','e) Nezaket','davranışlarda bulunmak.',[],''),
 ('8','ceza','mesaiye geç gelmek','uyarma; özürsüz mesaiye geç gelmek, erken ayrılmak','d) Özürsüz veya izinsiz olarak mesaiye','riayet etmemek.',[],''),
 ('8','ceza','yüzük, bilezik, kolye','kınama; yüzük, bilezik, kolye takmak','d) Mevzuat veya talimatlarla taşınmasına','benzeri şeyleri takmak.',[],''),
 ('8','ceza','Nöbeti teslimden sonra','kınama; nöbet sonrası görev yerine geç dönmek','c) Nöbeti teslimden','geç dönmek.',[],''),
 ('8','ceza','demirbaş tabancanın üzerinde','kınama; demirbaş tabancayı boyamak, gravür','ğ) Zati demirbaş','değişiklikler yapmak.',[],''),
 ('8','ceza','eksik kuşam ve teçhizatla','üç güne kadar aylıktan kesme; eksik kuşam','a) Üç günlüğe kadar aylıktan kesme','eksik kuşam ve teçhizatla göreve çıkmak.',[],''),
 ('8','ceza','yirmidört saate kadar göreve gelmemek','üç güne kadar aylıktan kesme; göreve gelmemek','4) İzinsiz veya kurumunca kabul edilebilir bir özrü','göreve gelmemek.',[],''),
 ('8','ceza','kahvehane, kıraathane','resmi kıyafetle oturmak: üç güne kadar aylıktan kesme','7) Görevli bulunduğu sırada','benzeri yerlerde oturmak.',[],''),
 ('8','ceza','il sınırları dışına çıkmak','amirinden izin almadan: üç güne kadar aylıktan kesme','8) Amirinden izin almaksızın','dışına çıkmak.',[],''),
 ('8','ceza','personel kimlik kartını','kaybetmek: üç güne kadar aylıktan kesme','10) Kendisine verilmiş olan personel','kaybetmek.',[],''),
 ('8','ceza','hastalığını abartmak','hastalığı abartmak: üç güne kadar aylıktan kesme','11) Bazı isteklerini','alışkanlık haline getirmek.',[],''),
 ('8','ceza','Selamlama ile ilgili','kurallara uymama: üç güne kadar aylıktan kesme','15) Selamlama','riayet etmemek.',[],'protokol kuralları, kılık kıyafet de'),
 ('8','ceza','onur kırıcı söz','dört ila on gün aylıktan kesme; onur kırıcı söz','b) Dört ila on günlüğe','onur kırıcı söz söylemek',[],'aynı rütbedekilere, astlara, mesai arkadaşlarına'),
 ('9','ceza','İşkence yapmak','Devlet memurluğundan çıkarma','(1) Devlet memurluğundan çıkarma cezası uygulanacak','İşkence yapmak.',[],'bölücü faaliyet de; diğer haller 657'),
 ('10','ceza','Silahla ölüme sebebiyet','meslekten çıkarma verilebilir (ağırlaştırıcı)','(5) Silahla ölüme','meslekten çıkarma cezası verilebilir.',[],''),
 ('10','ceza','Görevde uyumak','Devlet/kişi zarar görmüşse meslekten çıkarma','(8) Görevde uyumak','uygulanabilir.',[],''),
 ('10','ceza','Denetleme ve soruşturma görevlerini savsaklamak','zarar varsa dört ay kısa süreli durdurma','(12) Denetleme ve soruşturma','uygulanabilir.',[],''),
 ('10','ceza','yurtdışı liman ziyaretlerinde','sahil güvenlik personeli: bir üst ceza türü','(13) Bu Kanunda belirlenmiş','meslekten çıkarma cezası verilebilir.',[],'Türk karasuları dışında da'),
 ('11','gorev_yetki','geçici olarak kontrol altına almaya','operasyon komutanı, gemi komutanı; zarar, disiplin bozulması, sarhoşluk','(1) Jandarma Genel Komutanlığının terörle','yetkilidir.',[],''),
 ('11','sure','yirmidört saati geçmeyecek','kontrol altında bulundurma süresi','(2) Kontrol altında bulundurma','en kısa sürede bilgi verilir.',[],''),
 ('11','sure','oniki saati geçmesi','yakınlarına ve komutanın üstüne bilgi','(2) Kontrol altında bulundurma','en kısa sürede bilgi verilir.',[],'KONTROL EN ÇOK 24 SAAT, 12 SAATTE HABER'),
 ('12','sayi_oran','yirmi disiplin cezası puanı','son bir yılda; ya da iki amirden oniki ceza','a) En son alınan disiplin cezasının kesinleştiği tarihten geriye doğru son bir yıl','disiplin cezası almak.',[],'meslekten çıkarma; disiplin kurulu verir'),
 ('12','sayi_oran','kırk disiplin cezası puanı','son beş yılda; ya da yirmibeş ceza: meslekten çıkarma','b) En son alınan','disiplin cezası almak.',[],'BİR YIL: 20 PUAN / 12 CEZA · BEŞ YIL: 40 PUAN / 25 CEZA'),
 ('13','makam','en üst disiplin amiridir','kaymakam ilçede, vali ilde','(3) Kaymakamlar ilçe','bir üst disiplin amiridir.',[],''),
 ('13','makam','bir üst disiplin amiridir','vali kaymakama; Bakan EGM, JGK, SGK ve valilere','(3) Kaymakamlar ilçe','bir üst disiplin amiridir.',[],''),
 ('13','sira_usul','fiilen görevli olduğu teşkilat bünyesinde','teşkilat dışında görevlendirilenin soruşturması; dosya kendi teşkilatına','(6) Bakanlık merkez','kurullarına gönderilir.',[],''),
 ('14','sira_usul','heyet başkanı hariç olmak üzere','soruşturma heyetine ast üye konabilir','Ancak gerek görülmesi halinde','görevlendirilebilir.',[],'soruşturmacı kural olarak üst konumunda ya da müfettiş'),
 ('14','gorev_yetki','kriminal inceleme yaptırma','soruşturmacının yetkisi (hâkim/savcı kararı gerektirmeyen)','(3) Disiplin soruşturmacıları ve heyeti','yazışma yetkisini haizdir.',[('26', 'disiplin kurullarının yetkileri, aynı ifade')],'ifade alma, tanık, bilirkişi, keşif de'),
 ('15','kosul','bu sıfatlarından doğan yetkilerini kullanamazlar','disiplin amiri yetki kullanamaz; üst amir kullanır','(3) Disiplin amirleri boşanmış','tarafından kullanılır.',[],'eş (boşanmış olsa da), ikinci dereceye kadar hısım'),
 ('15','yasak','yetkisi devredilemez','disiplin amirliği','(4) Disiplin amirliği','devredilemez.',[],'vekâleten, ikinci ve geçici görevle yürütenler kullanabilir'),
 ('19','makam','vali yardımcısının başkanlığında','il jandarma disiplin kurulu','a) İl jandarma disiplin kurulu, vali','vali yardımcısının başkanlığında,',[],'hukuk işleri müdürü, il jandarma komutanı, personel ve asayiş şube müdürleri'),
 ('19','makam','en az tuğgeneral rütbesini','JGK Merkez Disiplin Kurulu başkanı','ç) (Değişik:18/10/2018-7148/39 md.) Jandarma Genel Komutanlığı Merkez','başmüfettişten oluşur.',[],''),
 ('19','makam','jandarma genel komutan yardımcısının başkanlığında','JGK Yüksek Disiplin Kurulu; Personel, Teftiş, Hukuk başkanları','d) (Değişik:18/10/2018-7148/39 md.) Jandarma Genel Komutanlığı Yüksek','bir başkandan oluşur.',[],'Jandarma Genel Komutanı da başkanlık edebilir'),
 ('19','kosul','en kıdemli astsubay üye olarak','astsubayın disiplin işinde kıdemli astsubay üye bulunur (Yüksek DK hariç)','Hakkında disiplin soruşturması yapılandan daha kıdemli bir astsubay yok ise','üye olarak görevlendirilir.',[],''),
 ('20','gorev_yetki','Yüzbaşı ve altı rütbelerdeki','il/kurum disiplin kurulları: çıkarma cezaları dışındakiler','a) İl jandarma disiplin kurulu il jandarma','diğer disiplin cezalarını,',[],'uzman erbaş, sözleşmeli erbaş-ere memurluktan çıkarma dışındakiler'),
 ('20','gorev_yetki','albay rütbesinde bulunanlara','JGK Yüksek Disiplin Kurulu: çıkarma cezaları dışındaki cezalar','2) Genel Komutanlık merkez teşkilatı, asayiş kolordu','dışında kalan disiplin cezalarını,',[],'binbaşı-yarbaya meslekten çıkarma da YDK'),
 ('20','gorev_yetki','Generaller hakkında tüm disiplin cezalarını','Bakanlık Yüksek Disiplin Kurulu; albaya meslekten çıkarma da','a) Albay rütbesindeki personele','Bakanlık Yüksek Disiplin Kurulu yetkilidir.',[],''),
 ('21','makam','valinin onayıyla','il jandarma disiplin kurulunun meslekten çıkarma dışındaki kararları kesinleşir','a) İl jandarma disiplin kurulunun','Bakanın onayıyla,',[],''),
 ('21','makam','valinin önerisi','il JDK meslekten çıkarma: YDK uygun görüşü + Bakan onayı','a) İl jandarma disiplin kurulunun','Bakanın onayıyla,',[],''),
 ('21','makam','Jandarma Genel Komutanının onayıyla','kurum, kolordu, Merkez DK kararları (meslekten çıkarma dışı)','b) Asayiş kolordu komutanlıkları, komando tugay komutanlıkları, komando alay komutanlıkları, Jandarma Komando Özel Asayiş ve Kurtarma Tugay Komutanlığı, eğitim tugay ve birlik komutanlıkları disiplin kurulu, Genel','Bakanın onayıyla,',[],'meslekten çıkarma: YDK uygun görüşü + Bakan onayı; YDK kararları Bakan onayıyla'),
 ('21','makam','Kurulunca kesin karara','Bakan/JGK/YDK\'nın uygun görmediği dosyalar','(2) Birinci fıkra kapsamında','kesin karara bağlanır.',[],''),
 ('27','sira_usul','kurulun yetkisizliğine','disiplin kurulu karar türlerinden; gerekçeli yazılır','(1) Disiplin kurulu, soruşturma','karar verebilir.',[],'ceza yok, karar yok, ceza, yetkisizlik'),
 ('28','kosul','görevden uzaklaştırma önlemi derhal kaldırılır','meslekten çıkarma hafif cezaya indirilince','(2) Disiplin kurullarınca haklarında','derhal kaldırılır.',[],'uzaklaştırmada 657 uygulanır'),
 ('29','sure','bir ay içinde','uyarma–durdurma cezalarında soruşturmaya başlama (öğrenmeden)','a) Uyarma, kınama, aylıktan kesme','zamanaşımına uğrar.',[],'ÖĞRENMEDEN: HAFİF BİR AY, ÇIKARMA ALTI AY'),
 ('29','sure','altı ay içinde','çıkarma cezalarında soruşturmaya başlama; mahkeme iptalinde yeniden değerlendirme de','a) Uyarma, kınama, aylıktan kesme','zamanaşımına uğrar.',[],''),
 ('29','sure','iki yıl içinde disiplin cezası','ceza verme yetkisi zamanaşımına uğrar (fiil tarihinden)','(2) Disiplin cezasını gerektiren fiillerin','zamanaşımına uğrar.',[],'kesintisizde kesinti, zincirlemede son suç tarihinden'),
 ('30','sure','on gün içinde itiraz','disiplin amiri cezasına; bir üst amire yazılı','(1) Disiplin amirleri tarafından verilen','Süresi içinde itiraz edilmeyen cezalar kesinleşir.',[],''),
 ('30','makam','Kaymakamın doğrudan verdiği','valiye itiraz','(1) Disiplin amirleri tarafından verilen','Süresi içinde itiraz edilmeyen cezalar kesinleşir.',[],'KAYMAKAMDAN VALİYE'),
 ('30','makam','Bakanlık Yüksek Disiplin Kuruluna itiraz','vali, EGM, JGK, SGK doğrudan cezaları; karar kesin','(1) Disiplin amirleri tarafından verilen','Süresi içinde itiraz edilmeyen cezalar kesinleşir.',[],''),
 ('30','sure','otuz gün içinde karara','itiraz mercii karar süresi','(2) İtiraz, yetkili merci','karara bağlanır.',[],'İTİRAZ ON GÜN, KARAR OTUZ GÜN'),
 ('30','yasak','daha ağır ceza verilemez','itiraz üzerine','(4) İtiraz üzerine','ceza verilemez.',[],'hafifletebilir ya da kaldırabilir'),
 ('30','kosul','ancak idari yargı yoluna','Bakan ve disiplin kurulu cezalarına itiraz yok','(5) Bakan ile disiplin','başvurulabilir.',[],''),
 ('31','sure','yedi günden az olamaz','savunma süresi','Savunma için verilen süre','vazgeçmiş sayılır.',[],'savunmasız ceza verilemez; süresinde yapmayan vazgeçmiş sayılır'),
 ('31','kosul','tanık dinletmeye','çıkarma cezası istenen personelin hakkı; vekille savunma','(4) Hakkında meslekten çıkarma','savunma yapma hakkına sahiptir.',[],''),
 ('32','sure','üsse veya limana dönmesiyle','seyirdeki gemide verilen cezada dava süresi başlar','Ancak Sahil Güvenlik Komutanlığının seyir','dönmesiyle başlar.',[],'normalde tebliğden'),
 ('33','sure','takip eden aybaşında','aylıktan kesme uygulanır (kesinleşme sonrası)','(2) Aylıktan kesme cezası, kesinleşme','aybaşında uygulanır.',[],''),
 ('33','makam','Devlet Personel Başkanlığına','meslekten/memurluktan çıkarma cezaları ayrıca bildirilir','(3) Verilen disiplin cezaları','Devlet Personel Başkanlığına bildirilir.',[],''),
 ('34','kosul','uzun süreli durdurma cezası gibi','657\'deki kademe ilerlemesinin durdurulması','(2) 657 sayılı Kanundaki','telakki edilir ve uygulanır.',[],'boşlukta 657 disiplin hükümleri'),
 ('8', 'ceza', 'usul ve kurallara riayet etmeden', 'kınama; usulsüz sözlü, yazılı veya elektronik müracaat/şikâyet', '(2) Kınama cezasını gerektiren fiiller', 'müracaat veya şikâyette bulunmak.', [], ''),
 ('4', 'kosul', 'kasten veya taksirle oluşabilir', 'aynı fiile birden fazla ceza verilemez; idari yaptırım engel değil', '(1) Disiplinsizlik kasten veya taksirle', 'engel teşkil etmez.', [], ''),
 ('6', 'kosul', 'ölçülü, adaletli ve hakkaniyetli', 'takdir hakkı; mutlaka gerekçeli; işleniş, zaman-yer, zarar, kusur, geçmiş, pişmanlık', '(1) Bu Kanun ile disiplin cezası vermeye yetkilendirilen', 'pişmanlık, gözönüne alınır.', [], ''),
 ('7', 'ceza', 'onbeş günlüğe kadar kesinti', 'aylıktan kesme: zam-tazminat hariç brüt aylıktan; tam lira', 'c) Aylıktan kesme cezası: Disiplin', 'kuruşlar dikkate alınmaz.', [], ''),
 ('7', 'tanim', 'memurluktan çıkarılmasıdır', 'ceza türleri: uyarma, kınama, aylıktan kesme, durdurma (kısa/uzun), meslekten/memurluktan çıkarma', 'f) Devlet memurluğundan çıkarma', 'memurluktan çıkarılmasıdır.', [], 'görevden uzaklaştırma ceza değil, tedbir'),
 ('7', 'kosul', 'bir derece hafif olanı uygulanabilir', 'iyi/çok iyi değerlendirme puanlı, geçmişi olumlu personele', '(2) Kurumda geçmiş hizmetleri sırasında', 'hafif olanı uygulanabilir.', [], ''),
 ('7', 'sure', 'özlük dosyasından silinmesini isteyebilir', 'uyarma-kınama beş yıl, diğerleri on yıl özlük dosyasından silinme istenebilir', '(5) Devlet memurluğundan çıkarma ya da meslekten', 'özlük dosyasından silinir.', [], 'atamaya yetkili amire başvuru'),
 ('10', 'ceza', 'emrinin yapılmaması fiilinin neticesinde', 'zarar/gecikme/durma doğmuşsa meslekten çıkarma uygulanabilir (ağırlaştırıcı)', '(1) Amirin emrinin yapılmaması', 'meslekten çıkarma cezası uygulanabilir.', [], ''),
 ('10', 'ceza', 'Denetleme ve soruşturma görevlerini savsaklamak', 'zarar/gecikme doğurmuşsa dört ay kısa süreli durdurma', '(12) Denetleme ve soruşturma görevlerini', 'kısa süreli durdurma cezası uygulanabilir.', [], ''),
 ('10', 'ceza', 'yurtdışı liman ziyaretlerinde', 'sahil güvenlik personelinin fiilinde ceza bir kademe ağırlaşabilir (karasuları dışında)', '(13) Bu Kanunda belirlenmiş ve bir disiplin', 'meslekten çıkarma cezası verilebilir.', [], ''),
 ('12', 'kosul', 'iki farklı disiplin amirinden', 'alışkanlık: bir yılda oniki, beş yılda yirmibeş ceza; meslekten çıkarma', 'a) En son alınan disiplin cezasının kesinleştiği tarihten geriye doğru son bir yıl', 'yirmibeş defa veya daha fazla disiplin cezası almak.', [], 'puan eşiği: yirmi / kırk'),
 ('12', 'kosul', 'en yüksek olanın puanı', 'aynı disiplin dosyasında birden fazla ceza; değerlendirmeye esas', '(2) Aynı disiplin dosyası kapsamında', 'değerlendirmeye esas alınır.', [], ''),
 ('12', 'kosul', 'ekli (2) sayılı çizelgede', 'JGK-SGK personelinin ceza puanı hesabı (EGM: (1) sayılı çizelge)', '(3) Birinci fıkra kapsamında ceza puanlarının', 'çizelgede gösterilmiştir.', [], 'uyarma 1 puan'),
 ('12', 'kosul', 'sözleşmelerinin feshine ilişkin özel', 'sözleşmeli personelin fesih hükümleri saklı', '(4) Sözleşmeli personelin sözleşmelerinin', 'hükümler saklıdır.', [], ''),
 ('13', 'kosul', 'rütbe veya kıdemce büyük olması', 'disiplin amiri şartı; amir konumunda bulunmalı', '(1) Disiplin amirinin, disiplin cezası', 'amir konumunda bulunması gerekir.', [], ''),
 ('13', 'makam', 'en üst disiplin amiridir', 'kaymakam ilçede, vali ilde; Bakan EGM-JGK-SGK ve valilere göre üst', '(3) Kaymakamlar ilçe, valiler il', 'bir üst disiplin amiridir.', [], ''),
 ('13', 'makam', 'amirleri tarafından da kullanılabilir', 'disiplin soruşturması yapma ve ceza verme yetkisi (üst disiplin amirleri)', '(5) Disiplin soruşturması yapma', 'tarafından da kullanılabilir.', [], ''),
 ('14', 'makam', 'kişinin üstü konumundaki bir', 'soruşturmacı; müfettiş de; heyet üyesi ast olabilir (başkan hariç)', '(2) Disiplin soruşturmacısı olarak hakkında', 'herhangi bir personel görevlendirilemez.', [], ''),
 ('14', 'gorev_yetki', 'bilirkişi görevlendirme, keşif yapma', 'soruşturmacı yetkileri: bilgi-belge toplama, ifade alma, tanık dinleme, kriminal inceleme', '(3) Disiplin soruşturmacıları ve heyeti', 'ilgili makamlarla yazışma yetkisini haizdir.', [], ''),
 ('14', 'yasak', 'kan ve kayın hısımları', 'hısım personelin soruşturmasında soruşturmacı görevlendirilemez (boşanmış eş dahil)', '(4) Disiplin soruşturmacısı olarak görevlendirilebileceği', 'soruşturmalarda görevlendirilemez.', [('15', 'disiplin amirinin hısımı: yetkiyi üst amir kullanır')], ''),
 ('15', 'makam', 'üst konumdaki disiplin amiri tarafından', 'eş/ikinci derece hısım personel hakkında disiplin amirliği yetkisini o kullanır', 'Bu hallerde, disiplin amirliği yetkisi', 'tarafından kullanılır.', [], ''),
 ('15', 'yasak', 'Disiplin amirliği yetkisi devredilemez', 'vekâleten/ikinci görevle/geçici görevle yürütenler yetkiyi kullanabilir; devir yok', '(2) Disiplin amiri olarak tayin edilen', 'yetkisi devredilemez.', [], ''),
 ('20', 'ceza', 'İl jandarma disiplin kurulu', 'il jandarma disiplin kurulu: yüzbaşı altı rütbeler; meslekten çıkarma veremez', 'a) İl jandarma disiplin kurulu il jandarma', 'kalan disiplin cezalarını,', [('19', 'kurulların oluşumu maddesi'), ('21', 'kararların kesinleşmesi: valinin onayı')], ''),
 ('20', 'ceza', 'binbaşı ve yarbay rütbelerindeki', 'JGK Yüksek Disiplin Kurulu meslekten çıkarma verir; albay: Bakanlık YDK', 'd) Jandarma Genel Komutanlığı Yüksek Disiplin Kurulu', 'subaylara meslekten çıkarma cezasını,', [], ''),
 ('27', 'kosul', 'kurulun yetkisizliğine karar verebilir', 'disiplin kurulu kararları: ceza; ceza/karar verilmesine yer olmadığı; yetkisizlik', '(1) Disiplin kurulu, soruşturma sonucunda', 'yetkisizliğine karar verebilir.', [], 'görevden uzaklaştırma kurul kararı değil'),
 ('29', 'sure', 'altı ay içinde', 'meslekten çıkarmada soruşturmaya başlama zamanaşımı; diğer cezalarda bir ay (öğrenmeden)', 'b) Meslekten çıkarma cezası ve Devlet', 'zamanaşımına uğrar.', [], 'ceza verme: fiilden itibaren iki yıl'),
 ('29', 'kosul', 'zincirleme suçlarda ise son suçun', 'zamanaşımı başlangıcı; tamamlanmış: işlendiği tarih; kesintisiz: kesintinin gerçekleştiği', '(3) Zamanaşımı, tamamlanmış suçlarda', 'itibaren işlemeye başlar.', [], ''),
 ('30', 'sure', 'on gün içinde itiraz edilebilir', 'disiplin amiri cezasına; üst disiplin amirine yazılı; otuz günde karar', '(1) Disiplin amirleri tarafından verilen disiplin cezalarına', 'otuz gün içinde karara bağlanır.', [], ''),
 ('30', 'makam', 'Kaymakamın doğrudan verdiği', 'disiplin cezasına valiye itiraz; süresinde itiraz edilmeyen kesinleşir', 'Kaymakamın doğrudan verdiği disiplin', 'edilmeyen cezalar kesinleşir.', [], ''),
 ('30', 'kosul', 'ancak idari yargı yoluna', 'Bakan ve disiplin kurullarının cezalarına karşı (itiraz yok)', '(5) Bakan ile disiplin kurullarının', 'idari yargı yoluna başvurulabilir.', [], ''),
 ('31', 'sure', 'yedi günden az olamaz', 'savunma süresi; savunma alınmadan ceza verilemez; süresinde yapmayan vazgeçmiş sayılır', 'Savunma için verilen süre yedi', 'vazgeçmiş sayılır.', [], ''),
 ('31', 'makam', 'görevlendireceği kurul üyelerinden biri', 'savunmayı disiplin amiri ya da kurul başkanı/üyesi ister', '(2) Disiplin amirince veya yetkili disiplin kurulu', 'ilgiliden savunma istenir.', [], ''),
 ('31', 'kosul', 'vekili vasıtasıyla savunma yapma', 'meslekten/memurluktan çıkarma istenen personel; tanık dinletme, evrak inceleme de', '(4) Hakkında meslekten çıkarma cezası', 'savunma yapma hakkına sahiptir.', [], ''),
 ('32', 'kosul', 'iptal davası açılabilir', 'kesinleşen disiplin cezasına; süre tebliğden başlar (SG gemide: üsse dönüşle)', '(1) Kesinleşen disiplin cezalarına karşı', 'üsse veya limana dönmesiyle başlar.', [], ''),
 ('8', 'ceza', 'sorumluluğu üstlenmekten imtina', 'kınama (tevdi edilen görevin gerektirdiği sorumluluk)', '(2) Kınama cezasını', 'imtina ettiğini gösterecek tavır ve davranışlarda bulunmak.', [], ''),
 ('8', 'ceza', 'dövme girişiminde bulunmak', 'dört ay kısa süreli durdurma (ast, aynı rütbe, mesai arkadaşı)', 'a) Dört ay kısa süreli durdurma', 'dövme girişiminde bulunmak.', [], ''),
 ('8', 'ceza', 'Toplu olarak sözlü veya yazılı', 'şikâyette bulunmak: dört ay kısa süreli durdurma', 'a) Dört ay kısa süreli durdurma', 'Toplu olarak sözlü veya yazılı şikâyette bulunmak.', [], ''),
 ('8', 'ceza', 'Kriptolu telsiz cihazının', 'kaybını/çalındığını mazeretsiz derhal bildirmemek: yirmidört ay uzun süreli durdurma', 'ç) Yirmidört ay uzun süreli durdurma', 'ilgili birime derhal bildirmemek.', [], ''),
 ('8', 'ceza', 'Yetkisini veya nüfuzunu kendisine', 'çıkar/kin-dostlukla kötüye kullanmak: meslekten çıkarma', '(6) Meslekten çıkarma cezasını', 'nedenlerle kötüye kullanmak.', [], ''),
 ('8', 'ceza', 'Kumar oynamak veya oynatmak', 'kumar oynatanlarla ilişki kurmak da: meslekten çıkarma', '(6) Meslekten çıkarma cezasını', 'kumar oynatanlarla ilişki kurmak.', [], 'üç sınavda da soruldu'),
 ('8', 'ceza', 'Kaçakçılık yapmak veya kaçakçılarla', 'ilişki kurmak: meslekten çıkarma', '(6) Meslekten çıkarma cezasını', 'kaçakçılarla ilişki kurmak.', [], ''),
]
yaz(12, "7068 sayılı Genel Kolluk Disiplin Hükümleri Hakkında KHK'nın Kabul Edilmesine Dair Kanun", K)
