# 4678 TSK'da İstihdam Edilecek Sözleşmeli Subay ve Astsubaylar Hakkında Kanun — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('3','tanim','nasıp onayı tarihine kadar','ön sözleşme; askerî eğitime alınma','a) (Değişik: 16/6/2009-5907/1 md.) Ön sözleşme','kapsayan sözleşmeyi,',[],''),
 ('3','sure','hizmet yükümlülüğü getiren','sözleşme: üç yıldan az, dokuz yıldan fazla olmayan','b) Sözleşme : Türk','yazılı bir belgeyi,',[],''),
 ('4','sure','otuziki yaşını','lisansüstü mezunu sözleşmeli subay adayı yaş sınırı; lisans yirmiyedi','Sözleşmeli subay kaynaklarını','bitirmemiş olanlar teşkil eder.',[],'ocak ayının ilk günü; düzeltilmemiş nüfus kaydı'),
 ('4','sayi_oran','% 85 veya daha üstünde','TSK\'da/yedek subaylıkta sicil şartı','Türk Silahlı Kuvvetlerinde istihdam edilenler ile yedek subay','olması şarttır.',[('8','sözleşmeli astsubayda da aynı % 85 şartı')],'sıralı üstlerden olumlu nitelik belgesi de'),
 ('4','yasak','Askeri hakim sınıfına','sözleşmeli subay alınmaz','Askeri hakim sınıfına','personel alınmaz.',[],'TSK\'dan ilişiği kesilenler de alınmaz'),
 ('6','kosul','teğmen rütbesine nasbedilirler','askerî eğitimi başarıyla bitiren sözleşmeli subay adayı','Madde 6 – Sözleşmeli subay adayları','teğmen rütbesine nasbedilirler.',[('10','astsubay adayı: astsubay çavuş')],''),
 ('6','kosul','talebe bakılmaksızın uzatılabilir','seferberlik, savaş, alıkonulma; MSB ya da İçişleri onayı','Sözleşme süreleri; terörle mücadele','talebe bakılmaksızın uzatılabilir.',[('10','sözleşmeli astsubayda aynı kural')],'Kuvvet, JGK, SGK komutanının lüzum göstermesiyle'),
 ('7','sure','yedinci fiilî hizmet yılı','muvazzaf subaylığa başvuru başlangıcı; onikinci yıl sonuna kadar','Muvazzaf subaylığa geçiş için','istifa edemezler.',[('11','astsubay dördüncü yıldan başvurur')],'SUBAY YEDİDE, ASTSUBAY DÖRTTE BAŞVURUR'),
 ('7','sure','onbeş yıl hizmet etmedikçe istifa','muvazzaf subaylığa geçenler','Muvazzaf subaylığa geçiş için','istifa edemezler.',[('11','astsubaylıkta da onbeş yıl')],'yaş şartı uygulanmaz'),
 ('8','sure','yirmidört yaşını','dört yıldan az yükseköğrenimli astsubay adayı; dört yıl+ yirmiyedi','(Değişik birinci fıkra: 26/6/2012-6336/21 md.) Sözleşmeli astsubay kaynaklarını','bulunanlar teşkil eder.',[],''),
 ('8','kosul','aynı şartları haiz uzman erbaşlardan','sözleşmeli astsubay kaynağı','(Değişik birinci fıkra: 26/6/2012-6336/21 md.) Sözleşmeli astsubay kaynaklarını','bulunanlar teşkil eder.',[],'kısa dönem/erbaş-er terhisliler de olabilir'),
 ('10','kosul','astsubay çavuş rütbesine','eğitimi bitiren sözleşmeli astsubay adayı','Madde 10 – Sözleşmeli astsubay adayları','astsubay çavuş rütbesine nasbedilirler.',[],''),
 ('11','sure','dördüncü fiilî hizmet yılı','muvazzaf astsubaylığa başvuru; onikinci yıl sonuna kadar','Muvazzaf astsubaylığa geçiş için','istifa edemezler.',[('7','subay yedinci yıldan')],''),
 ('12','sure','en az üç ay önce','sözleşme yenileme bildirimi; yoksa kendiliğinden sona erer','Her sözleşme süresinin sona erme','kendiliğinden sona erer.',[],''),
 ('12','yasak','tek taraflı olarak fesh edemezler','sözleşmeli subay/astsubay, süre dolmadan','Sözleşmeli subay veya astsubaylar, sözleşme süreleri','fesh edemezler.',[],''),
 ('12','sure','iki katı kadar','yurt dışı altı ay+ öğrenim/kurs: sözleşme uzar','Subay veya astsubay nasbedildikten sonra','geçen süreler kadar uzatılır.',[],'yurt içi TSK hesabına öğrenim: geçen süre kadar'),
 ('12','sure','sürelerin yarısı kadar uzatılır','yurt içi tıp/diş uzmanlığı, doktora','hekimliğinde veya eczacılıkta','yarısı kadar uzatılır.',[],'YURT DIŞI İKİ KAT, YURT İÇİ BİR KAT, UZMANLIK YARIM'),
 ('12','istisna','devlet hizmet yükümlülüğüne tâbi olmazlar','sözleşmeli tabip subaylar (sözleşmesi feshedilenler hariç)','Sözleşme süresi sona ermeden sözleşmesi fesih','başlayabilirler.',[],'TUS kazanan üç yıl kıt\'a hizmetinden sonra uzmanlığa'),
 ('13','kosul','üçte birine','askeri eğitime katılmama: ön sözleşme feshi; kazayla bir kez tekrar','d) Askeri eğitimin üçte birine','eğitime alınırlar.',[],''),
 ('13','ceza','bir ay ve daha fazla','hürriyeti bağlayıcı ceza: sözleşme feshi (taksirli hariç)','e) Taksirli suçlar hariç','mahkum olmak.',[],''),
 ('13','sayi_oran','toplam sekiz defa','iki amirden bir yılda: fesih; otuz gün oda hapsi de','f) (Değişik: 31/1/2013-6413/45 md.) Son olarak verilen','disiplin cezası almak.',[],''),
 ('13','kosul','Milli Savunma Bakanlığınca uygun görülmemek','yabancıyla evlilik: sözleşme feshi','ı) Yabancı uyruklu','Türk vatandaşlığından çıkarılmak.',[],'vatandaşlık kaybı da'),
 ('13','sure','doksan günü geçmek','bir sözleşme yılında sıhhi izin: fesih (kaza, kanser vb. hariç)','hariç olmak kaydıyla, bir sözleşme yılı','doksan günü geçmek.',[],''),
 ('15','sure','rütbe verilmeksizin bir üst dereceye','subay onbeşinci, astsubay onsekizinci yılda; sicil yüzde altmış','Sözleşmeli subaylardan onbeşinci','bir yılını tamamlamış olmak.',[],'derecede üç yıl, üçüncü kademede bir yıl'),
 ('16','sure','en çok on yılı','idarece yenilenmeyenlerin sağlık hakkı; hizmet süresi kadar','a) Kendi kusurları olmaksızın','en çok on yılı,',[],''),
 ('16','sure','en çok beş yılı','kendi isteğiyle yenilemeyenler; hizmetin yarısı kadar','b) Sözleşme süresi sonunda kendi','en çok beş yılı,',[],'İDARE YENİLEMEDİ ON, KENDİ İSTEMEDİ BEŞ'),
 ('16','sure','oniki ayı geçmemek üzere tedavi','sağlıktan sözleşmesi bitenlere net maaşın üçte ikisi yardım','Sözleşmeleri sağlık nedeniyle sona erenlerden','kurumlarınca ödeme yapılır.',[],''),
 ('3', 'tanim', 'yürürlüğe girdiği ay ve günü', 'sözleşme yılı: bu tarihten itibaren geçen her bir yıllık süre', 'Sözleşme yılı: Sözleşmenin yürürlüğe', 'her bir yıllık süreyi,', [], ''),
 ('3', 'tanim', 'teğmen, üsteğmen ve yüzbaşı rütbelerini', 'sözleşmeli subay (tanım); binbaşı yok', 'e) Sözleşmeli subay : Bu Kanunda', 'yüzbaşı rütbelerini haiz subayları,', [], 'astsubay: çavuş-kıdemli üstçavuş'),
 ('3', 'tanim', 'astsubay meslek yüksekokullarından mezun olan', 'emsal (sözleşmeli astsubay için); subay için harp okulu mezunu muvazzaflar', 'Emsal: Sözleşmeli subaylar için', 'mezun olan muvazzaf astsubayları,', [], ''),
 ('3', 'tanim', 'yapılarak askerî eğitime alınanları', 'sözleşmeli subay/astsubay adayı (tanım): ön sözleşme yapılmış', 'c) Sözleşmeli subay adayı', 'askerî eğitime alınanları,', [], ''),
 ('3', 'tanim', 'astsubaylık anlayışı kazandırma eğitimini', 'askeri eğitim (tanım): okul, kurum, sınıf okulu, kıta, eğitim merkezinde', 'Askeri eğitim: Sözleşmeli subay ve', 'anlayışı kazandırma eğitimini,', [], ''),
 ('4', 'sure', 'en az dört yıllık fakülte', 'sözleşmeli subay kaynağı; yirmiyedi yaş (lisansüstü otuziki); ocak başı ölçüt', 'Sözleşmeli subay kaynaklarını; en az dört', 'otuziki yaşını bitirmemiş olanlar teşkil eder.', [], ''),
 ('4', 'yasak', 'olursa olsun ilişikleri kesilen', 'sözleşmeli subay olarak alınmaz (askerlik yapan/terhis edilenler hariç)', 'Askeri okullardan ve Türk Silahlı Kuvvetlerinden her ne', 'sözleşmeli subay olabilirler.', [('8', 'astsubayda istisna: kısa dönem/1111 erbaş-er')], ''),
 ('4', 'kosul', 'öğrenim ile ilgili koşulları', 'genel nitelikler: vatandaşlık, öğrenim, sağlık, haklar, mahkûmiyetsizlik, güvenlik soruşturması, sınav', 'Sözleşmeli subaylık için genel olarak', 'g) Yapılacak olan sınavlarda başarılı olmak.', [('8', 'astsubay genel nitelikleri aynı liste')], ''),
 ('4', 'kosul', 'yalan yere yemin, suç uydurma', 'sözleşmeli subaylığa engel suçlar (ertelense de); taksirli suç listede yok', '1) Devletin güvenliğine karşı işlenen suçlar, halkı askerlikten soğutmak', 'devlet sırlarını açığa vurma suçlarından birisinden,', [('8', 'astsubay nitelikleri aynı liste'), ('13', 'fesih sebebi: aynı suçlardan mahkûm olmak')], ''),
 ('8', 'istisna', 'kısa dönem erbaş veya er', 'askerliğini böyle yapanlar/terhis edilenler sözleşmeli astsubay olabilir (ilişiği kesilenlerin istisnası)', 'Ancak, askerliğini 16/6/1927 tarihli ve 1076 sayılı', 'sözleşmeli astsubay olabilir.', [], ''),
 ('10', 'kosul', 'astsubay çavuş rütbesine nasbedilirler', 'askeri eğitimi başarıyla bitiren sözleşmeli astsubay adayı; sözleşme üç-dokuz yıl', 'Madde 10 – Sözleşmeli astsubay adayları', 'branşlara göre yönetmelikte belirlenir.', [], ''),
 ('10', 'makam', 'talebe bakılmaksızın uzatılabilir', 'seferberlik/savaş/silahlı çatışmada sözleşme; MSB veya İçişleri Bakanlığı onayı', 'seferberlik, savaş veya silahlı', 'talebe bakılmaksızın uzatılabilir.', [('6', 'subay sözleşme süreleri maddesi, aynı kural')], ''),
 ('12', 'kosul', 'kadro açığı bulunmadığı için', 'sözleşme sonuna kadar derece ilerlemesi yapar (terfi şartlarını haizse)', 'Sözleşmeli subaylardan üst rütbede kadro açığı', 'derece ilerlemesi yaparlar.', [], ''),
 ('12', 'sure', 'en az üç ay önce', 'yazılı yenileme bildirimi yoksa sözleşme kendiliğinden sona erer', 'sözleşme süresinin sona erme tarihinden en az üç ay', 'sözleşme kendiliğinden sona erer.', [], ''),
 ('12', 'sure', 'sürenin iki katı kadar', 'yurt dışına altı ay+ öğrenim/kurs: sözleşme uzar; yurt içi: süre', 'Subay veya astsubay nasbedildikten sonra; yabancı', 'buralarda geçen süreler kadar uzatılır.', [], ''),
 ('12', 'sure', 'aylıksız izin süresi kadar uzatılır', "926'ya göre aylıksız izin alan sözleşmelinin sözleşmesi", '926 sayılı Türk Silahlı Kuvvetleri Personel Kanunu hükümlerine göre aylıksız', 'izin süresi kadar uzatılır.', [], ''),
 ('13', 'kosul', 'daha fazla süreli hürriyeti bağlayıcı', 'bir ay+ mahkûmiyet fesih sebebi (taksirli suçlar hariç); yasadışı faaliyet', 'e) Taksirli suçlar hariç olmak üzere', 'benimsediği tespit edilmek.', [], ''),
 ('13', 'ceza', 'sekiz defa veya daha fazla', 'bir yılda iki disiplin amirinden ceza: fesih sebebi', 'Son olarak verilen de dahil olmak üzere', 'daha fazla disiplin cezası almak.', [], 'oda hapsi/hizmet yerini terk etmeme toplam otuz gün de'),
 ('13', 'sure', 'doksan günü geçmek', 'sözleşme yılında sıhhi izin toplamı; fesih sebebi (yatarak tedavi hariç)', '2) Kanser, tüberküloz, kronik böbrek', 'doksan günü geçmek.', [], 'görev kazası/meslek hastalığı da hariç'),
 ('13', 'kosul', 'Kanunu kapsamında malul olan', 'isteklilerin sözleşmeleri uzatılabilir (faydalı, uygun görülen, sağlık niteliği)', 'Sözleşmeli subay ve astsubaylardan 12/4/1991 tarihli', 'şartıyla uzatılabilir.', [], ''),
 ('16', 'kosul', 'sosyal hakları ve sağlık işlemlerinde', 'sözleşme süresince 211 sayılı Kanunun muvazzaf hükümleri (İç Hizmet Kanunu)', 'sosyal hakları ve sağlık işlemlerinde', 'hükümleri uygulanır.', [], ''),
 ('16', 'istisna', 'sağlık hizmetlerinden yararlanma hakkı doğanlar', 'başka kurumdan hak doğunca sözleşme sonrası ücretsiz sağlık hizmetinden yararlanamaz', 'Ancak, kamu kurum ve kuruluşlarının ve sosyal', 'asker hastanelerinden yararlanamazlar.', [], ''),
 ('16', 'sayi_oran', "2/3'ü oranında", 'sağlık nedeniyle sözleşmesi bitene tedavi sürerken oniki ay sağlık yardımı', 'Sözleşmeleri sağlık nedeniyle sona erenlerden', 'Bu ödemeden hiçbir kesinti yapılmaz.', [], ''),
]
yaz(13, "4678 sayılı TSK'da İstihdam Edilecek Sözleşmeli Subay ve Astsubaylar Hakkında Kanun", K)
