# Resmî Yazışmalarda Uygulanacak Usul ve Esaslar Hakkında Yönetmelik — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('3','tanim','paraf yerine geçecek kaydın','elektronik onay','e) Elektronik onay','alınmasını,',[],'güvenli e-imza kullanılmayan durumlarda'),
 ('3','tanim','ek veya ekleri hariç kısmını','üst yazı','r) Üst yazı','hariç kısmını,',[],''),
 ('3','tanim','Devlet Arşivleri Başkanlığı tarafından yayımlanan','standart dosya planı','ö) Standart dosya planı','sınıflama şemasını,',[],''),
 ('3','tanim','periyodik olarak alınan zaman damgası','arşiv imza','b) Arşiv imza','korunan elektronik imzayı,',[],''),
 ('3','tanim','Çok Gizli','kurumsal belge kayıt sistemiyle sayı alınır (EBYS dışı)','m) Kurumsal belge kayıt sistemi','elektronik kaydı,',[],'EBYS kullanamayan idare ve olağanüstü durum belgeleri de'),
 ('3','tanim','Dijital Dönüşüm Ofisi Başkanlığı tarafından','DETSİS','ç) Devlet Teşkilatı Merkezi','tanımlandığı sistemi,',[],'e-Yazışma Teknik Rehberi de DDO yayımlar'),
 ('4','yasak','çıktısı alınarak el yazısıyla','imzalanmaz ve fiziksel ortamda saklanmaz','Ayrıca güvenli elektronik imza ile imzalanan belgeler, çıktısı','fiziksel ortamda saklanmaz.',[],''),
 ('5','sayi_oran','tek nüsha','güvenli e-imzalı belge','(1) Elektronik ortamda güvenli elektronik imza ile imzalanan belgeler tek','tek nüsha olarak hazırlanır.',[],''),
 ('5','sayi_oran','en az iki nüsha','zorunlu hâl/olağanüstü durum belgesi; paraflı nüsha idarede kalır','(2) Zorunlu hâllerde veya olağanüstü durumlarda hazırlanacak belgeler, paraflı','iki nüsha olarak düzenlenir.',[],'E-İMZA TEK, KÂĞIT İKİ'),
 ('6','sira_usul','kâğıdın bir yüzü kullanılır','fiziksel üst yazı; eklerde iki yüz olabilir','(3) Zorunlu hâllerde veya olağanüstü durumlarda hazırlanacak belgelerin üst','kâğıdın bir yüzü kullanılır.',[],'A4'),
 ('7','sayi_oran','Arial için 11 punto','Times New Roman 12; en az 9, iletişimde 8','(1) Hazırlanan belgelerde','8 puntoya kadar düşürülebilir.',[],''),
 ('8','sayi_oran','1,5 cm','yazı alanı üst, sol, sağ boşluk; logoda üst 0,5','(1) Belgenin yazı alanı','0,5 cm olarak düzenlenir.',[],''),
 ('9','sayi_oran','en fazla iki logo','üst idare logosu solda, alt sağda','Belge üzerinde iki ayrı logo','en fazla iki logo kullanılabilir (Örnek 1).',[],''),
 ('10','kosul','DETSİS’te yer alan başlık kayıtları','başlık yazımında esas alınır','(6) Başlığın yazımında','esas alınır.',[],'T.C. / idare adı BÜYÜK / birim adı ilk harfler büyük'),
 ('11','tanim','zorunlu hâller için','sayıda Z; elektronik E, olağanüstü O','“Sayı:” sırasıyla','kısa çizgi işareti (-) konulur (Örnek 3).',[],'E/Z/O – DETSİS no – dosya planı kodu – kayıt no'),
 ('11','sira_usul','kısa çizgi işareti','sayı bölümleri arasına (-)','“Sayı:” sırasıyla','kısa çizgi işareti (-) konulur (Örnek 3).',[],''),
 ('11','kosul','kayıt numarasının eşsiz olması','EBYS/kurumsal kayıt sisteminde zorunlu','İdarece kullanılan EBYS','eşsiz olması zorunludur.',[],''),
 ('12','tanim','zaman damgasındaki tarih bilgisi','e-imzalı belgenin tarihi (son yetkilinin imzası)','(2) Belgenin en son yetkili','üstveri alanında yer alır.',[],'gün.ay.yıl rakamla; ay harfle yazılırsa işaret yok'),
 ('12','istisna','metnin bitiminde yer alabilir','tutanak, rapor, tebliğ-tebellüğ belgesinde tarih','(4) Tutanak, rapor','metnin bitiminde yer alabilir.',[],''),
 ('13','sira_usul','herhangi bir noktalama işareti konulmaksızın','konu; kelime baş harfleri büyük; dikey ortayı geçmez','Belgenin konusu, yazı alanının','konulmaksızın yazılır (Örnek 3).',[],''),
 ('14','sira_usul','yönelme hâl eklerinden','muhatap idare adı büyük harflerle + yönelme eki','(2) Muhatabın idare veya özel hukuk','getirilerek yazılır.',[],'birim adı parantez içinde alt satıra'),
 ('14','sira_usul','DAĞITIM YERLERİNE','birden fazla muhataba dağıtımlı belge','(6) Birden fazla muhataba','ibaresi yazılır (Örnek 15, 16).',[],''),
 ('14','sira_usul','Sayın','gerçek kişi muhatap; adı ilk harf büyük, soyadı büyük','Muhatap gerçek kişi ise','büyük harflerle yazılır (Örnek 5).',[],''),
 ('15','sira_usul','önceki tarihli olandan başlanarak','ilgiler tarih sırasıyla; küçük harf ve kapama parantez','(5) İlginin birden fazla olması','konularak kullanılır (Örnek 7).',[],''),
 ('15','istisna','idare adı belirtilmez','ilgi tutulan belge muhatabın kendi belgesiyse','Ancak ilgi tutulan belgenin, muhatap idarenin','idare adı belirtilmez (Örnek 7).',[],''),
 ('15','sira_usul','İsimsiz ve tarihsiz başvuru','gerçek kişi ve tarih bilgisi olmayan dilekçe ilgisi','(10) Gerçek kişi ve tarih bilgisi','biçiminde yazılır.',[],''),
 ('16','sira_usul','alt makamlara','rica ederim; üst ve aynı düzeye arz ederim','a) Yazışma yapan makamlar','ibaresiyle bitirilir.',[],'ASTA RİCA, ÜSTE VE EŞİTE ARZ'),
 ('16','sira_usul','arz ve rica ederim','üst, aynı düzey ve alt makamlara birlikte dağıtım','b) Üst, aynı düzey ve alt makamlara','ibaresiyle bitirilir.',[],'arz/rica ederim de olur'),
 ('16','istisna','Cumhurbaşkanlığı İdari İşler Başkanı tarafından','bakanlıklarla yazışmada Rica ederim','ç) 1 sayılı Cumhurbaşkanlığı Kararnamesinin 6 ncı','ibaresiyle bitirilir.',[],''),
 ('16','sira_usul','Saygılarımla','gerçek kişi muhataba bitiş; İyi dileklerimle, Bilgilerinize sunulur da','e) Muhatabı gerçek kişi olan','ibareleriyle bitirilebilir.',[],''),
 ('16','sayi_oran','1,25 cm','paragraf girintisi; iki yana hizalı; paragraf arası boşluk yok','(4) Paragrafa 1,25 cm','satır boşluğu bırakılmaz (Örnek 8).',[],''),
 ('16','sira_usul','üçlü gruplara ayrılarak','dört ve çok haneli sayılar; nokta ile; kesirler virgülle','(7) Dört ve dörtten çok haneli','virgül (,) ile ayrılır (Örnek: 10.545,72).',[],''),
 ('16','sira_usul','sadece ilk sayfada','çok sayfalı üst yazıda sayı-tarih-konu-muhatap-ilgi; imza ve ekler son sayfada','(5) Birden fazla sayfa tutan üst yazılarda','sadece son sayfada yer verilir (Örnek 9).',[],'iletişim ve doğrulama bilgisi her sayfada'),
 ('17','sayi_oran','iki ilâ dört satır','metin bitimi ile imza arası boşluk','(1) Metnin bitiminden itibaren','yer verilir (Örnek 9).',[],'ad-soyad-unvan yazı alanının en sağında ortalı'),
 ('17','sira_usul','mavi renkli kalemle','el yazısı imza (zorunlu hâl); paraf da mavi','El yazısıyla atılan imza, kaybolmayacak','mavi renkli kalemle atılır.',[],''),
 ('17','makam','bakan veya ilgili bakan yardımcısı','bakanlıkların Cumhurbaşkanlığı ile yazışmasını imzalar','(8) Bakanlıklar ile bunlara bağlı','bakan yardımcısı tarafından imzalanır.',[],'CB\'ye bağlı kurumlarda en üst yönetici'),
 ('17','sira_usul','yetki devreden makamı gösteren','ikinci satıra “Bakan a.”, “Vali a.”; iç yazışmada kullanılmaz','(9) Belgeyi imza yetkisi devredilen','yetki devredenin unvanı kullanılmaz.',[],''),
 ('17','sira_usul','Belge vekâleten imzalandığında','ikinci satıra “Genel Müdür V.” gibi','(10) Belge vekâleten','ikinci satıra yazılır (Örnek 10).',[],'YETKİ DEVRİ a., VEKÂLET V.'),
 ('17','sira_usul','imzası sağda yer alır','iki yetkilide üst unvan sağda; ikiden fazlada en üst solda','(11) Belgenin iki yetkili','sıralanır (Örnek 11).',[],''),
 ('17','yasak','ibareye, şekle veya ifadeye','e-imzalı belgede imzalandığına dair işaret konmaz','Elektronik ortamda yapılan yazışmalarda, yetkili makamın','yer verilmez.',[],''),
 ('18','sira_usul','EK LİSTESİ','ek listesi sığmazsa ayrı sayfa; üst yazıda Ek: Ek Listesi','(4) Ek listesi','şeklinde gösterilir (Örnek 13).',[],'ek numarası sağ üst köşede EK-1, EK-2'),
 ('18','sira_usul','Ek konulmadı','ekler muhataba gönderilmediğinde','(5) Belge eklerinin','“Ek konulmadı”',[],''),
 ('19','sira_usul','bilgi sahibi olması istenenler','Dağıtım: Bilgi kısmı; gereğini yapacaklar Gereği kısmı','(2) Belgenin gereğini yerine getirme','“Bilgi:” kısmına yazılır.',[],''),
 ('20','sira_usul','Uygun görüşle arz ederim','olura katılan ara makam ibaresi','(4) Oluru teklif eden birim','“Uygun görüşle arz ederim.” ibaresi yazılır',[],''),
 ('20','sira_usul','“OLUR” ibaresinin alt satırına','ortaya büyük harfle; olur makamının imza tarihi belge tarihi','(2) Belge, olur için makama','belge görüntüsü üzerinde gösterilir (Örnek 17).',[],''),
 ('21','kosul','paraf bilgileri paylaşılmaz','belge muhataba iletildiğinde; üstveride tutulur','Belge muhataba iletildiğinde','paraf bilgileri paylaşılmaz.',[],'elektronik paraf: e-imza ya da elektronik onay'),
 ('21','sure','günlük olarak zaman damgasıyla','EBYS günlük raporları damgalanır; saklama süresi belgeden kısa olamaz','Günlük raporlar, günlük olarak','daha kısa olamaz.',[],''),
 ('22','sira_usul','“Koordinasyon” seçimi yapılır','işbirliğiyle hazırlanan belgede paraf hiyerarşisinden sonra','(1) İdare içinde birden fazla','belirtilir (Örnek 20).',[],''),
 ('23','sira_usul','karekod','iletişim bilgileri alanının en sağında; doğrulama e-Devlet üzerinden','Belge doğrulama bilgilerini içeren','e-Devlet) üzerinden sağlanır.',[],'"Bu belge, güvenli elektronik imza ile imzalanmıştır." ibaresi'),
 ('24','sira_usul','bilgi alınacak kişinin','iletişim bilgilerinin sağında; solda idarenin adresi, KEP','(1) İletişim bilgileri; solda','çizgi ile ayrılır (Örnek 21).',[],''),
 ('25','kosul','“Hizmete Özel” gizlilik derecesi','elektronik ortamda işlem görür; Özel ve üstü fiziksel','(1) “Hizmete Özel” gizlilik','fiziksel ortamda gerçekleştirilir.',[],'HİZMETE ÖZEL E-ORTAM, ÖZEL VE ÜSTÜ KÂĞIT'),
 ('25','makam','gizlilik derecesinin belirlenmesinden sorumludur','belgenin imzacısı olan yetkili makam','(3) Belgenin imzacısı','belirlenmesinden sorumludur.',[],''),
 ('26','sure','“ACELE” ibaresi taşıyan belgeye','derhâl ve süratle cevap; GÜNLÜDÜR belirtilen sürede','(2) “ACELE” ibaresi taşıyan belgeye','cevap verilir.',[],''),
 ('26','sira_usul','kırmızı renkli olarak','ACELE/GÜNLÜDÜR sağ üst köşede; yalnız birinci sayfada','(3) Elektronik ortamda veya zorunlu','sadece birinci sayfada belirtilir (Örnek 9).',[],''),
 ('26','sira_usul','zarfı açılmadan','KİŞİYE ÖZEL belge; zarf bilgileri kaydedilir, ilgilisine teslim','(5) “KİŞİYE ÖZEL” ibaresi taşıyan belgenin zarfı','ilgilinin talebi ile EBYS’ye kaydedilir.',[],'yalnız ilgili tasarruf eder'),
 ('27','sira_usul','kaçıncısı olduğunu gösterecek','sayfa numarası; iletişim bilgilerinin altında, ortada','(1) Birden fazla sayfa tutan belgelere','gösterecek şekilde belirtilir (Örnek 9).',[],''),
 ('28','kosul','ayrılmaz bir bütünüdür','e-imzalı belgenin üstverisi; tarih-sayı görüntüyle aynı olmalı','(3) Elektronik ortamda güvenli elektronik imza ile imzalanan belgenin üstveri','arasında fark olamaz.',[],''),
 ('29','sira_usul','ASLI GİBİDİR','fiziksel belge örneği; yetkili görevli imzalar; asıl gibi kabul','(2) Zorunlu hâllerde veya olağanüstü durumlarda ya da bu Yönetmeliğin','asıl belge gibi kabul edilir.',[],'e-imzalı belge çoğaltması: yetkili görevli çıktı alır'),
 ('30','kosul','reddetme hakkına sahiptir','Rehbere uygun olmayan belge; ikinci iş günü sonuna kadar bildirim','(4) İdare, başka bir idareden','sonuna kadar bildirir.',[],''),
 ('30','kosul','açılmış, içeriğine erişilmiş','şifreli belge; idare bildirimde bulunmazsa kabul edilmiş sayılır','İdarenin bildirimde bulunmaması','kabul edilmiş sayılır.',[],''),
 ('30','sira_usul','DETSİS üzerinden paylaşılır','idarelerin elektronik şifreleme sertifikaları','İdareler için oluşturulan elektronik şifreleme','DETSİS üzerinden paylaşılır.',[],''),
 ('31','sira_usul','zarfın sol üst köşesine','gönderen idarenin başlığı, tarih-sayı; muhatap zarfın ortasına','(2) Belge zarflanarak','büyük harflerle belirtilir (Örnek 22).',[],'ACELE, GÜNLÜDÜR, KİŞİYE ÖZEL zarfın sağ üstünde kırmızı'),
 ('31','istisna','işleme alınmasına engel değildir','dilekçenin arz ederim ile bitmemesi, rica ederim denmesi','(7) Kişiler tarafından idareye','engel değildir.',[],''),
 ('31','istisna','Kodlu veya Kriptolu Haberleşme','yetkili idareler gizlilik dereceli belgeyi e-imzayla elektronik gönderebilir','Ancak 23/10/2010 tarihli','elektronik ortamda da gönderebilir.',[],'kural: Hizmete Özel dışı gizlilik dereceli belge fiziksel gönderilir'),
 ('32','sira_usul','gönderene iade edilir','fiziksel gelen, muhatabı olmayan, asıl muhatabı anlaşılamayan belge','(2) İdareye muhatabı olmadığı hâlde fiziksel','gönderene iade edilir.',[],'asıl muhatap belliyse ona gönderilir, gönderene bilgi'),
 ('33','sure','en geç beş iş günü','süre belirtilmeyen belge talebi','İdareler, ilgili mevzuattaki özel hükümler','içinde yerine getirir.',[],'BELGE BEŞ, GÖRÜŞ ON BEŞ İŞ GÜNÜ'),
 ('33','sure','on beş iş günü içinde','süre belirtilmeyen bilgi ve görüş talebi','İdareler, ilgili mevzuattaki özel hükümler','içinde yerine getirir.',[],'talep tarihi: EBYS giriş kaydı'),
 ('34','sira_usul','tekit yazısı','süresinde cevap verilmeyen belge için muhataba','(1) Belgeye süresi içinde','tekit yazısı yazılabilir (Örnek 24).',[],''),
 ('35','istisna','süreli belgeler hariç','Yönetmeliğe aykırı yazı devam ederse gerekçeyle iade','Söz konusu durumun devam etmesi','iade edilebilir.',[],'önce muhatap uyarılır'),
 ('36','makam','Yönetmelik Kılavuzu','Cumhurbaşkanlığı İdari İşler Başkanlığı hazırlar; tereddütleri de giderir','(1) Cumhurbaşkanlığı İdari İşler Başkanlığınca, bu Yönetmeliğin uygulama','hazırlanır ve duyurulur.',[],''),
 ('6', 'sayi_oran', 'A4 (210x297 mm)', 'belge boyutu; ekler farklı form ve ebatta olabilir', 'MADDE 6- (1) Belgeler, A4', 'farklı form, format veya ebatlarda hazırlanabilir.', [], ''),
 ('3', 'tanim', 'hazırlanmasından tasfiyesine kadar', 'aidiyet zinciri (belgenin süreci)', 'a) Aidiyet zinciri: Belgenin', 'tasfiyesine kadar olan sürecini,', [], ''),
 ('3', 'tanim', 'delil teşkil ederek aidiyet zincirini', 'belge (tanım); e-imza ya da el yazısıyla imzalanmış kayıtlı bilgi', 'c) Belge: Herhangi bir bireysel', 'kayıt altına alınmış her türlü bilgiyi,', [], ''),
]
yaz(15, 'Resmî Yazışmalarda Uygulanacak Usul ve Esaslar Hakkında Yönetmelik', K)
