# Jandarma Teşkilat, Görev ve Yetkileri Yönetmeliği — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('3','tanim','ilçelerde kaymakamı','mülki amir tanımı','l) Mülki amir','ilçelerde kaymakamı,',[],'illerde vali'),
 ('3','tanim','Jandarma hizmet merkezi','mülki amirin onayıyla geçici kurulan jandarma birimi','ğ) Jandarma hizmet merkezi','jandarma birimini,',[],''),
 ('3','tanim','Genel Komutanlığının ihtiyatını oluşturmak','jandarma komando birlikleri; Bakanlıkça konuşlandırılır','ı) Jandarma komando birlikleri','konuşlandırılan birlikleri,',[],'mahalli birliklerin gücünü aşan toplumsal olay, terörle mücadele'),
 ('3','tanim','takip ve tenkil harekatını','jandarma asayiş komando birlikleri; il jandarma komutanlığını takviye','g) Jandarma asayiş komando birlikleri','genel kolluk birliklerini,',[],''),
 ('4','makam','Jandarma Genel Komutanı, Bakana karşı','Jandarma Genel Komutanı','MADDE 4- (1) Jandarma Genel Komutanlığı Bakanlığa','Bakana karşı sorumludur.',[],'JGK İçişleri Bakanlığına bağlı'),
 ('5','tanim','Doğrudan merkeze bağlı birimler','asayiş kolordu, komando tugay, JÖAK, eğitim kurumları, havacılık grup/filo','c) Doğrudan merkeze bağlı birimler','5) Havacılık grup/filo komutanlıkları.',[],''),
 ('5','tanim','Taşra teşkilatı şunlardır','bölge, il, ilçe komutanlıkları; komando alay/tabur/bölük; JÖH tabur','b) Taşra teşkilatı','6) Asayiş komando bölük komutanlıkları.',[],'asayiş komando bölük de taşra'),
 ('6','makam','Bakan onayı ile kurulabilir','her düzeydeki jandarma birliği','Her düzeydeki jandarma birlikleri','Bakan onayı ile kurulabilir.',[],'konuş düzeninde mülki taksimat esas'),
 ('6','makam','karakolların konuş yerleri','Bakan onayı; sorumluluk bölgeleri vali onayı','(7) Karakolların sorumluluk bölgeleri','valinin onayıyla teşkil edilir.',[],'KARAKOL BÖLGESİ = VALİ, KARAKOL YERİ = BAKAN; geçici karakol/hizmet merkezi vali onayı'),
 ('6','makam','kuvvet tasarrufu yoluyla','geçici karakol kuvveti; il jandarma komutanlığınca','Geçici karakolların kuvveti','kuvvet tasarrufu yoluyla sağlanır.',[],''),
 ('6','tanim','il merkez jandarma komutanlığı','merkez ilçe jandarma komutanlığı; özel adı yoksa il adıyla','Merkez ilçelerde kurulan','o ilin adıyla adlandırılır.',[],''),
 ('7','makam','Bakanın kararıyla bir il','il/ilçenin tamamı polis ya da jandarma alanı','Bakanın kararıyla bir il','olarak belirlenebilir.',[],''),
 ('8','gorev_yetki','arama kurtarma görevlerini','mülki görev (yönetmelikte); trafik, kritik tesis koruma da','a) Mülki görevler: Emniyet','jandarmaya verilen görevleri yapmak.',[],''),
 ('9','kosul','kendiliğinden olaya elkoyması','özel kolluk alanında; o yer jandarmanın görev alanı sayılır','c) Özel kolluk kuruluşlarının sorumluluk alanına giren konularda','jandarmanın görev alanı sayılır.',[],'polis teşkilatı kurulmamış yerde de'),
 ('10','makam','kesin olarak çözümlenir','kolluk birimleri arası sorumluluk alanı anlaşmazlığı; mülki amir','(4) Sorumluluk alanlarının sınırlarının','kesin olarak çözümlenir.',[],''),
 ('10','sure','devir ve teslim ile ilgili','en geç üç ay içinde tamamlanır','(5) Sorumluluk alanını belirleyen','en geç üç ay içerisinde tamamlanır.',[],''),
 ('13','kosul','Kişisel koruma ve kollama','mevzuat hükmü ya da mülki amir emriyle; esas genel koruma','Kişisel koruma ve kollama','mülki amirin emriyle yerine getirilir.',[],''),
 ('14','sira_usul','Yangının nedenlerini','jandarma saptar; tutanak mülki amire ve savcılığa','Yangının nedenlerini','Cumhuriyet savcılığına verir.',[],''),
 ('15','kosul','akıl hastalarının','polis olmayan yerde yalnız saldırıya engel; sevkten sorumlu değil','(3) Polis teşkilatı olmayan yerlerde','sevk görevi de jandarmaya aittir.',[],'il/ilçenin tamamı jandarmaysa sevk de jandarmanın'),
 ('18','gorev_yetki','denetim kesintisiz sürdürülür','silah ve av tüfeği izin belgesi işlemleri; jandarma yürütür','(1) Sorumluluk alanında olmak kaydıyla','denetim kesintisiz sürdürülür.',[],''),
 ('19','sure','yedi gün içinde verir','jandarma görüşü; umuma açık yer ruhsatı için','Jandarma görüşünü genel güvenlik','yedi gün içinde verir.',[],'izinsiz açılan yer kapatılır'),
 ('19','makam','il özel idareleri tarafından verilir','belediye ve mücavir alan dışındaki umuma açık yerlerin ruhsatı','(3) Jandarma sorumluluk alanında, umuma açık','il özel idareleri tarafından verilir.',[],'belediye sınırı içinde belediye'),
 ('19','sira_usul','kat’i delil elde edilmesi','kumar, uyuşturucu, fuhuş yeri vb. mülki amire bildirilir','(4) Jandarma tarafından kat’i delil','gereği yapılmak üzere mülki amire bildirilir.',[],''),
 ('20','makam','İnternet Toplu Kullanım Sağlayıcıları','açma-kapatma mülki amir emriyle; jandarma güvenlik yönünden denetler','MADDE 20- (1) 1/11/2007','mülki amire bildirir.',[],''),
 ('21','sure','saat yirmidörtten sonra','civarı rahatsız eden gürültü jandarmaca men edilir; Kabahatler','MADDE 21- (1) Mesken içinde','menolunur.',[],''),
 ('21','sure','kırksekiz saat önce mülki amire','düğün, nişan, konser, panayır bildirimi','(2) Düğün, nişan','bildirimde bulunmak zorundadır.',[],''),
 ('22','sira_usul','teslim almaktan kaçındıklarında','kanuni temsilci; jandarma tutanak tutar, kanuni işlem','(2) Yardıma muhtaçların','kanuni işlem yapılır.',[],''),
 ('22','makam','Sosyal Politikalar Bakanlığı yetkililerine','korunmaya muhtaç kişiler bildirilir','(3) Jandarma, 5237 sayılı Kanun ve 24/5/1983','işbirliği içinde bulunmakla görevlidir.',[],''),
 ('23','gorev_yetki','jandarmaya haber verir, yitebilecek delilleri','özel kolluk, jandarmanın görevine giren olayda el koyar','MADDE 23- (1) Özel kolluk','eylemcileri yakalar.',[],''),
 ('23','sira_usul','özel güvenlik teşkilatına devredilir','özel kolluk yokken jandarmanın yaptığı işlem ve soruşturmalar','Mevzuatta aykırı bir hüküm bulunmadıkça','özel güvenlik teşkilatına devredilir.',[],''),
 ('23','makam','onayıyla bu yerlerden bilgi','işyerlerindeki çalışanların kimlik ve nitelikleri','Jandarma, bu yerlerde bulunan','İstenilen bilgiler hemen verilir.',[],'işyeri denetimi de mülki amirin emri/onayıyla'),
 ('24','yasak','infaz koruma memurluğu görevlerinde','jandarma hiçbir şekilde kullanılamaz','(3) Jandarma hiçbir şekilde','kullanılamaz.',[],'dış koruma jandarmanın'),
 ('24','kosul','infaz koruma memurlarının başvurusu','içerideki kargaşaya jandarma müdahale eder; müdür/vekili de','Ceza infaz kurumlarının içinde burada','sükûnu sağlar.',[],''),
 ('24','yasak','jandarma muhafazasında olmadıkça','izinsiz hiçbir tutuklu/hükümlü dışarı gönderilemez','(5) Ceza infaz kurumlarının yetkili','dışarıya gönderilemez.',[],''),
 ('25','sira_usul','inzibat aletleri','savcı, hâkim, mahkeme önünde çıkarılır; çıkışta tekrar takılabilir','(3) Hükümlü ve tutuklular Cumhuriyet','tekrar takılabilir.',[],''),
 ('25','makam','muhafız devriyenin kuvvetini','jandarma komutanı saptar; liste infaz müdüründen yazıyla','MADDE 25- (1) Soruşturma ve duruşmalar','hazır bulundurur.',[],''),
 ('26','kosul','yazılı istemi üzerine','kurumlar arası sevk; jandarma götürür','MADDE 26- (1) Bir ceza infaz','istenilen yere götürülürler.',[],''),
 ('27','yasak','hizmet araçları sevklerde kullanılmaz','jandarmanın araçları; esas ceza infaz kurumu araçları','(3) Jandarmaya ait hizmet','sevklerde kullanılmaz.',[],'yoksa kamu kitle ulaşımı; özel taşıt yok; uçak olabilir'),
 ('27','kosul','özel bir bölüm ayrılması','kamu kitle ulaşım aracıyla sevkte zorunlu','Kamuya ait kitle ulaşım araçlarıyla sevk','özel bir bölüm ayrılması zorunludur.',[],''),
 ('28','sira_usul','alındı belgesi','teslim alınan para/eşya için tutuklu-hükümlüye verilir; sevk pusulasına','Teslim alınan nesnelerin','sevk pusulasına yazılır.',[('65','polis/sahil güvenlik el koyduğu nesneyi jandarmaya alındı belgesiyle teslim eder')],''),
 ('28','kosul','doktor raporuyla saptandığında','sevke engel sağlık durumu: sevk yapılmaz, makama yazı','(3) Sağlık açısından','yazıyla bildirilir.',[],''),
 ('29','yasak','birlikte sevk edilemez','erkek ve kadın tutuklu; iştirak halinde suç ve yakınlar hariç','MADDE 29- (1) İştirak halinde','birlikte sevk edilemez.',[],''),
 ('29','kosul','kadın ceza infaz koruma görevlisi','sevk edilen kadın tutuklu-hükümlüye verilir','(2) Sevk edilen tutuklu','koruma görevlisi verilir.',[],''),
 ('30','sira_usul','yolda hastalandığında','en yakın hekimli jandarma birliğine; devam edemezse savcı talimatıyla cezaevine','MADDE 30- (1) Sevk ve nakil sırasında tutuklu ya da hükümlü yolda','teslim edilir.',[],''),
 ('31','sira_usul','birisi öldüğünde','en yakın jandarma birliğine, oradan savcılığa; devriye komutanı tutanak','MADDE 31- (1) Sevk ve nakil sırasında tutuklu ya da hükümlülerden birisi','ilgili makama verilir.',[],''),
 ('32','gorev_yetki','silah kullanılacağı ihtar edilir','isyan/firar hazırlığında devriye komutanı; başka çare yoksa silah','MADDE 32- (1) Sevk ve nakil sırasında tutuklu veya hükümlülerin isyan','silah kullanılır.',[],''),
 ('32','makam','sevke devam edip edemeyeceklerini','Cumhuriyet savcısı belirler; jandarma tutuklanırsa o yer jandarması','(3) Bu gibi durumlarda','o yer jandarması tarafından yapılır.',[],''),
 ('33','sira_usul','gündüz varılacak biçimde','sevk hareketi; konaklama cezaevi, emniyet odası, karakol, köy odası','MADDE 33- (1) Sevk ve nakillerde','kalınabilir.',[],''),
 ('35','kosul','özel yerleri ilgili kuruluşlarca','hastanede tutuklu için; jandarma görüşüyle önceden hazır','(2) Sağlık kurumlarında önceden','bakımlı bulundurulur.',[],'hastanede muhafaza jandarmanın'),
 ('36','makam','Adalet Bakanlığınca düzenlenen','tutuklu çalıştırmada muhafaza jandarma; diğer kurumlarda infaz kurumu personeli','MADDE 36- (1) Adalet Bakanlığınca','personelince yürütülür.',[],''),
 ('38','makam','haricindeki hizmetlerde, üstlerinin emrindedir','adli kolluk; adli görevde Cumhuriyet savcısının','(2) Soruşturma işlemleri','üstlerinin emrindedir.',[],''),
 ('40','makam','yeme, içme ve nakil masrafları','gözaltındakinin adli makama kadar; JGK bütçesinden','MADDE 40- (1) Gözaltına','bütçesinden ödenir.',[],''),
 ('41','kosul','2941 sayılı Seferberlik','seferberlik ve savaşta jandarma bu kanunla verilen görevleri yapar','Jandarma, seferberlik ve savaş halinde, 4/11/1983','verilen görevleri yapar.',[],''),
 ('42','gorev_yetki','polisin sahip olduğu yetki','jandarma görevde aynı yetkilere sahip (PVSK, CMK)','Jandarma bu görevlerini yerine getirirken polisin','sorumluluklara sahiptir.',[],''),
 ('42','kosul','yazılı olarak tekrar ederse','aykırı emir yerine getirilir; yapan sorumlu olmaz','(2) Jandarma amirinden aldığı emri','Yerine getirenler sorumluluktan kurtulamaz.',[],'AYKIRI EMİR: BİLDİR; YAZILI ISRAR = YAP'),
 ('42','yasak','Konusu suç teşkil eden emir','hiçbir suretle yerine getirilmez; yapan sorumlu','(2) Jandarma amirinden aldığı emri','Yerine getirenler sorumluluktan kurtulamaz.',[],''),
 ('42','sira_usul','yazılı olarak verilmesi istenilemez','sayılan acele hallerde sözlü emir; sorumluluk emri verene','j) Kanunlarda istisnai olarak','sorumluluk emri verene aittir.',[],'can-ırz-mal, kaçan şahıs, afet, yol açma, kanunsuz toplantı dağıtma…'),
 ('44','gorev_yetki','zor kullanarak karşı koyanlar','jandarma yakalar; Cumhuriyet savcısına derhal bilgi','(2) Görevini yaptığı sırada jandarmaya','emri doğrultusunda işlem yapılır.',[],''),
 ('45','yasak','veli ve vasileri olsa bile','onsekiz yaşını doldurmamış küçükler içkili yere, kıraathaneye, internet salonuna giremez','(3) Jandarma; bar, pavyon','girmesini engeller.',[],'belgeli turizm işletmeleri hariç; izne bağlı yerlerde çalıştırma da yasak'),
 ('45','gorev_yetki','herhangi bir şikâyet olmasa bile','genel ahlaka aykırı davranış, sarkıntılık, müstehcen yayın engellenir','c) Genel ahlaka aykırı mahiyette','gerekli kanuni işlemleri yapar.',[],''),
 ('46','kosul','makul bir sebebin bulunması','durdurma yetkisi şartı; süreklilik ve keyfilik yasak','(2) Durdurma yetkisinin','durdurma işlemi yapılamaz.',[],'durdurma sebebi bildirilir; süre zorunlu süreyi aşamaz'),
 ('46','yasak','elbisenin çıkarılması','durdurmada istenemez; aracın görünmeyen bölümünü açma da','Bu amaçla kişinin üzerindeki elbisenin','açılması istenemez.',[],''),
 ('46','makam','görevlendireceği kolluk amirinin yazılı','durdurulanın üstünü/aracını arama emri; acele sözlü, yirmidört saatte hâkim onayı','Ancak el ile dıştan kontrol hariç','hakimin onayına sunulur.',[],'mülki amirin görevlendirdiği kolluk amiri; araç aramasında belge verilir'),
 ('46','sira_usul','jandarma olduğunu belirleyen belgeyi','belgeyi gösterdikten sonra kimliğini sorabilir','(8) Jandarma, görevini yerine getirirken kendisinin','kimliğini sorabilir.',[],'kimliği belirlenemeyen tutulur, savcıya haber'),
 ('46','sira_usul','fotoğraf ve parmak izi','nüfusa kayıtsız kimliği belirlenemeyen kişi kayda alınır','(10) Nüfusa kayıtlı olmadığı','kayda alınır.',[],''),
 ('47','makam','mülki amirin vereceği yazılı emirle','önleme araması; gecikmesinde sakınca varsa (asıl: sulh ceza hâkimi)','MADDE 47- (1) Jandarma, tehlikenin','gerekli işlemleri yapar.',[],''),
 ('47','yasak','kamuya açık olmayan işyerlerinde','önleme araması yapılamaz; konut, yerleşim yeri de','(5) Konutta, yerleşim yerinde','önleme araması yapılamaz.',[],''),
 ('47','kosul','sakınca bulunan hal var sayılır','spor karşılaşması, miting, konser, festival, ani topluluk','(6) Spor karşılaşması','var sayılır.',[],''),
 ('47','gorev_yetki','emir veya karar olmasına bakılmaksızın','jandarmanın koruduğu bina/tesise girenlerin üstü-aracı aranır; kimlik ibrazı zorunlu','(7) Jandarma, tehlikenin önlenmesi veya bertaraf','ibraz etmek zorundadır.',[],''),
 ('47','kosul','İdarecilerinin talebiyle','yükseköğretim kurumlarının içinde önleme araması','ç) İdarecilerinin talebiyle','giriş ve çıkışlarında.',[],'toplantı yeri, genel kurul çevresi, umuma açık yer, toplu taşıma da'),
 ('48','gorev_yetki','boğulma gibi büyük tehlikelerin','konut ve işyerine girilebilir (acele hal)','MADDE 48- (1) Jandarma;','eklentilerine girebilir.',[],'suçun işlenmesini/devamını engellemek için de'),
 ('50','gorev_yetki','yeri ve zamanına bakılmaksızın','jandarma suçla karşılaşınca el koyar; delili yetkili kolluğa teslim','MADDE 50- (1) Jandarma, sorumluluk alanı içinde hizmet','görevli ve yetkilidir.',[],''),
 ('52','makam','üst yöneticiye verilen','Jandarma Genel Komutanı (5018 Kamu Malî Yönetimi)','f) 10/12/2003 tarihli ve 5018','yerine getirmek.',[],''),
 ('53','makam','bulunmadığı zamanlarda vekalet etmek','jandarma genel komutan yardımcıları','b) Jandarma Genel Komutanının bulunmadığı','yetkilerini kullanmak.',[],''),
 ('54','makam','iller arasında kuvvet kaydırması','bölge komutanı; konuşlu olduğu ilin valisinin onayıyla','MADDE 54- (1) Jandarma bölge komutanları','kuvvet kaydırması yapmakla görevlidir.',[],'terör operasyonlarını da o valinin onayıyla planlar'),
 ('54','makam','faaliyette bulunulan ilin valisine','bölge komutanı operasyonel faaliyette ona karşı da sorumlu','Bölge komutanı bu görevlerinin ifasından','valisine karşı sorumludur.',[],'il ve ilçe jandarma komutanlıklarına emir verebilir'),
 ('56','makam','kaymakam tarafından verilen görevlerin','ilçe jandarma komutanı takip ve kontrol eder','d) Kanunlarla ve kaymakam tarafından','sonuçlarını bildirmek.',[],'il jandarma komutanı: vali'),
 ('57','makam','ilçe jandarma komutanı tarafından verilen','karakol komutanı takip eder; vali → il J.K.','d) Kanunlarla ve ilçe jandarma komutanı tarafından','sonuçlarını bildirmek.',[],''),
 ('58','makam','en üst amiridir ve teşkilatı','Bakan; JGK Bakana karşı sorumlu','Bakan, jandarma teşkilatının en üst','teşkilatı idare eder.',[],'bölge komutanı valiye, il-ilçe komutanı mülki amire bağlı'),
 ('58','makam','doğrudan emir verme yetkisine','mülki amirler ve adli makamlar; diğer makamlar mülki amire başvurur','(3) Mülki amirler ile adli makamlar','görevin ifasını emreder.',[],''),
 ('58','makam','araç ve gereçlerin seçimi','jandarma komutanına ait; mülki amir yetersizlikte başka kurumdan sağlar','(7) Jandarma birimlerinin üstlendikleri','jandarmanın hizmetine verebilir.',[],''),
 ('59','sira_usul','vakit geçirmeksizin mülki amire','suç, afet, salgın, propaganda bilgileri; suçla ilgili olanlar savcılığa da','MADDE 59- (1) Jandarma; bölgelerindeki','Cumhuriyet savcılığına da bildirilir.',[],''),
 ('60','yasak','resen muhabere edemez','JGK merkez ve taşra teşkilatı birbiriyle (teknik/lojistik/özlük hariç)','MADDE 60- (1) Jandarma Genel Komutanlığı merkez ve taşra','resen muhabere edemez ve yazışma yapamaz.',[],'yazışma Bakanlık ve mülki amir aracılığıyla'),
 ('60','sira_usul','her halükarda valilikler aracılığıyla','hak-yükümlülük doğuran, irade beyanı niteliğindeki yazışmalar','Hak ve yükümlülük doğuran','valilikler aracılığıyla yapılır.',[],''),
 ('60','makam','vali imzasıyla gönderilir','Bakanlığa asayiş raporu; il jandarma komutanlığı hazırlar','(4) Bakanlığa gönderilecek asayiş','vali imzasıyla gönderilir.',[],''),
 ('60','sayi_oran','beş örnek olarak birleştirilip','emniyet-asayiş istatistikleri emniyet müdürlüğünce; iki örneği Bakanlığa','(5) Emniyet ve asayiş görevlerine ait','vali imzasıyla Bakanlığa sunulur.',[],'il J.K., emniyet müdürü, SG komutanı parafe eder'),
 ('63','sure','yediemin otoparkına','icra talebiyle yakalanan araç; üç işgünü içinde icra müdürlüğüne bildirim','MADDE 63- (1) İcra müdürlüklerinin','bildirimde bulunulur.',[],''),
 ('65','yasak','olay yerinde soruşturma yapamaz','jandarma alanında suçla karşılaşan polis/sahil güvenlik; delilleri korur, haber verir','MADDE 65- (1) Jandarma sorumluluk alanında herhangi','talimatına göre hareket eder.',[],'jandarma gelemezse savcıya haber'),
 ('65','makam','hangi kolluk kuvvetine ait olduğu','ortak operasyonda komuta-sevk-idare; mülki amir belirler','(6) Jandarma, sahil güvenlik ve polisin birlikte','mülki amir tarafından belirlenir.',[],''),
 ('66','makam','uluslararası kuruluşlara üye olabilir','JGK; Bakan onayı ile','(3) Jandarma Genel Komutanlığı, Bakan onayı','üye olabilir.',[],''),
 ('66','sure','dış ilişkiler uygulama planı','yıllık; Dışişleri görüşü, İçişleri Bakanlığı onayı','MADDE 66- (1) Jandarma Genel Komutanlığı yurtdışında','Bakanlıkça onaylanır.',[],'plan dışı faaliyete ayrıca Bakanlık onayı'),
 ('67','makam','Mülkiye Teftiş Kurulu Başkanlığı','Bakan adına jandarma birimlerini denetler; illerde vali, ilçelerde kaymakam','MADDE 67- (1) Bakan her kademedeki','kaymakamlar tarafından yapılır.',[],'JGK adına Teftiş Kurulu ve İç Denetim'),
 ('68','makam','kadro tavanını aşmamak üzere','yıl içi kadro değişikliği Bakan onayıyla; kadrolar bütçe kanunuyla','Yıl içinde ihtiyaç duyulan','Bakandan onay alınır.',[],''),
 ('70','makam','değişik kılık ve kıyafetle','mülki amir ya da il jandarma komutanı izniyle; gizli takip','Ancak suç ve suçluların gizli','hizmet yürütülebilir.',[],'kaçakçılık ve terörle mücadelede de; esas resmi kıyafet'),
 ('71','sure','hiç bir zaman süreklilik taşımaz','geçici görevlendirme; sonuç alınınca döner; mülki amir onayı','Bu görev hiç bir zaman','mülki amirin onayı ile yapılır.',[],'jandarma, sahil güvenlik, emniyet birbirinin alanında'),
 ('72','gorev_yetki','sorumluluk alanı ile sınırlı değildir','merkezden/iller arası görevlendirilen ekiplerin kolluk yetkisi; mahallin mülki amirine bilgi','(2) Görevlendirilen ekiplerin','mülki amirine karşı da sorumludur.',[],'Bakanlıkça ya da vali talebiyle; iller arası valiliklerce'),
 ('74','sure','en yakın askerlik şubesine getirilirler','yakalanan yoklama kaçağı/bakaya; en geç yirmidört saat','Yakalanarak muhafaza altına alınan','derhal serbest bırakılırlar.',[],''),
 ('74','kosul','derhal serbest bırakılırlar','askerlik şubesince teslim alınamayan yükümlü; jandarma tutanağıyla','Yakalanarak muhafaza altına alınan','derhal serbest bırakılırlar.',[],'firar/izin tecavüzünde yakalama kararı varsa aranır'),
 ('75','makam','koruma ve müdahale harekat planı','jandarma hazırlar; planlar mülki amir onayıyla yürürlüğe girer','MADDE 75- (1) Jandarma birimleri, emniyet','(3) Planlar, mülki amirin onayı ile yürürlüğe konulur.',[],'suç önleme/müdahale planı, doğal afet-yardım planı da'),
 ('76','sure','stratejik hedef planı','beş yıllık; Bakan onayı; iki yılda bir gözden geçirilir','MADDE 76- (1) Jandarma teşkilatının personel','en az iki yılda bir gözden geçirilir.',[],''),
 ('77','yasak','hiçbir tebligat işlemi jandarmaya','mevzuatta belirtilmeyen; görev olarak verilemez','Mevzuatta belirtilmeyen hiçbir tebligat','yerine getirilemez.',[],''),
 ('78','makam','Jandarma Müzesinde','mevcut sancaklar muhafaza edilir','MADDE 78- (1) Jandarma Genel Komutanlığı merkez ve taşra teşkilatlarındaki mevcut','muhafaza edilir.',[],''),
 ('80','sure','otuz günü geçmemek üzere','PVSK m.8 halinde işyeri faaliyetten men; mülki idare amiri','“2559 sayılı Kanunun 8 inci','faaliyetten men edilir.',[],'İşyeri Açma ve Çalışma Ruhsatları Yönetmeliği m.39'),
 ('80','sure','mühürlemek suretiyle','yetkili idare üç işgünü içinde uygular; uygulamazsa kolluk re\'sen','Yetkili idare en geç üç işgünü','yetkili idareye bilgi verilir.”',[],''),
]
yaz(17, 'Jandarma Teşkilat, Görev ve Yetkileri Yönetmeliği', K)
