# Jandarma Teşkilat, Görev ve Yetkileri Yönetmeliği — kelime → cevap
# KURAL (başkan, 4 Eki 2026): SOL = soru KÖKÜNDE göreceğin ifade, SAĞ = doğru ŞIKTA arayacağın kelime.
# Sorulardan geriye doğru yazıldı (199 cevaplı soru + kitapçık kökleri); kanıt resmî metin.
# Tanım satırlarında "Kamu düzeni:" gibi iki noktalı sol = tanım etiketi (metinde yalnız tanım maddesinde geçer).
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 # m.1-3 — amaç, dayanak, tanımlar
 ('1','tanim','Yönetmeliğin amacı','teşkilat, görev-yetki-sorumluluk, makamlarla ilişki, işbirliği, komuta-kontrol','MADDE 1- (1) Bu Yönetmeliğin amacı','ilişkilerini düzenlemektir.',[],'özlük hakları amaç DEĞİL'),
 ('2','kosul','dayanılarak','2803 sayılı Jandarma Kanunu m.24','MADDE 2- (1) Bu Yönetmelik','dayanılarak hazırlanmıştır.',[],''),
 ('3','tanim','hayatın normal akışı','asayiş','a) Asayiş:','yerleşik ve yaygın inancı,',[],'emniyet = önlemlerin tümü; asayiş = huzurlu hal ve yaygın inanç; 2026 Uzman sınavında soruldu'),
 ('3','tanim','önlemlerin tümü','emniyet','d) Emniyet:','alınmış bulunduğu hali,',[],'asayiş = bu önlemler sonucu oluşan hal'),
 ('3','tanim','talep ya da yasağın','emir','ç) Emir:','sair suretle ifadesini,',[],'söz, yazı ve sair suretle ifade'),
 ('3','tanim','amir tarafından verilen emir','görev','f) Görev:','verilen emirleri,',[],'mevzuatla öngörülen hususlar da'),
 ('3','tanim','huzur ve sükun','kamu düzeni (emniyet-asayiş, genel sağlık-ahlak da); ekonomik istikrar DEĞİL','i) Kamu düzeni:','kullanımına elverişli ortamı,',[('11', 'kamunun huzur-sükununu bozan eylemlere jandarma engel olur')],'hak ve hürriyetlerin tam kullanımına elverişli ortam'),
 ('3','tanim','yerleşik ve yaygın','asayiş','a) Asayiş:','yerleşik ve yaygın inancı,',[],'dirlik ve düzenin varlığı konusunda'),
 ('3','tanim','Genel kolluk:','Bakanlığa bağlı jandarma, sahil güvenlik, polis; özel kanun-orman muhafaza DEĞİL','e) Genel kolluk:','sahil güvenlik ve polisi,',[],'silah kullanma yetkili; özel kanunla kurulan özel kolluktur'),
 ('3','tanim','Özel kolluk:','özel kanunla kurulan; jandarma, sahil güvenlik, polis dışı','m) Özel kolluk:','kolluk birimlerini, ifade eder.',[],'kendi görev alanında güvenlik'),
 ('3','tanim','Kapalı yerler:','konut, işyeri, eklenti; çit-duvarla çevrili; açık meydan DEĞİL','j) Kapalı yerler:','oda benzeri alanları),',[],'depo, ardiye, gemide kamara da'),
 ('3','tanim','Mülki amir:','illerde vali, ilçelerde kaymakam','l) Mülki amir:','ilçelerde kaymakamı,',[],''),
 ('3','tanim','Jandarma hizmet merkezi','mülki amir onayıyla geçici birim','ğ) Jandarma hizmet merkezi','jandarma birimini,',[('6','geçici asayiş karakolu ve hizmet merkezi: il J.K. önerisi, vali onayı')],''),
 ('3','tanim','ihtiyatını oluşturmak','jandarma komando birlikleri','ı) Jandarma komando birlikleri','konuşlandırılan birlikleri,',[],'mahalli birliklerin gücünü aşan olay, terörle mücadele; Bakanlıkça konuşlandırılır'),
 ('3','tanim','takip ve tenkil','jandarma asayiş komando birlikleri','g) Jandarma asayiş komando birlikleri','genel kolluk birliklerini,',[],'il jandarma komutanlığını takviye eder'),
 ('3','tanim','Jandarma kriminal birimleri','JKDB, laboratuvar, OYİT, patlayıcı imha timi','h) Jandarma kriminal birimleri','timleri,',[],'felaket kurbanı kimliklendirme timi de'),
 ('3','tanim','harekata hazırlanma','konuş','k) Konuş:','bulunduğu yeri,',[],'barınma, eğitim, tatbikat yeri'),
 # m.4-7 — bağlılık, teşkilat, konuşlanma, görev alanı
 ('4','makam','bağlıdır','Bakanlığa; Genel Komutan Bakana sorumlu','MADDE 4- (1) Jandarma Genel Komutanlığı','Bakana karşı sorumludur.',[('58','çalışma esaslarında da JGK Bakanlığa bağlı, Bakan en üst amir')],'İçişleri Bakanlığı'),
 ('5','tanim','taşra teşkilatı','bölge/il/ilçe; komando alay-tabur-bölük; özel harekat tabur; asayiş komando bölük','b) Taşra teşkilatı','6) Asayiş komando bölük komutanlıkları.',[('60', 'merkez-taşra birbiriyle Bakanlık ve mülki amir aracılığıyla yazışır'), ('72', 'merkez veya taşra teşkilatından ekip görevlendirilir'), ('78', 'merkez-taşradaki sancaklar Jandarma Müzesinde')],'JÖH = jandarma komando özel harekat; Asayiş Başkanlığı, Lojistik K., İstihbarat Grup K. MERKEZ teşkilatı; Astsubay sınavında soruldu'),
 ('5','tanim','merkeze bağlı','asayiş kolordu, eğitim kurumu, komando tugay, Özel Asayiş-Kurtarma Tugayı, havacılık','c) Doğrudan merkeze bağlı birimler','5) Havacılık grup/filo komutanlıkları.',[],'JÖAK = Komando Özel Asayiş ve Kurtarma Tugay; 2026 Uzman sınavında soruldu'),
 ('5','tanim','Merkez teşkilatı','başkanlıklar, Lojistik K., İstihbarat Okul-Grup, Personel Temin, Denetleme, Destek Kıtaları','a) Merkez teşkilatı','19) Sosyal tesisler birimleri.',[('60','merkez-taşra yazışması Bakanlık ve mülki amir aracılığıyla')],''),
 ('6','kosul','konuşlarının düzenlenmesinde','mülki taksimat esas','MADDE 6- (1) Jandarma birimlerinin','mülki taksimat esas alınır.',[],''),
 ('6','makam','her düzeydeki jandarma birlikleri','Bakan onayı ile kurulur','Her düzeydeki jandarma birlikleri','Bakan onayı ile kurulabilir.',[],''),
 ('6','makam','birden çok ili','geçici bölge komutanlığı; konuşlu il valisine sorumlu','(2) Sevk ve idare ihtiyaçları','valisine karşı sorumlu olarak görev yapar.',[],''),
 ('6','makam','Karakolların sorumluluk bölgeleri','vali onayı; konuş yeri Bakan onayı','(7) Karakolların sorumluluk bölgeleri','ise Bakan onayı ile belirlenir.',[],'il jandarma komutanı önerir; KARAKOL BÖLGESİ = VALİ, KARAKOL YERİ = BAKAN'),
 ('6','tanim','bir ya da birden çok','karakol sorumluluk bölgesine ayrılır (ilçe alanı)','İlçe jandarma komutanlıklarının sorumluluk alanı','karakol sorumluluk bölgesine ayrılabilir.',[],'karakol bölgesini vali onaylar'),
 ('6','makam','Geçici asayiş karakolları','il J.K. önerisi, vali onayı','Geçici asayiş karakolları ile','valinin onayıyla teşkil edilir.',[],'jandarma hizmet merkezleri de'),
 ('6','kosul','Karakol sorumluluk bölgesinin belirlenmesinde','asayiş/suç analizi/coğrafya-ekonomi-kamu hizmeti/yerleşim/nüfus/ulaşım/sosyal-kültürel; personel sayısı DEĞİL','Karakol sorumluluk bölgesinin belirlenmesinde','f) Sosyal ve kültürel gelişimi ve benzeri özellikler.',[],''),
 ('6','makam','kuvvet tasarrufu','geçici karakol kuvveti il J.K.’nca','Geçici karakolların kuvveti','kuvvet tasarrufu yoluyla sağlanır.',[],''),
 ('6','tanim','il merkez jandarma komutanlığı','merkez ilçe; özel adı yoksa il adıyla','Merkez ilçelerde kurulan','o ilin adıyla adlandırılır.',[],''),
 ('7','tanim','genel olarak görev','belediye sınırı dışı; polis ve sahil güvenlik olmayan yer','MADDE 7- (1) Jandarmanın genel olarak','bulunmayan yerlerdir.',[],'hizmet gereği belediye içinde de belirlenebilir'),
 ('7','makam','Bakanın kararıyla','il-ilçenin tamamı polis ya da jandarma alanı','Bakanın kararıyla bir il','olarak belirlenebilir.',[],'sulh ceza hâkimi, il sınır komisyonu DEĞİL'),
 # m.8-10 — görev sınırı, görev alanı sayılan haller, sorumluluk alanı
 ('8','gorev_yetki','Mülki görevler:','asayiş, kaçakçılık, suç önleme, dış koruma, trafik; işlenmiş suç DEĞİL','a) Mülki görevler:','jandarmaya verilen görevleri yapmak.',[],'cezaevi dış koruması, arama kurtarma, kritik tesis koruma da mülki; işlenmiş suç işlemleri ADLİ'),
 ('8','gorev_yetki','Adli görevler:','işlenmiş suçlarla ilgili işlemler','b) Adli görevler:','adli hizmetleri yerine getirmek.',[],'suç önleme tedbiri MÜLKİ görev'),
 ('8','gorev_yetki','askeri görev','seferberlik-savaşta kuvvet komutanlıkları emrinde; illerde vali onayı','c) Askeri görevler:','askeri görevleri icra etmek.',[('41','askeri görevler maddesi: garnizon talebi + vali onayı; Genelkurmay talebi + Bakan'),('69','askeri görev verilen birliğin ihtiyacını MSB karşılar')],'Genelkurmay talebiyle Bakan; illerde garnizon komutanı talebi + vali onayı'),
 ('8','yasak','Görev sınırı','mevzuatta öngörülmeyen hiçbir görev istenemez','Görev sınırı','jandarmadan istenemez.',[],''),
 ('9','kosul','sorumluluk alanı dışında','polis yoksa; özel kolluk alanı-yokluğu; iç güvenlik devri DEĞİL','MADDE 9- (1) Jandarma sorumluluk alanı dışında','jandarmanın görev alanı sayılır.',[('43', 'polis alanı dışında jandarma trafiği düzenler')],'görevlendirme ya da kendiliğinden el koyma; o yer görev alanı sayılır'),
 ('9','kosul','kendiliğinden','o yer jandarmanın görev alanı sayılır','c) Özel kolluk kuruluşlarının','jandarmanın görev alanı sayılır.',[],''),
 ('9','makam','geçici olarak koruma','mülki amirin yetkisi saklı','(2) Kamu ve özel hukuk','yetkisi saklıdır.',[],'iç güvenliği kurumun kendisi sağlar'),
 ('10','makam','komisyon','vali-vali yardımcısı başkanlığında; kararı Bakan onaylar','(2) Birinci fıkrada belirlenen','harita veya kroki üzerinde gösterilir.',[],'ilçede kaymakam başkan; jandarma-emniyet temsilcileri üye; çağrıyı vali-kaymakam yapar'),
 ('10','sure','sınırlarda değişiklik','üç ay içinde yeniden düzenlenir','Büyükşehir, il veya ilçe belediyesi','yeniden düzenlenir.',[],'devir-teslim de en geç üç ay'),
 ('10','makam','anlaşmazlık','mülki amir kesin çözer','(4) Sorumluluk alanlarının','kesin olarak çözümlenir.',[],''),
 ('10','sure','devir ve teslim','en geç üç ay içerisinde','(5) Sorumluluk alanını belirleyen','üç ay içerisinde tamamlanır.',[],''),
 # m.11-23 — mülki görevler
 ('11','gorev_yetki','halkın','can, ırz ve malını korur','a) Halkın can','ırz ve malını korur.',[('13','can-ırz-malda esas genel koruma; kişisel koruma mülki amir emriyle'),('21','civar halkını rahatsız eden gürültü saat yirmi dörtten sonra men'),('47','halkın topluca bulunduğu yerde önleme araması')],''),
 ('11','gorev_yetki','kişilerin güvenliğini','ve konut dokunulmazlığını korur; asayişi de','c) Asayişi, kamunun ve kişilerin','konut dokunulmazlığını korur.',[],''),
 ('11','gorev_yetki','yardım eder','yardım isteyen, muhtaç çocuk, engelli, hasta, yaşlı, kimsesiz, yabancı','e) Yardım isteyenlere','yabancılara yardım eder.',[],''),
 ('11','gorev_yetki','Mülki görevlerin esasları','can-ırz-mal, suç önleme, kaçakçılık, cezaevi DIŞ koruma, trafik, istihbarat','Mülki görevlerin esasları','trafik kazalarıyla ilgili işlemleri yapar.',[],'cezaevi iç güvenliği, hakemlik DEĞİL'),
 ('12','gorev_yetki','Önleyici kolluk','devriye ile aksatmadan','b) Önleyici kolluk görevini','aksatmadan yürütmek.',[],''),
 ('13','kosul','Kişisel koruma ve kollama','mevzuatta özel hüküm ya da mülki amir emri','Kişisel koruma ve kollama','mülki amirin emriyle yerine getirilir.',[],'esas genel ve koruyucu önlem'),
 ('14','sira_usul','tutanağın','mülki amire ve Cumhuriyet savcılığına','Olayla ilgili olarak düzenlenen','Cumhuriyet savcılığına verir.',[('80','mühürleme tutanağının sureti mülki makama')],'yangın, sel, deprem; amirlere ve ilgililere haber verir, olay yerine gider'),
 ('15','kosul','akıl hastalarının','polis yoksa yalnız saldırıya engel','(3) Polis teşkilatı olmayan','sevk görevi de jandarmaya aittir.',[],'sevkten sorumlu DEĞİL; il-ilçenin tamamı jandarmadaysa sevk de jandarmanın'),
 ('15','gorev_yetki','kuduz','sağlık kuruluşuna ivedilikle bildirir','(2) Jandarma kendi görev alanındaki kuduz','yerine getirmekle de yükümlüdür.',[],'gözetim-ayırmada yardım istemini yerine getirir'),
 ('16','gorev_yetki','aile hayatının gizliliğini','konut dokunulmazlığı görevleri','Konut dokunulmazlığına ilişkin görevler','gizliliğini korumakla,',[],'hak ve hürriyetler başlığı DEĞİL'),
 ('17','gorev_yetki','korkusuz ve güvenlik içinde','hak ve hürriyetlerin korunması','Hak ve hürriyetlerin korunmasına','gerekli önlemleri alır.',[],''),
 ('18','gorev_yetki','denetim kesintisiz','silah-bıçak ve av tüfeği izin belgesi işlemleri','(1) Sorumluluk alanında olmak kaydıyla','denetim kesintisiz sürdürülür.',[],'silah izin belgesini vali verir'),
 ('19','tanim','umuma açık istirahat','konaklama, içkili yer, sinema-kahvehane, oyun-internet salonu; düğün salonu DEĞİL','MADDE 19- (1) Kişilerin','ticari yerler de umuma açık istirahat ve eğlence yeri sayılır.',[],'taşıtlarda bu faaliyet varsa o da sayılır; 2026 Subay sınavında soruldu'),
 ('19','sure','görüşünü','yedi gün içinde','Jandarma görüşünü genel güvenlik','yedi gün içinde verir.',[],'ruhsatı belediye, dışında il özel idaresi verir; izinsiz açılan kapatılır'),
 ('19','makam','ruhsatı','belediye; dışında il özel idaresi','(3) Jandarma sorumluluk alanında','il özel idareleri tarafından verilir.',[],'jandarmanın görüşü alınır'),
 ('19','sira_usul','kat’i delil','mülki amire bildirilir','(4) Jandarma tarafından kat’i delil','mülki amire bildirilir.',[],'kumar, uyuşturucu, fuhuş yeri vb.'),
 ('20','makam','İnternet Toplu Kullanım','açma-kapatma mülki amir emriyle; jandarma denetler','MADDE 20- (1) 1/11/2007','mülki amire bildirir.',[],'genel güvenlik ve asayiş yönünden'),
 ('21','sure','gürültü','saat yirmidört sonrası; mesken içi-dışı fark etmez','MADDE 21- (1) Mesken içinde','menolunur.',[],'civar halkının huzurunu bozan; Kabahatler K. ve TCK uygulanır'),
 ('21','sure','Düğün, nişan','kırksekiz saat önce mülki amire bildirilir','(2) Düğün, nişan','bildirimde bulunmak zorundadır.',[],'konser, panayır, festival de'),
 ('22','gorev_yetki','imdat isteyen','herkese yardım; yol soranlara bilgi','a) Bir tehlike karşısında','gereken bilgiyi vermek.',[],'yolda kalana yer, hastaya araç bulur'),
 ('22','sira_usul','teslim almaktan kaçın','jandarma tutanakla saptar, kanuni işlem','(2) Yardıma muhtaçların','kanuni işlem yapılır.',[],'kanuni temsilci'),
 ('22','gorev_yetki','ısrarlı takip','6284 kapsamında koruma; mülki amire bildirim','(4) Jandarma; 8/3/2012','bildirimde bulunmakla görevlidir.',[('42','aykırı emirde amir yazılı ısrar ederse emir yapılır')],'şiddete uğrayan kadın, çocuk, aile bireyleri'),
 ('22','makam','korunmaya, bakıma','Aile ve Sosyal Politikalar Bakanlığına bildirir','(3) Jandarma, 5237 sayılı Kanun','işbirliği içinde bulunmakla görevlidir.',[],''),
 ('23','gorev_yetki','jandarmanın görevine giren','özel kolluk el koyar, haber verir, delili korur, yakalar','(1) Özel kolluk, jandarmanın','eylemcileri yakalar.',[],''),
 ('23','sira_usul','personelinin bulunmadığı','jandarma yetkilerini kullanır; dosyayı onlara devreder','(3) Özel kolluk veya özel güvenlik','teşkilatına devredilir.',[],''),
 ('23','makam','mülki amirin emri veya onayıyla','işyeri çalışanlarının kimlik-nitelik bilgisi istenir','(4) Jandarma, kendi görev','İstenilen bilgiler hemen verilir.',[],''),
 # m.24-36 — cezaevi dış koruma, sevk ve nakil
 ('24','gorev_yetki','dış korunması','jandarmaya ait','MADDE 24- (1) Ceza infaz kurumlarının','jandarmanın kendi kuruluş ve kadrolarında gösterilir.',[],'tutuklu-hükümlünün kaçmasını önler'),
 ('24','yasak','infaz koruma memurluğu','jandarma hiçbir şekilde kullanılamaz','(3) Jandarma hiçbir şekilde','kullanılamaz.',[],'cezaevi iç işlerinde de'),
 ('24','kosul','genel bir hareket ve kargaşa','müdür ya da memur başvurusuyla jandarma müdahale','Ceza infaz kurumlarının içinde burada','sükûnu sağlar.',[],''),
 ('24','yasak','görüşmeleri ve ilişki kurmaları','jandarmaya yasak','Jandarmaların hükümlü ve tutuklularla','karışmaları yasaktır.',[],'cezaevi içindeki işlere karışmak da yasak'),
 ('24','yasak','girmesi yasak olan silah','sokulmasına jandarma engel olur','(4) Jandarma ceza infaz kurumlarına','engel olur.',[],''),
 ('24','yasak','jandarma muhafazasında olmadıkça','hiçbir tutuklu dışarı gönderilemez','(5) Ceza infaz kurumlarının yetkili','dışarıya gönderilemez.',[],'yetkili izni de şart'),
 ('25','makam','muhafız devriyenin kuvvetini','jandarma komutanı saptar','MADDE 25- (1) Soruşturma ve duruşmalar','hazır bulundurur.',[],'isim listesini infaz kurum müdürü yazıyla bildirir'),
 ('25','yasak','başkalarıyla görüşmelerine','izin verilmez','(2) Hükümlü ve tutukluların gerek yolda','izin verilmez.',[],'bir şey alıp vermek de'),
 ('25','sira_usul','inzibat aletleri','savcı-hâkim önünde çıkarılır; çıkışta takılabilir','(3) Hükümlü ve tutuklular','tekrar takılabilir.',[],''),
 ('26','kosul','gönderilmesi gereken','yetkili makamın yazılı istemi; jandarma götürür','MADDE 26- (1) Bir ceza infaz','istenilen yere götürülürler.',[],''),
 ('27','kosul','sevk ve nakillerinin','ceza infaz kurumu araçları; yoksa kamu toplu taşıma','MADDE 27- (1) Hükümlü ve tutukluların','özel taşıtlarla sevk yoluna gidilemez.',[],'kamu aracında özel bölüm zorunlu; ihtiyaçta uçak'),
 ('27','yasak','sevklerde kullanılmaz','jandarmanın hizmet araçları','(3) Jandarmaya ait hizmet','sevklerde kullanılmaz.',[],'ceza infaz kurumu aracı, yoksa toplu taşıma; ihtiyaçta uçak'),
 ('27','kosul','özel taşıt','sağlık mazereti, zorunlu hal dışında yok','Sağlık mazereti bulunanlar','sevk yoluna gidilemez.',[],''),
 ('28','sira_usul','alındı belgesi','alınan para-eşya için tutukluya verilir','Teslim alınan nesnelerin','sevk pusulasına yazılır.',[('65','polis/SG el koyduğu nesneyi jandarmaya alındı belgesiyle teslim eder')],''),
 ('28','kosul','doktor raporuyla','sevk yapılmaz, makama yazı','(3) Sağlık açısından','yazıyla bildirilir.',[],''),
 ('29','kosul','kadın olması','kadın ceza infaz koruma görevlisi verilir','(2) Sevk edilen tutuklu','koruma görevlisi verilir.',[],''),
 ('29','yasak','birlikte sevk','kadın-erkek olmaz; iştirak ve yakınlar hariç','MADDE 29- (1) İştirak halinde','birlikte sevk edilemez.',[],''),
 ('30','sira_usul','yolda hastalan','en yakın hekimli birlik; devam edemezse savcı talimatıyla cezaevine','MADDE 30- (1) Sevk ve nakil','teslim edilir.',[('22','yolda hastalanan yolcuya araç bulur, sağlık kuruluşuna gönderir')],''),
 ('31','sira_usul','birisi öldüğünde','en yakın jandarma birliği, oradan savcılık; devriye komutanı tutanak','MADDE 31- (1) Sevk ve nakil','ilgili makama verilir.',[],''),
 ('32','gorev_yetki','firar hazırlığı','önce ihtar; uymaz ve başka çare yoksa silah','MADDE 32- (1) Sevk ve nakil','silah kullanılır.',[],'ihtarı devriye komutanı yapar'),
 ('32','sira_usul','yaralandığında veya öldüğünde','en yakın jandarma komutanlığı, oradan savcılık','(2) Silah kullanma sonunda','tutanakla saptanır.',[],''),
 ('32','gorev_yetki','başka şekilde önlenmesine','silah kullanılır','Bu ihtara uymayarak','silah kullanılır.',[],'önce ihtar edilir'),
 ('32','makam','sevke devam edip edemeyeceklerini','Cumhuriyet savcısı belirler','(3) Bu gibi durumlarda','o yer jandarması tarafından yapılır.',[],'jandarma tutuklanırsa sevki o yer jandarması yapar'),
 ('33','sira_usul','varılacak biçimde','gündüz','MADDE 33- (1) Sevk ve nakillerde','hareket edilir.',[],'gece DEĞİL'),
 ('33','sira_usul','konaklamak durumunda','cezaevi; zorunlulukta emniyet odası; köyde karakol-köy odası','Zorunluluk nedeniyle konaklamak','kalınabilir.',[],''),
 ('34','kosul','kaçmalarını önlemek','sağlığa zarar vermeyen bütün önlemler','MADDE 34- (1) Tutuklu ve hükümlülerin','gerekli önlemleri alması sağlanır.',[],'gidilecek yerin jandarmasına önceden bilgi'),
 ('35','gorev_yetki','revirlerinde','iyileştirme esas; diğer sağlık kurumunda muhafaza jandarmanın','MADDE 35- (1) Tutuklu ve hükümlülerden','jandarma tarafından sağlanır.',[],'özel yerler jandarma görüşüyle önceden hazırlanır'),
 ('36','makam','Adalet Bakanlığınca düzenlenen','çalıştırmada muhafaza jandarma; diğer kurumlarınkinde cezaevi personeli','MADDE 36- (1) Adalet Bakanlığınca','personelince yürütülür.',[],''),
 ('37','gorev_yetki','Diğer mülki görevler','mülki amirin karar ve emirlerini uygular','Diğer mülki görevler','emirleri uygular.',[],'huzur, kişi dokunulmazlığı, kamu esenliği, suç önleme amacıyla'),
 # m.38-41 — adli ve askeri görevler
 ('38','makam','Soruşturma işlemleri','adli kolluğa','(2) Soruşturma işlemleri','adli kolluğa yaptırılır.',[('61','jandarma CMK soruşturma görevlerini yapar, mülki amire bilgi verir')],'Cumhuriyet savcısının emir ve talimatıyla; 2026 Subay sınavında soruldu'),
 ('38','makam','haricindeki hizmetlerde','üstlerinin emrinde','Adli kolluk, adli görevlerin haricindeki','üstlerinin emrindedir.',[],'adli görevde savcının emrinde'),
 ('39','kosul','soruşturulması ve kovuşturulması','5271 sayılı Ceza Muhakemesi Kanunu','MADDE 39- (1) Ceza muhakemesine','esaslara göre yürütülür.',[],'adli amirlerin talimatına göre hareket'),
 ('39','sira_usul','amirlerin talimat','adli amirlerin talimatı ve ilgili mevzuata göre','Adli görevler bakımından ilgili mevzuat','talimatlarına göre hareket edilir.',[],'adli görevlerde'),
 ('40','makam','yeme, içme ve nakil','Jandarma Genel Komutanlığı bütçesinden; adli makama çıkarılıncaya kadar','MADDE 40- (1) Gözaltına alınan','bütçesinden ödenir.',[],'yalnız adli makam önüne çıkarılıncaya kadar'),
 ('40','makam','yakıt ve benzeri','Jandarma Genel Komutanlığı bütçesinden; jandarma taşıtıyla sevkte','MADDE 40- (1) Gözaltına alınan','bütçesinden ödenir.',[],'sevk JGK taşıtıyla yapılırsa'),
 ('41','makam','belirlenecek bölümleriyle','kuvvet komutanlıkları emrine girer','MADDE 41- (1) Jandarma birlikleri;','normal görevlerine devam eder.',[],'Bakanlar Kurulu kararıyla belirlenen bölümler; kalanı normal görevde'),
 ('41','kosul','seferberlik ve savaş halinde','2941 sayılı Seferberlik ve Savaş Hali Kanunu','Jandarma, seferberlik ve savaş halinde','verilen görevleri yapar.',[],''),
 ('41','makam','garnizon komutan','vali onayı','(2) Jandarma birlikleri; Genelkurmay','Bakanlıkça belirlenir.',[('8','askeri görev tanımında da illerde garnizon talebi + vali onayı')],'onaysız doğrudan görev DEĞİL'),
 ('41','makam','Genelkurmay Başkanlığının talebi','Bakanın onayı','(2) Jandarma birlikleri; Genelkurmay','Bakanlıkça belirlenir.',[],'görevin kapsamını Genelkurmay ve Bakanlık belirler'),
 # m.42-51 — yetkiler
 ('42','gorev_yetki','sahip olduğu yetki','polisin yetki ve sorumlulukları','Jandarma bu görevlerini yerine getirirken','sorumluluklara sahiptir.',[],'PVSK, CMK, 2803 uygulanır'),
 ('42','kosul','aykırı görürse','yerine getirmez, emri verene bildirir','(2) Jandarma amirinden aldığı emri','emri verene bildirir.',[],''),
 ('42','kosul','ısrar','yazılı tekrar ederse yapılır; yapan sorumlu olmaz','Ancak, amir emrinde ısrar','emri yerine getiren sorumlu olmaz.',[('22','ısrarlı takip mağduruna 6284 koruması')],'AYKIRI EMİR: BİLDİR; YAZILI ISRAR = YAP'),
 ('42','yasak','suç teşkil eden','hiçbir suretle yapılmaz; yapan sorumlu','Konusu suç teşkil eden','sorumluluktan kurtulamaz.',[],'yazılı tekrar da meşrulaştırmaz'),
 ('42','kosul','sözlü emirler','derhal yapılır; yazılı istenemez; sorumluluk verende','yetkili amir tarafından verilecek sözlü','sorumluluk emri verene aittir.',[],'can-ırz-mal, devlet güvenliği, kaçanı yakalama, suçun devamını önleme, arama, kanunsuz toplantı, afet, tören düzeni, tıkalı yol; 2026 Subay sınavında soruldu'),
 ('43','gorev_yetki','trafiği düzenlemeye','polis alanı dışında; trafik suçlarına el koyar','b) Polisin sorumluluk alanı dışında','trafik suçlarına elkoymaya,',[],'Karayolları Trafik Yönetmeliğine göre'),
 ('44','gorev_yetki','uyarır','yasak ihlalini ve suçun devamını önlemek için','MADDE 44- (1) Jandarma, mevzuat','riayet edilmesini ister.',[],''),
 ('44','gorev_yetki','zor kullanarak karşı koyan','yakalanır; savcıya derhal bilgi','(2) Görevini yaptığı sırada','emri doğrultusunda işlem yapılır.',[],''),
 ('45','yasak','veli ve vasileri olsa bile','onsekiz yaş altı giremez','(3) Jandarma; bar, pavyon','girmesini engeller.',[],'içkili yer, kıraathane, internet salonu, oyun yeri; belgeli turizm işletmesi hariç'),
 ('45','yasak','küçüklerin çalıştırılması','izne bağlı eğlence-içki yerinde engellenir','(2) Kanuni istisnalar saklı','çalıştırılmasını engeller.',[],'onsekiz yaşından küçükler'),
 ('45','gorev_yetki','şikâyet olmasa bile','genel ahlaka aykırılık, sarkıntılık engellenir','c) Genel ahlaka aykırı','gerekli kanuni işlemleri yapar.',[],'müstehcen eser üreten-satan da'),
 ('46','gorev_yetki','durdurabilir','suç-kabahat-tehlike önleme, kaçan fail-kimlik, yakalama emri; ceza tahsili DEĞİL','MADDE 46- (1) Jandarma, kişileri','amacıyla durdurabilir.',[],''),
 ('46','kosul','durdurma yetkisi','makul sebep (tecrübe ve izlenim)','(2) Durdurma yetkisinin','durdurma işlemi yapılamaz.',[],'süreklilik ve keyfilik yasak'),
 ('46','sure','Durdurma süresi','zorunlu süreyi aşamaz','(4) Durdurma süresi','fazla olamaz.',[],'sebep kalkınca ayrılmaya izin'),
 ('46','yasak','elbise','çıkarılması istenemez; el ile dıştan kontrol','Bu amaçla kişinin üzerindeki elbisenin','açılması istenemez.',[],'aracın içi görünmeyen bölümü de açtırılamaz'),
 ('46','makam','kolluk amirinin','yirmidört saatte hâkim onayına sunulur','Ancak el ile dıştan kontrol hariç','hakimin onayına sunulur.',[],'üst-eşya-araç araması mülki amirin görevlendirdiği kolluk amirinin yazılı emriyle; acelede sözlü'),
 ('46','sira_usul','araç aramalarına','arama gerekçesini içeren belge verilir','Bu fıkra kapsamında yapılan araç','belge verilir.',[],''),
 ('46','sira_usul','jandarma olduğunu belirleyen','belgeyi gösterip kimlik sorar','(8) Jandarma, görevini yerine getirirken','gerekli kolaylık gösterilir.',[],'kimliğini ispat için kolaylık gösterilir'),
 ('46','sira_usul','kimliği belirlenemeyen','tutulur, derhal savcıya haber','(9) Kişilerin kimliğini ispatlayan','Cumhuriyet savcısı haberdar edilir.',[],''),
 ('46','sira_usul','Nüfusa kayıtlı olmadığı','fotoğraf ve parmak izi kaydı','(10) Nüfusa kayıtlı','kayda alınır.',[],''),
 ('46','sira_usul','yabancı olduğunun','Pasaport Kanunu ve Yabancılar ve Uluslararası Koruma Kanunu','(11) Kimliği tespit edilemeyen','hükümlerine göre işlem yapılır.',[],'6458 Yabancılar ve Uluslararası Koruma K.'),
 ('47','makam','önleme araması','sulh ceza hâkimi kararı; gecikmede mülki amir yazılı emri','Önleme araması','gerekli işlemleri yapar.',[],''),
 ('47','kosul','talep yazısında','makul sebeplerin gerekçesi','(2) Arama talep yazısında','gösterilmesi gerekir.',[],''),
 ('47','kosul','kararında veya emrinde','sebep, konu-kapsam, yer, zaman-süre; personel adı DEĞİL','(3) Arama kararında veya emrinde','geçerli olacağı süre.',[],''),
 ('47','kosul','İdarecilerinin talebiyle','üniversite içinde önleme araması','ç) İdarecilerinin talebiyle','giriş ve çıkışlarında.',[],''),
 ('47','yasak','yapılamaz','konut, yerleşim yeri, kamuya açık olmayan işyeri','(5) Konutta, yerleşim yerinde','önleme araması yapılamaz.',[('46','keyfi, sürekli durdurma da yapılamaz')],'eklentileri de; yapılabilir: toplantı-gösteri yeri, genel kurul çevresi, halkın toplandığı yer, üniversite, umuma açık yer, toplu taşıma-taşıt'),
 ('47','kosul','aniden toplulukların','gecikmesinde sakınca var sayılır','(6) Spor karşılaşması','var sayılır.',[],'spor, miting, konser, festival, gösteri'),
 ('47','gorev_yetki','güvenliğini sağladığı bina','emir-karar olmadan aranır; kimlik sorulmadan ibraz','(7) Jandarma, tehlikenin önlenmesi','ibraz etmek zorundadır.',[],'teknik cihazla, gerektiğinde el ile'),
 ('47','sira_usul','Önleme aramasının sonucu','karar-emir veren makama tutanakla','(8) Önleme aramasının sonucu','tutanakla bildirilir.',[],''),
 ('48','gorev_yetki','girebilir','imdat, yangın, su baskını, boğulma; suçun işlenmesi-devamını önleme','MADDE 48- (1) Jandarma;','eklentilerine girebilir.',[],'kira uyuşmazlığı DEĞİL'),
 ('49','gorev_yetki','Silah kullanma yetkisi','ilgili mevzuatına göre','Silah kullanma yetkisi','silah kullanma yetkisine sahiptir.',[('3','genel kolluk tanımında: silah kullanma yetkili')],''),
 ('50','gorev_yetki','yeri ve zamanına bakılmaksızın','suça el koyar, delili yetkili kolluğa teslim','MADDE 50- (1) Jandarma, sorumluluk alanı','görevli ve yetkilidir.',[],'hizmet branşına da bakılmaz'),
 ('51','gorev_yetki','diğer mevzuatta yer alan','mülki görev yetkilerini kullanır','MADDE 51- (1) Jandarma bu Yönetmelikte','yetkileri kullanır.',[],''),
 # m.52-57 — komutanlar
 ('52','makam','Jandarma Genel Komutanı;','Bakana karşı sorumlu','(3) Jandarma Genel Komutanı;','Bakana karşı sorumludur.',[('4','bağlılık maddesinde de Genel Komutan Bakana sorumlu')],'sevk-idare, mevzuatın yürütülmesi, emirlerin uygulanmasından; Astsubay sınavında soruldu'),
 ('52','makam','üst yöneticiye verilen','Jandarma Genel Komutanı','(2) Jandarma Genel Komutanının görev','yerine getirmek.',[],'5018 Kamu Mali Yönetimi'),
 ('53','makam','bulunmadığı zamanlarda','genel komutan yardımcısı vekalet eder','b) Jandarma Genel Komutanının bulunmadığı','yetkilerini kullanmak.',[],''),
 ('54','makam','Bölge komutanı','konuşlu olduğu ilin valisine sorumlu','Bölge komutanı bu görevlerinin','ilin valisine karşı sorumludur.',[('6','geçici bölge komutanlığı da konuşlu il valisine sorumlu')],'operasyonda faaliyet gösterilen ilin valisine de; il-ilçe komutanlıklarına emir verebilir'),
 ('54','makam','kuvvet kaydırması','konuşlu il valisinin onayıyla','MADDE 54- (1) Jandarma bölge komutanları','kuvvet kaydırması yapmakla görevlidir.',[],'terör operasyonu planlama da; diğer valilerle koordinasyonu bu vali sağlar'),
 ('55','tanim','İl jandarma komutanları','il jandarma teşkilatının komutanıdır','(1) İl jandarma komutanları','teşkilatının komutanıdır.',[],'ilçede ilçe jandarma komutanı, karakolda karakol komutanı'),
 ('55','makam','vali tarafından verilen','il J.K. takip ve kontrol eder','ç) Kanunlarla ve vali','sonuçlarını bildirmek.',[('56','kaymakamın verdiğini ilçe J.K.'),('57','ilçe J.K.’nın verdiğini karakol komutanı')],''),
 ('55','makam','Komutanın yokluğunda','komutan yardımcısı aynı yetkileri taşır','(3) İl jandarma komutan yardımcıları','görevlerini yerine getirir.',[('56','ilçe komutan yardımcısı da yoklukta aynı yetkiler')],''),
 ('56','makam','kaymakam tarafından verilen','ilçe J.K. takip eder','d) Kanunlarla ve kaymakam','sonuçlarını bildirmek.',[],''),
 ('57','makam','ilçe jandarma komutanı tarafından','karakol komutanı takip eder','d) Kanunlarla ve ilçe jandarma','sonuçlarını bildirmek.',[],''),
 ('57','gorev_yetki','karakol komutanlarının','tedbir, öneri, adli, denetim, yetiştirme, disiplin, özlük','(2) Jandarma karakol komutanlarının','g) Personelin özlük işlemlerini yürütmek.',[],'lojistik-teknik destek planlama karakol komutanında YOK (il-ilçe komutanında var)'),
 # m.58-66 — çalışma ve işbirliği
 ('58','makam','doğrudan emir','yalnız mülki amir ve adli makam; diğerleri mülki amire başvurur','(3) Mülki amirler ile adli makamlar','görevin ifasını emreder.',[],'belediye başkanı doğrudan emir veremez'),
 ('58','makam','Bakan, jandarma teşkilatı','en üst amir; teşkilatı idare eder','Bakan, jandarma teşkilatının','teşkilatı idare eder.',[],''),
 ('58','makam','il ve ilçe jandarma komutanları','mülki amirlere bağlı ve sorumlu','(2) Jandarma bölge komutanları','bağlı ve sorumlu olarak görev yapar.',[],'bölge komutanı konuşlu il valisine'),
 ('58','makam','doğrudan doğruya sorumlu','mülki amir; jandarma aracılığıyla','(5) Emniyet ve asayiş görevlerinden','jandarma aracılığıyla sağlar.',[],'emniyet ve asayişten'),
 ('58','makam','her kademedeki amir','mülki amirlere karşı sorumlu','(6) Jandarma birimlerindeki','mülki amirlere karşı sorumludur.',[],'görevleri kanuna uygun yürütmekten'),
 ('58','makam','araç ve gereçlerin seçimi','kendi komutanlarına ait','(7) Jandarma birimlerinin','jandarmanın hizmetine verebilir.',[],'yetersizlikte mülki amir başka kurumdan sağlar'),
 ('59','sira_usul','vakit geçirmeksizin','mülki amire sözlü-yazılı; suçsa savcılığa da','MADDE 59- (1) Jandarma; bölgelerindeki','Cumhuriyet savcılığına da bildirilir.',[('74','yakalanan yoklama kaçağı vakit geçirmeksizin askerlik şubesine')],'suç, asayiş olayı, afet, salgın, propaganda; basit alacak-verecek DEĞİL'),
 ('59','sira_usul','afetleri','vakit geçirmeksizin mülki amire, sözlü-yazılı','MADDE 59- (1) Jandarma; bölgelerindeki','Cumhuriyet savcılığına da bildirilir.',[],'suç olayları savcılığa da'),
 ('60','sira_usul','Taşra teşkilatının merkez','Bakanlık ve mülki amirler aracılığıyla','MADDE 60- (1) Jandarma Genel','aracılığı ile yapılır.',[],'resen yazışma yok; teknik, muhasebe, lojistik, özlük hariç'),
 ('60','sira_usul','hak ve yükümlülük doğuran','valilikler aracılığıyla','Hak ve yükümlülük doğuran','valilikler aracılığıyla yapılır.',[],'irade beyanı niteliğindeki yazışma'),
 ('60','sira_usul','yazı işleri','sorumluluk alanına göre jandarma ya da emniyette','(2) İl ve ilçelerde','yürütülür ve dosyalanır.',[],''),
 ('60','sira_usul','emir ve tebligat','jandarma hazırlar, mülki amir imzalar','(3) Emniyet ve asayiş görevlerinden','gereken yerlere gönderilir.',[],''),
 ('60','makam','asayiş raporlarından','il J.K. hazırlar, vali imzalar','(4) Bakanlığa gönderilecek','vali imzasıyla gönderilir.',[],''),
 ('60','sayi_oran','istatistikler','emniyet müdürlüğü beş örnek birleştirir; iki örnek vali imzasıyla Bakanlığa','(5) Emniyet ve asayiş görevlerine','vali imzasıyla Bakanlığa sunulur.',[],'aylık ve yıllık; il J.K., emniyet müdürü, SG komutanı parafe eder; üç örnek ilde kalır'),
 ('61','makam','genel hayatın akışını','mülki amire bilgi verir','MADDE 61- (1) Jandarma, 5271','mülki amire bilgi verir.',[],'soruşturma işlemleri CMK’ya göre'),
 ('62','kosul','Adli kolluk makamları ile işbirliği','Adlî Kolluk Yönetmeliği','MADDE 62- (1) Adli kolluk makamları','Yönetmeliğine göre yürütülür.',[],''),
 ('63','sure','İcra müdürlüklerinin talebi','yediemin otoparkı; üç işgünü içinde bildirim','MADDE 63- (1) İcra müdürlüklerinin','bildirimde bulunulur.',[],''),
 ('64','makam','askeri makamlarla ilişkisi','8 ve 41. maddelerle sınırlı','MADDE 64- (1) Jandarmanın askeri','hallerle sınırlıdır.',[],''),
 ('65','yasak','suçla karşılaş','müdahale, haber; jandarma gelene dek soruşturma yapmaz, korur','MADDE 65- (1) Jandarma sorumluluk alanında','talimatına göre hareket eder.',[('50','jandarma her yerde suça el koyar, delili yetkili kolluğa teslim eder')],'el koyduğu nesneyi alındı belgesiyle teslim; jandarma gelemezse savcıya haber'),
 ('65','kosul','Zorunlu durumlarda, jandarma da','polis-sahil güvenlik alanında birinci fıkra kuralına uyar','(2) Zorunlu durumlarda','hükümlere uygun olarak hareket eder.',[],''),
 ('65','gorev_yetki','Faillerin belirlenmesi','üç kolluk birbirine yardımla yükümlü','(3) Faillerin belirlenmesi','yardımı yapmakla yükümlüdür.',[],''),
 ('65','makam','hangi kolluk kuvvetine','mülki amir belirler','(6) Jandarma, sahil güvenlik ve polisin','mülki amir tarafından belirlenir.',[],'ortak operasyonda komuta, sevk ve idare'),
 ('66','makam','dış ilişkiler uygulama planı','yıllık; Dışişleri görüşü, Bakanlık onayı','MADDE 66- (1) Jandarma Genel Komutanlığı yurtdışında','Bakanlıktan ayrıca alınır.',[],'plan dışı faaliyete ayrıca Bakanlık onayı'),
 ('66','makam','uluslararası kuruluşlara','Bakan onayıyla üye olabilir','(3) Jandarma Genel Komutanlığı, Bakan onayı','üye olabilir.',[],''),
 # m.67-82 — denetim, kadro, görev icrası, planlar, son hükümler
 ('67','makam','denetle','Bakan, Mülkiye Teftiş, vali, kaymakam, Genel Komutan; belediye başkanı DEĞİL','MADDE 67- (1) Bakan her kademedeki','sıralı amirler tarafından da denetlenir.',[('5','Denetleme Grubu merkez teşkilatında'),('19','umuma açık yerleri jandarma denetler'),('20','internet salonlarını jandarma denetler'),('52','Genel Komutan teşkilatı denetler-denetletir'),('53','yardımcı Genel Komutanın emriyle denetler'),('55','il J.K. görev ve işlemleri denetler'),('56','ilçe J.K. görev ve işlemleri denetler'),('57','karakol komutanı görev ve işlemleri denetler')],'sıralı amirler de; Genel Komutan adına Teftiş Kurulu, İç Denetim'),
 ('68','makam','kadro tavanını','yıl içi değişiklik Bakan onayıyla','Yıl içinde ihtiyaç duyulan','Bakandan onay alınır.',[],'kadrolar her yıl bütçe kanunuyla onaylanır'),
 ('69','kosul','Savunma Sanayi Destekleme Fonundan','TSK usulüyle yararlanır','Ancak Jandarma Genel Komutanlığı, Savunma','yararlanır.',[],'ihtiyaçlar kendi bütçesinden; Bakanlık MSB’ye doğrudan teklif eder'),
 ('69','makam','sefer stokları','Millî Savunma Bakanlığı karşılar','(3) Seferberlik ve savaş hallerinde','Millî Savunma Bakanlığınca karşılanır.',[],'kuvvet emrine girecek ya da askeri görev verilen birliklerin'),
 ('70','makam','değişik kılık','gizli takip için; mülki amir ya da il J.K. izni','Ancak suç ve suçluların gizli','hizmet yürütülebilir.',[],'resmî kıyafet esas; istihbarat, kaçakçılık, terör için de'),
 ('70','makam','farklı tertiplenme','mülki amir onayıyla','(2) Mülki amirin onayı ile','farklı tertiplenme ile göreve gönderilebilir.',[],''),
 ('71','makam','birbirlerinin sorumluluk alanlarında','yetersiz kalırsa, mülki amir onayıyla, süreksiz','MADDE 71- (1) Jandarma, sahil güvenlik','mülki amirin onayı ile yapılır.',[],'sonuç alınınca kendi görevine döner'),
 ('72','gorev_yetki','görevlendirilen ekipler','jandarma alanıyla sınırlı değil; mahallin mülki amirine bilgi','(2) Görevlendirilen ekiplerin','mülki amirine karşı da sorumludur.',[],'Bakanlıkça ya da vali talebiyle; iller arası valiliklerce'),
 ('72','makam','önemli olayları','Bakanlık doğrudan ya da vali talebiyle ekip görevlendirir','MADDE 72- (1) Kamu düzeni ve güvenliği','ekipler görevlendirilebilir.',[('59','suç ve diğer önemli olaylar vakit geçirmeksizin mülki amire bildirilir')],'kamu düzeni, kaçakçılık, uyuşturucu'),
 ('73','makam','tahsis','Bakanın onayı','MADDE 73- (1) Bakanın onayı ile','bedelsiz olarak devredebilirler.',[],'JGK, SGK, EGM silah-taşıt-taşınmaz; bedelsiz devir de'),
 ('74','sure','yoklama kaçağı','en geç yirmidört saatte askerlik şubesine','Yoklama kaçağı, bakaya','en yakın askerlik şubesine getirilirler.',[],'vakit geçirmeksizin; bakaya da'),
 ('74','makam','yakalanmaları için','Milli Savunma İçişlerine, askerlik şubesi mülki amire bildirir','(1) Yoklama kaçakları ve bakayalar','mülki amire bildirilirler.',[],''),
 ('74','kosul','teslim alınamayan','tutanakla derhal serbest','Askerlik şubesince teslim','derhal serbest bırakılırlar.',[],''),
 ('74','makam','Firar, izin veya hava değişimi','yakalama kararı varsa jandarma arar','(2) Firar, izin veya hava değişimi','talimatı doğrultusunda işlem yapılır.',[],'adli makam talimatıyla işlem'),
 ('75','tanim','Emniyet ve asayiş planları','suç önleme-müdahale, doğal afet-yardım, koruma-müdahale harekât','Emniyet ve asayiş planları','müdahale harekat planı hazırlar.',[('23','işyeri gözetim usulü emniyet ve asayiş planlarında düzenlenir')],'stratejik hedef planı bu maddede DEĞİL (m.76)'),
 ('75','makam','Planlar','mülki amir onayıyla yürürlüğe; örneği Jandarma Genel Komutanlığına','(3) Planlar, mülki amirin onayı','Jandarma Genel Komutanlığına gönderilir.',[('23', 'işyeri gözetim usulü emniyet ve asayiş planlarında'), ('53', 'genel komutan yardımcısı gelişim planlarını hazırlar')],'mülki amirlik, jandarma, SG, polis birimlerinde saklanır'),
 ('76','sure','stratejik hedef planı','beş yıllık, Bakan onayı, iki yılda bir gözden geçirme','Stratejik hedef planı','en az iki yılda bir gözden geçirilir.',[],'en az iki yılda bir'),
 ('77','yasak','tebligat','Tebligat Kanunu; mevzuatta yoksa jandarmaya verilemez','MADDE 77- (1) Tebligat','yerine getirilemez.',[('60','emir ve tebligatı jandarma hazırlar, mülki amir imzalar')],''),
 ('78','makam','sancaklar','Jandarma Müzesinde muhafaza','MADDE 78- (1) Jandarma Genel Komutanlığı','muhafaza edilir.',[],''),
 ('79','makam','düzenleyici işlemler','Bakanlık yürürlüğe koyar','MADDE 79- (1) Bu Yönetmeliğin','Bakanlık tarafından yürürlüğe konulur.',[],''),
 ('80','kosul','83/7362','Bakanlar Kurulu Kararı; eski yönetmelik kaldırıldı','MADDE 80- (1) 3/11/1983','yürürlükten kaldırılmıştır.',[],''),
 ('80','sure','8 inci maddesinde sayılan','otuz güne kadar faaliyetten men','“2559 sayılı Kanunun 8 inci','faaliyetten men edilir.',[],'ruhsatsızsa süresiz; mahallin en büyük mülki idare amiri'),
 ('80','sure','mühürle','yetkili idare üç işgünü içinde; yapmazsa kolluk resen','Yetkili idare en geç üç işgünü','yetkili idareye bilgi verilir.”',[],''),
 ('81','sure','yürürlüğe girer','yayımı tarihinde','MADDE 81- (1) Bu Yönetmelik','yürürlüğe girer.',[('10','komisyon kararı İçişleri Bakanı onayıyla yürürlüğe girer')],''),
 ('82','makam','Yönetmelik hükümlerini','Cumhurbaşkanı yürütür','MADDE 82- (1) Bu Yönetmelik hükümlerini','Cumhurbaşkanı yürütür.',[],'eskiden Bakanlar Kurulu'),
]
yaz(17, 'Jandarma Teşkilat, Görev ve Yetkileri Yönetmeliği', K)
