# 2803 Jandarma Teşkilat, Görev ve Yetkileri Kanunu — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('3','tanim','silahlı genel kolluk kuvvetidir','jandarmanın tanımı; emniyet, asayiş, kamu düzeni','Türkiye Cumhuriyeti Jandarması','silahlı genel kolluk kuvvetidir.',[],''),
 ('4','makam','İçişleri Bakanlığına bağlıdır','Jandarma Genel Komutanlığı','Jandarma Genel Komutanlığı İçişleri','bağlıdır.',[],''),
 ('5','makam','konuş yerleri','İçişleri Bakanlığınca düzenlenir','Jandarma Genel Komutanlığının kuruluş','Genelkurmay Başkanlığının görüşü alınır.',[],'seferberlik ve savaşta Kuvvet emrine girecek birlikler için Genelkurmay görüşü; mülki taksimat esas'),
 ('5','makam','Bölge komutanı','konuşlu olduğu ilin valisine karşı sorumlu','Bölge komutanı','görev yapar.',[],'bölge teşkilatı geçici, birden çok il'),
 ('7','gorev_yetki','dış korunmalarını','mülki görev','a) Mülki görevleri','dış korunmalarını yapmak,',[],'ceza infaz kurumu ve tutukevi dış koruması'),
 ('7','gorev_yetki','kaçakçılığı men, takip ve tahkik','mülki görev','a) Mülki görevleri','dış korunmalarını yapmak,',[],''),
 ('7','gorev_yetki','İşlenmiş suçlarla ilgili','adli görev','b) Adli görevleri','adli hizmetleri yerine getirmek.',[],'askeri görev: kanun ve CB kararnamesiyle verilen askeri hizmet'),
 ('8','makam','Kuvvet Komutanlıkları emrine girer','seferberlik ve savaşta, Cumhurbaşkanı kararıyla belirlenen bölümleriyle','Jandarma birlikleri; seferberlik','normal görevlerine devam eder.',[],'kalan bölüm normal görevine devam eder'),
 ('8','makam','garnizon komutanının talep etmesi','valinin onayıyla askeri görev','Ayrıca, Jandarma birlikleri','askeri görevleri de yaparlar.',[],'Genelkurmay talep ederse İçişleri Bakanı onayı'),
 ('9','yasak','hiçbir görev jandarmadan istenemez','kanun, nizam, emir ve kararların öngörmediği','Kanun ve nizamlar ile','jandarmadan istenemez.',[],''),
 ('10','gorev_yetki','polis teşkilatı bulunmayan yerlerdir','jandarma görev alanı','Jandarmanın genel olarak görev ve sorumluluk alanı','polis teşkilatı bulunmayan yerlerdir.',[],'il ve ilçe belediye hudutları dışı da'),
 ('10','makam','bir il veya ilçenin tamamı','İçişleri Bakanının kararıyla polis ya da jandarma alanı','İçişleri Bakanının kararıyla bir il','olarak belirlenebilir.',[],''),
 ('10','makam','komisyon','sınırları belirler; ilçede kaymakam, ilde vali başkanlığında','İl ve ilçelerdeki jandarma ve polis','bir komisyon tarafından belirlenir.',[],'jandarma ve emniyet temsilcileri; karar İçişleri Bakanı onayıyla yürürlüğe girer'),
 ('10','sure','en geç üç ay içerisinde','belediye sınırı değişince sorumluluk alanı yeniden düzenlenir','Büyükşehir, il veya ilçe belediyesi','yeniden düzenlenir.',[],''),
 ('10','makam','birbirlerinin sorumluluk sahalarında','mahalli mülki amir geçici görevlendirir','Jandarma veya Emniyet Teşkilatı, kendi','görevlendirilebilirler.',[],'yetersiz kalma halinde'),
 ('12','makam','il valilerine devredebilir','İçişleri Bakanı, geçici personel görevlendirme yetkisini','Lüzum görüldüğü hallerde','il valilerine devredebilir.',[],'EGM, Sahil Güvenlik, Jandarma arası'),
 ('12','makam','bedelsiz olarak devredebilirler','silah, taşıt, taşınmaz; İçişleri Bakanı onayıyla','Ayrıca, İçişleri Bakanının onayıyla','bedelsiz olarak devredebilirler.',[],''),
 ('13','kosul','bu Kanunda hüküm bulunmayan hallerde','657 sayılı Devlet Memurları Kanunu','Jandarma Hizmetleri Sınıfı personelinin','657 sayılı Devlet Memurları Kanunu uygulanır.',[],'nasıp, terfi, aylık → 926 / 4678 / 3466 / 3269 / 6191'),
 ('13','sure','60 yaşına','albaylar; generaller 65; İçişleri Bakanı onayıyla görevde kalır','Rütbelerindeki bekleme süresinin','görevde bırakılabilirler.',[],'hizmetine ihtiyaç duyulanlar'),
 ('13','makam','kadrosuzluk tazminatı','albay ve üstü, bekleme süresi dolmadan Cumhurbaşkanı onayıyla emekli','İlgili personel, personel kaynağı','emekliye sevk edilebilir.',[],''),
 ('13','makam','Subaylığa ve astsubaylığa nasıp','İçişleri Bakanlığının onayıyla','Subaylığa ve astsubaylığa nasıp','İçişleri Bakanlığının onayıyla yapılır.',[],''),
 ('13','makam','uzman erbaşların nasıp ve terfileri','Jandarma Genel Komutanlığınca, özel kanunlarına göre','Uzman jandarma ve uzman erbaşların nasıp','özel kanunlarına göre yapılır.',[],'uzman jandarma da'),
 ('13/A','makam','yükseköğretim kurumu olarak','Akademi, İçişleri Bakanlığına bağlı; giderleri JGK bütçesinden','yükseköğretim kurumu olarak','Jandarma Genel Komutanlığı bütçesinden karşılanır.',[],''),
 ('13/A','makam','Akademi Başkanı','İçişleri Bakanı atar; general, amiral, albay ya da profesör','Akademi Başkanı, en az yüksek lisans','en fazla dört başkan yardımcısı atanır.',[],'en az yüksek lisans; en fazla dört yardımcı'),
 ('13/A','sayi_oran','haftada yirmi','ders ücreti sınırı; yılda üç yüz altmış saat','Akademide ücret karşılığı','ders ücreti ödenir.',[],''),
 ('14','makam','dışında kalanlar İçişleri Bakanınca yapılır','atama; general, bölge ve il komutanı hariç','Jandarma Genel Komutanı, Genel Komutan Yardımcıları','İçişleri Bakanınca yapılır.',[],'JGK, yardımcıları, generaller, bölge ve il komutanı dışındakiler'),
 ('14','makam','valilik emrine atanır','nokta ataması yapılmayanlar; il içi yer değişikliği vali yapar','Nokta ataması yapılmayan','vali tarafından yapılır.',[],'subay, astsubay, uzman jandarma'),
 ('15','kosul','mülki görevlerinden doğan suçlarında','4483 sayılı Kanun (Memurların Yargılanması)','b) Jandarma personelinin mülki','hükümlerine göre işlem yapılır.',[],''),
 ('15','kosul','Adli görevlerinden doğan suçlarda','CMK 161 inci maddesinin beşinci fıkrası','c) Adli görevlerinden','beşinci fıkrası hükmü uygulanır.',[],''),
 ('15','kosul','askeri görev verildiği','askeri birlik personelini yargılayan mahkeme','Jandarma personeline askeri görev verildiği','yetkili olan mahkemede görülür.',[],''),
 ('15','kosul','kişisel suçlarında','genel hükümler','e) Jandarma personelinin kişisel','genel hükümlere göre işlem yapılır.',[],''),
 ('15','ceza','daha fazla süreyle hapis','ilişik kesilir; İçişleri Bakanının onayıyla','Ertelenmiş, seçenek yaptırımlara','İçişleri Bakanının onayı ile kesilir.',[],'kasten suçtan bir yıl ve üstü hapis; affa uğrasa, ertelense, HAGB olsa bile; sayılan katalog suçlar'),
 ('15/A','sure','yirmi dört saat içinde','gecikmesinde sakınca: komutanın yazılı emri, hâkim onayına sunulur','Tehlikenin veya suç işlenmesinin','gerekli işlemler yapılır.',[],'asıl kural sulh ceza hâkimi kararı'),
 ('15/A','kosul','erbaş ve erlerin üstü','jandarma hizmet binalarında aranır; sulh ceza hâkimi kararı','Tehlikenin veya suç işlenmesinin','gerekli işlemler yapılır.',[],'özel kâğıtları ve eşyası da'),
 ('15/A','yasak','Konutta ve yerleşim yerinde','önleme araması yapılamaz','Konutta ve yerleşim yerinde','önleme araması yapılamaz.',[],''),
 ('18','makam','bütçesinden ayrı olarak düzenlenir','JGK bütçesi; İçişleri Bakanlığı bünyesinde','Jandarma Genel Komutanlığının bütçesi','ayrı olarak düzenlenir.',[],''),
 ('19','makam','sefer stokları dahil','Kuvvet emrine giren birliklerin ihtiyacı Milli Savunma Bakanlığınca','Seferberlik ve savaş hallerinde Kuvvet','Milli Savunma Bakanlığınca sağlanır.',[],'normalde JGK kendi bütçesinden'),
 ('19','kosul','Savunma Sanayi Destekleme Fonundan','TSK\'nın tabi olduğu usulle yararlanır','Ancak Jandarma Genel Komutanlığı, Savunma Sanayi','dahilinde yararlanır.',[],''),
 ('19','kosul','ihtiyaç fazlası ve standart dışı','4645 sayılı Kanun (EGM) hükümlerine göre devir','Jandarma Genel Komutanlığının ihtiyaç fazlası','hükümlerine göre yürütülür.',[],''),
 ('21','sayi_oran','Komando ve sınır birliklerinde','asayiş tazminatı en çok yüzde elli iki','Jandarma Genel Komutanlığı fiili kadrolarına','asayiş tazminatı ödenir.',[],'diğer birliklerde yüzde kırk; metindeki ",20" ve ",21" dipnot numarasıdır'),
 ('21','sayi_oran','Diğer karargah, birlik ve kurumlarda','asayiş tazminatı yüzde kırk','Jandarma Genel Komutanlığı fiili kadrolarına','asayiş tazminatı ödenir.',[],'en yüksek Devlet memuru aylığının; İçişleri Bakanlığı usulüyle'),
 ('21','istisna','vergi ve kesinti yapılmaz','asayiş tazminatından; yalnız damga vergisi','Bu tazminattan damga','kesinti yapılmaz.',[],''),
 ('24','makam','Cumhurbaşkanınca yürürlüğe konulan yönetmelikle','Kanunun uygulama yönetmeliği: teşkilat, terfi, kılık-kıyafet','Bu Kanunla münhasıran','yönetmelikle düzenlenir.',[],''),
 ('Geçici','sayi_oran','rütbe yaş hadleri','teğmen-üsteğmen 49, yüzbaşı 55, binbaşı 56, yarbay 57, albay 60','astsubaylıktan subaylığa geçenlerin','Yaş Haddi 49 55 56 57 60',[],'astsubaylıktan subaylığa geçenler (geçici madde 12)'),
]
yaz(2, '2803 sayılı Jandarma Teşkilat, Görev ve Yetkileri Kanunu', K)
