# 2803 Jandarma Teşkilat, Görev ve Yetkileri Kanunu — kelime → cevap
# KURAL (başkan, 4 Eki 2026): SOL = soru KÖKÜNDE göreceğin ifade, SAĞ = doğru ŞIKTA arayacağın kelime.
# Sorulardan geriye doğru yazıldı (237 cevaplı soru + kitapçık kökleri); kanıt resmî metin.
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 # m.1-3 — konu, kapsam, tanım
 ('1','tanim','Teşkilatının görev, yetki ve sorumluluklarına','görev-yetki-sorumluluk, bağlılık-ilişkiler, teşkilat-konuş; özel hukuk sözleşmesi YOK','Madde 1 – Bu Kanun','esas ve usulleri düzenler.',[],''),
 ('2','tanim','kapsar','karargah, birlik, kurumlar ve buralarda hizmet gören personel','Madde 2 – Bu Kanun','faaliyet ve esasları kapsar.',[],''),
 ('3','tanim','Türkiye Cumhuriyeti Jandarması','silahlı genel kolluk; emniyet-asayiş, kamu düzeni; yalnız şehir merkezi DEĞİL','Türkiye Cumhuriyeti Jandarması','silahlı genel kolluk kuvvetidir.',[],'özel, silahsız, askeri kolluk DEĞİL; 2026 Astsubay sınavında soruldu'),
 ('3','tanim','verdiği görevleri','diğer kanunlar ve Cumhurbaşkanlığı kararnameleri','Türkiye Cumhuriyeti Jandarması','silahlı genel kolluk kuvvetidir.',[],''),
 # m.4-5 — bağlılık, kuruluş
 ('4','makam','bağlıdır','İçişleri Bakanlığı','Jandarma Genel Komutanlığı İçişleri','Bakanlığına bağlıdır.',[],'Milli Savunma Bakanlığı DEĞİL; 2026 Uzman sınavında soruldu'),
 ('5','makam','kuruluş ve kadrolarıyla konuş','İçişleri Bakanlığı düzenler','Jandarma Genel Komutanlığının kuruluş','İçişleri Bakanlığınca düzenlenir.',[],'Kuvvet emrine girecek birliklerde Genelkurmay görüşü alınır'),
 ('5','makam','emrine girecek birliklerin','Genelkurmay Başkanlığının görüşü alınır','Ancak seferberlik ve savaşta Kuvvet','Genelkurmay Başkanlığının görüşü alınır.',[('8','emrine girecek BÖLÜMLERİ Cumhurbaşkanı kararıyla belirlenir'),('19','bu birliklerin ihtiyacını Milli Savunma Bakanlığı sağlar')],'kuruluş, kadro ve konuş yerlerinin düzenlenmesinde'),
 ('5','kosul','birliklerinin kuruluş ve konuşlarının','mülki taksimat esas alınır','Jandarma birliklerinin kuruluş ve konuşlarının','mülki taksimat esas alınır.',[],'ordu, bölge, kuvvet taksimatı DEĞİL; 2026 Uzman sınavında soruldu'),
 ('5','kosul','birden çok ili içine alan','geçici olarak bölge teşkilatı kurulabilir','Ancak geçici olarak birden çok ili','bölge teşkilatı da kurulabilir.',[],''),
 ('5','makam','Bölge komutanı','konuşlu bulunduğu ilin valisine karşı sorumlu','Bölge komutanı','görev yapar.',[],''),
 # m.6, Ek 6 — Genel Komutan, yetki devri
 ('6','makam','tüm Jandarma Teşkilatının','komutanı Jandarma Genel Komutanı','Jandarma Genel Komutanı tüm','Teşkilatının komutanıdır.',[],''),
 ('6','makam','nizam hükümlerinin icrasını','Jandarma Genel Komutanı sorumlu; bütçe onayı DEĞİL','Jandarma Genel Komutanı, Teşkilatın sevk','uygulanmasından sorumludur.',[],'sevk-idare, kanun-nizam icrası, emir-karar uygulaması'),
 ('Ek 6','makam','bir kısmını','Jandarma Genel Komutanına veya valilere; sınırları yazılı ve açıkça belirli','İçişleri Bakanı, bu Kanundaki','valilere devredebilir.',[],'İçişleri Bakanının yetki devri'),
 # m.7 — görevler
 ('7','gorev_yetki','mülki görevleri','asayiş, kaçakçılık, ceza infaz kurumu dış koruması; işlenmiş suç DEĞİL','a) Mülki görevleri','emir ve kararlarla Jandarmaya verilen görevleri yapmak.',[('15','mülki görevden doğan suçta 4483 sayılı Kanun uygulanır')],'suç önleme ve diğer kanunlarla verilen görevler de; işlenmiş suç işlemi adli; cezaevi İÇ güvenliği yok'),
 ('7','gorev_yetki','İşlenmiş suçlarla ilgili','adli görev','b) Adli görevleri','adli hizmetleri yerine getirmek.',[],'2026 Astsubay sınavında soruldu'),
 ('7','gorev_yetki','Askeri görevleri','kanunlarla ve Cumhurbaşkanlığı kararnameleriyle verilen askeri hizmetler','c) Askeri görevleri','askeri hizmetleri yerine',[('8','garnizon komutanı talebiyle valinin onayıyla verilen askeri görevler')],''),
 ('Geçici 7','makam','eğitim ve işbirliği','İçişleri Bakanlığı yürütür; anlaşma ve protokollerdeki esaslara göre','Jandarma Genel Komutanlığının halihazırda devam eden yabancı','Bakanlığı tarafından yürütülür.',[],''),
 # m.8 — seferberlik, askeri görev
 ('8','makam','Kuvvet Komutanlıkları emrine','girecek bölümü Cumhurbaşkanı kararıyla belirlenir','Jandarma birlikleri; seferberlik','normal görevlerine devam eder.',[('5', 'emrine girecek birliklerin konuş yerinde Genelkurmay görüşü alınır'), ('19', 'emrine girecek birliklerin ihtiyacını Milli Savunma Bakanlığı sağlar')],'Kuvvet Komutanlıkları emrine girecek bölümleri; kalanı normal görevine devam eder; Genelkurmay, MSB DEĞİL; 2026 Uzman sınavında soruldu'),
 ('8','makam','garnizon komutanının talep etmesi','valinin onayı','Ayrıca, Jandarma birlikleri','askeri görevleri de yaparlar.',[],'illerde askeri görev verilmesi'),
 ('8','makam','Genelkurmay Başkanlığının talebi','İçişleri Bakanının onayı','Ayrıca, Jandarma birlikleri','askeri görevleri de yaparlar.',[],'illerde garnizon talebinde vali'),
 # m.9, Ek 9 — hizmet sınırı, ödül
 ('9','yasak','hiçbir görev','jandarmadan istenemez (kanun-nizam, emir-kararların öngörmediği)','Kanun ve nizamlar ile','jandarmadan istenemez.',[],'hizmet sınırı'),
 ('Ek 9','sayi_oran','yüksek hizmetleri','aylığın iki katından beş katına kadar','a) Ülkenin güvenlik ve esenliği','beş katına kadar,',[],'büyük yararlık: altı katından yirmidört katına'),
 ('Ek 9','sayi_oran','büyük yararlık','aylığın altı katından yirmidört katına kadar','b) Olağanüstü durumlarda','para verilerek ödüllendirilir.',[],'yüksek hizmet: iki katından beş katına'),
 ('Ek 9','makam','kahramanlık','Üstün Cesaret ve Feragat, Şeref, Üstün Hizmet madalyası; İçişleri Bakanı','Jandarma Genel Komutanlığı personelinden kendisine tevdi','Jandarma Üstün Hizmet Madalyası.',[],'cesaret, feragat, kahramanlık, üstün başarı'),
 ('Ek 9','makam','Başka devletlerce tevcih','İçişleri Bakanlığı tasvip ve tescil eder, sonra takılır','Başka devletlerce tevcih edilen madalya','sonra takılabilir.',[],''),
 # m.10 — görev ve sorumluluk alanı
 ('10','gorev_yetki','sorumluluk alanı','belediye hudutları dışı veya polis teşkilatı bulunmayan yerler','Jandarmanın genel olarak görev ve sorumluluk alanı','polis teşkilatı bulunmayan yerlerdir.',[('7','m.7: sorumluluk alanlarındaki görevler mülki, adli, askeri'),('9','m.9: kanunun öngörmediği görev jandarmadan istenemez'),('Ek 5','önleyici dinleme yalnız kendi sorumluluk alanında yapılır')],'polis görev sahası dışı'),
 ('10','kosul','belediye sınırları içinde','hizmet gereği uygun görülen yer jandarma alanı olabilir','Ancak, belediye sınırları içinde','sorumluluk alanı olarak tespit edilebilir.',[],''),
 ('10','makam','bir il veya ilçenin tamamı','İçişleri Bakanının kararı','İçişleri Bakanının kararıyla bir il','olarak belirlenebilir.',[],'polis ya da jandarma alanı olarak; Jandarma Genel Komutanı DEĞİL'),
 ('10','makam','komisyon','ilçede kaymakam, ilde vali ya da vali yardımcısı başkanlığında','İl ve ilçelerdeki jandarma ve polis','bir komisyon tarafından belirlenir.',[('Ek 5','dinleme denetim raporu TBMM Güvenlik ve İstihbarat Komisyonuna sunulur'),('13/A','Akademi ile ilgili komisyon/kurul hükümleri ayrı')],'jandarma ve emniyet temsilcileri katılır; vali veya kaymakamın çağrısıyla toplanır'),
 ('10','sure','değişiklik olması halinde','en geç üç ay içinde yeniden düzenlenir','Büyükşehir, il veya ilçe belediyesi','yeniden düzenlenir.',[],'belediye kurulması, kaldırılması, sınır değişikliği'),
 ('10','makam','yürürlüğe girer','İçişleri Bakanının onayıyla (komisyon kararları)','Komisyon tarafından alınan kararlar','kroki üzerinde gösterilir.',[('13/A','Akademi hükümlerindeki yürürlük tarihi ayrı'),('26','Kanunun kendisinin yürürlüğü')],'sınırlar harita veya kroki üzerinde; Genelkurmay DEĞİL'),
 ('10','makam','yetersiz','kalınca mahalli mülki amirler geçici görevlendirir','Jandarma veya Emniyet Teşkilatı, kendi','görevlendirilebilirler.',[('Ek 8', 'tesislerde personel yetersizliğinde hizmet dışarıdan kiralanabilir'), ('13/A', 'Akademide disiplin notu yetersiz olanın öğrenimine son verilir')],'jandarma ve emniyet birbirinin sahasında'),
 ('10','kosul','diğer güvenlik kuvvetleriyle','işbirliği ve koordinasyon; esasları ve emir komuta yönetmelikle','Jandarmanın diğer güvenlik kuvvetleriyle','yönetmelikle belirlenir.',[],''),
 ('Geçici 3','kosul','polis sahaları','polis yetersizse jandarma devam eder; arttıkça Emniyet Genel Müdürlüğüne devreder','Bu Kanunun yürürlüğe girdiği tarihte, yeterli polis','Genel Müdürlüğüne devreder.',[],''),
 # m.11, Ek 11 — silah kullanma, avukat
 ('11','kosul','silah kullanma yetkisi','kanunlarda öngörülen; hizmete uygun, görev gereği; yönetmelik-genelge DEĞİL','Jandarma, kendisine verilen görevlerin ifası','silah kullanma yetkisine sahiptir.',[],'İçişleri onayına bağlı DEĞİL; 2026 Astsubay sınavında soruldu (yalnız kanun)'),
 ('Ek 11','kosul','avukat','karakol/devriye/sevk/asayiş/kaçakçılık/adli görevden sanığa; Jandarma bütçesinden; trafik tespiti YOK','Kanunlarla veya Cumhurbaşkanlığı Kararnameleriyle verilen','ödenekten karşılanır.',[],'olayın mahiyeti ve kusura göre uygun görülürse; karargâh personeli dahil'),
 ('Ek 11','makam','Avukat tutma ve ücret','İçişleri Bakanlığı yönetmeliği','Avukat tutma ve ücret ödeme','yönetmelikle düzenlenir.',[],''),
 # m.12 — geçici görevlendirme, tahsis
 ('12','makam','her kademedeki personel','İçişleri Bakanı geçici görevlendirir; il valilerine devredebilir','Lüzum görüldüğü hallerde','il valilerine devredebilir.',[],'EGM, Sahil Güvenlik, Jandarma arasında'),
 ('12','makam','birbirlerine geçici olarak tahsis','İçişleri Bakanının onayıyla; bedelsiz devir de olur','Ayrıca, İçişleri Bakanının onayıyla','bedelsiz olarak devredebilirler.',[],'silah, mühimmat, taşıt, taşınmaz'),
 # m.13 — personel ve mevzuat
 ('13','kosul','bu Kanunda hüküm bulunmayan hallerde','657 sayılı Devlet Memurları Kanunu','Jandarma Hizmetleri Sınıfı personelinin','657 sayılı Devlet Memurları Kanunu uygulanır.',[],'Jandarma Hizmetleri Sınıfının özlük işlerinde'),
 ('13','kosul','nasıp ve terfi, aylık','926, 4678, 3466, 3269, 6191 sayılı kanunlar','Ancak, nasıp ve terfi, aylık','tabi personel hakkındaki hükümler uygulanır.',[],'statü ve rütbeye göre; 657 bu listede yok'),
 ('13','kosul','çarşı ve mahalle bekçileri','Emniyetteki emsal bekçinin mali-sosyal hakları; nasıp-terfi hükmü uygulanmaz','Jandarma Hizmetleri Sınıfında yer alan çarşı','ikinci cümlesi uygulanmaz.',[],'926 vb. kanunların nasıp-terfi hükümleri bekçilere uygulanmaz'),
 ('13','makam','Subaylığa ve astsubaylığa','İçişleri Bakanlığının onayı','Subaylığa ve astsubaylığa nasıp','İçişleri Bakanlığının onayıyla yapılır.',[],'2026 Uzman sınavında soruldu'),
 ('13','makam','hizmetlerine ihtiyaç duyulan albaylar','60 yaşına kadar, İçişleri Bakanının onayıyla','Rütbelerindeki bekleme süresinin','görevde bırakılabilirler.',[],'generaller 65; 2026 Subay sınavında soruldu'),
 ('13','makam','kadrosuzluk tazminatı','Cumhurbaşkanı onayı ile emekliye sevk','İlgili personel, personel kaynağı','emekliye sevk edilebilir.',[],'albay ve üstü, bekleme süresi dolmadan'),
 ('13','makam','uzman erbaşların nasıp ve terfileri','Jandarma Genel Komutanlığı, özel kanunlarına göre','Uzman jandarma ve uzman erbaşların nasıp','özel kanunlarına göre yapılır.',[],'uzman jandarma da'),
 ('13','istisna','inha, seçim, görüş alma','İçişleri dışındaki mercilere verilmiş yetkiler uygulanmaz','Nasıp ve terfi yetkilerinin kullanılmasıyla','bakımından uygulanmaz.',[],''),
 ('13','kosul','Ordu Yardımlaşma Kurumu','205 sayılı Kanun; TSK karşılığı rütbe ve kıdemle','Jandarma Genel Komutanlığı personeli hakkında, Türk Silahlı','Kurumu Kanunu uygulanır.',[],''),
 ('13','kosul','İşçilerin işe alınma','4857 sayılı İş Kanunu ve toplu iş sözleşmesi','İşçilerin işe alınma, işyeri değişikliği','sözleşmesi hükümlerine göre yapılır.',[],''),
 ('13','kosul','nam ve hesabına eğitim','Güvenlik Soruşturması ve Arşiv Araştırması Kanunu','Jandarma Genel Komutanlığı nam ve hesabına','arşiv araştırması yapılır.',[],'Akademi öğrencileri de'),
 # m.13/A — Akademi
 ('13/A','makam','yükseköğretim kurumu olarak','İçişleri Bakanlığına bağlı; ihtiyaçları JGK bütçesinden','yükseköğretim kurumu olarak','Jandarma Genel Komutanlığı bütçesinden karşılanır.',[],''),
 ('13/A','makam','Akademi Başkanı','İçişleri Bakanı atar; general, amiral, albay ya da profesör','Akademi Başkanı, en az yüksek lisans','arasından İçişleri Bakanı tarafından atanır.',[],'en az yüksek lisans'),
 ('13/A','makam','başkan yardımcısı','en fazla dört; İçişleri Bakanı atar','Akademi Başkanına yardımcı olmak üzere','en fazla dört başkan yardımcısı atanır.',[],'albaylar veya öğretim üyeleri arasından'),
 ('13/A','makam','Dekanların ataması','İçişleri Bakanınca','Akademi bünyesindeki fakültelerin dekanları','Dekanların ataması, İçişleri Bakanınca yapılır.',[],'dekanlar Akademi Başkanına karşı sorumlu'),
 ('13/A','sayi_oran','ücret karşılığı ders','haftada yirmi, yılda üç yüz altmış saat','Akademide ücret karşılığı ders vermek','ders ücreti ödenir.',[],''),
 ('13/A','sure','dört yıl süreli fakülte','ocak ilk günü yirmi yedi yaş; lisansüstü otuz iki','En az dört yıl süreli fakülte bitirenlerden','ilgili branşlara nasbedilebilirler.',[],'düzeltilmemiş nüfus kaydına göre'),
 ('13/A','ceza','yılının son gününe kadar','öğretim masraflarının iki katını ödeyerek istifa edebilir','eğitime başladıklarının ilk','istifa edebilirler.',[],'lisans-önlisans öğrencisi; yabancı uyruklular hariç'),
 ('13/A','ceza','disiplinsizlik nedeniyle ilişiği','öğretim masraflarının dört katı','sağlık sebebi hariç öğrenciliği','ödemek zorundadırlar.',[],'sağlık dışı sebeple ayrılan iki katı öder'),
 ('13/A','istisna','sağlık sebebi hariç','sağlık sebebiyle ilişiği kesilen tazminat ödemez','sağlık sebebi hariç öğrenciliği','ödemek zorundadırlar.',[('Ek 14','mecburi hizmette ilişiği kesilen subay-astsubay iki katı, disiplinle çıkarılan dört katı öder')],'şehit ve vazife malulü yakını akademik başarısızlıkta muaf'),
 ('13/A','sayi_oran','döner sermaye işletmesi','onmilyon Türk Lirası sermaye','olarak döner sermaye işletmesi kurulmuştur.','sermaye tahsis edilmiştir.',[],'Maliye Bakanlığı uygun görüşüyle artırılabilir'),
 ('13/A','kosul','öğrenimlerine son','verilir: disiplin notu/çıkarma/azami süre/memurluk niteliği/sağlık/giriş niteliği/istek/devamsızlık; askerlik erteleme DEĞİL','Akademide öğrenim gören öğrencilerin aşağıdaki hallerde','ilişik kesilmesine karar verilenler.',[],'kendi isteği: ön sözleşmeli aday ayrılmak isterse'),
 # m.14 — atama
 ('14','makam','ataması','JGK, yardımcıları, generaller, bölge-il komutanları dışındakiler İçişleri Bakanınca','Jandarma Genel Komutanı, Genel Komutan Yardımcıları','nokta atamasına tabi tutulabilir.',[('13/A','Akademi dekanlarının ataması İçişleri Bakanınca')],'Jandarma Genel Komutanının ataması İçişleri Bakanınca YAPILMAZ'),
 ('14','makam','Nokta ataması yapılmayan','valilik emrine atanır; il içi yer değiştirme vali','Nokta ataması yapılmayan','vali tarafından yapılır.',[],'subay, astsubay, uzman jandarma; özel eğitimliler nokta atamasına tabi'),
 ('14','kosul','il jandarma komutanlıklarına general','hizmet gereği uygunsa atanabilir','Hizmet gerekleri bakımından uygun görülmesi halinde il','subaylar da atanabilir.',[],''),
 # m.15, 15/A — disiplin-soruşturma, arama
 ('15','kosul','Disiplin işleri','özel kanun hükümlerine göre','a) Disiplin işleri','özel kanun hükümlerine göre yürütülür.',[],'bugün 7068 sayılı Genel Kolluk Disiplin Kanunu'),
 ('15','kosul','personelinin mülki görevlerinden doğan suçlarında','4483 sayılı Memurların Yargılanması Kanunu','b) Jandarma personelinin mülki','hükümlerine göre işlem yapılır.',[],'özel kanun hükümleri saklı'),
 ('15','kosul','Adli görevlerinden doğan suçlarda','Ceza Muhakemesi Kanunu 161. madde beşinci fıkra','c) Adli görevlerinden','beşinci fıkrası hükmü uygulanır.',[],''),
 ('15','kosul','askeri görev','emrine verildiği askeri birliğin mahkemesi','Jandarma personeline askeri görev verildiği','yetkili olan mahkemede görülür.',[('7','m.7 askeri görev: kanun ve CB kararnamesiyle verilen askeri hizmet'),('8','m.8 askeri görev: garnizon talebinde valinin onayı'),('19','askeri görev verilen birliklerin ihtiyacını MSB sağlar')],''),
 ('15','kosul','kişisel suç','genel hükümler','e) Jandarma personelinin kişisel','genel hükümlere göre işlem yapılır.',[],'görevle ilgisi olmayan suç, ör. komşuyla kavga'),
 ('15','ceza','bir yıl veya daha fazla','İçişleri Bakanı onayıyla ilişik kesilir; katalog suçta süre aranmaz','Ertelenmiş, seçenek yaptırımlara','İçişleri Bakanının onayı ile kesilir.',[],'kasten suçta bir yıl+; ertelense, HAGB, af olsa bile; dokuz ay kasten yaralama ilişik kestirmez'),
 ('15/A','makam','gecikmesinde sakınca','birlik komutanı/kurum amiri yazılı emri; yirmi dört saatte hâkime','Tehlikenin veya suç işlenmesinin','gerekli işlemler yapılır.',[('Ek 5','önleyici dinlemede gecikmede Jandarma Genel Komutanı veya istihbarat başkanının yazılı emri')],'asıl: sulh ceza hâkimi kararı; jandarma hizmet binalarında erbaş-er araması'),
 ('15/A','kosul','erbaş ve erlerin üstü','jandarma hizmet binalarında aranır','Tehlikenin veya suç işlenmesinin','gerekli işlemler yapılır.',[],'özel kâğıtları ve eşyası da; askerlik yükümlüleri'),
 ('15/A','kosul','Arama kararında veya emrinde','sebebi, konusu, kapsamı, yeri, zamanı, süresi; personel adı YOK','Arama kararında veya emrinde','geçerli olacağı süre belirtilir.',[],'aramayı yapacak personelin adı YAZILMAZ'),
 ('15/A','yasak','önleme araması','konutta, yerleşim yerinde ve eklentilerinde yapılamaz','Konutta ve yerleşim yerinde','önleme araması yapılamaz.',[],''),
 ('15/A','sira_usul','Aramanın sonucu','kararı ya da emri veren makama tutanakla bildirilir','Aramanın sonucu','bir tutanakla bildirilir.',[],''),
 # m.18-22 — bütçe, ikmal, özlük, tazminat
 ('18','makam','Komutanlığının bütçesi','İçişleri Bakanlığı bünyesinde, bütçesinden ayrı','Jandarma Genel Komutanlığının bütçesi','ayrı olarak düzenlenir.',[],''),
 ('19','makam','ikmal hizmetleri','kendi bütçesinden; İçişleri Bakanlığı standartlarına uygun','Jandarma Genel Komutanlığı ikmal hizmetleriyle','kendi bütçesinden karşılar.',[],'Savunma Sanayi Destekleme Fonundan TSK usulüyle yararlanır'),
 ('19','makam','Savunma Sanayii Müsteşarlığına','İçişleri Bakanlığı doğrudan teklif eder','Jandarma Genel Komutanlığının ihtiyaçları, İçişleri','güvenlik önceliklerine göre değerlendirilir.',[],''),
 ('19','makam','sefer stokları','Milli Savunma Bakanlığı sağlar','Seferberlik ve savaş hallerinde Kuvvet','Milli Savunma Bakanlığınca sağlanır.',[],'Kuvvet emrine girecek ya da askeri görev verilen birliklerin ihtiyacı'),
 ('19','kosul','ihtiyaç fazlası ve standart dışı','4645 sayılı Kanuna göre devir','Jandarma Genel Komutanlığının ihtiyaç fazlası','hükümlerine göre yürütülür.',[],'EGM araç-gereç kanunu'),
 ('19','kosul','muafiyet ve istisna','MSB-TSK’ya tanınan gümrük, vergi, harç muafiyetleri Jandarma Genel Komutanlığına da','Bütçe kanunları ve diğer kanunlarla Milli Savunma','hakkında da uygulanır.',[],''),
 ('20','kosul','haklardan da yararlanır','926 ve 657 sayılı kanunlar ile diğer kanunlar','Madde 20 – Jandarma Genel Komutanlığı personeli','haklardan da yararlanır.',[],'özlük hakları bakımından'),
 ('21','sayi_oran','Komando ve sınır','% 52 en yüksek memur aylığının','Jandarma Genel Komutanlığı fiili kadrolarına','asayiş tazminatı ödenir.',[],'asayiş tazminatı üst sınırı, en yüksek Devlet memuru aylığına göre; diğer birliklerde yüzde kırk; metindeki 20 ve 21 dipnot numarası'),
 ('21','sayi_oran','Diğer karargah','% 40 en yüksek memur aylığının','Jandarma Genel Komutanlığı fiili kadrolarına','asayiş tazminatı ödenir.',[],'komando ve sınırda yüzde elli iki'),
 ('21','makam','asayiş tazminatı','komando-sınır %52, diğer %40; usul İçişleri; damga dışı vergi yok','Jandarma Genel Komutanlığı fiili kadrolarına','asayiş tazminatı ödenir.',[],'fazla çalışma karşılığı; usul İçişleri Bakanlığınca'),
 ('21','istisna','vergi ve kesinti','damga vergisi hariç yapılmaz','Bu tazminattan damga','kesinti yapılmaz.',[],''),
 ('22','kosul','beslenme usulleri','uzman jandarmalar ile erbaş ve erler: özel kanunlarında','Madde 22 – Uzman jandarmaların','özel kanunlarında gösterildiği gibidir.',[],'erbaş ve erlerin kaynakları, hizmet süreleri, kıyafetleri de'),
 ('24','makam','Kanunun uygulanmasına ilişkin diğer hususlar','Cumhurbaşkanınca yönetmelik: teşkilat/görev/komuta-kontrol/terfi/değerlendirme/ödül/kıyafet; izin YOK','Bu Kanunla münhasıran','yönetmelikle düzenlenir.',[],''),
 # Ek 1, Ek 2 — denetim, değerlendirme raporu
 ('Ek 1','makam','eylem ve işlemleri','İçişleri Bakanlığı, mülki idare amirleri, kendi amirleri; TBMM-Genelkurmay YOK','eylem ve işlemleri İçişleri Bakanlığı','teftiş edilir.',[],'denetler ve teftiş eder'),
 ('Ek 2','makam','merkez ilçe jandarma komutanı','il valisi düzenler','İl jandarma komutanı ile merkez','değerlendirme raporu düzenlenir.',[],'her yıl sonunda değerlendirme raporu'),
 ('Ek 2','makam','ilçe jandarma komutanı hakkında','kaymakamın değerlendirmesi alınarak il valisi','İl jandarma komutanı ile merkez','değerlendirme raporu düzenlenir.',[],'il ve merkez ilçe komutanında doğrudan il valisi'),
 ('Ek 2','kosul','Değerlendirme raporları','terfi, ödüllendirme, atama ve yer değiştirmede dikkate alınır','Değerlendirme raporları; personelin terfi','yönetmelikle düzenlenir.',[],'içerik ve esaslar İçişleri Bakanlığı yönetmeliği; MSB DEĞİL'),
 # Ek 3 — izinler
 ('Ek 3','sure','yıllık izin hakkı','her yıl otuz gün, yol dahil değil','a) Personelin her yıl otuz','Bu müddete yol dâhil değildir.',[],''),
 ('Ek 3','sure','kısa süreli mazeretlerde','on beş güne kadar yıllık mazeret izni','Ayrıca, kısa süreli mazeretlerde','yıllık mazeret izni verilebilir.',[],''),
 ('Ek 3','sure','müteakip sene içinde','toplam altmış günü geçemez','ç) Yıllık izinlerin senesi içinde','altmış günü geçemez.',[],'hizmet, alıkonulma, esaret gibi zorunlu nedenlerle'),
 ('Ek 3','makam','izinden geriye','asgari yıllık izin planlamasını onaylayan makam','d) Görev ve hizmet ihtiyacının','izinden geriye çağrılabilir.',[],'savaş ve olağanüstü halde Cumhurbaşkanı izinleri kısaltır ya da kaldırır'),
 ('Ek 3','sure','evlenmesi halinde','yedi güne kadar mazeret izni','a) Eşinin doğum yapması','mazeret izni verilebilir.',[],'kendisinin veya çocuğunun evlenmesi'),
 ('Ek 3','sure','mazeret izin','doğum-ölüm on gün, evlenme yedi, afet otuz; askerlik kaydı YOK','birinci fıkrada yazılı on beş günlük yıllık mazeret izinleri dışında','otuz güne kadar mazeret izni verilebilir.',[],'doğum, eşin-çocuğun-ana-baba-kardeşin ölümü on gün; kendisinin ya da çocuğunun evlenmesi yedi'),
 ('Ek 3','sure','Yangın, deprem, su baskını','bir yıl içinde otuz güne kadar mazeret izni','b) Yangın, deprem, su baskını','mazeret izni verilebilir.',[],''),
 ('Ek 3','sure','radyoaktif ışınlarla','her yıl ayrıca bir aylık izin','c) Hizmetleri sırasında radyoaktif','bir aylık izin verilir.',[],'yıllık izinden ayrı'),
 ('Ek 3','sure','kaza geçirmesi','üç aya kadar aylıklı; bir katına kadar uzatılır','d) Bakmakla yükümlü olduğu','bir katına kadar uzatılır.',[],'sonra altı aya kadar aylıksız; sağlık kurulu raporu; bir defaya mahsus'),
 ('Ek 3','sure','yüzde 70','bir yıl içinde on güne kadar mazeret izni','e) En az yüzde 70','on güne kadar mazeret izni verilir.',[],'engelli ya da süreğen hastalıklı çocuk; ana-babadan yalnız biri'),
 ('Ek 3','kosul','yıllık izne mahsup','mazeret izinleri mahsup edilmez','f) Bu fıkra kapsamında verilen mazeret','yıllık izne mahsup edilmez.',[],''),
 ('Ek 3','sure','Hizmet yapamayacak şekilde hastalanan','geçici hastalıkta toplam fiilen iki yıl','a) Hizmet yapamayacak şekilde hastalanan','iki yılı geçmemek üzere,',[],'hastanede teşhis-tedavi süreleri hariç'),
 ('Ek 3','sure','kötü huylu tümör','toplam fiilen üç yıl','b) Kanser, her türlü kötü huylu tümör','hava değişimine tabi tutulabilirler.',[],'verem, kronik böbrek yetmezliği, akıl ve ruh hastalığı da'),
 ('Ek 3','sure','iklim değiştirme raporları','sıhhi izin süresi dört yıl','c) Sağlık durumundan dolayı','dört yıl olarak hesaplanır.',[],''),
 ('Ek 3','sure','Kadın personele doğum','önce sekiz, sonra on altı; toplam yirmi dört hafta aylıklı','ç) Kadın personele doğum','toplam yirmi dört hafta süre ile aylıklı izin verilir.',[],'çoğul gebelikte doğum öncesine iki hafta eklenir'),
 ('Ek 3','sure','çocuklarını emzirmeleri','ilk altı ay günde üç, sonra bir buçuk saat','Doğum yapan personele çocuklarını emzirmeleri','süt izni verilir.',[],'aylıklı izin bitiminden itibaren'),
 ('Ek 3','kosul','görevlerinden dolayı bir saldırıya','iyileşinceye kadar izinli sayılır','d) Görev esnasında veya görev dışında','iyileşinceye kadar izinli sayılır.',[],'meslek hastalığı da'),
 ('Ek 3','sure','Meslekî bilgi ve görgüsünü','bir yıla kadar yurt dışı izni','2) Meslekî bilgi ve görgüsünü','bir yıla kadar,',[],'İçişleri Bakanlığınca; öğrenimde öğrenim süresi; mazerette yıllık izinle üç aya kadar'),
 ('Ek 3','sure','memleketlerin emsal kurum ve kuruluşlarında','İçişleri Bakanlığınca dört yıla kadar aylıklı izin','a) Yabancı memleketlerin emsal','aylıklı izin verilebilir.',[],''),
 ('Ek 3','sure','uluslararası kuruluşlarda görev','İçişleri onayıyla beş yıla kadar aylıksız izin','b) Yabancı bir memlekette','aylıksız izin verilebilir.',[],''),
 ('Ek 3','sure','barış gücünde','Cumhurbaşkanı kararıyla beş yıla kadar aylıklı izin','barış gücünde görevlendirilenlere','aylıklı izin verilebilir.',[],''),
 ('Ek 3','sure','Savaş ve olağanüstü hallerde','Cumhurbaşkanı izin sürelerini kısaltır ya da kaldırır','Savaş ve olağanüstü hallerde','izinden geriye çağrılabilir.',[],''),
 ('Ek 3','istisna','diğer kanunlarda düzenlenen izin','jandarma personeline uygulanmaz','Subay, sözleşmeli subay, astsubay, sözleşmeli astsubay, uzman jandarmalar','izin hükümleri uygulanmaz.',[],'izin usulü İçişleri Bakanlığı yönetmeliği'),
 # Ek 4, Ek 5 — gözaltı masrafı, önleyici dinleme
 ('Ek 4','makam','yeme, içme','gözaltına alınanların; Jandarma Genel Komutanlığı bütçesinden','Gözaltına alınanların yeme','ödenekle karşılanır.',[],'nakil masrafları da'),
 ('Ek 5','makam','gecikmesinde sakınca bulunan hallerde','Jandarma Genel Komutanı veya istihbarat başkanının yazılı emri','Jandarma, bu Kanunun 7 nci maddesinin (a)','kayda alabilir.',[('15/A','erbaş-er aramasında gecikmede birlik komutanı veya kurum amirinin yazılı emri')],'asıl: hâkim kararı; yalnız kendi sorumluluk alanında'),
 ('Ek 5','sure','verilen yazılı emir','yirmidört saat içinde hâkime; karar kırk sekiz saatte','Gecikmesinde sakınca bulunan hallerde verilen yazılı emir','kırk sekiz saat içinde verir.',[],''),
 ('Ek 5','makam','Yetkili ve görevli hâkim','Ankara ağır ceza mahkemesi üyesi','Yetkili ve görevli hâkim, Ankara','mahkemesi üyesidir.',[],''),
 ('Ek 5','sure','en fazla üç ay','üçer ay, en fazla üç defa uzatılır','Kararlar, en fazla üç ay için verilebilir','müteaddit defalar uzatılmasına karar verebilir.',[],'terör örgütü faaliyetinde müteaddit defa; altı ay DEĞİL'),
 ('Ek 5','sure','terör örgütünün faaliyeti','terörde müteaddit defa; dışında üçer ay, en fazla üç defa','Kararlar, en fazla üç ay için verilebilir','müteaddit defalar uzatılmasına karar verebilir.',[],'hâkim karar verir'),
 ('Ek 5','sure','yok edilir','en geç on gün içinde','Uygulanan tedbirin sona ermesi halinde','ibraz edilmek üzere muhafaza edilir.',[],'dinleme kayıtları; tutanakla tespit'),
 ('Ek 5','makam','aykırı hareket edenler','Cumhuriyet savcılarınca doğrudan soruşturma','Bu madde hükümlerine göre yürütülen faaliyetler','doğrudan soruşturma yapılır.',[],'gizliliği ihlal; görev sırasında işlense bile'),
 ('Ek 5','sure','denetle','sıralı/mülki amir, JGK/bakanlık/Cumhurbaşkanlığı teftişi yılda bir; TBMM komisyonuna; Sayıştay YOK','Bu maddede yer alan faaliyetlerin denetimi','Güvenlik ve İstihbarat Komisyonuna sunulur.',[('Ek 1', 'jandarmanın eylem ve işlemlerini İçişleri, mülki idare amirleri ve kendi amirleri denetler')],'Cumhurbaşkanlığı elemanları da denetleyebilir; sonuç rapor hâlinde TBMM Güvenlik ve İstihbarat Komisyonuna'),
 # Ek 7, Ek 8 — tereddüt, tesisler
 ('Ek 7','kosul','bu Kanuna aykırı','bu Kanun hükümleri uygulanır','Diğer kanunlarda bu Kanuna aykırı','Kanun hükümleri uygulanır.',[('Geçici 1','yönetmelikler çıkana kadar Tüzüğün Kanuna aykırı olmayan hükümleri uygulanır')],'diğer kanunlarda aykırı hüküm varsa'),
 ('Ek 7','makam','tereddütleri gidermeye','İçişleri Bakanlığı','Bu Kanunun uygulanmasıyla ilgili tereddütleri','yetkilidir.',[],'yeni ihtiyaçta düzenleme yetkisi Cumhurbaşkanı'),
 ('Ek 7','makam','yeni ihtiyaçların','Cumhurbaşkanı düzenleme yapar','Bu Kanunda bu maddeyi ihdas eden','Cumhurbaşkanı yetkilidir.',[],'teşkilat, personel, eğitim'),
 ('Ek 8','tanim','tesisler','yatakhane, eğitim-kongre, sosyal tesis, gazino, moral merkezi, kantin; konut YOK','Jandarma Genel Komutanlığı, vardiya yatakhaneleri','kantinler kurabilir.',[],'konut sitesi sayılmamış'),
 ('Ek 8','sayi_oran','gayrisafi hasılatının','yüzde bir her ay genel bütçeye','Özel, yerel ve kış eğitim merkezleri ile birlik','muhasebe birimine yatırılır.',[],'özel, yerel, kış eğitim merkezleri ve birlik dışı kantinler'),
 # Ek 12-19 — sözleşmeli geçiş, uzman erbaş, mecburi hizmet, ilaç, yaş hadleri
 ('Ek 12','sayi_oran','üst sınır','üst sınır: subayda yüzbaşılık, astsubayda kıdemli üstçavuşluk yaş haddi','Jandarma Genel Komutanlığına mensup sözleşmeli','rütbe yaş haddi şeklinde uygulanır.',[],'sözleşmeliden muvazzafa'),
 ('Ek 12','kosul','normal bekleme süresinin bitiminden','geçmişe yönelik hak talebinde bulunamaz','Yüzbaşılık ve astsubay kıdemli üstçavuşluk','hak talebinde bulunamaz.',[],''),
 ('Ek 13','sure','uzman erbaş adaylarının','ocak ilk günü itibarıyla yirmiyedi yaşını bitirmemiş','Jandarma Genel Komutanlığında istihdam edilecek uzman erbaş','bitirmemiş olması gerekir.',[],''),
 ('Ek 13','sure','muvazzaf askerlik yükümlülüğüne başlamadan','beş yıllık sözleşme; askerlik işlemleri ertelenir','Muvazzaf askerlik yükümlülüğüne başlamadan','askerlik işlemleri ertelenir.',[],''),
 ('Ek 13','sure','askerlik hizmetini yerine getirmiş','üç yıllık hizmet süresini tamamlayanlar','Birinci fıkra kapsamındakilerden, Jandarma','yerine getirmiş sayılır.',[],'bilgiler İçişleri Bakanlığınca MSB’ye bildirilir'),
 ('Ek 13','sure','Üç yıllık süre','fiilen göreve başlanılan tarihte başlar','Üç yıllık süre, fiilen','tarihte başlar.',[],''),
 ('Ek 13','kosul','ilişiği kesilen personel','askerlik hizmetini yerine getirir','Üç yıllık süreyi tamamlamadan','askerlik hizmetini yerine getirir.',[],'üç yıl dolmadan hangi nedenle olursa olsun'),
 ('Ek 14','sure','mecburi hizmet','nasıptan fiilen on beş yıl; statü değişikliği uzatmaz','a) Muvazzaf subay veya astsubayların mecburi','tarihten itibaren on beş yıldır.',[('13/A', 'm.13/A: dışarıdan alınan öğrencinin mecburi hizmeti Akademi öğrencisi gibi'), ('Ek 3', 'm.Ek 3: aylıksız izin süresi mecburi hizmetten sayılmaz')],'statü değiştirende ilk statüye nasıp tarihinden'),
 ('Ek 14','sure','lisans veya lisansüstü öğrenim','yükümlülük buralarda geçen süre kadar uzar','b) Subay veya astsubay nasbedildikten sonra','geçen süreler kadar uzatılır.',[],'tıp-diş uzmanlığı ve doktorada sürenin yarısı kadar'),
 ('Ek 14','sure','uzmanlık ya da yan dal','buralarda geçen sürelerin yarısı kadar uzar','c) Jandarma Genel Komutanlığı hesabına yurt içinde tıp','yarısı kadar uzatılır.',[],'tıpta, diş hekimliğinde, eczacılıkta doktora da'),
 ('Ek 14','sure','Pilotaj eğitimini','yükümlülük altı yıl uzar','d) Pilotaj eğitimini','altı yıl uzatılır.',[],''),
 ('Ek 14','sure','Yabancı memleketlere altı ay','gidiş-dönüş arası sürenin iki katı uzar','e) Yabancı memleketlere altı ay','iki katı kadar uzatılır.',[],'masrafın ödenme şekline bakılmaz'),
 ('Ek 14','sure','Yurt dışı sürekli göreve','buralarda geçen süre kadar uzar','f) Yurt dışı sürekli göreve','geçen süreler kadar uzatılır.',[],'yaş haddi, resen, kadrosuzluk emeklisine uygulanmaz'),
 ('Ek 14','ceza','mecburi hizmetle yükümlü','istifa: masrafın iki katı; 15. madde/7068 ile çıkarılan: dört katı','Durumları birinci fıkra hükümlerine uyanlardan','kanuni faizi ile birlikte tazminat olarak öderler.',[],'sağlık sebebiyle ilişiği kesilen ödemez'),
 ('Ek 14','ceza','meslekten','veya memurluktan çıkarılan: masrafların dört katı','Durumları birinci fıkra hükümlerine uyanlardan','kanuni faizi ile birlikte tazminat olarak öderler.',[],'istifa edende iki katı'),
 ('Ek 15','istisna','ilaç ve tıbbi sarf','ücret ya da katılım payı alınmaz; garnizon rutin poliklinik DEĞİL','Teröristle mücadele ve sınır ötesi operasyonlar','katılım payı alınmaz.',[],'terör, sınır ötesi, barış destekleme, üs bölgesi; garnizon rutin poliklinik kapsamda değil'),
 ('Ek 16','sure','kıdemli çavuş','43 (astsubay çavuş da); uzman jandarmadan geçen','Uzman jandarmalıktan astsubaylığa geçenlerin rütbe yaş','Astsubay kıdemli başçavuş: 55',[],''),
 ('Ek 17','kosul','kademe ilerleme','terfi, derece, kademe ilerlemesi yapılmaz; usul yönetmelikle','Bunlar ile hakkındaki görevden uzaklaştırma','yönetmelikle belirlenir.',[],'uzman erbaş; tedbir kalksa da soruşturma sürüyorsa'),
 ('Ek 18','sure','astsubay kıdemli başçavuşların yaş haddi','İçişleri Bakanı 60 yaşına uzatır; beş yıl şartı YOK','Emsalleri arasında temayüz etmiş','60 yaşına kadar uzatılabilir.',[],'istekli ve temayüz etmiş olanlar; rütbede beş yıl şartı YOK'),
 ('Ek 18','sayi_oran','sicil notu ortalaması','tam notun yüzde doksanının (dâhil) üzerinde','Emsalleri arasında temayüz etmiş','60 yaşına kadar uzatılabilir.',[],'kıdemli başçavuş yaş haddi uzatma şartı'),
 ('Ek 19','tanim','emniyet ve asayişe yönelik hizmetleri','Jandarma Asayiş Vakfı','Jandarma Genel Komutanlığının emniyet ve asayişe yönelik','vakıflara ilişkin hükümlere tabidir.',[],'5072 sayılı Kanun kapsamında'),
 # Geçici maddeler
 ('Geçici','sure','astsubaylıktan subaylığa','teğmen-üsteğmen 49, yüzbaşı 55, binbaşı 56, yarbay 57, albay 60','926 sayılı Kanunun ek geçici 94','Yaş Haddi 49 55 56 57 60',[('Ek 16','uzman jandarmalıktan astsubaylığa geçenler: 43, 52, 54, 55'),('Geçici 12','aynı hüküm: astsubaylıktan subaylığa geçenlerin yaş hadleri')],''),
 ('Geçici 1','kosul','Vazife Tüzüğü','Kanuna aykırı olmayan hükümleri, yönetmelikler çıkana kadar','Bu Kanunun 24 üncü maddesiyle çıkarılması','uygulanmasına devam edilir.',[],'Kanuna aykırı olmayan hükümleri'),
 ('Geçici 5','sure','askerlik yükümlüsü ihtiyacı','1111 sayılı Kanunla MSB üç yıl karşılar; Cumhurbaşkanı uzatabilir','Jandarma Genel Komutanlığının er ve erbaş','bütçesinden karşılanır.',[],'giderler JGK bütçesinden'),
 # ikinci ipucu satırları (sorular farklı köklerle soruyor)
 ('12','makam','devredebilir','il valilerine','Lüzum görüldüğü hallerde','il valilerine devredebilir.',[('Ek 6','İçişleri Bakanı Kanundaki yetkilerinin bir kısmını JGK veya valilere devreder')],'personel görevlendirme yetkisi'),
 ('13/A','makam','Akademinin ihtiyaçları','Jandarma Genel Komutanlığı bütçesinden','Akademinin ihtiyaçları Jandarma','bütçesinden karşılanır.',[],''),
 ('Ek 2','makam','raporlarının içeriği ve düzenlenme esasları','İçişleri Bakanlığı yönetmeliği','Değerlendirme raporlarının içeriği','yönetmelikle düzenlenir.',[],'MSB DEĞİL'),
 ('Ek 5','kosul','kayda alabilir','casusluk suçları hariç; yalnız kendi sorumluluk alanında','Jandarma, bu Kanunun 7 nci maddesinin (a)','kayda alabilir.',[],'önleyici iletişim tespiti, dinleme, kayda alma'),
 ('Ek 5','sure','kararını en geç','kırk sekiz saat içinde (hâkim)','Gecikmesinde sakınca bulunan hallerde verilen yazılı emir','kırk sekiz saat içinde verir.',[],'yazılı emir yirmidört saatte hâkime'),
 ('Ek 5','makam','rapor hâlinde','TBMM Güvenlik ve İstihbarat Komisyonuna','Bu maddede yer alan faaliyetlerin denetimi','Güvenlik ve İstihbarat Komisyonuna sunulur.',[],'dinleme faaliyetlerinin denetim sonuçları'),
 ('Ek 16','sure','kıdemli üstçavuş','52 (astsubay üstçavuş da); uzman jandarmadan geçen','Uzman jandarmalıktan astsubaylığa geçenlerin rütbe yaş','Astsubay kıdemli başçavuş: 55',[('Ek 12', 'sözleşmeliden muvazzafa geçişte astsubay üst sınırı kıdemli üstçavuşluk yaş haddi')],''),
 ('Ek 16','sure','astsubay başçavuş','54; uzman jandarmadan geçen','Uzman jandarmalıktan astsubaylığa geçenlerin rütbe yaş','Astsubay kıdemli başçavuş: 55',[],''),
 ('Ek 16','sure','kıdemli başçavuş','55; uzman jandarmadan geçen','Uzman jandarmalıktan astsubaylığa geçenlerin rütbe yaş','Astsubay kıdemli başçavuş: 55',[('Ek 18', 'temayüz etmiş kıdemli başçavuşun yaş haddi İçişleri Bakanınca 60’a uzatılabilir')],'temayüz edenin yaş haddi İçişleri Bakanınca 60’a uzatılabilir (Ek 18)'),
 ('Ek 19','tanim','Jandarma Asayiş Vakfı','5072 sayılı Kanun kapsamındaki vakıf hükümlerine tabi','Jandarma Genel Komutanlığının emniyet ve asayişe yönelik','vakıflara ilişkin hükümlere tabidir.',[],''),
 ('Geçici 1','kosul','yönetmelikler yürürlüğe girinceye','Jandarma Teşkilat ve Vazife Tüzüğü uygulanır','Bu Kanunun 24 üncü maddesiyle çıkarılması','uygulanmasına devam edilir.',[],'24 üncü madde yönetmelikleri'),
 ('Geçici 5','makam','giderleri','Jandarma Genel Komutanlığı bütçesinden','Jandarma Genel Komutanlığının er ve erbaş','bütçesinden karşılanır.',[('13/A','Akademi ihtiyaçları da JGK bütçesinden'),('Ek 8','tesis giderleri genel bütçeden karşılanabilir'),('Ek 9','madalya imalat giderleri bir defaya mahsus bütçeden')],'MSB’nin karşıladığı er-erbaş ve askerlik yükümlüleri'),
]
yaz(2, '2803 sayılı Jandarma Teşkilat, Görev ve Yetkileri Kanunu', K)
