# 6284 sayılı Kanuna İlişkin Uygulama Yönetmeliği — kelime → cevap
# KURAL (başkan, 4 Eki 2026): SOL = soru KÖKÜNDE göreceğin ifade, SAĞ = doğru ŞIKTA arayacağın kelime.
# Sorulardan geriye doğru yazıldı (119 cevaplı soru + kitapçık kökleri); kanıt resmî metin.
# Metinde satır sonu cümle ortasına düşer; kanıt baş/son ortak yazıcıda boşluk esnek aranır.
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 # m.1-3 — kapsam, dayanak, tanımlar
 ('1','tanim','usul ve esasları kapsar','kadın, çocuk, aile bireyi, ısrarlı takip mağduru; koruma-önleme tedbirleri','(1) Bu Yönetmelik, şiddete uğrayan','usul ve esasları kapsar.',[],''),
 ('2','kosul','dayanılarak','6284 sayılı Kanun m.22','(1) Bu Yönetmelik, 8/3/2012','dayanılarak hazırlanmıştır.',[('16','kimlik değişikliği aydınlatılmış rızaya dayanılarak verilir')],''),
 ('3','tanim','korku ve çaresizlik','tek taraflı ısrarlı takip','ş) Tek taraflı ısrarlı takip:','tutum ve davranışı,',[],'aile bağı ya da ilişki aranmaz; boşanmış eşlerle sınırlı DEĞİL; Astsubay sınavında soruldu'),
 ('3','tanim','özgür iradesi','aydınlatılmış rıza','a) Aydınlatılmış rıza:','yazılı beyanını,',[],'sebepleri, aşamaları, sonuçları açıklanıp yazılı kabul; 2026 Uzman sınavında soruldu'),
 ('3','tanim','Hâkim:','aile mahkemesi hâkimi','e) Hâkim:','Aile mahkemesi hâkimini,',[],'sulh ceza hâkimi DEĞİL'),
 ('3','tanim','Kolluk:','polis, jandarma, sahil güvenlik; gümrük DEĞİL','h) Kolluk:','sahil güvenlik birimlerini,',[],''),
 ('3','tanim','Gecikmesinde sakınca bulunan hal:','derhal işlem yapılmazsa zarar; mülki amir-hâkimden karar için vakit yok','c) Gecikmesinde sakınca bulunan hal:','vakit bulunamaması halini,',[],'kolluk tahkikatı ve risk değerlendirmesi sonucu'),
 ('3','tanim','Şikâyet mercileri:','kolluk, mülki amir, Cumhuriyet başsavcılığı, hâkim, Bakanlık birimleri','r) Şikâyet mercileri:','Bakanlığın ilgili birimlerini,',[],'sulh ceza hâkimliği, merkez komutanlığı DEĞİL'),
 ('3','tanim','Korunan kişi:','mağdur + çocukları, aile bireyleri, ısrarlı takip mağduru','j) Korunan kişi:','tek taraflı ısrarlı takip mağdurunu,',[],''),
 ('3','tanim','ölümle sonuçlanabilecek','hayati tehlike','f) Hayati tehlike:','bulunması halini,',[],''),
 ('3','tanim','kesintisiz','geçici koruma','ç) Geçici koruma:','getirilen tedbiri,',[],'hayati tehlikesi olan mağdur; yirmi dört saat, teknik cihazla, kolluk'),
 ('3','tanim','uyruğuna bakılmaksızın','şiddet mağduru','n) Şiddet mağduru:','bulunan kişiyi',[],'mütekabiliyet ilkesi çerçevesinde'),
 ('3','tanim','yatılı sosyal hizmet kuruluşu','konukevi','i) Konukevi:','sosyal hizmet kuruluşunu,',[],'sığınmaevi, kadın sığınağı, şefkatevi'),
 ('3','tanim','Kadının Statüsü','Genel Müdürlük','d) Genel Müdürlük:','Genel Müdürlüğünü,',[],'Müdürlük = Aile ve Sosyal Politikalar il-ilçe müdürlüğü'),
 ('3','tanim','özgürlüğün keyfî engellenmesi','şiddet','m) Şiddet:','her türlü tutum ve davranışı,',[],'fiziksel, cinsel, psikolojik, ekonomik; tehdit ve baskı da'),
 ('3','tanim','üçüncü kişiler tarafından','ihbar; şikâyet mağdurun kendi başvurusu','g) İhbar ve şikâyet:','mercilere müracaat etmesini,',[],''),
 # m.4-5 — ihbar ve şikâyet, yapılacak işlemler
 ('4','kosul','ihbar edebilir','herkes','(1) Kişinin, şiddete uğraması','mercilere ihbar edebilir.',[],'Astsubay sınavında soruldu'),
 ('4','kosul','haberdar olan kamu','derhal şikâyet mercilerine bildirmek zorunda','Şiddet veya şiddete uğrama tehlikesinden haberdar','bildirmek zorundadır.',[],'kamu kurumu niteliğindeki meslek kuruluşları da'),
 ('4','kosul','Kanun kapsamındaki görevlerini','gecikmeksizin yerine getirir','(3) Şikâyet mercileri','gecikmeksizin yerine getirmekle yükümlüdür.',[],'şikâyet mercileri'),
 ('4','sira_usul','ŞÖNİM’e yapılan','kolluğa, mülki amire, başsavcılığa veya hâkime gecikmeksizin','(4) Müdürlük veya ŞÖNİM’e yapılan','hâkime gecikmeksizin bildirilir.',[],''),
 ('4','sira_usul','Sözlü yapılan','derhal tutanağa geçirilir','(5) Sözlü yapılan','tutanağa geçirilir.',[],''),
 ('5','makam','onaylanmak üzere','tedbirin niteliğine göre mülki amire veya hâkime','(1) Kolluk, kendisine yapılan','hâkime sunar.',[],'gecikmesinde sakınca bulunan hallerde kolluğun aldığı tedbir'),
 ('5','sira_usul','intikal eden her olay','en seri vasıtalarla ŞÖNİM’e bilgi','Kolluk, kendisine intikal eden','ŞÖNİM’e bilgi verir.',[],'gecikmeksizin'),
 ('5','makam','Cumhuriyet başsavcılığı, yapılan ihbar','evrakı ivedilikle hâkime veya mülki amire','(2) Cumhuriyet başsavcılığı, yapılan ihbar','hâkime veya mülki amire gönderir.',[],''),
 ('5','makam','Mülki amire yapılan','koruyucu tedbire karar; kolluğa ya da başsavcılığa bildirir','(3) Mülki amire yapılan','Cumhuriyet başsavcılığına bildirir.',[],''),
 ('5','sira_usul','tarafından verilen kararlar','ivedilikle ŞÖNİM’e','(4) Hâkim veya mülki amir tarafından verilen','ŞÖNİM’e bildirilir.',[('32','m.32 metninin sonunda m.33 başlığı: mülki amir kararlarına itiraz')],'hâkim ya da mülki amirin kararları'),
 # m.6-11 — mülki amirin koruyucu tedbirleri
 ('6','tanim','mülkî amir tarafından','barınma/maddi yardım/rehberlik/geçici koruma/kreş; delil aranmaz; konut şerhi YOK','(1) Kanun kapsamında korunan kişilerle','kreş imkânının sağlanması.',[('5', 'mülki amir ve hâkim kararları ivedilikle ŞÖNİM’e'), ('10', 'fiziki korumayı hâkim ya da mülki amir belirler'), ('12', 'hâkim, mülki amirin tedbirlerini de verebilir'), ('32', 'm.32 metninin sonunda m.33 başlığı: mülki amir kararlarına itiraz'), ('29', 'mülki amir tedbirini gecikmede kolluk amiri alır, kırk sekiz saatte onaylanır'), ('30', 'tehlike kalkınca tedbiri kaldırabilir'), ('33', 'mülki amirin kararına iki haftada aile mahkemesine itiraz')],'iş yeri değişikliği, aile konutu şerhi HÂKİM tedbiri'),
 ('6','kosul','delil veya belge','aranmaz; talep, Bakanlık-kolluk başvurusu ya da resen','(1) Kanun kapsamında korunan kişilerle','resen karar verilebilir:',[('12','hâkim de delil-belge aramaz'),('30','koruyucu tedbirde delil-belge aranmaz')],''),
 ('6','kosul','Hayatî tehlikesinin bulunması','mülki amir talebiyle ya da resen geçici koruma verir','ç) Hayatî tehlikesinin','geçici koruma altına alınması,',[('7','hayati tehlikede yerleştirmeye kolluk refakat eder'),('10','geçici korumayı mülki amir, gecikmede kolluk amiri verir'),('16','kimlik değişikliği: hayati tehlike + aydınlatılmış rıza')],''),
 ('7','kosul','barınma yerlerine getirilen','başka karar-onay aranmadan derhal kabul','(5) Mülki amirin veya kolluk amirinin','derhal kabul edilir.',[],'mülki amir ya da kolluk amiri kararıyla'),
 ('7','makam','Barınma ve iaşe giderleri','ŞÖNİM öder','(2) Korunan kişi varsa','ŞÖNİM tarafından ödenir.',[],'geçici barınmada'),
 ('7','kosul','barınma yerlerinin yetersiz','kamu sosyal tesis, yurdunda geçici','(1) Hakkında barınma yeri','geçici olarak barındırılır.',[],'güvenli nakil sağlanıncaya kadar'),
 ('7','kosul','kalmak istememesi','aydınlatılmış rızayla istediği yere ŞÖNİM ulaştırır','(6) Resen hakkında barınma','ŞÖNİM tarafından ulaştırılır.',[],'hayati tehlike varsa kolluk refakati'),
 ('8','sayi_oran','Geçici maddi yardım kararı','günlük asgari ücretin otuzda biri; ek kişiye yüzde yirmi','(3) Geçici maddi yardım kararı','azaltılarak uygulanır.',[],'tavan bir buçuk kat; barınma sağlanana yüzde elli az'),
 ('8','sira_usul','Bordro','ayın onbeşinde ve otuzunda; elden ödeme yok','Bordro, her ayın','Korunan kişiye elden ödeme yapılmaz.',[],'banka hesabına'),
 ('8','istisna','gelir vergisi','muaf; veraset de, kâğıtlar damga vergisinden','(7) Bu madde kapsamında','damga vergisinden istisnadır.',[('45','Kanun m.17 ödemeleri de aynı vergilerden müstesna')],''),
 ('9','makam','koordinasyon','ŞÖNİM','(3) Bu hizmetlerin','ŞÖNİM tarafından sağlanır.',[('27','tedavi takibini ŞÖNİM kurumlarla koordinasyonla yapar'),('39','m.39 metninin sonunda m.40 başlığı: kurumlararası koordinasyon'),('40','Kanunun uygulanmasında kurumlararası koordinasyon Bakanlık')],'rehberlik, psikolojik destek, hukuki danışmanlıkta'),
 ('10','makam','geçici koruma altına alma','mülki amir; gecikmede kolluk amiri','(1) Mülkî amir veya gecikmesinde','koruma altına alma tedbiri verilir.',[],'hayati tehlike varsa, talep ya da resen'),
 ('10','sure','gideceği yere','acilde hemen, diğer hallerde yirmidört saat önce kolluğa bilgi','(2) Geçici koruma altına alınma','tedbir kararı uygulanmaya devam olunur.',[],'gidilen yerin kolluğu haberdar edilir'),
 ('10','makam','fiziki koruma tedbirleri','hâkim ya da mülki amir; gecikmede kolluk','(3) Korunan kişinin ne şekilde','kolluk tarafından belirlenir.',[],''),
 ('10','sira_usul','arayabileceği telefon','kolluk açıklar, tutanağa geçirir, tebliğ eder','(4) Korunan kişiye, geçici koruma','tutanağa geçirilir ve tebliğ edilir.',[],''),
 ('11','sure','kreş imkânı','çalışmayana dört, çalışana iki ay; asgari ücretin yarısı','(1) Çocuk sahibi olan','kreş imkânı sağlanması tedbiri verilir.',[('6','mülki amirin tedbirleri listesinde de'),('10','m.10 metninin sonunda bu maddenin başlığı yer alır')],'mülki amir tedbiri; belgelendirme şartı'),
 ('11','sira_usul','Kreş bedelinin','azsa belgedeki, fazlaysa tavan; Müdürlük kreşe öder','(3) Kreş bedelinin','kreşe yapılır.',[],''),
 ('11','kosul','suiistimal','ödenen tutar korunan kişiden tahsil','(4) Kreş imkânı sağlanmasına','tahsil edilir.',[],''),
 # m.12-16 — hâkimin koruyucu tedbirleri
 ('12','tanim','koruyucu tedbirlerden','işyeri, ayrı yerleşim, konut şerhi, kimlik değişikliği; silah teslimi ÖNLEYİCİ','(1) Kanun kapsamında korunan kişilerle ilgili olarak hâkim','belgelerinin değiştirilmesi.',[('5', 'mülki amir de koruyucu tedbirlere karar verebilir')],'uzaklaştırma da ÖNLEYİCİ; hâkim mülki amir tedbirlerini de verebilir; delil aranmaz'),
 ('12','kosul','evli olması','ayrı yerleşim yeri; hâkim, koruyucu','b) Kişinin evli olması','ayrı yerleşim yeri belirlenmesi.',[('14','ayrı yerleşim yeri kararını nüfus müdürlüğü işler')],''),
 ('13','kosul','işyerinin bulunduğu il','il içi ya da dışı; talep ya da onayla','(1) Hâkim tarafından, korunan kişinin tabî','değiştirilmesine karar verilebilir.',[],'karar işyerine tebliğ edilir'),
 ('14','makam','nüfus müdürlüğü','ayrı yerleşim yeri adres işlemleri','(2) Hakkında ayrı yerleşim','yerine getirilir.',[('32','gizlilik şerhini nüfus müdürlüğü işler')],''),
 ('15','tanim','aile konutu şerhi','koruyucu tedbir; hâkim, talep üzerine; tapu siciline ivedilikle','(1) Hâkim tarafından, Türk Medenî','müdürlüğüne gönderilir.',[('12','koruyucu tedbirler listesinde'),('14','m.14 metninin sonunda bu maddenin başlığı yer alır')],'önleyici tedbir DEĞİL'),
 ('16','makam','Kimlik ve diğer bilgi','hâkim; hayati tehlike, aydınlatılmış rıza; İçişleri Bakanlığı uygular','(1) Kimlik ve diğer bilgi','Cumhuriyet başsavcılığına bildirilir.',[('15','m.15 metninin sonunda bu maddenin başlığı yer alır')],'Tanık Koruma Kanunu; Adalet Bakanlığı DEĞİL'),
 # m.17-28 — hâkimin önleyici tedbirleri
 ('17','tanim','önleyici tedbirlerden','uzaklaştırma, yaklaşmama, rahatsız etmeme, silah teslimi; iş yeri değişikliği DEĞİL','(1) Hâkim tarafından şiddet uygulayanlarla','tedavisinin sağlanması.',[],'aile konutu şerhi, ayrı yerleşim yeri de KORUYUCU; hakaret yasağı, eşyaya zarar vermeme, tedavi önleyici'),
 ('17','tanim','Müşterek konuttan','derhal uzaklaştırma: önleyici, hâkim; gecikmede kolluk amiri','b) Müşterek konuttan','korunan kişiye tahsis edilmesi.',[('19', 'uzaklaştırılan konut giderlerini ödemeye devam eder')],'konut korunan kişiye tahsis edilir'),
 ('17','kosul','Silah taşıması zorunlu','zimmetteki silahı kurumuna teslim','ğ) Silah taşıması zorunlu','kurumuna teslim etmesi.',[('26','kurum amiri süre bitmeden iade etmez')],''),
 ('17','kosul','ailenin geçimini sağlayan','talep edilmese de tedbir nafakası','(3) Şiddet uygulayan, aynı zamanda','tedbir nafakasına hükmedebilir.',[],'TMK nafakası yoksa'),
 ('17','makam','velayet, kayyım','hâkim Türk Medeni Kanununa göre de karar verir','(2) Hâkim, 3/7/2005','karar verebilir.',[],'Çocuk Koruma Kanunu tedbirleri de'),
 ('18','makam','küçük düşürme','tehdit, hakaret, aşağılama da: söz-davranış yasağı (hâkim)','(1) Hâkim tarafından, şiddet uygulayanın korunan kişiye','bulunmamasına ilişkin olarak karar verilebilir.',[('17', 'm.17: hâkimin önleyici tedbirleri toplu listesi')],'önleyici tedbir; gecikmede kolluk amiri de alır'),
 ('19','kosul','kira, elektrik, su','uzaklaştırılan ödemeye devam eder','(3) Bu tedbirin uygulanması','karar verebilir.',[],'kira sözleşmesini feshetmemesine karar verilebilir'),
 ('19','makam','kişisel eşya ve belgelerin','mülki amir ya da hâkim; kolluk teslim eder','(2) Mülki amir ya da hâkim','tedbir kararında gösterilir.',[],''),
 ('20','tanim','sair yerlere','yaklaşmama; konut, okul, işyeri','(1) Hâkim tarafından, şiddet uygulayanın','yaklaşmamasına ilişkin karar verilebilir.',[],'önleyici'),
 ('21','makam','refakatçi eşliğinde','kişisel ilişki refakatçiyle, sınırlı ya da tümden kaldırılır (hâkim)','(1) Hâkim tarafından daha önce verilmiş','kaldırılmasına ilişkin karar verilebilir.',[('17', 'm.17: hâkimin önleyici tedbirleri toplu listesi')],'daha önce kişisel ilişki kararı varsa'),
 ('22','makam','şiddete uğramamış olsa bile','yakın, tanık ve çocuklara yaklaşmama (hâkim)','(1) Hâkim tarafından gerekli görülmesi hâlinde','yaklaşmamasına ilişkin karar verilebilir.',[('17', 'm.17: hâkimin önleyici tedbirleri toplu listesi')],'kişisel ilişki hâlleri saklı'),
 ('23','makam','ev eşyalarına','şahsi ve ev eşyasına zarar vermeme kararı (hâkim)','(1) Hâkim tarafından, şiddet uygulayanın, korunan kişinin şahsi','zarar vermemesine yönelik karar',[('17', 'm.17: hâkimin önleyici tedbirleri toplu listesi')],''),
 ('24','makam','iletişim araçlarıyla','görsel, işitsel, yazılı, internetle rahatsız etmeme (hâkim)','(1) Hâkim tarafından, şiddet mağdurunun korunması','rahatsız etmemesine yönelik karar verilebilir.',[('17', 'm.17: hâkimin önleyici tedbirleri toplu listesi'), ('23', 'm.23 metninin sonunda m.24 başlığı yer alır')],'sair surette rahatsız etme de'),
 ('25','sure','kolluğa teslim','tedbir sonuna kadar emanet','(1) Hâkim tarafından, şiddet mağdurunun','karar verilebilir.',[('17','önleyici tedbirler listesinde silah teslimi')],'şiddet uygulayanın silahları'),
 ('26','yasak','Silahı teslim alan kurum amiri','süre bitmeden, yeni karar olmadan iade etmez','(2) Silahı teslim alan','iade etmez.',[],''),
 ('26','sira_usul','teslim alınması ve iadesi','kurum amiri, şiddet uygulayan ve bir tanık tutanağı','(3) Silahın teslim alınması','yerine getirilir.',[],''),
 ('27','sira_usul','tedaviyi reddetme','tutanakla başsavcılığa ve ŞÖNİM’e','(3) Hakkında tedbir kararı verilen','ŞÖNİM’e bildirilir.',[('28','sağlık kuruluşu tedavisinde de aynı')],'tedavi takibini ŞÖNİM yapar'),
 ('28','makam','il halk sağlığı müdürlüğü','illerde; ilçelerde toplum sağlığı merkezi','(2) Şiddet uygulayanın muayene','başvurulması zorunludur.',[],'kamu sağlık kuruluşuna sevk'),
 # m.29-35 — kolluk amirinin tedbiri, tedbir kararı usulü
 ('29','sure','kolluk amirince','koruyucuda mülki amir kırk sekiz, önleyicide hâkim yirmi dört saat','(1) Mülkî amir tarafından alınabilecek','kendiliğinden kalkar.',[('7','kolluk amirince uygulanan barınmada kişi ŞÖNİM’e ulaştırılır')],'evrak ilk işgününde onaya sunulur; onaylanmazsa kendiliğinden kalkar'),
 ('29','makam','Mülkî amir tarafından alınabilecek','gecikmede ilgili kolluk amiri de alır','(1) Mülkî amir tarafından alınabilecek','kolluk amirince de alınabilir.',[('12','hâkim mülki amirin tedbirlerini de verebilir')],'barınma ve geçici koruma'),
 ('29','sure','mülkî amirin onayına','ilk işgününde sunulur; kırk sekiz saatte onaylanmazsa kalkar','(1) Mülkî amir tarafından alınabilecek','kendiliğinden kalkar.',[],'kolluk amirinin aldığı barınma ve geçici koruma tedbiri'),
 ('29','sure','Tatil günleri','süreye dahil; bitişi tatile rastlarsa ilk iş günü','(3) Tatil günleri','ilk iş günü sona erer.',[],''),
 ('30','sure','ilk defasında','en çok altı ay; tehlike sürerse uzatılabilir','(2) Tedbir kararı ilk defasında','aynen devam etmesine karar verilebilir.',[],''),
 ('30','makam','en kolay ulaşılabilecek','hâkim, mülki amir ya da kolluk','(1) Tedbir kararı ilgilinin','kolluktan talep edilebilir.',[],''),
 ('30','kosul','Koruyucu tedbir kararı verilebilmesi','delil-belge aranmaz; önleyici geciktirilmeden','(3) Koruyucu tedbir kararı','geciktirilemez.',[],''),
 ('30','kosul','ortadan kalktığının','kararı veren merci kaldırır; korunan kişiye tebliğ','(4) Hâkim veya mülki amir tarafından resen','korunan kişiye de tebliğ edilir.',[],''),
 ('31','sira_usul','reddine ilişkin karar','sadece korunan kişiye tebliğ','(2) Tedbir talebinin','korunan kişiye tebliğ edilir.',[('35','başvuruların kabul-ret kararları ŞÖNİM’e bildirilir')],'kabul kararı korunan kişiye ve şiddet uygulayana'),
 ('31','sira_usul','kolluk birimi tarafından alınan','önleyici tedbir uygulayana tutanakla derhal tebliğ; ŞÖNİM ve mahkemeye bildirim','(4) Gecikmesinde sakınca bulunan','bildirimde bulunulur.',[],''),
 ('31','sira_usul','ihtar','aykırılıkta zorlama hapsi ihtarı kararda ve tebliğde','(5) Şiddet uygulayana','bu ihtar yapılır.',[('38','ihtarlı kararın tebliği zorlama hapsinin şartı')],''),
 ('32','sure','gizlilik şerhi','tedbir bitimini takip eden on beşinci gün MERNİS’ten silinir','(6) Korunan kişinin nüfus','tabanından silinir.',[],'MERNİS'),
 ('32','yasak','ifşa','Türk Ceza Kanunu hükümleri','(1) Gerekli bulunması','ilgili hükümleri uygulanır.',[],'gizli bilgiyi hukuka aykırı veren, açıklayan'),
 ('32','sira_usul','gizlilik kararı verilen','kayıtlar yalnız elektronik ortamda; adres beyanı istenmez','(5) Korunan kişi hakkında gizlilik','sadece elektronik ortamda tutulur.',[],'şerh ŞÖNİM müdürü aracılığıyla nüfus kaydına'),
 ('32','sira_usul','tebligatlarda','ŞÖNİM’in adresi kullanılır','(3) Korunan kişiye yapılacak','adres bilgileri kullanılır.',[],''),
 ('33','sure','aile mahkemesine itiraz','tebliğden iki hafta; duruşmasız; bir haftada kesin karar','(1) Kanun hükümlerine göre mülki amir','İtiraz üzerine verilen karar kesindir.',[('34','hâkim kararlarına da iki haftada aile mahkemesine itiraz')],'mülki amirin koruyucu tedbirine'),
 ('33','sure','koruyucu tedbir kararına karşı','iki hafta içinde aile mahkemesine','(1) Kanun hükümlerine göre mülki amir','aile mahkemesine itiraz edilebilir.',[],'mülki amirin kararına; tefhim-tebliğden'),
 ('33','sure','İtiraz üzerine','bir hafta içinde karar; kesin','(3) İtiraz hakkında duruşma','İtiraz üzerine verilen karar kesindir.',[('34','hâkim kararlarına itirazda da bir hafta, kesin; dosya sonraki daireye')],'duruşmasız'),
 ('34','sure','zorlama hapsi kararlarına','iki hafta içinde aile mahkemesine','(1) Kanun hükümlerine göre hâkim','aile mahkemesine itiraz edilebilir.',[],'hâkimin koruyucu-önleyici tedbir kararlarına da'),
 ('34','makam','İtiraz üzerine dosya','sonraki daire; tek daire ise asliye hukuk','(2) İtiraz üzerine dosya','gecikmeksizin gönderilir.',[],'aynı hâkimse en yakın asliye hukuk'),
 ('34','kosul','Asıl dava ile birlikte','esas davadan bağımsız itiraz','(5) Asıl dava ile','itiraz edilebilir.',[],''),
 ('34','sure','Karar bir hafta','itirazda karar bir haftada, kesin','(7) Karar bir hafta','karar kesindir.',[('33','mülki amir kararına itirazda da bir hafta')],'duruşmasız'),
 ('35','sure','ziyaret','haftada en az bir kez','Bu kontrol korunan kişinin;','şeklinde yerine getirilir.',[],'ayda bir DEĞİL'),
 ('35','sira_usul','kolluk tarafından kontrol','haftada bir ziyaret, ikinci derece yakın, komşu, muhtar, çevre araştırması','Önleyici tedbir kararlarının yerine getirilip','şeklinde yerine getirilir.',[],'aykırılık tutanakla başsavcılığa'),
 ('35','yasak','uzlaşma ya da arabuluculuk','önerilemez','(3) Tedbir kararları, kararın niteliğine','önerilemez.',[],''),
 ('35','sure','aşamaları ve sonucu','aynı gün saat 16.00’ya kadar ŞÖNİM’e','(6) Tedbir kararlarının alınması','ŞÖNİM’e bildirilir.',[],''),
 ('35','kosul','tefhim veya tebliğ edilmemesi','uygulamaya engel değil','(8) Tedbir kararının','engel teşkil etmez.',[],''),
 ('36','kosul','eğitim almış personel','kadın-çocuk hakları ve eşitlik eğitimi almışlardan','(2) Bu görevliler','arasından belirlenir.',[],'kolluk görevlileri'),
 # m.37-46 — teknik takip, zorlama hapsi, ŞÖNİM, koordinasyon, mali hükümler
 ('37','yasak','teknik araç','hâkim karar verir; ses-görüntü kaydı, dinleme, izleme yok','(1) Hâkim, tedbir kararlarının','dinlenemez ve izlenemez.',[],''),
 ('38','ceza','aykırı hareket eden','ilk ihlalde üç-on gün; tekrarında onbeş-otuz gün; toplam altı ay','(5) Kanun hükümlerine göre','toplam süresi altı ayı geçemez.',[],'fiil suç olsa bile'),
 ('38','sure','her tekrarında','onbeş-otuz gün; toplam altı ayı geçemez','(6) Tedbir kararının gereklerine','altı ayı geçemez.',[],''),
 ('38','istisna','zorlama hapsi','tekerrüre esas olmaz, sicile işlenmez; toplam altı ayı geçemez','(7) Zorlama hapsi kararları','işlenmez.',[('31','zorlama hapsi ihtarı kararda yer alır'),('33','m.33 metninin sonunda m.34 başlığı: zorlama hapsi kararına itiraz'),('34','zorlama hapsine iki haftada aile mahkemesine itiraz')],'duruşmasız; koşullu salıverilme yok'),
 ('38','kosul','karar verilebilmesi için','ihtarlı tedbir kararı tefhim-tebliğ edilmiş olmalı','(3) Zorlama hapsine','edilmiş olması gerekir.',[],''),
 ('38','sira_usul','mükerrer','önceki zorlama hapsi sorulur','Ancak tedbirin başka bir mahkemenin','bilgi istenilir.',[],'başka mahkemenin yargı alanında ihlalde'),
 ('38','sira_usul','kolluk tarafından tespit','tutanak başsavcılığa, oradan aile mahkemesine','(1) Tedbir kararlarının ihlal','resen zorlama hapsine ilişkin karar verilebilir.',[],''),
 ('39','makam','ŞÖNİM’i kurar','Bakanlık; yedi gün yirmidört saat; tercihen kadın personel','(1) Bakanlık, şiddetin önlenmesi','ŞÖNİM’i kurar.',[],'yalnız kadın personel DEĞİL'),
 ('40','sayi_oran','Materyaller','ayda en az doksan dakika; otuzu 17.00-22.00 arası','Materyaller, Türkiye Radyo','tarafından denetlenir.',[],'yayın 08.00-22.00; RTÜK denetler'),
 ('40','makam','kurumlararası ve sivil toplum','koordinasyon Bakanlık','(1) Kanun hükümlerinin yerine','gerçekleştirilir.',[],''),
 ('41','kosul','müfredat','kadın insan hakları, eşitlik dersleri; MEB ve Genel Müdürlük','(2) İlköğretim ve ortaöğretim','birlikte hazırlanır.',[],''),
 ('41','kosul','mezun oldukları tarihte','sertifika (sosyal sorumluluk projesine katılana)','(3) Ortaöğretim öğrencileri','sertifika verilir.',[],''),
 ('42','sure','ödemelerin tahsili','şiddet uygulayana tebliğ; bir ayda ödemezse 6183 ile vergi dairesi','(1) Geçici maddi yardımlar','takip ve tahsil edilir.',[],'süre tebliğden başlar'),
 ('42','sure','süresinde yapılmaması','6183 ile vergi dairesi takip eder','(1) Geçici maddi yardımlar','takip ve tahsil edilir.',[],'Amme Alacaklarının Tahsil Usulü Kanunu'),
 ('42','kosul','gerçeğe aykırı beyan','korunan kişiden 6183 ile tahsil; uygulayana iade','(2) Korunan kişinin gerçeğe aykırı','kendisine iade edilir.',[],''),
 ('43','sira_usul','nafaka','resen icra müdürlüğüne; Sosyal Güvenlik bağlantılıysa maaştan; harç alınmaz','(1) Kanun hükümlerine göre nafakaya','masraf alınmaz.',[('17', 'hâkim talep edilmese de tedbir nafakasına hükmedebilir'), ('42', 'm.42 metninin sonunda bu maddenin başlığı yer alır')],''),
 ('43','makam','posta giderleri','Cumhuriyet başsavcılığı suçüstü ödeneği','(4) İcra müdürlüklerinin','suçüstü ödeneğinden karşılanır.',[],'harç alınmaz'),
 ('44','kosul','sağlık giderleri','genel sağlık sigortası; GSS’siz gelir testsiz sigortalı','(1) Korunan kişinin sağlık giderleri','sigortalısı sayılır.',[('43','m.43 metninin sonunda bu maddenin başlığı yer alır')],''),
 ('44','kosul','prim borcu','gelir testi olmadan GSS’li sayılır','(1) Korunan kişinin sağlık giderleri','sigortalısı sayılır.',[],'bu hal sürdükçe'),
 ('44','kosul','sıra beklememesi','gizlilik kararlı kişi sağlıkta öncelikli','(2) Korunan kişinin kimlik','tamamlanması esastır.',[],''),
 ('44','makam','rehabilitasyon','GSS karşılamazsa Bakanlık bütçesi','(3) Kanun hükümlerine göre','ilgili tertiplerinden karşılanır.',[],'önleyici tedbirli kişinin'),
 ('45','istisna','icra ve infazı','yargılama gideri, harç, posta gideri alınmaz','(1) Kanun kapsamındaki başvurular','masraf alınmaz.',[],''),
 ('45','istisna','müstesna','gelir, veraset-intikal; kâğıtlar damga vergisinden','(2) Kanunun 17 nci maddesi','damga vergisinden müstesnadır.',[],''),
 ('46','makam','müdahil','Bakanlık; idari, cezai, hukuki dava, çekişmesiz yargı; icra YOK','(1) Bakanlık, gerekli görmesi','müdahil olarak katılabilir.',[('9', 'hukuki rehberlikte davalara müdahil olmayı içeren destek')],''),
 ('47','sure','yürürlüğe girer','yayımı tarihinde','(1) Bu Yönetmelik yayımı','yürürlüğe girer.',[],''),
 ('48','makam','hükümlerini','Aile ve Sosyal Politikalar Bakanı yürütür','(1) Bu Yönetmelik hükümlerini','Bakanı yürütür.',[('40','Kanun hükümlerinin yerine getirilmesinde koordinasyon Bakanlık')],''),
]
yaz(21, '6284 sayılı Kanuna İlişkin Uygulama Yönetmeliği', K)
