# 6284 sayılı Kanuna İlişkin Uygulama Yönetmeliği — kelime → cevap (Kanun'da olmayan, yönetmeliğe özgü kurallar)
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('3','tanim','yeterince vakit bulunamaması','gecikmesinde sakınca bulunan hal (mülki amir/hâkimden karar için)','c) Gecikmesinde sakınca','vakit bulunamaması halini,',[],'kolluk tahkikatı ve risk değerlendirmesi sonucu'),
 ('3','tanim','kesintisiz olarak','geçici koruma; yirmidört saat esasıyla, teknik cihazlarla','ç) Geçici koruma','getirilen tedbiri,',[],'hayati tehlikesi bulunan mağdur; kolluk yerine getirir'),
 ('3','tanim','ölümle sonuçlanabilecek','hayati tehlike (tanım)','f) Hayati tehlike','bulunması halini,',[],''),
 ('3','tanim','Şikâyet mercileri: Kolluğu','kolluk, mülki amir, Cumhuriyet başsavcılığı, hâkim, Bakanlık birimleri','r) Şikâyet mercileri','Bakanlığın ilgili birimlerini,',[],''),
 ('3','tanim','bulunup bulunmadığına bakılmaksızın','tek taraflı ısrarlı takip; korku ve çaresizlik duygusu','ş) Tek taraflı ısrarlı takip','tutum ve davranışı,',[],'aile bağı aranmaz'),
 ('3','tanim','uyruğuna bakılmaksızın','şiddet mağduru; mütekabiliyet ilkesi','n) Şiddet mağduru','bulunan kişiyi,',[],''),
 ('3','tanim','yazılı beyanını','aydınlatılmış rıza; sebepleri, aşamaları, sonuçları açıklanarak','a) Aydınlatılmış rıza','yazılı beyanını,',[],''),
 ('3','tanim','yatılı sosyal hizmet kuruluşunu','konukevi (sığınmaevi, kadın sığınağı, şefkatevi)','i) Konukevi','sosyal hizmet kuruluşunu,',[],''),
 ('3','tanim','Kadının Statüsü Genel Müdürlüğünü','Yönetmelikteki Genel Müdürlük','d) Genel Müdürlük','Genel Müdürlüğünü,',[],'Müdürlük = Aile ve Sosyal Politikalar il/ilçe müdürlüğü'),
 ('4','kosul','bildirmek zorundadır','şiddetten haberdar kamu kurumları ve meslek kuruluşları (derhal)','Şiddet veya şiddete uğrama tehlikesinden haberdar','bildirmek zorundadır.',[],'herkes ihbar edebilir'),
 ('4','sira_usul','derhal tutanağa geçirilir','sözlü şikâyet ve ihbar','(5) Sözlü yapılan','tutanağa geçirilir.',[],''),
 ('5','sira_usul','her olay hakkında gecikmeksizin','kolluk, intikal eden olayı ŞÖNİM\'e bildirir','Kolluk, kendisine intikal eden','ŞÖNİM’e bilgi verir.',[],''),
 ('6','kosul','belge aranmaksızın mülkî amir','koruyucu tedbir; talep, Bakanlık/kolluk başvurusu ya da resen','(1) Kanun kapsamında korunan kişilerle ilgili olarak aşağıdaki tedbirlerden','verilebilir:',[],''),
 ('7','kosul','derhal kabul edilir','mülki amir/kolluk amiri kararıyla gelen mağdur; başka onay aranmaz','(5) Mülki amirin veya kolluk amirinin','derhal kabul edilir.',[],''),
 ('7','makam','Barınma ve iaşe giderleri, ŞÖNİM','geçici barınmada ŞÖNİM öder','Barınma ve iaşe giderleri','ŞÖNİM tarafından ödenir.',[],'ŞÖNİM konukevi/ilk kabul birimini belirler'),
 ('7','kosul','kalmak istediği yere ŞÖNİM','barınmak istemeyen; aydınlatılmış rızayla ulaştırılır','(6) Resen hakkında barınma','ŞÖNİM tarafından ulaştırılır.',[],'hayati tehlike varsa kolluk refakati'),
 ('8','sayi_oran','otuzda birine kadar','günlük geçici maddi yardım; aylık net asgari ücretin','(3) Geçici maddi yardım kararı','azaltılarak uygulanır.',[],''),
 ('8','sayi_oran','yüzde yirmisi','ilave her kişi için; toplam bir buçuk katı aşamaz','(3) Geçici maddi yardım kararı','azaltılarak uygulanır.',[],''),
 ('8','sayi_oran','yüzde elli oranında azaltılarak','barınma yeri sağlananlarda geçici maddi yardım','(3) Geçici maddi yardım kararı','azaltılarak uygulanır.',[],'GÜNLÜK 1/30, EK KİŞİ %20, TAVAN 1,5 KAT, BARINANA YARIM'),
 ('8','sira_usul','onbeşinde ve otuzunda','bordro düzenlenir; banka hesabına; elden ödeme yok','Bordro, her ayın','banka hesabına yatırılır.',[],''),
 ('10','sure','yirmidört saat öncesinden','korunan kişi gideceği yeri kolluğa bildirir; acilde hemen','Korunan kişi acil durumlarda','kolluğa bilgi verir.',[],''),
 ('10','makam','fiziki koruma tedbirleri','hâkim ya da mülki amir belirler; gecikmede kolluk','(3) Korunan kişinin ne şekilde','kolluk tarafından belirlenir.',[],''),
 ('11','sira_usul','Bu ödemeler Müdürlük tarafından kreşe','Müdürlük kreşe öder; belgedeki tutar ya da üst sınır','(3) Kreş bedelinin','kreşe yapılır.',[],''),
 ('11','kosul','suiistimalinin öğrenilmesi','ödenen kreş bedeli korunan kişiden tahsil edilir','(4) Kreş imkânı sağlanmasına','tahsil edilir.',[],''),
 ('12','kosul','alınabilecek tedbirler de dâhil','hâkim, mülki amirin koruyucu tedbirlerini de verebilir','(1) Kanun kapsamında korunan kişilerle ilgili olarak hâkim','verilebilir:',[],''),
 ('13','kosul','ya da il dışında','hâkim işyeri değişikliği; korunan kişinin talebi/onayı','(1) Hâkim tarafından, korunan kişinin tabî','değiştirilmesine karar verilebilir.',[],'karar işyerine tebliğ; yetkili kurum uygular'),
 ('14','makam','nüfus müdürlüğü tarafından kişinin','ayrı yerleşim yeri kararı sonrası adres işlemleri','(2) Hakkında ayrı yerleşim','yerine getirilir.',[],''),
 ('15','makam','ilgili tapu sicil müdürlüğüne','aile konutu şerhi kararı ivedilikle gönderilir','(2) Karar, hâkim tarafından ivedilikle','müdürlüğüne gönderilir.',[],''),
 ('16','makam','İçişleri Bakanlığınca gereği yerine getirilmek','kimlik değişikliği kararı; hâkim → savcılık → İçişleri','(2) Karar, İçişleri Bakanlığınca','başsavcılığına gönderilir.',[],''),
 ('19','kosul','kira, elektrik, su, telefon, doğalgaz','uzaklaştırılan şiddet uygulayan giderleri karşılamaya devam eder','(3) Bu tedbirin uygulanması','karar verebilir.',[],''),
 ('19','kosul','kira sözleşmesini feshetmemesine','hâkim koruma süresince karar verebilir; kamu konutu tahsisi kaldırılmaz','(3) Bu tedbirin uygulanması','karar verebilir.',[],'kiralayana ve kamu kurumuna bildirilir'),
 ('25','sure','sonuna kadar emanetine','şiddet uygulayanın silahları kolluğa; tedbir süresince','(1) Hâkim tarafından, şiddet mağdurunun korunması amacıyla şiddet uygulayana ait','karar verilebilir.',[],''),
 ('26','yasak','hiçbir şekilde iade etmez','kurum amiri; yeni karar verilmedikçe (zimmet silahı)','(2) Silahı teslim alan kurum amiri','iade etmez.',[],''),
 ('26','sira_usul','bir tanık arasında imzalanan tutanak','silahın teslim alınması ve iadesi; kurum amiri, şiddet uygulayan','(3) Silahın teslim alınması','yerine getirilir.',[],''),
 ('27','sira_usul','tedaviyi reddetmesi halinde','tutanakla savcılığa ve ŞÖNİM\'e bildirilir','(3) Hakkında tedbir kararı verilen kişinin sağlık kuruluşunda','ŞÖNİM’e bildirilir.',[('28','sağlık kuruluşunda tedavide de aynı')],'tedavi takibi ŞÖNİM; kolluktan yardım isteyebilir'),
 ('28','makam','toplum sağlığı merkezi tarafından','ilçelerde sevk; illerde il halk sağlığı müdürlüğü (ruh sağlığı şubesi)','(3) Şiddet uygulayan, illerde','sevk edilir.',[],''),
 ('29','sure','Tatil günleri sürenin hesabına','onay süresine dâhil; bitimi tatilse ilk iş günü','(3) Tatil günleri','ilk iş günü sona erer.',[],''),
 ('30','kosul','tedbirlerin kaldırılmasına karar','şiddet tehlikesi kalkınca kararı veren merci; korunan kişiye tebliğ','(4) Hâkim veya mülki amir tarafından resen','korunan kişiye de tebliğ edilir.',[],''),
 ('31','sira_usul','kararının kalktığı korunan kişiye','onaylanmayan kolluk tedbiri; tebliğ edilir, kolluğa bildirilir','(3) 29 uncu maddenin','ilgili kolluğa bildirilir.',[],''),
 ('32','sira_usul','ŞÖNİM’e ait adres bilgileri','gizlilik kararında korunan kişiye tebligat adresi','(3) Korunan kişiye yapılacak tebligatlarda','adres bilgileri kullanılır.',[],''),
 ('32','sure','onbeşinci gün MERNİS','tedbir süresi bitince gizlilik şerhi silinir','(6) Korunan kişinin nüfus kaydına','tabanından silinir.',[],'şerh ŞÖNİM müdürü aracılığıyla nüfus kaydına işlenir'),
 ('32','istisna','adres beyanı istenilmez','gizlilik şerhli korunan kişiden resmi işlemlerde','Bu durumda korunan kişilerin','adres beyanı istenilmez.',[],'kayıtlar yalnız elektronik ortamda'),
 ('33','sure','koruyucu tedbir kararına karşı','mülki amir kararına aile mahkemesine iki hafta içinde itiraz','(1) Kanun hükümlerine göre mülki amir','itiraz edilebilir.',[],'duruşmasız; karar bir haftada; kesin'),
 ('34','makam','numara olarak kendisini izleyen daireye','hâkim tedbirine itirazı inceler; tek daire varsa asliye hukuk','(2) İtiraz üzerine dosya','gecikmeksizin gönderilir.',[],'aynı hâkimse en yakın asliye hukuk; zorlama hapsi itirazı da'),
 ('34','kosul','esas davadan bağımsız olarak','asıl davayla istenen tedbire itiraz edilebilir','(5) Asıl dava ile','itiraz edilebilir.',[],''),
 ('35','yasak','uzlaşma ya da arabuluculuk','önerilemez; şiddet mağduru ile uygulayan arasında','yerine getirilir. Koruyucu','önerilemez.',[],''),
 ('35','sure','haftada en az bir kez','kolluk, korunan kişinin konutunu ziyaret eder (önleyici tedbir kontrolü)','Bu kontrol korunan kişinin;','şeklinde yerine getirilir.',[],''),
 ('35','sira_usul','muhtarından bilgi alınması','önleyici tedbir kontrolü; komşular, ikinci derece yakınlar, çevre araştırması','Bu kontrol korunan kişinin;','şeklinde yerine getirilir.',[],'aykırılık tutanakla savcılığa'),
 ('35','sure','saat 16.00’ya kadar','tedbir işlemlerinin sonucu aynı gün ŞÖNİM\'e bildirilir','(6) Tedbir kararlarının alınması ve uygulanması','ŞÖNİM’e bildirilir.',[],''),
 ('38','istisna','tekerrüre esas olmaz','zorlama hapsi; koşullu salıverilme yok, adli sicile işlenmez','(7) Zorlama hapsi kararları','işlenmez.',[],''),
 ('38','kosul','ihtarın da yer aldığı','zorlama hapsi için tedbir kararı tebliğ/tefhim edilmiş olmalı','(3) Zorlama hapsine karar verilebilmesi','edilmiş olması gerekir.',[],'duruşmasız verilir'),
 ('38','sira_usul','mükerrerliğe neden olmamak','başka mahkeme alanında ihlalde önceki zorlama hapsi sorulur','Ancak tedbirin başka bir mahkemenin','bilgi istenilir.',[],''),
 ('39','makam','ŞÖNİM’i kurar','Bakanlık; yedi gün yirmidört saat; tercihen kadın personel','(1) Bakanlık, şiddetin önlenmesi','ŞÖNİM’i kurar.',[],''),
 ('40','sayi_oran','ayda en az doksan dakika','TRT ve özel kanallar yayınlar; otuz dakikası 17.00-22.00 arası','Materyaller, Türkiye Radyo','tarafından denetlenir.',[],''),
 ('40','makam','Radyo ve Televizyon Üst Kurulu','yayın kopyaları her ay teslim; süreleri denetler','Materyaller, Türkiye Radyo','tarafından denetlenir.',[],''),
 ('41','kosul','müfredatına','ilk ve ortaöğretim; kadının insan hakları, kadın-erkek eşitliği dersleri','(2) İlköğretim ve ortaöğretim','birlikte hazırlanır.',[],'MEB + Genel Müdürlük hazırlar'),
 ('42','sure','ilgili vergi dairesi tarafından takip','geçici maddi yardım rücusu; bir ayda ödenmezse 6183','(1) Geçici maddi yardımlar için yapılan ödemelerin tahsili','takip ve tahsil edilir.',[],''),
 ('42','kosul','gerçeğe aykırı beyanda bulunduğunun','korunan kişiden tahsil; şiddet uygulayandan alınan iade','(2) Korunan kişinin gerçeğe aykırı','tahsil edilir.',[],''),
 ('43','makam','suçüstü ödeneğinden','nafaka icra posta giderleri; Cumhuriyet başsavcılığı','(4) İcra müdürlüklerinin nafakanın','masraf alınmaz.',[],'harç alınmaz'),
 ('43','kosul','başvurusu aranmaksızın','SGK\'lı borçlunun maaşından icra müdürlüğü nafakayı keser','(3) Nafaka ödemekle yükümlü','tahsil edilir.',[],''),
 ('44','kosul','gelir testine tabî tutulmaksızın','GSS\'siz korunan kişi genel sağlık sigortalısı sayılır','Ancak Kanun hükümlerine göre hakkında','sigortalısı sayılır.',[],''),
 ('44','kosul','öncelikli ve en kısa zamanda','gizlilik kararlı korunan kişi sağlık hizmetinde; sıra beklemez','(2) Korunan kişinin kimlik ve adres','tamamlanması esastır.',[],''),
 ('45','istisna','yargılama giderleri, harç, posta','Kanun kapsamındaki başvuru ve kararların infazında alınmaz','(1) Kanun kapsamındaki başvurular','masraf alınmaz.',[],''),
 ('46','makam','müdahil olarak katılabilir','Bakanlık; şiddetle ilgili idari, cezai, hukuki davalara','(1) Bakanlık, gerekli görmesi','müdahil olarak katılabilir.',[],''),
 ('3', 'tanim', 'özgürlüğün keyfî engellenmesini', 'şiddet (tanım): fiziksel, cinsel, psikolojik, ekonomik zarar; tehdit ve baskı', 'm) Şiddet: Kişinin, fiziksel', 'her türlü tutum ve davranışı,', [], ''),
 ('3', 'tanim', 'jandarma ve sahil güvenlik birimlerini', 'kolluk (tanım): polis, jandarma, sahil güvenlik; gümrük muhafaza dâhil değil', 'h) Kolluk: Polis, jandarma', 'sahil güvenlik birimlerini,', [], ''),
 ('3', 'tanim', 'Aile mahkemesi hâkimini', 'Yönetmelikteki Hâkim (sulh ceza değil)', 'e) Hâkim: Aile mahkemesi', 'Aile mahkemesi hâkimini,', [], ''),
 ('3', 'tanim', 'üçüncü kişiler tarafından ilgili makam', 'ihbar (şikâyet: mağdurun kendisinin müracaatı)', 'g) İhbar ve şikâyet: İhbar', 'mercilere müracaat etmesini,', [], ''),
 ('3', 'tanim', 'komutanını/amirini', 'kolluk amiri: yerleşim yeri/bulunduğu/uygulama yerindeki yetkili kolluk birimi amiri', 'ı) Kolluk amiri: Hakkında tedbir', 'komutanını/amirini,', [], ''),
 ('4', 'kosul', 'herkes durumu yazılı, sözlü', 'şiddet veya tehlikesini ilgili makamlara ihbar edebilir', '(1) Kişinin, şiddete uğraması', 'mercilere ihbar edebilir.', [], 'kamu kurumları ve meslek kuruluşları için zorunluluk'),
 ('4', 'sira_usul', 'Müdürlük veya ŞÖNİM’e yapılan', 'şikâyet-ihbar gecikmeksizin kolluğa, mülki amire, Cumhuriyet başsavcılığına veya hâkime', '(4) Müdürlük veya ŞÖNİM’e yapılan', 'hâkime gecikmeksizin bildirilir.', [], ''),
 ('5', 'makam', 'evrakın bir örneğini ivedilikle', 'Cumhuriyet başsavcılığı ihbar-şikâyeti hâkime veya mülki amire gönderir (tedbir için)', '(2) Cumhuriyet başsavcılığı, yapılan ihbar', 'hâkime veya mülki amire gönderir.', [], ''),
 ('5', 'sira_usul', 'ivedilikle ŞÖNİM’e bildirilir', 'hâkim veya mülki amirin verdiği kararlar', '(4) Hâkim veya mülki amir tarafından verilen', 'ŞÖNİM’e bildirilir.', [], ''),
 ('6', 'tanim', 'rehberlik ve danışmanlık hizmeti verilmesi', 'mülkî amir tedbirleri: barınma, maddi yardım, rehberlik, geçici koruma, kreş', 'a) Kendisine ve gerekiyorsa beraberindeki', 'kreş imkânının sağlanması.', [], 'aile konutu şerhi, işyeri değişikliği HÂKİM tedbiri'),
 ('6', 'kosul', 'resen geçici koruma altına alınması', 'hayatî tehlike halinde (mülkî amir; gecikmede kolluk amiri de)', 'ç) Hayatî tehlikesinin bulunması hâlinde', 'geçici koruma altına alınması,', [], ''),
 ('9', 'makam', 'koordinasyon ŞÖNİM tarafından sağlanır', 'ŞÖNİM sağlar: destek, iş bulma, hukuki rehberlik hizmetlerinde koordinasyon', '(3) Bu hizmetlerin yerine getirilmesinde', 'ŞÖNİM tarafından sağlanır.', [], ''),
 ('10', 'makam', 'geçici koruma altına alma tedbiri', 'mülkî amir verir; gecikmede kolluk amiri (hayati tehlike)', '(1) Mülkî amir veya gecikmesinde', 'koruma altına alma tedbiri verilir.', [], ''),
 ('10', 'sira_usul', 'tutanağa geçirilir ve tebliğ edilir', 'geçici koruma kararının kapsamı, telefonlar, kolluğun sorumlulukları korunan kişiye açıklanır', '(4) Korunan kişiye, geçici koruma kararının', 'tutanağa geçirilir ve tebliğ edilir.', [], ''),
 ('17', 'tanim', 'derhâl uzaklaştırılması ve müşterek konutun', 'hâkim önleyici tedbiri; müşterek konut korunan kişiye tahsis', 'b) Müşterek konuttan veya bulunduğu', 'korunan kişiye tahsis edilmesi.', [], ''),
 ('17', 'tanim', 'hakaret, aşağılama veya küçük düşürmeyi', 'önleyici tedbirler: hakaret yasağı, uzaklaştırma, yaklaşmama, rahatsız etmeme, silah teslimi', 'a) Şiddet mağduruna yönelik olarak şiddet tehdidi', 'tedavisinin sağlanması.', [], 'aile konutu şerhi, işyeri değişikliği KORUYUCU tedbir'),
 ('17', 'kosul', 'zimmetinde bulunan silahı kurumuna', 'silah taşıması zorunlu kamu görevlisi şiddet uygulayan; önleyici tedbir', 'ğ) Silah taşıması zorunlu olan', 'kurumuna teslim etmesi.', [('26', 'silahın kurum amirine teslimi ve iadesi usulü')], ''),
 ('29', 'sure', 'kırk sekiz saat içinde onaylanmayan', 'kolluk amirinin aldığı barınma/geçici koruma tedbiri; mülkî amir onayı', '(1) Mülkî amir tarafından alınabilecek barınma', 'kendiliğinden kalkar.', [], ''),
 ('30', 'makam', 'en kolay ulaşılabilecek yer', 'tedbir kararı talep yeri: hâkim, mülkî amir, kolluk', 'Tedbir kararları en çabuk', 'ya da kolluktan talep edilebilir.', [], ''),
 ('30', 'sure', 'ilk defasında en çok', 'tedbir kararı süresi; tehlike sürerse süre/şekil değiştirilebilir, aynen devam', '(2) Tedbir kararı ilk defasında', 'aynen devam etmesine karar verilebilir.', [], ''),
 ('30', 'kosul', 'geciktirilmeksizin verilir', 'önleyici tedbir kararı; koruyucu tedbirde delil-belge aranmaz', '(3) Koruyucu tedbir kararı verilebilmesi için', 'geciktirilemez.', [], ''),
 ('34', 'sure', 'bir hafta içinde verilir', 'itiraz üzerine aile mahkemesi kararı; kesin; duruşmasız', '(7) Karar bir hafta', 'karar kesindir.', [('33', 'mülki amir kararına itirazda da bir hafta')], ''),
 ('37', 'yasak', 'ses ve görüntü kaydı alınamaz', 'teknik araçla tedbir takibinde; kişiler dinlenemez, izlenemez (hâkim karar verir)', '(1) Hâkim, tedbir kararlarının uygulanmasında teknik', 'dinlenemez ve izlenemez.', [], ''),
 ('38', 'sira_usul', 'tutulan tutanak Cumhuriyet başsavcılığına', 'kolluk ihlali tespit edince başsavcılığa; mahkeme tespitinde resen zorlama hapsi', '(1) Tedbir kararlarının ihlal edildiğinin kolluk', 'resen zorlama hapsine ilişkin karar verilebilir.', [], ''),
 ('38', 'ceza', 'üç günden on güne kadar', 'zorlama hapsi (tedbire aykırılık); tekrarında onbeş-otuz gün; altı ayı geçemez', 'hâkim tarafından üç günden', 'altı ayı geçemez.', [], ''),
 ('40', 'makam', 'kurumlararası ve sivil toplum kuruluşları', 'koordinasyon Bakanlık tarafından; kurumlar tedbir kararlarını ivedilikle yerine getirir', '(1) Kanun hükümlerinin yerine getirilmesinde kurumlararası', 'gerçekleştirilir.', [], ''),
 ('41', 'kosul', 'kadın erkek eşitliği konusunda eğitim', 'kamu kurumları personelini Bakanlığın koordine ettiği eğitim programlarına katılmasını sağlar', '(1) Kanunun etkin bir biçimde uygulanması', 'katılmasını sağlar.', [('36', 'ŞÖNİM personeline verilecek eğitim')], ''),
 ('41', 'kosul', 'mezun oldukları tarihte', 'sosyal sorumluluk projelerine katılan öğrencilere sertifika (Bakanlık + MEB/YÖK)', '(3) Ortaöğretim öğrencileri ile yükseköğrenim', 'hazırlanan bir sertifika verilir.', [], ''),
 ('42', 'sure', 'bir ay içinde ödenmesi hususu', 'geçici maddi yardım rücusu şiddet uygulayana tebliğ; ödenmezse 6183 takibi', '(1) Geçici maddi yardımlar için yapılan ödemelerin', 'takip ve tahsil edilir.', [], ''),
 ('43', 'sira_usul', 'kararın bir örneği, resen', 'nafaka kararı icra müdürlüğüne gönderilir (alacaklı/borçlu yerleşim yeri)', '(1) Kanun hükümlerine göre nafakaya karar', 'icra müdürlüğüne gönderilir.', [], ''),
 ('44', 'kosul', 'genel sağlık sigortası kapsamında karşılanır', "korunan kişinin sağlık giderleri; GSS'siz gelir testi olmadan sigortalı sayılır", '(1) Korunan kişinin sağlık giderleri', 'sigortalısı sayılır.', [], ''),
 ('45', 'istisna', 'veraset ve intikal vergisinden', 'Kanun m.17 ödemeleri gelir vergisinden de müstesna; kâğıtlar damga vergisinden', '(2) Kanunun 17 nci maddesi uyarınca', 'damga vergisinden müstesnadır.', [('8', 'geçici maddi yardım ödemelerinde vergi istisnası')], ''),
 ('3', 'tanim', 'beraberindeki çocukları, aile bireylerini', 'korunan kişi: tedbir kapsamındaki mağdur + çocukları, aile bireyleri', 'j) Korunan kişi: Tedbir kararı', 'aile bireylerini ve tek taraflı', [], ''),
 ('5', 'makam', 'niteliğine göre mülki amire', 'gecikmesinde sakınca: kolluğun aldığı koruyucu/önleyici tedbir onaya sunulur', 'sakınca bulunan hallerde Kanun kapsamında', 'hâkime sunar.', [], 'koruyucu → mülki amir, önleyici → hâkim'),
 ('12', 'tanim', 'ayrı yerleşim yeri belirlenmesi', 'hâkim koruyucu tedbiri (evli ise); işyeri değişikliği, aile konutu şerhi', 'b) Kişinin evli olması hâlinde müşterek', 'ilgili diğer bilgi ve belgelerinin', [('13', 'işyeri değişikliği uygulama maddesi'), ('14', 'ayrı yerleşim yeri uygulama maddesi, nüfus')], 'silah teslimi ÖNLEYİCİ tedbir (m.17)'),
 ('17', 'kosul', 'talep edilmese dahi tedbir nafakasına', 'hâkim hükmedebilir; şiddet uygulayan ailenin geçimini sağlıyorsa (TMK nafakası yoksa)', '(3) Şiddet uygulayan, aynı zamanda ailenin', 'talep edilmese dahi tedbir nafakasına', [], ''),
 ('29', 'sure', 'dört saat içinde onaylanmayan', 'kolluk amirinin aldığı önleyici tedbir hâkimce onaylanmazsa kendiliğinden kalkar', 'tarafından yirmi dört saat içinde onaylanmayan', 'kendiliğinden kalkar.', [], 'koruyucu tedbirde mülkî amir, kırk sekiz saat'),
 ('43', 'istisna', 'Ayrıca harç ve benzeri', 'nafaka tahsilinde harç ve masraf yok; posta gideri suçüstü ödeneğinden', 'suçüstü ödeneğinden karşılanır', 'masraf alınmaz.', [], ''),
]
yaz(21, '6284 sayılı Kanuna İlişkin Uygulama Yönetmeliği', K)
