# 6284 sayılı Kanuna İlişkin Uygulama Yönetmeliği — kelime → cevap (Kanun'da olmayan, yönetmeliğe özgü kurallar)
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('3','tanim','yeterince vakit bulunamaması','gecikmesinde sakınca bulunan hal (mülki amir/hâkimden karar için)','c) Gecikmesinde sakınca','vakit bulunamaması halini,',[],'kolluk tahkikatı ve risk değerlendirmesi sonucu'),
 ('3','tanim','kesintisiz olarak','geçici koruma; yirmidört saat esasıyla, teknik cihazlarla','ç) Geçici koruma','getirilen tedbiri,',[],'hayati tehlikesi bulunan mağdur; kolluk yerine getirir'),
 ('3','tanim','ölümle sonuçlanabilecek','hayati tehlike (tanım)','f) Hayati tehlike','bulunması halini,',[],''),
 ('3','tanim','Şikâyet mercileri: Kolluğu','kolluk, mülki amir, Cumhuriyet başsavcılığı, hâkim, Bakanlık birimleri','r) Şikâyet mercileri','Bakanlığın ilgili birimlerini,',[],''),
 ('3','tanim','bulunup bulunmadığına bakılmaksızın','tek taraflı ısrarlı takip; korku ve çaresizlik duygusu','ş) Tek taraflı ısrarlı takip','tutum ve davranışı,',[],'aile bağı aranmaz'),
 ('3','tanim','uyruğuna bakılmaksızın','şiddet mağduru; mütekabiliyet ilkesi','n) Şiddet mağduru','bulunan kişiyi,',[],''),
 ('3','tanim','yazılı beyanını','aydınlatılmış rıza; sebepleri, aşamaları, sonuçları açıklanarak','a) Aydınlatılmış rıza','yazılı beyanını,',[],''),
 ('3','tanim','yatılı sosyal hizmet kuruluşunu','konukevi (sığınmaevi, kadın sığınağı, şefkatevi)','i) Konukevi','sosyal hizmet kuruluşunu,',[],''),
 ('3','tanim','Kadının Statüsü Genel Müdürlüğünü','Yönetmelikteki Genel Müdürlük','d) Genel Müdürlük','Genel Müdürlüğünü,',[],'Müdürlük = Aile ve Sosyal Politikalar il/ilçe müdürlüğü'),
 ('4','kosul','bildirmek zorundadır','şiddetten haberdar kamu kurumları ve meslek kuruluşları (derhal)','Şiddet veya şiddete uğrama tehlikesinden haberdar','bildirmek zorundadır.',[],'herkes ihbar edebilir'),
 ('4','sira_usul','derhal tutanağa geçirilir','sözlü şikâyet ve ihbar','(5) Sözlü yapılan','tutanağa geçirilir.',[],''),
 ('5','sira_usul','her olay hakkında gecikmeksizin','kolluk, intikal eden olayı ŞÖNİM\'e bildirir','Kolluk, kendisine intikal eden','ŞÖNİM’e bilgi verir.',[],''),
 ('6','kosul','belge aranmaksızın mülkî amir','koruyucu tedbir; talep, Bakanlık/kolluk başvurusu ya da resen','(1) Kanun kapsamında korunan kişilerle ilgili olarak aşağıdaki tedbirlerden','verilebilir:',[],''),
 ('7','kosul','derhal kabul edilir','mülki amir/kolluk amiri kararıyla gelen mağdur; başka onay aranmaz','(5) Mülki amirin veya kolluk amirinin','derhal kabul edilir.',[],''),
 ('7','makam','Barınma ve iaşe giderleri, ŞÖNİM','geçici barınmada ŞÖNİM öder','Barınma ve iaşe giderleri','ŞÖNİM tarafından ödenir.',[],'ŞÖNİM konukevi/ilk kabul birimini belirler'),
 ('7','kosul','kalmak istediği yere ŞÖNİM','barınmak istemeyen; aydınlatılmış rızayla ulaştırılır','(6) Resen hakkında barınma','ŞÖNİM tarafından ulaştırılır.',[],'hayati tehlike varsa kolluk refakati'),
 ('8','sayi_oran','otuzda birine kadar','günlük geçici maddi yardım; aylık net asgari ücretin','(3) Geçici maddi yardım kararı','azaltılarak uygulanır.',[],''),
 ('8','sayi_oran','yüzde yirmisi','ilave her kişi için; toplam bir buçuk katı aşamaz','(3) Geçici maddi yardım kararı','azaltılarak uygulanır.',[],''),
 ('8','sayi_oran','yüzde elli oranında azaltılarak','barınma yeri sağlananlarda geçici maddi yardım','(3) Geçici maddi yardım kararı','azaltılarak uygulanır.',[],'GÜNLÜK 1/30, EK KİŞİ %20, TAVAN 1,5 KAT, BARINANA YARIM'),
 ('8','sira_usul','onbeşinde ve otuzunda','bordro düzenlenir; banka hesabına; elden ödeme yok','Bordro, her ayın','banka hesabına yatırılır.',[],''),
 ('10','sure','yirmidört saat öncesinden','korunan kişi gideceği yeri kolluğa bildirir; acilde hemen','Korunan kişi acil durumlarda','kolluğa bilgi verir.',[],''),
 ('10','makam','fiziki koruma tedbirleri','hâkim ya da mülki amir belirler; gecikmede kolluk','(3) Korunan kişinin ne şekilde','kolluk tarafından belirlenir.',[],''),
 ('11','sira_usul','Bu ödemeler Müdürlük tarafından kreşe','Müdürlük kreşe öder; belgedeki tutar ya da üst sınır','(3) Kreş bedelinin','kreşe yapılır.',[],''),
 ('11','kosul','suiistimalinin öğrenilmesi','ödenen kreş bedeli korunan kişiden tahsil edilir','(4) Kreş imkânı sağlanmasına','tahsil edilir.',[],''),
 ('12','kosul','alınabilecek tedbirler de dâhil','hâkim, mülki amirin koruyucu tedbirlerini de verebilir','(1) Kanun kapsamında korunan kişilerle ilgili olarak hâkim','verilebilir:',[],''),
 ('13','kosul','ya da il dışında','hâkim işyeri değişikliği; korunan kişinin talebi/onayı','(1) Hâkim tarafından, korunan kişinin tabî','değiştirilmesine karar verilebilir.',[],'karar işyerine tebliğ; yetkili kurum uygular'),
 ('14','makam','nüfus müdürlüğü tarafından kişinin','ayrı yerleşim yeri kararı sonrası adres işlemleri','(2) Hakkında ayrı yerleşim','yerine getirilir.',[],''),
 ('15','makam','ilgili tapu sicil müdürlüğüne','aile konutu şerhi kararı ivedilikle gönderilir','(2) Karar, hâkim tarafından ivedilikle','müdürlüğüne gönderilir.',[],''),
 ('16','makam','İçişleri Bakanlığınca gereği yerine getirilmek','kimlik değişikliği kararı; hâkim → savcılık → İçişleri','(2) Karar, İçişleri Bakanlığınca','başsavcılığına gönderilir.',[],''),
 ('19','kosul','kira, elektrik, su, telefon, doğalgaz','uzaklaştırılan şiddet uygulayan giderleri karşılamaya devam eder','(3) Bu tedbirin uygulanması','karar verebilir.',[],''),
 ('19','kosul','kira sözleşmesini feshetmemesine','hâkim koruma süresince karar verebilir; kamu konutu tahsisi kaldırılmaz','(3) Bu tedbirin uygulanması','karar verebilir.',[],'kiralayana ve kamu kurumuna bildirilir'),
 ('25','sure','sonuna kadar emanetine','şiddet uygulayanın silahları kolluğa; tedbir süresince','(1) Hâkim tarafından, şiddet mağdurunun korunması amacıyla şiddet uygulayana ait','karar verilebilir.',[],''),
 ('26','yasak','hiçbir şekilde iade etmez','kurum amiri; yeni karar verilmedikçe (zimmet silahı)','(2) Silahı teslim alan kurum amiri','iade etmez.',[],''),
 ('26','sira_usul','bir tanık arasında imzalanan tutanak','silahın teslim alınması ve iadesi; kurum amiri, şiddet uygulayan','(3) Silahın teslim alınması','yerine getirilir.',[],''),
 ('27','sira_usul','tedaviyi reddetmesi halinde','tutanakla savcılığa ve ŞÖNİM\'e bildirilir','(3) Hakkında tedbir kararı verilen kişinin sağlık kuruluşunda','ŞÖNİM’e bildirilir.',[('28','sağlık kuruluşunda tedavide de aynı')],'tedavi takibi ŞÖNİM; kolluktan yardım isteyebilir'),
 ('28','makam','toplum sağlığı merkezi tarafından','ilçelerde sevk; illerde il halk sağlığı müdürlüğü (ruh sağlığı şubesi)','(3) Şiddet uygulayan, illerde','sevk edilir.',[],''),
 ('29','sure','Tatil günleri sürenin hesabına','onay süresine dâhil; bitimi tatilse ilk iş günü','(3) Tatil günleri','ilk iş günü sona erer.',[],''),
 ('30','kosul','tedbirlerin kaldırılmasına karar','şiddet tehlikesi kalkınca kararı veren merci; korunan kişiye tebliğ','(4) Hâkim veya mülki amir tarafından resen','korunan kişiye de tebliğ edilir.',[],''),
 ('31','sira_usul','kararının kalktığı korunan kişiye','onaylanmayan kolluk tedbiri; tebliğ edilir, kolluğa bildirilir','(3) 29 uncu maddenin','ilgili kolluğa bildirilir.',[],''),
 ('32','sira_usul','ŞÖNİM’e ait adres bilgileri','gizlilik kararında korunan kişiye tebligat adresi','(3) Korunan kişiye yapılacak tebligatlarda','adres bilgileri kullanılır.',[],''),
 ('32','sure','onbeşinci gün MERNİS','tedbir süresi bitince gizlilik şerhi silinir','(6) Korunan kişinin nüfus kaydına','tabanından silinir.',[],'şerh ŞÖNİM müdürü aracılığıyla nüfus kaydına işlenir'),
 ('32','istisna','adres beyanı istenilmez','gizlilik şerhli korunan kişiden resmi işlemlerde','Bu durumda korunan kişilerin','adres beyanı istenilmez.',[],'kayıtlar yalnız elektronik ortamda'),
 ('33','sure','koruyucu tedbir kararına karşı','mülki amir kararına aile mahkemesine iki hafta içinde itiraz','(1) Kanun hükümlerine göre mülki amir','itiraz edilebilir.',[],'duruşmasız; karar bir haftada; kesin'),
 ('34','makam','numara olarak kendisini izleyen daireye','hâkim tedbirine itirazı inceler; tek daire varsa asliye hukuk','(2) İtiraz üzerine dosya','gecikmeksizin gönderilir.',[],'aynı hâkimse en yakın asliye hukuk; zorlama hapsi itirazı da'),
 ('34','kosul','esas davadan bağımsız olarak','asıl davayla istenen tedbire itiraz edilebilir','(5) Asıl dava ile','itiraz edilebilir.',[],''),
 ('35','yasak','uzlaşma ya da arabuluculuk','önerilemez; şiddet mağduru ile uygulayan arasında','yerine getirilir. Koruyucu','önerilemez.',[],''),
 ('35','sure','haftada en az bir kez','kolluk, korunan kişinin konutunu ziyaret eder (önleyici tedbir kontrolü)','Bu kontrol korunan kişinin;','şeklinde yerine getirilir.',[],''),
 ('35','sira_usul','muhtarından bilgi alınması','önleyici tedbir kontrolü; komşular, ikinci derece yakınlar, çevre araştırması','Bu kontrol korunan kişinin;','şeklinde yerine getirilir.',[],'aykırılık tutanakla savcılığa'),
 ('35','sure','saat 16.00’ya kadar','tedbir işlemlerinin sonucu aynı gün ŞÖNİM\'e bildirilir','(6) Tedbir kararlarının alınması ve uygulanması','ŞÖNİM’e bildirilir.',[],''),
 ('38','istisna','tekerrüre esas olmaz','zorlama hapsi; koşullu salıverilme yok, adli sicile işlenmez','(7) Zorlama hapsi kararları','işlenmez.',[],''),
 ('38','kosul','ihtarın da yer aldığı','zorlama hapsi için tedbir kararı tebliğ/tefhim edilmiş olmalı','(3) Zorlama hapsine karar verilebilmesi','edilmiş olması gerekir.',[],'duruşmasız verilir'),
 ('38','sira_usul','mükerrerliğe neden olmamak','başka mahkeme alanında ihlalde önceki zorlama hapsi sorulur','Ancak tedbirin başka bir mahkemenin','bilgi istenilir.',[],''),
 ('39','makam','ŞÖNİM’i kurar','Bakanlık; yedi gün yirmidört saat; tercihen kadın personel','(1) Bakanlık, şiddetin önlenmesi','ŞÖNİM’i kurar.',[],''),
 ('40','sayi_oran','ayda en az doksan dakika','TRT ve özel kanallar yayınlar; otuz dakikası 17.00-22.00 arası','Materyaller, Türkiye Radyo','tarafından denetlenir.',[],''),
 ('40','makam','Radyo ve Televizyon Üst Kurulu','yayın kopyaları her ay teslim; süreleri denetler','Materyaller, Türkiye Radyo','tarafından denetlenir.',[],''),
 ('41','kosul','müfredatına','ilk ve ortaöğretim; kadının insan hakları, kadın-erkek eşitliği dersleri','(2) İlköğretim ve ortaöğretim','birlikte hazırlanır.',[],'MEB + Genel Müdürlük hazırlar'),
 ('42','sure','ilgili vergi dairesi tarafından takip','geçici maddi yardım rücusu; bir ayda ödenmezse 6183','(1) Geçici maddi yardımlar için yapılan ödemelerin tahsili','takip ve tahsil edilir.',[],''),
 ('42','kosul','gerçeğe aykırı beyanda bulunduğunun','korunan kişiden tahsil; şiddet uygulayandan alınan iade','(2) Korunan kişinin gerçeğe aykırı','tahsil edilir.',[],''),
 ('43','makam','suçüstü ödeneğinden','nafaka icra posta giderleri; Cumhuriyet başsavcılığı','(4) İcra müdürlüklerinin nafakanın','masraf alınmaz.',[],'harç alınmaz'),
 ('43','kosul','başvurusu aranmaksızın','SGK\'lı borçlunun maaşından icra müdürlüğü nafakayı keser','(3) Nafaka ödemekle yükümlü','tahsil edilir.',[],''),
 ('44','kosul','gelir testine tabî tutulmaksızın','GSS\'siz korunan kişi genel sağlık sigortalısı sayılır','Ancak Kanun hükümlerine göre hakkında','sigortalısı sayılır.',[],''),
 ('44','kosul','öncelikli ve en kısa zamanda','gizlilik kararlı korunan kişi sağlık hizmetinde; sıra beklemez','(2) Korunan kişinin kimlik ve adres','tamamlanması esastır.',[],''),
 ('45','istisna','yargılama giderleri, harç, posta','Kanun kapsamındaki başvuru ve kararların infazında alınmaz','(1) Kanun kapsamındaki başvurular','masraf alınmaz.',[],''),
 ('46','makam','müdahil olarak katılabilir','Bakanlık; şiddetle ilgili idari, cezai, hukuki davalara','(1) Bakanlık, gerekli görmesi','müdahil olarak katılabilir.',[],''),
]
yaz(21, '6284 sayılı Kanuna İlişkin Uygulama Yönetmeliği', K)
