# Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı Personel Yönetmeliği — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('4','tanim','temsil ettiği mevkii','makam (tanım)','i) Makam','temsil ettiği mevkii,',[],'MAKAM = KOLTUK, AMİR = KOLTUKTAKİ'),
 ('4','tanim','rütbe veya kıdem büyüklüğünü','üst: makam, rütbe ya da kıdem büyüklüğü','k) Üst','kıdem büyüklüğünü,',[],''),
 ('4','tanim','inha eden makamı','müşterek kararla atananda atamaya yetkili amir','b) Atamaya yetkili amir','inha eden makamı,',[],''),
 ('5','makam','insan gücü planına','personel ihtiyacı; JGK/SGK hazırlar, Bakanlık onaylar','(4) Personel ihtiyacı','insan gücü planına göre karşılanır.',[],'kaynak: Akademi ve eğitim komutanlıkları'),
 ('7','tanim','Uçak ve helikopter teknisyeni','JGK astsubay branşı (subayda Pilot)','b) Astsubaylar 1) Jandarma','Uçak ve helikopter teknisyeni',[],''),
 ('7','tanim','Bilgi teknolojileri','Sahil Güvenlik astsubay branşı','b) Astsubaylar 1) Güverte','6) Bilgi teknolojileri',[],'SG astsubay: güverte, makine, ikmal, uçak bakım, idari'),
 ('7','tanim','İnsansız Hava Aracı','JGK subay ve astsubay branşı (2024)','(1) Jandarma Genel Komutanlığında bulunan branşlar','19) (Ek:RG-16/1/2024) İnsansız Hava Aracı',[],'Hukuk branşı 2020'),
 ('8','makam','branş belirleme kurul kararı','branş değişikliği; sağlık, uçuştan ayrılma, ikinci tahsil, kadro değişikliği','(2) Personelin branşları','kurul kararı ile değiştirilebilir.',[],''),
 ('9','sira_usul','Çekimser oy kullanılamaz','branş belirleme kurulu; üye tam sayısı, oyçokluğu, eşitlikte başkan tarafı','(2) Branş belirleme kurulları üye','onayı ile kesinleşir.',[],''),
 ('9','makam','Akademisi Başkanının','ilk branş belirleme kurulu kararını onaylar; değişiklikleri JGK/SGK','(2) Branş belirleme kurulları üye','onayı ile kesinleşir.',[],''),
 ('10','kosul','temayüz etmiş astsubaylar','subay kadrolarına atanabilir; astları değerlendirmede rütbe şartı yok','(7) İhtiyaç duyulması halinde subay','rütbe şartı aranmaz.',[],''),
 ('10','istisna','kritik ve kilit kadrolar','puanlama sisteminden hariç; Bakanlık belirler','(4) Bakanlık tarafından belirlenecek kritik','gözönünde bulundurulabilir.',[],''),
 ('11','sira_usul','kura ile yapılır','ilk görev yeri ataması; branş ve ihtisasa göre','MADDE 11- (1) Öğrenimlerini','kura ile yapılır.',[],''),
 ('12','yasak','evlenmeden önceki nüfusa kayıtlı','o ilçeye atanmaz; nüfusu bir milyonu aşan ilçeler hariç','(2) Personel, belediye sınırları','ilçelere atanmaz.',[],'kendisinin ve eşinin'),
 ('14','sure','Mayıs ve Ekim','genel atama dönemi; Bakanlık başka zaman da belirleyebilir','(2) Genel atamalar, her yılın','önceden duyurulabilir.',[],''),
 ('15','sure','Aynı yerdeki görevlere atananlar','tebliğ gününü izleyen işgünü içinde işe başlar','a) Aynı yerdeki görevlere','işe başlamak zorundadırlar.',[],'AYNI YER AYNI GÜN'),
 ('15','sure','Başka yerdeki görevlere atananlar','tebliğden onbeş gün içinde hareket; yol süresi; izleyen işgünü başlar','b) Başka yerdeki görevlere','işe başlamak zorundadırlar.',[],'savaş ve OHAL\'de süre kısaltılabilir'),
 ('15','sure','hiçbir şekilde bir ayı geçemez','sayman, mal sorumlusu, mutemedin devir süresi','b) Hesaplarını, yerlerine','tarihinde başlar.',[],'süre devrin bitiminde başlar'),
 ('15','sure','amire ulaşmasından itibaren','atama emri en geç on gün içinde tebliğ edilir','(4) Atama emrinde aksi','ilgilisine tebliğ edilir.',[],''),
 ('15','sira_usul','gıyaplarında evrak üzerinden','izinli, raporlu, tutuklu, uzaklaştırılmış personelin ilişik kesme ve katılışı','(5) Atamaya tabi tutulan','ödenmeye başlanır.',[],'tebligata engel değil'),
 ('16','makam','kendi kurumunun bütçesinden karşılanır','geçici görevlendirilen kolluk personelinin aylığı','(2) Birinci fıkraya göre görevlendirilen personelin;','bütçesinden karşılanır.',[],'görevlendirme Bakan; valiye devredebilir; disiplin soruşturması fiilen görevli kurumda'),
 ('19','yasak','siyasi partiye üye olamaz','personel; ayrım yapamaz, siyasi beyan-eylemde bulunamaz','MADDE 19- (1) Personel siyasi','bu eylemlere katılamaz.',[],''),
 ('21','yasak','hediyesini kabul edemez','amir, maiyetindekinden; borç da alamaz, menfaat isteyemez','(3) Amir, maiyetindeki personele kanunlara','borç alamaz.',[],'kanunlara aykırı emir de veremez'),
 ('23','kosul','rayiç bedeli üzerinden','kasıt, kusur, ihmalle idareye verilen zarar personelce ödenir','(2) Personelin kasıt','ödenmesi esastır.',[],''),
 ('24','kosul','ilgili kurum aleyhine dava açarlar','kamu görevinden zarar gören kişi; personele değil; kurumun rücu hakkı','MADDE 24- (1) Kişiler kamu hukukuna','rücu hakkı saklıdır.',[],''),
 ('24','kosul','cezai takibat sonucu beklenmeden','zimmete geçirilen parayı Hazine hak sahibine öder','MADDE 24- (1) Kişiler kamu hukukuna','rücu hakkı saklıdır.',[],'ZİMMETİ HAZİNE BEKLEMEDEN ÖDER'),
 ('24','kosul','Avrupa İnsan Hakları Mahkemesince','işkence tazminatı ödenirse sorumlu personele rücu','(2) İşkence ya da zalimane','birinci fıkra hükmü uygulanır.',[],''),
 ('25','yasak','basına, haber ajanslarına','personel bilgi/demeç veremez; valiler ve Bakanın yetkilendirdiği verir','MADDE 25- (1) Personel, kamu görevleri','tarafından verilebilir.',[],''),
 ('26','kosul','mirasçılarına da şamildir','resmî belge, araç, gereci iade zorunluluğu','(2) Personel görevleri icabı','mirasçılarına da şamildir.',[],''),
 ('29','kosul','görevine son verilmez','güvenlik hakkı; aylık ve hakları alınamaz','MADDE 29- (1) Kanunlarda yazılı','elinden alınamaz.',[],'kanunda yazılı haller dışında'),
 ('30','sure','Temmuz ve Ağustos ayları içinde','emeklilik talebi dönemi; kabul bir aydan fazla gecikmez','(2) Personel, emeklilik taleplerini','kabul edilebilir.',[('31','çekilme talebi de aynı aylarda')],'Ocak-Şubat da; dışındaki talep hizmet gereğine göre'),
 ('31','sure','çekilme taleplerini','Ocak-Şubat, Temmuz-Ağustos; kabul bir ayda; mecburi hizmet saklı','(3) Personel çekilme taleplerini','kabul edilebilir.',[],''),
 ('32','sira_usul','şikâyet edilen amirler atlanarak','en yakın amirden başlayarak silsile yoluyla; söz veya yazıyla','(2) Müracaat ve şikâyetler söz','atlanarak yapılır.',[],''),
 ('33','kosul','uydurma bir suç isnadı','isnat sabit olmazsa amir/vali savcılıktan kamu davası ister','(1) Personel hakkındaki ihbar','Cumhuriyet savcılığından ister.',[],'garaz ya da hakaret amaçlı ihbar'),
 ('36','yasak','greve karar vermeleri','yasak; propaganda, katılma, destekleme de','MADDE 36- (1) Personelin greve','teşvik edemez.',[],'toplu görevden çekilme de yasak'),
 ('37','sure','bağlı oldukları kuruma bildirmekle','eşi/çocuğu ticaret yapıyorsa onbeş gün içinde','(3) Eşleri, reşit olmayan','bildirmekle yükümlüdürler.',[],''),
 ('37','istisna','tüketim kooperatifleri','yönetim-denetim kurulu üyeliği ticaret yasağı dışında','(2) Personelin üyesi oldukları yapı','yasaklamanın dışındadır.',[],'yapı ve kalkınma kooperatifi, meslek kuruluşu, yardım sandığı da'),
 ('38','makam','Kamu Görevlileri Etik Kurulu','hediye yasağının kapsamı bu kurul kararlarıyla','(2) Hediye alma yasağının','uygulama yapılır.',[],''),
 ('40','yasak','657 sayılı Kanuna tabi kurumlarda','ikinci görev verilemez; Devlet bankaları, KİT\'ler de; hakem-bilirkişi ücreti saklı','MADDE 40- (1) Personele;','yarar sağlanamaz.',[],''),
 ('41','makam','Bakanın yazılı izni','gizli bilgi açıklamak için; görevden ayrılmış olsa da','(2) Personel, kamu hizmetleri ile ilgili gizli','açıklayamaz.',[],''),
 ('42','sure','yirmidört saati geçemez','nöbet süresi','(2) Nöbet, kurumlarda','yirmidört saati geçemez.',[],''),
 ('42','istisna','doğumdan sonraki iki yıl','kadın memura gece nöbeti/vardiyası verilemez (rapor varsa hamilelikte de)','Ancak kadın memurlara','görevi verilemez.',[],''),
 ('42','istisna','isteği dışında gece nöbeti','engelli memura verilemez','Engelli memurlara da','görevi verilemez.',[],''),
 ('42','sira_usul','bir tanesi tutturulur','mazeretle girilmeyen nöbetlerden, mazeret kalkınca','(3) Kendisine nöbet hizmeti','bir tanesi tutturulur.',[],'nöbet sonrakine devredilir'),
 ('43','sure','izleyen yıl içinde verilebilir','zorunlu nedenle kullanılamayan yıllık izin','MADDE 43- (1) Yıllık izinlerin','izleyen yıl içinde verilebilir.',[],'esas: senesi içinde'),
 ('44','makam','Jandarma bölge komutanları için konuşlu','izin: konuşlu bulunduğu ilin valisi','1) Jandarma Genel Komutanı için Bakan','6) Diğer personel için birinci amirler, tarafından verilir.',[],''),
 ('44','makam','personel için vali ve kaymakamlar','il ve ilçe jandarma komutanlıklarında yıllık ve mazeret izni','1) Jandarma Genel Komutanı için Bakan','6) Diğer personel için birinci amirler, tarafından verilir.',[],'diğer personele birinci amir'),
 ('44','makam','Jandarma Genel Komutanı için Bakan','izin; yardımcıları için JGK; Akademi Başkanı için de Bakan','1) Jandarma Genel Komutanı için Bakan','6) Diğer personel için birinci amirler, tarafından verilir.',[],''),
 ('45','sure','yılda en az bir kez','değerlendirme yapılır; atama, terfi, ödülde dikkate alınır','(4) Değerlendirme yılda','en az bir kez yapılır.',[],''),
 ('46','tanim','şerit rozet, bröve ve madalyadır','ödül türleri; başarı, üstün başarı, takdir belgesi de','(4) Bu Yönetmelik kapsamında verilen ödüller','bröve ve madalyadır.',[],''),
 ('46','kosul','cezalardan bağımsız çalışır','ödül sistemi','(3) Ödül sistemi, disiplinle','durum içinde değerlendirilir.',[],''),
 ('47','sayi_oran','Üç defa başarı belgesi','üstün başarı belgesi verilir','(2) Görevli oldukları kurumlarda olağanüstü','üstün başarı belgesi verilir.',[],'ÜÇ BAŞARI = BİR ÜSTÜN BAŞARI'),
 ('47','makam','ilçelerde kaymakamlar tarafından başarı belgesi','başarı belgesi: merkezde Bakan, illerde vali, ilçede kaymakam','(2) Görevli oldukları kurumlarda olağanüstü','üstün başarı belgesi verilir.',[],''),
 ('47','makam','takdir belgesi ile ödüllendirilir','amirleri tarafından; görevini eksiksiz yapan','MADDE 47- (1) Personel, görevlerini eksiksiz','takdir belgesi ile ödüllendirilir.',[],'TAKDİR AMİRDEN, BAŞARI BAKAN/VALİ/KAYMAKAMDAN'),
 ('50','makam','üstün cesaret ve feragat madalyası','Bakan verir; hayatını tehlikeye atarak görev','MADDE 50- (1) Kendisine tevdi','Bakan tarafından verilir.',[],''),
 ('51','makam','ihtiyati bir tedbirdir','görevden uzaklaştırma; yetkili: atamaya yetkili amir, Bakanlık müfettişi, vali, kaymakam','MADDE 51- (1) Görevden uzaklaştırma Devlet','ç) İlçelerde kaymakamlar.',[],'657 usulü; vali/kaymakam tedbiri kuruma derhal bildirilir'),
 ('53','kosul','353 sayılı Askeri Mahkemeler','askeri görevden doğan suçlarda (jandarma/SG hizmetleri sınıfı)','ç) Jandarma hizmetleri ve sahil güvenlik hizmetleri sınıfları personeline askeri','askeri mahkemede görülür.',[],'mülki görev suçu 4483; adli görev CMK 161/5; kişisel suç genel hükümler'),
 ('55','istisna','hamileliğini belgelediği takdirde','üniformalı kadın personel sivil kıyafetle görev yapabilir','e) Resmi üniformalı olarak görev yapan kadın','görev yapabilir.',[],''),
 ('55','yasak','eskimiş dahi olsa','resmi üniforma personel dışına verilemez, giydirilemez','c) Resmi üniformalar eskimiş','bu kişilere verilemez.',[],'ilişiği kesilen üniformayı çıkarır'),
 ('55','kosul','kravat takmış olarak','sivil elbiseyle çalışanlar; mülki amir izni hariç','d) Sivil elbise ile çalışanlar','görevde bulunmak zorundadırlar.',[],''),
 ('57','makam','peşin olarak ödenir','sevk/refakatte il dışına çıkan erbaş-er yolluğu; görevlendiren makam','MADDE 57- (1) Hükümlü, tutuklu','peşin olarak ödenir.',[],''),
 ('58','kosul','müfreze usulü ile','beslenemeyen erbaş-ere tayın bedeli (5668, 2155)','MADDE 58- (1) Görevlerinin niteliği','kapsamında ödenir.',[],''),
 ('60','sira_usul','üstlerden evvel selam vermeye','astlar mecbur; aynı rütbedekiler beklemeden selamlaşır','(2) Selamlama her yerde','selamını alırlar.',[],''),
 ('61','makam','sosyal tesislerden yararlanmayı','kimlik kartı düzenlemesi; İçişleri–MSB protokolü','(2) Kimlik kartlarının Türk Silahlı','protokol ile belirlenir.',[],''),
 ('4', 'tanim', 'teknik bilgi ve beceri gerektiren', 'ihtisas: özel hizmet alanı (branş: alt hizmet alanı)', 'ğ) İhtisas: Jandarma Genel Komutanlığı', 'özel hizmet alanlarını,', [], ''),
 ('4', 'tanim', 'Bakan: İçişleri Bakanını', 'Personel Yönetmeliğinde Bakan = İçişleri Bakanı', 'c) Bakan: İçişleri Bakanını', 'ç) Bakanlık: İçişleri Bakanlığını,', [], ''),
 ('7', 'tanim', 'Öğretmen', 'Öğretmen yalnız subay listesinde; Astsubaylar listesinde yok', '11) Maliye 12) Öğretmen', 'b) Astsubaylar 1) Jandarma', [], ''),
 ('1', 'tanim', 'uygulanmasına dair usul ve esasları', 'Personel Yönetmeliğinin amacı: 2803, 2692 ve 657 hükümlerinin uygulanma usulü', 'MADDE 1- (1) Bu Yönetmeliğin amacı', 'usul ve esasları belirlemektir.', [], ''),
 ('2', 'tanim', 'sözleşmeli erbaş ve erlerin kaynakları', 'kapsam: subay, astsubay, sözleşmeli, uzman jandarma/erbaş, sözleşmeli er', 'MADDE 2- (1) Bu Yönetmelik; Jandarma', 'diğer özlük işlerine ilişkin hükümleri kapsar.', [], 'sivil memur kapsamda değil'),
 ('2', 'kosul', 'nasıp ve terfi, aylık', 'nasıp-terfi, mali-sosyal haklar: 926, 4678, 3466, 3269, 6191 ve 657', '(2) Birinci fıkradaki personelin nasıp', 'hükümlerine göre yürütülür.', [], ''),
 ('3', 'kosul', '2692 sayılı Kanunun 23 üncü', 'dayanak: 2803 sayılı Kanun m.24, 2692 sayılı Kanun m.23', 'MADDE 3- (1) Bu Yönetmelik; 2803', 'dayanılarak hazırlanmıştır.', [], ''),
 ('4', 'tanim', 'amir olarak yetkilendirilmiş olan diğer', 'Amir (tanım): kadro ve kuruluş yönünden bağlı olunan kimse +', 'a) Amir: Kadro ve kuruluş', 'yetkilendirilmiş olan diğer kişileri,', [], ''),
 ('4', 'tanim', 'rütbe veya kıdem büyüklüğünü', 'Üst (tanım): makam, rütbe veya kıdem büyüklüğü', 'k) Üst: Makam, rütbe', 'kıdem büyüklüğünü, ifade eder.', [], ''),
 ('4', 'tanim', 'durumuna göre belirlenen atama', 'hizmet bölgesi (tanım): konuş-kuruluşa göre belirlenen atama yeri', 'g) Hizmet bölgesi: Jandarma', 'belirlenen atama yerini,', [], ''),
 ('4', 'tanim', 'alt hizmet alanlarını', 'Branş (tanım); ihtisas: özel yetenek-teknik bilgi gerektiren hizmet alanı', 'd) Branş: Jandarma Genel Komutanlığı', 'alt hizmet alanlarını,', [], ''),
 ('4', 'tanim', 'inha eden makamı', 'atamaya yetkili amir (müşterek kararla atananlar için)', 'b) Atamaya yetkili amir', 'inha eden makamı,', [], ''),
 ('4', 'tanim', 'başarı düzeyini ölçen', 'değerlendirme (tanım); mesleki gelişimi sağlayan işlemler', 'f) Değerlendirme: Personelin tanımlanan', 'mesleki gelişimini sağlayan işlemleri,', [], ''),
 ('8', 'kosul', 'İlk branş belirlenme işlemine', 'Akademi ve diğer yükseköğretim kurumlarında JGK/SGK adına öğrenim gören öğrenciler', 'MADDE 8- (1) İlk branş belirlenme', 'öğrenim gören öğrencilerdir.', [], ''),
 ('8', 'kosul', 'branş belirleme kurul kararı', 'branş değişikliği: sağlık, uçuştan ayrılma, ikinci tahsil, kadro değişikliği', '(2) Personelin branşları; sağlık durumu', 'kurul kararı ile değiştirilebilir.', [], ''),
 ('10', 'kosul', 'hizmet bölgesinin özellikleri esas alınır', 'atama ilkesi; farklı hizmet bölgeleri arasında zorunlu atama', 'MADDE 10- (1) Atamalarda hizmet bölgesinin', 'zorunlu atama işlemine tabi tutulur.', [], ''),
 ('10', 'kosul', 'varsa puanlama sistemi de', 'aynı ili tercih eden aynı branşlılara m.12 esasları da', '(4) Bakanlık tarafından belirlenecek kritik', 'gözönünde bulundurulabilir.', [], ''),
 ('10', 'kosul', 'hizmet bölgesi sürelerini tamamlamadan', 'subay-astsubay bölge değiştirerek atanmaz (atama yönetmeliğindeki sebepler hariç)', '(6) Subay ve astsubayların atandığı hizmet', 'atamaya tabi tutulmazlar.', [], ''),
 ('12', 'kosul', 'Asayiş, idari ve zaruri sebepler', 'atama kriterleri: mesleki gelişim, kadro, hizmet süresi, terfi, branş, sağlık', 'a) Mesleki gelişim durumu.', 'ğ) Asayiş, idari ve zaruri sebepler.', [], 'atanma isteği de var; çocukların eğitim durumu listede yok'),
 ('13', 'kosul', 'bölgenin istenilirlik düzeyi', 'bölge derecesi kriterleri: gelişmişlik, barınma, iklim, eğitim, asayiş, sağlık', 'MADDE 13- (1) Hizmet bölgelerinin dereceleri', 'kriterler dikkate alınarak belirlenir.', [], 'ulaştırma-haberleşme, günlük yaşam da; nüfus yoğunluğu, ikinci iş imkânı YOK'),
 ('15', 'tanim', 'yer değiştirme suretiyle atamalarda', 'ilk defa, yeniden, yer değiştirme: Yönetmeliğin atama türleri; yolluk tebliğde', 'MADDE 15- (1) İlk defa veya yeniden', 'ödeme emri aranmaksızın, saymanlıklarca derhal ödenir.', [], ''),
 ('15', 'sure', 'bir ayı geçemez', 'sayman/mal sorumlusu/mutemet devir süresi; işe başlama süresi devrin sonunda başlar', 'b) Hesaplarını, yerlerine gelenlere devir', 'tarihinde başlar.', [], ''),
 ('15', 'sure', 'on gün içerisinde ilgilisine', 'atama emri amire ulaşınca tebliğ süresi', '(4) Atama emrinde aksi belirlenmedikçe', 'ilgilisine tebliğ edilir.', [], ''),
 ('15', 'kosul', 'tebligata engel olmaz', 'izinli, raporlu, tutuklu, uzaklaştırılmış, hastanede yatan personele atama tebliği', '(5) Atamaya tabi tutulan personelin izinli', 'tebligata engel olmaz.', [], 'ilişik kesme gıyabında evrak üzerinden'),
 ('18', 'kosul', 'memuriyet yeminine uygun hareket', 'sadakat: Anayasa ve kanunlara sadakatle bağlı kalmak', 'MADDE 18- (1) Personel, Türkiye Cumhuriyeti Anayasasına', 'hareket etmek zorundadır.', [], ''),
 ('19', 'yasak', 'siyasi partiye üye olamaz', 'dil, ırk, cinsiyet, siyasi düşünce, felsefi inanç, din-mezhep ayrımı yapamaz', 'MADDE 19- (1) Personel siyasi partiye', 'eylemlere katılamaz.', [], 'kıdem ayrım ölçütü değil'),
 ('19', 'kosul', 'her durumda Devletin menfaatlerini', 'personel korumak mecburiyetinde; bağımsızlığı bozan faaliyete, gruplaşmaya katılamaz', '(2) Personel her durumda Devletin', 'bunlara yardım edemez.', [], ''),
 ('20', 'kosul', 'hizmet içindeki ve dışındaki davranışlarıyla', 'resmi sıfatın gerektirdiği itibar ve güvene layık olduğunu gösterme zorunluluğu', 'MADDE 20- (1) Personel, resmi sıfatının', 'göstermek zorundadır.', [], ''),
 ('20', 'kosul', 'hesap verebilirlik, hizmetin sonucuna', 'ilkeler: hukukun üstünlüğü, kamu yararı, tarafsızlık, katılımcılık, şeffaflık, sürekli gelişim', 'a) Görev ve hizmetin yerine getirilmesinde', 'sürekli gelişim ilkelerini esas alır.', [], ''),
 ('23', 'kosul', 'dikkat ve itina ile yerine', 'görevler yapılır; teslim edilen Devlet malı korunur, hizmete hazır tutulur', 'MADDE 23- (1) Personel, görevlerini dikkat', 'gerekli tedbirleri almak zorundadır.', [], ''),
 ('24', 'kosul', 'cezai takibat sonucu beklenmeden', 'zimmete geçirilen para Hazinece hak sahibine ödenir; kurumun rücu hakkı', 'Ancak, Devlet dairelerine tevdi', 'rücu hakkı saklıdır.', [], ''),
 ('24', 'kosul', 'Avrupa İnsan Hakları Mahkemesince', 'işkence/kötü muamele tazminatlarında sorumlu personele rücu (aynı usul)', '(2) İşkence ya da zalimane', 'birinci fıkra hükmü uygulanır.', [], ''),
 ('25', 'yasak', 'basına, haber ajanslarına veya radyo', 'personel bilgi/demeç veremez; illerde valiler ve Bakanın yetkili kılacağı görevli', 'MADDE 25- (1) Personel, kamu görevleri', 'görevli tarafından verilebilir.', [], ''),
 ('26', 'yasak', 'yetki verilen mahaller dışına çıkaramaz', 'resmi belge, araç ve gereçler; hususi işte kullanamaz; güvenliğinden sorumlu', 'MADDE 26- (1) Personel, görevleri ile ilgili resmi', 'güvenlik ve muhafazasından sorumludur.', [], ''),
 ('31', 'sure', 'bir aydan fazla geciktirilemez', 'çekilme talebinin kabulü (müracaattan itibaren); talepler Ocak-Şubat ve Temmuz-Ağustos', '(3) Personel çekilme taleplerini Ocak', 'halinde kabul edilebilir.', [('30', 'önceki çekilme maddesi, aynı süre')], 'mecburi hizmet hükümleri saklı'),
 ('35', 'yasak', 'kasıtlı olarak birlikte çekilmeleri', 'toplu eylem yasağı: kamu hizmetini aksatacak şekilde; göreve gelmeme, yavaşlatma', 'Madde 35- (1) Personelin kamu hizmetlerini', 'hareketlerde bulunmaları yasaktır.', [], ''),
 ('36', 'yasak', 'grev tertiplemeleri, ilan etmeleri', 'grev yasağı: karar verme, tertip, ilan, propaganda; greve katılma, teşvik', 'MADDE 36- (1) Personelin greve karar', 'destekleyemez veya teşvik edemez.', [], ''),
 ('37', 'yasak', 'tacir veya esnaf sayılmalarını', 'ticaret yasağı; kollektif ortak/komandite ortak olamaz; ofis-muayenehane açamaz', 'MADDE 37- (1) Personel, 13/1/2011', 'vakıf yükseköğretim kurumlarında çalışamaz.', [], ''),
 ('37', 'istisna', 'yapı, kalkınma ve tüketim kooperatifleri', 'üyelikler ve yardım sandığı kurul üyelikleri ticaret yasağı dışında', '(2) Personelin üyesi oldukları yapı', 'bu yasaklamanın dışındadır.', [], ''),
 ('37', 'sure', 'onbeş gün içinde bağlı', 'eş, reşit olmayan/mahcur çocuk yasak faaliyette bulunursa personel bildirir', '(3) Eşleri, reşit olmayan veya mahcur', 'bildirmekle yükümlüdürler.', [], ''),
 ('38', 'yasak', 'iş sahiplerinden borç para istemeleri', 'hediye isteme, menfaatle hediye kabulü yasak; kapsamı Etik Kurulu belirler', 'MADDE 38- (1) Personelin doğrudan doğruya', 'Etik Kurulu kararları çerçevesinde uygulama yapılır.', [], ''),
 ('39', 'yasak', 'denetimi altında bulunan veya', 'teşebbüsten doğrudan/aracı eliyle her ne ad altında menfaat sağlamak yasak', 'MADDE 39- (1) Personelin, denetimi', 'menfaat sağlaması yasaktır.', [], ''),
 ('40', 'yasak', 'ikinci görev verilemez', "657'ye tabi kurumlar, KİT'ler, Devlet bankaları; ödeme ve yarar sağlanamaz", 'a) 657 sayılı Kanuna tabi kurumlarda', 'yarar sağlanamaz.', [], 'hakem, bilirkişi, kurul-komisyon ücretleri saklı'),
 ('41', 'tanim', 'gizli olarak nitelendirilen bilgidir', 'gizli bilgi; görevden ayrılsa bile Bakanın yazılı izni olmadan açıklanamaz', 'MADDE 41- (1) Gizli bilgi; doğrudan', 'yazılı izni olmadıkça açıklayamaz.', [], ''),
 ('42', 'sure', 'yirmidört saati geçemez', 'nöbet süresi; amirin münasip göreceği zamanda başlar', '(2) Nöbet, kurumlarda amirin münasip', 'yirmidört saati geçemez.', [], ''),
 ('42', 'istisna', 'doğumdan sonraki iki yıl süreyle', 'kadın memura gece nöbeti verilemez (hamilelik boyunca); engelliye isteği dışında', 'tabip raporlarında belirtilmesi halinde hamilelik', 'gece vardiyası görevi verilemez.', [], ''),
 ('42', 'kosul', 'nöbet yerinden ayrılmaz', 'nöbetçi her zaman göreve hazır bulunur; devir yetkili amirin izniyle', '(6) Nöbetçi personel, birden bire hastalanma', 'göreve hazır bulunur.', [], ''),
 ('45', 'tanim', 'liderlik yeteneği gibi kriterler', 'değerlendirme ölçütleri: genel görünüş, temsil, adalet, disiplin-itaat, meslek bilgisi, işbirliği', '(2) Değerlendirme personelin genel görünüşü', 'kriterler esas alınarak yapılır.', [], ''),
 ('45', 'kosul', 'statüler arası geçişte, terfiinde', 'değerlendirme sonuçları: görev seçimi, atama, mesleki gelişim, kıdem sırası, ödül', '(3) Değerlendirme sonuçları personelin', 'ödüllendirilmesinde dikkate alınır.', [], 'emeklilik yaşı belirlemede değil'),
 ('45', 'sure', 'yılda en az bir kez', 'değerlendirme; sistem Bakanlıkça yürürlüğe konulan yönetmelikle', '(4) Değerlendirme yılda en az', 'yönetmelik ile belirlenir.', [], ''),
 ('50', 'makam', 'üstün cesaret ve feragat madalyası', 'Bakan verir (hayatını tehlikeye atarak); usul JGK-SGK ayrı yönetmelikleri', 'MADDE 50- (1) Kendisine tevdi edilen', 'yönetmeliklerle belirlenir.', [], ''),
 ('51', 'kosul', 'ihtiyati bir tedbirdir', 'görevden uzaklaştırma; usul 657 sayılı Kanun', 'MADDE 51- (1) Görevden uzaklaştırma Devlet', 'usul ve esaslara uyulur.', [], ''),
 ('52', 'makam', 'Bakanlık müfettişleri', 'görevden uzaklaştırmaya yetkililer: atamaya yetkili amirler, valiler, kaymakamlar da', 'MADDE 52- (1) Görevden uzaklaştırmaya yetkililer', 'ç) İlçelerde kaymakamlar.', [('51', 'uzaklaştırma tanımı maddesi, metni tekrarlı')], ''),
 ('52', 'sira_usul', 'personelin kurumuna derhal bildirilir', 'vali ve kaymakamların aldığı görevden uzaklaştırma tedbiri', '(2) Valiler ve kaymakamlar tarafından', 'kurumuna derhal bildirilir.', [('51', 'uzaklaştırma tanımı maddesi, metni tekrarlı')], ''),
 ('53', 'kosul', 'Disiplin işleri özel kanun', 'disiplin: özel kanun hükümleri; kişisel suçlar: genel hükümler', 'a) Disiplin işleri özel kanun', 'genel hükümlere göre işlem yapılır.', [], ''),
 ('53', 'kosul', 'mülki görevlerinden doğan suçlarında', '4483 sayılı Kanun; adli görev suçunda CMK 161 beşinci fıkra', 'b) Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı teşkilatları personelinin mülki', 'beşinci fıkrası hükmü uygulanır.', [], ''),
 ('53', 'kosul', 'askeri görev verildiği takdirde', 'bu görevlerden doğan suçlarda 353 sayılı Kanun; askeri mahkeme', 'ç) Jandarma hizmetleri ve sahil güvenlik', 'askeri mahkemede görülür.', [], ''),
 ('54', 'kosul', 'resmi üniforma giymesi zorunludur', 'görev sırasında; Yönetmelik/mevzuattaki istisnalar saklı', 'MADDE 54- (1) Personelin görev sırasında', 'üniforma giymesi zorunludur.', [], ''),
 ('55', 'yasak', 'personel dışındaki kişiler tarafından giyilemez', 'resmi üniforma eskimiş olsa da; işaretler sökülerek sivile dönüştürülemez', 'c) Resmi üniformalar eskimiş dahi', 'birlikte giyilemez;', [], ''),
 ('55', 'istisna', 'hamileliğini belgelediği takdirde', 'kadın personel sivil kıyafetle görev yapabilir (üniforma yasağı değil)', 'e) Resmi üniformalı olarak görev yapan kadın', 'sivil kıyafet ile görev yapabilir.', [], ''),
 ('55', 'kosul', 'resmi üniformasını çıkarmaya mecburdur', 'emeklilik, çekilme veya ilişik kesilmesinden itibaren', '(3) Personel; emeklilik, çekilme', 'çıkarmaya mecburdur.', [], ''),
 ('56', 'kosul', 'özlük hakları saklıdır', 'genel-özel kanunlarla verilen; JGK-SGK kadrosundaki personel asayiş tazminatından yararlanır', 'MADDE 56- (1) Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı personeline', 'Asayiş Tazminatından yararlanır.', [], ''),
]
yaz(22, 'Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı Personel Yönetmeliği', K)
