# Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı Personel Yönetmeliği — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('4','tanim','temsil ettiği mevkii','makam (tanım)','i) Makam','temsil ettiği mevkii,',[],'MAKAM = KOLTUK, AMİR = KOLTUKTAKİ'),
 ('4','tanim','rütbe veya kıdem büyüklüğünü','üst: makam, rütbe ya da kıdem büyüklüğü','k) Üst','kıdem büyüklüğünü,',[],''),
 ('4','tanim','inha eden makamı','müşterek kararla atananda atamaya yetkili amir','b) Atamaya yetkili amir','inha eden makamı,',[],''),
 ('5','makam','insan gücü planına','personel ihtiyacı; JGK/SGK hazırlar, Bakanlık onaylar','(4) Personel ihtiyacı','insan gücü planına göre karşılanır.',[],'kaynak: Akademi ve eğitim komutanlıkları'),
 ('7','tanim','Uçak ve helikopter teknisyeni','JGK astsubay branşı (subayda Pilot)','b) Astsubaylar 1) Jandarma','Uçak ve helikopter teknisyeni',[],''),
 ('7','tanim','Bilgi teknolojileri','Sahil Güvenlik astsubay branşı','b) Astsubaylar 1) Güverte','6) Bilgi teknolojileri',[],'SG astsubay: güverte, makine, ikmal, uçak bakım, idari'),
 ('7','tanim','İnsansız Hava Aracı','JGK subay ve astsubay branşı (2024)','(1) Jandarma Genel Komutanlığında bulunan branşlar','19) (Ek:RG-16/1/2024) İnsansız Hava Aracı',[],'Hukuk branşı 2020'),
 ('8','makam','branş belirleme kurul kararı','branş değişikliği; sağlık, uçuştan ayrılma, ikinci tahsil, kadro değişikliği','(2) Personelin branşları','kurul kararı ile değiştirilebilir.',[],''),
 ('9','sira_usul','Çekimser oy kullanılamaz','branş belirleme kurulu; üye tam sayısı, oyçokluğu, eşitlikte başkan tarafı','(2) Branş belirleme kurulları üye','onayı ile kesinleşir.',[],''),
 ('9','makam','Akademisi Başkanının','ilk branş belirleme kurulu kararını onaylar; değişiklikleri JGK/SGK','(2) Branş belirleme kurulları üye','onayı ile kesinleşir.',[],''),
 ('10','kosul','temayüz etmiş astsubaylar','subay kadrolarına atanabilir; astları değerlendirmede rütbe şartı yok','(7) İhtiyaç duyulması halinde subay','rütbe şartı aranmaz.',[],''),
 ('10','istisna','kritik ve kilit kadrolar','puanlama sisteminden hariç; Bakanlık belirler','(4) Bakanlık tarafından belirlenecek kritik','gözönünde bulundurulabilir.',[],''),
 ('11','sira_usul','kura ile yapılır','ilk görev yeri ataması; branş ve ihtisasa göre','MADDE 11- (1) Öğrenimlerini','kura ile yapılır.',[],''),
 ('12','yasak','evlenmeden önceki nüfusa kayıtlı','o ilçeye atanmaz; nüfusu bir milyonu aşan ilçeler hariç','(2) Personel, belediye sınırları','ilçelere atanmaz.',[],'kendisinin ve eşinin'),
 ('14','sure','Mayıs ve Ekim','genel atama dönemi; Bakanlık başka zaman da belirleyebilir','(2) Genel atamalar, her yılın','önceden duyurulabilir.',[],''),
 ('15','sure','Aynı yerdeki görevlere atananlar','tebliğ gününü izleyen işgünü içinde işe başlar','a) Aynı yerdeki görevlere','işe başlamak zorundadırlar.',[],'AYNI YER AYNI GÜN'),
 ('15','sure','Başka yerdeki görevlere atananlar','tebliğden onbeş gün içinde hareket; yol süresi; izleyen işgünü başlar','b) Başka yerdeki görevlere','işe başlamak zorundadırlar.',[],'savaş ve OHAL\'de süre kısaltılabilir'),
 ('15','sure','hiçbir şekilde bir ayı geçemez','sayman, mal sorumlusu, mutemedin devir süresi','b) Hesaplarını, yerlerine','tarihinde başlar.',[],'süre devrin bitiminde başlar'),
 ('15','sure','amire ulaşmasından itibaren','atama emri en geç on gün içinde tebliğ edilir','(4) Atama emrinde aksi','ilgilisine tebliğ edilir.',[],''),
 ('15','sira_usul','gıyaplarında evrak üzerinden','izinli, raporlu, tutuklu, uzaklaştırılmış personelin ilişik kesme ve katılışı','(5) Atamaya tabi tutulan','ödenmeye başlanır.',[],'tebligata engel değil'),
 ('16','makam','kendi kurumunun bütçesinden karşılanır','geçici görevlendirilen kolluk personelinin aylığı','(2) Birinci fıkraya göre görevlendirilen personelin;','bütçesinden karşılanır.',[],'görevlendirme Bakan; valiye devredebilir; disiplin soruşturması fiilen görevli kurumda'),
 ('19','yasak','siyasi partiye üye olamaz','personel; ayrım yapamaz, siyasi beyan-eylemde bulunamaz','MADDE 19- (1) Personel siyasi','bu eylemlere katılamaz.',[],''),
 ('21','yasak','hediyesini kabul edemez','amir, maiyetindekinden; borç da alamaz, menfaat isteyemez','(3) Amir, maiyetindeki personele kanunlara','borç alamaz.',[],'kanunlara aykırı emir de veremez'),
 ('23','kosul','rayiç bedeli üzerinden','kasıt, kusur, ihmalle idareye verilen zarar personelce ödenir','(2) Personelin kasıt','ödenmesi esastır.',[],''),
 ('24','kosul','ilgili kurum aleyhine dava açarlar','kamu görevinden zarar gören kişi; personele değil; kurumun rücu hakkı','MADDE 24- (1) Kişiler kamu hukukuna','rücu hakkı saklıdır.',[],''),
 ('24','kosul','cezai takibat sonucu beklenmeden','zimmete geçirilen parayı Hazine hak sahibine öder','MADDE 24- (1) Kişiler kamu hukukuna','rücu hakkı saklıdır.',[],'ZİMMETİ HAZİNE BEKLEMEDEN ÖDER'),
 ('24','kosul','Avrupa İnsan Hakları Mahkemesince','işkence tazminatı ödenirse sorumlu personele rücu','(2) İşkence ya da zalimane','birinci fıkra hükmü uygulanır.',[],''),
 ('25','yasak','basına, haber ajanslarına','personel bilgi/demeç veremez; valiler ve Bakanın yetkilendirdiği verir','MADDE 25- (1) Personel, kamu görevleri','tarafından verilebilir.',[],''),
 ('26','kosul','mirasçılarına da şamildir','resmî belge, araç, gereci iade zorunluluğu','(2) Personel görevleri icabı','mirasçılarına da şamildir.',[],''),
 ('29','kosul','görevine son verilmez','güvenlik hakkı; aylık ve hakları alınamaz','MADDE 29- (1) Kanunlarda yazılı','elinden alınamaz.',[],'kanunda yazılı haller dışında'),
 ('30','sure','Temmuz ve Ağustos ayları içinde','emeklilik talebi dönemi; kabul bir aydan fazla gecikmez','(2) Personel, emeklilik taleplerini','kabul edilebilir.',[('31','çekilme talebi de aynı aylarda')],'Ocak-Şubat da; dışındaki talep hizmet gereğine göre'),
 ('31','sure','çekilme taleplerini','Ocak-Şubat, Temmuz-Ağustos; kabul bir ayda; mecburi hizmet saklı','(3) Personel çekilme taleplerini','kabul edilebilir.',[],''),
 ('32','sira_usul','şikâyet edilen amirler atlanarak','en yakın amirden başlayarak silsile yoluyla; söz veya yazıyla','(2) Müracaat ve şikâyetler söz','atlanarak yapılır.',[],''),
 ('33','kosul','uydurma bir suç isnadı','isnat sabit olmazsa amir/vali savcılıktan kamu davası ister','(1) Personel hakkındaki ihbar','Cumhuriyet savcılığından ister.',[],'garaz ya da hakaret amaçlı ihbar'),
 ('36','yasak','greve karar vermeleri','yasak; propaganda, katılma, destekleme de','MADDE 36- (1) Personelin greve','teşvik edemez.',[],'toplu görevden çekilme de yasak'),
 ('37','sure','bağlı oldukları kuruma bildirmekle','eşi/çocuğu ticaret yapıyorsa onbeş gün içinde','(3) Eşleri, reşit olmayan','bildirmekle yükümlüdürler.',[],''),
 ('37','istisna','tüketim kooperatifleri','yönetim-denetim kurulu üyeliği ticaret yasağı dışında','(2) Personelin üyesi oldukları yapı','yasaklamanın dışındadır.',[],'yapı ve kalkınma kooperatifi, meslek kuruluşu, yardım sandığı da'),
 ('38','makam','Kamu Görevlileri Etik Kurulu','hediye yasağının kapsamı bu kurul kararlarıyla','(2) Hediye alma yasağının','uygulama yapılır.',[],''),
 ('40','yasak','657 sayılı Kanuna tabi kurumlarda','ikinci görev verilemez; Devlet bankaları, KİT\'ler de; hakem-bilirkişi ücreti saklı','MADDE 40- (1) Personele;','yarar sağlanamaz.',[],''),
 ('41','makam','Bakanın yazılı izni','gizli bilgi açıklamak için; görevden ayrılmış olsa da','(2) Personel, kamu hizmetleri ile ilgili gizli','açıklayamaz.',[],''),
 ('42','sure','yirmidört saati geçemez','nöbet süresi','(2) Nöbet, kurumlarda','yirmidört saati geçemez.',[],''),
 ('42','istisna','doğumdan sonraki iki yıl','kadın memura gece nöbeti/vardiyası verilemez (rapor varsa hamilelikte de)','Ancak kadın memurlara','görevi verilemez.',[],''),
 ('42','istisna','isteği dışında gece nöbeti','engelli memura verilemez','Engelli memurlara da','görevi verilemez.',[],''),
 ('42','sira_usul','bir tanesi tutturulur','mazeretle girilmeyen nöbetlerden, mazeret kalkınca','(3) Kendisine nöbet hizmeti','bir tanesi tutturulur.',[],'nöbet sonrakine devredilir'),
 ('43','sure','izleyen yıl içinde verilebilir','zorunlu nedenle kullanılamayan yıllık izin','MADDE 43- (1) Yıllık izinlerin','izleyen yıl içinde verilebilir.',[],'esas: senesi içinde'),
 ('44','makam','Jandarma bölge komutanları için konuşlu','izin: konuşlu bulunduğu ilin valisi','1) Jandarma Genel Komutanı için Bakan','6) Diğer personel için birinci amirler, tarafından verilir.',[],''),
 ('44','makam','personel için vali ve kaymakamlar','il ve ilçe jandarma komutanlıklarında yıllık ve mazeret izni','1) Jandarma Genel Komutanı için Bakan','6) Diğer personel için birinci amirler, tarafından verilir.',[],'diğer personele birinci amir'),
 ('44','makam','Jandarma Genel Komutanı için Bakan','izin; yardımcıları için JGK; Akademi Başkanı için de Bakan','1) Jandarma Genel Komutanı için Bakan','6) Diğer personel için birinci amirler, tarafından verilir.',[],''),
 ('45','sure','yılda en az bir kez','değerlendirme yapılır; atama, terfi, ödülde dikkate alınır','(4) Değerlendirme yılda','en az bir kez yapılır.',[],''),
 ('46','tanim','şerit rozet, bröve ve madalyadır','ödül türleri; başarı, üstün başarı, takdir belgesi de','(4) Bu Yönetmelik kapsamında verilen ödüller','bröve ve madalyadır.',[],''),
 ('46','kosul','cezalardan bağımsız çalışır','ödül sistemi','(3) Ödül sistemi, disiplinle','durum içinde değerlendirilir.',[],''),
 ('47','sayi_oran','Üç defa başarı belgesi','üstün başarı belgesi verilir','(2) Görevli oldukları kurumlarda olağanüstü','üstün başarı belgesi verilir.',[],'ÜÇ BAŞARI = BİR ÜSTÜN BAŞARI'),
 ('47','makam','ilçelerde kaymakamlar tarafından başarı belgesi','başarı belgesi: merkezde Bakan, illerde vali, ilçede kaymakam','(2) Görevli oldukları kurumlarda olağanüstü','üstün başarı belgesi verilir.',[],''),
 ('47','makam','takdir belgesi ile ödüllendirilir','amirleri tarafından; görevini eksiksiz yapan','MADDE 47- (1) Personel, görevlerini eksiksiz','takdir belgesi ile ödüllendirilir.',[],'TAKDİR AMİRDEN, BAŞARI BAKAN/VALİ/KAYMAKAMDAN'),
 ('50','makam','üstün cesaret ve feragat madalyası','Bakan verir; hayatını tehlikeye atarak görev','MADDE 50- (1) Kendisine tevdi','Bakan tarafından verilir.',[],''),
 ('51','makam','ihtiyati bir tedbirdir','görevden uzaklaştırma; yetkili: atamaya yetkili amir, Bakanlık müfettişi, vali, kaymakam','MADDE 51- (1) Görevden uzaklaştırma Devlet','ç) İlçelerde kaymakamlar.',[],'657 usulü; vali/kaymakam tedbiri kuruma derhal bildirilir'),
 ('53','kosul','353 sayılı Askeri Mahkemeler','askeri görevden doğan suçlarda (jandarma/SG hizmetleri sınıfı)','ç) Jandarma hizmetleri ve sahil güvenlik hizmetleri sınıfları personeline askeri','askeri mahkemede görülür.',[],'mülki görev suçu 4483; adli görev CMK 161/5; kişisel suç genel hükümler'),
 ('55','istisna','hamileliğini belgelediği takdirde','üniformalı kadın personel sivil kıyafetle görev yapabilir','e) Resmi üniformalı olarak görev yapan kadın','görev yapabilir.',[],''),
 ('55','yasak','eskimiş dahi olsa','resmi üniforma personel dışına verilemez, giydirilemez','c) Resmi üniformalar eskimiş','bu kişilere verilemez.',[],'ilişiği kesilen üniformayı çıkarır'),
 ('55','kosul','kravat takmış olarak','sivil elbiseyle çalışanlar; mülki amir izni hariç','d) Sivil elbise ile çalışanlar','görevde bulunmak zorundadırlar.',[],''),
 ('57','makam','peşin olarak ödenir','sevk/refakatte il dışına çıkan erbaş-er yolluğu; görevlendiren makam','MADDE 57- (1) Hükümlü, tutuklu','peşin olarak ödenir.',[],''),
 ('58','kosul','müfreze usulü ile','beslenemeyen erbaş-ere tayın bedeli (5668, 2155)','MADDE 58- (1) Görevlerinin niteliği','kapsamında ödenir.',[],''),
 ('60','sira_usul','üstlerden evvel selam vermeye','astlar mecbur; aynı rütbedekiler beklemeden selamlaşır','(2) Selamlama her yerde','selamını alırlar.',[],''),
 ('61','makam','sosyal tesislerden yararlanmayı','kimlik kartı düzenlemesi; İçişleri–MSB protokolü','(2) Kimlik kartlarının Türk Silahlı','protokol ile belirlenir.',[],''),
 ('4', 'tanim', 'teknik bilgi ve beceri gerektiren', 'ihtisas: özel hizmet alanı (branş: alt hizmet alanı)', 'ğ) İhtisas: Jandarma Genel Komutanlığı', 'özel hizmet alanlarını,', [], ''),
 ('4', 'tanim', 'Bakan: İçişleri Bakanını', 'Personel Yönetmeliğinde Bakan = İçişleri Bakanı', 'c) Bakan: İçişleri Bakanını', 'ç) Bakanlık: İçişleri Bakanlığını,', [], ''),
 ('7', 'tanim', 'Öğretmen', 'Öğretmen yalnız subay listesinde; Astsubaylar listesinde yok', '11) Maliye 12) Öğretmen', 'b) Astsubaylar 1) Jandarma', [], ''),
]
yaz(22, 'Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı Personel Yönetmeliği', K)
