# Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı Personel Yönetmeliği — kelime → cevap
# KURAL (başkan, 4 Eki 2026): SOL = soru KÖKÜNDE göreceğin ifade, SAĞ = doğru ŞIKTA arayacağın kelime.
# Sorulardan geriye doğru yazıldı (169 cevaplı soru + kitapçık kökleri); kanıt resmî metin.
# Not: her soru kökünde Yönetmeliğin adı geçtiği için "Jandarma Genel Komutanlığı", "Sahil Güvenlik", "Personel" sol olarak kullanılmaz.
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 # m.1-6 — amaç, kapsam, dayanak, tanımlar, kaynak, ilk nasıp
 ('1','tanim','Yönetmeliğin amacı','2803, 2692 ve 657’nin personel hükümlerinin uygulanması','MADDE 1- (1) Bu Yönetmeliğin amacı','usul ve esasları belirlemektir.',[],''),
 ('2','tanim','özlük işlerine ilişkin hükümleri kapsar','subay, astsubay, sözleşmeli, uzman, er; sivil memur DEĞİL','MADDE 2- (1) Bu Yönetmelik;','diğer özlük işlerine ilişkin hükümleri kapsar.',[],'sivil memur ve işçi kapsamda değil'),
 ('2','tanim','mesleki gelişimleri','branşlaşma, hizmet şartı, nitelik, atama, ödev-hak-yükümlülük-sorumluluk, özlük','MADDE 2- (1) Bu Yönetmelik;','diğer özlük işlerine ilişkin hükümleri kapsar.',[('17', 'm.17 mesleki gelişim: lisansüstü eğitim, yurt içi-dışı kurs')],'kaynak ve işe alınma da'),
 ('2','kosul','nasıp ve terfi','TSK Personel K. 926, 4678, 3466, 3269, 6191, 657','(2) Birinci fıkradaki personelin nasıp','hükümlerine göre yürütülür.',[],'aylık, mali ve sosyal haklar da'),
 ('3','kosul','hükümlerine dayanılarak','2803 Kanunun m.24, 2692 Kanunun m.23','MADDE 3- (1) Bu Yönetmelik;','dayanılarak hazırlanmıştır.',[('40', 'özel kanunlara dayanılarak kurulan bankalarda ikinci görev yok')],''),
 ('4','tanim','Bakan:','İçişleri Bakanı','c) Bakan:','ç) Bakanlık: İçişleri Bakanlığını,',[],'2026 Uzman sınavında soruldu'),
 ('4','tanim','kıdem büyüklüğü','üst: makam, rütbe büyüklüğü','k) Üst:','kıdem büyüklüğünü,',[],'makam, rütbe ya da kıdem büyüklüğü'),
 ('4','tanim','temsil ettiği mevki','makam','i) Makam:','temsil ettiği mevkii,',[],'MAKAM = KOLTUK, AMİR = KOLTUKTAKİ'),
 ('4','tanim','amir olarak yetkilendirilmiş','amir','a) Amir:','yetkilendirilmiş olan diğer kişileri,',[],'kadro-kuruluş yönünden bağlı olunan kimse'),
 ('4','tanim','inha eden makam','atamaya yetkili amir','b) Atamaya yetkili amir:','inha eden makamı,',[],'müşterek kararla atananlarda'),
 ('4','tanim','teknik bilgi ve beceri','ihtisas','ğ) İhtisas:','özel hizmet alanlarını,',[],'özel yetenek gerektiren özel hizmet alanı'),
 ('4','tanim','alt hizmet alanları','branş','d) Branş:','alt hizmet alanlarını,',[],''),
 ('4','tanim','beden ve zihni kabiliyetleri','branşlaşma','e) Branşlaşma:','branşlara ayrılmasını,',[],'meslek hayatı boyunca değerlendirilir'),
 ('4','tanim','başarı düzeyini ölçen','değerlendirme','f) Değerlendirme:','mesleki gelişimini sağlayan işlemleri,',[],''),
 ('4','tanim','belirlenen atama yeri','hizmet bölgesi','g) Hizmet bölgesi:','belirlenen atama yerini,',[],'konuş ve kuruluş durumuna göre'),
 ('4','tanim','birçok birimi bir araya getiren','kuruluş','h) Kuruluş:','hizmet birimlerini,',[],''),
 ('5','makam','personel ihtiyacı','Akademi, eğitim komutanlığını başarıyla bitirenler; Bakanlık onaylı plan','MADDE 5- (1) Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığının personel ihtiyacı;','insan gücü planına göre karşılanır.',[],''),
 ('5','kosul','Akademide yetiştirilemeyen','diğer üniversitelerle protokol','(2) Jandarma ve Sahil Güvenlik Akademisi tarafından','Bakanlık tarafından belirlenir.',[],'JGK-SGK nam ve hesabına okutulabilir'),
 ('6','kosul','İlk nasıp','926, 4678, 3466, 3269, 6191 sayılı Kanunlar','İlk nasıp','hükümleri uyarınca yapılır.',[],''),
 # m.7-9 — branşlar
 ('7','tanim','28/5/2020','Hukuk branşı eklendi (Jandarma ve Sahil Güvenlik subayına)','(1) Jandarma Genel Komutanlığında bulunan branşlar','4) (Ek:RG-28/5/2020) Hukuk',[],''),
 ('7','tanim','16/1/2024','İnsansız Hava Aracı (Jandarma subay ve astsubay); Sahil Güvenlikte YOK','(1) Jandarma Genel Komutanlığında bulunan branşlar','11) (Ek:RG-16/1/2024) İnsansız Hava Aracı',[],''),
 ('7','tanim','astsubay','branşı: Jandarma: muhabere, uçak-helikopter teknisyeni; Sahil Güvenlik: güverte, makine, idari','(1) Jandarma Genel Komutanlığında bulunan branşlar','6) Bilgi teknolojileri',[('2', 'kapsamdaki personel: subay, astsubay, uzman, er'), ('4', 'personel tanımı: subay, astsubay, uzman, er'), ('9', 'subay ve astsubayların ilk branşı kurulca belirlenir'), ('10', 'subay kadrosuna temayüz etmiş astsubay atanabilir')],'pilot, öğretmen, tabip, kimyager, veteriner yalnız Jandarma subayında; astsubayda YOK'),
 ('8','kosul','İlk branş belirlenme','Akademi ve üniversitede Jandarma-Sahil Güvenlik adına okuyan öğrenci','MADDE 8- (1) İlk branş belirlenme','öğrenim gören öğrencilerdir.',[],''),
 ('8','makam','branş değişikliği','kurul kararıyla; kurum ihtiyacına göre','Branşların belirlenmesi ve branş değişikliği','kurul kararı ile değiştirilebilir.',[('9','branş değişikliği kararını Genel Komutan ya da SG Komutanı onaylar')],'sağlık, uçuştan ayrılma, ikinci tahsil, kadro değişikliği sebebiyle; kendi talebi tek başına yetmez'),
 ('9','sira_usul','Çekimser oy','kullanılamaz; tam sayıyla toplanır; eşitlikte başkanın tarafı','(2) Branş belirleme kurulları üye','başkanın bulunduğu taraf çoğunluk sayılır.',[],'oyçokluğuyla karar'),
 ('9','makam','onayı ile kesinleşir','ilk: Akademi Başkanı; değişiklik: Genel Komutan-Sahil Güvenlik Komutanı','İlk branş belirleme kurullarının kararları','onayı ile kesinleşir.',[],''),
 # m.10-16 — atama
 ('10','kosul','Atamalarda','hizmet bölgesinin özellikleri esas','MADDE 10- (1) Atamalarda','özellikleri esas alınır.',[('12','atamalarda dikkate alınacak kriterler maddesi'),('15','yer değiştirme atamalarında yolluk derhal ödenir')],''),
 ('10','kosul','zorunlu atama','farklı hizmet bölgeleri arasında, meslek boyu','(2) Personel, hizmet ihtiyacı','zorunlu atama işlemine tabi tutulur.',[],''),
 ('10','istisna','kritik ve kilit kadrolar','Bakanlık belirler; puanlama dışı','(4) Bakanlık tarafından belirlenecek kritik','gözönünde bulundurulabilir.',[],''),
 ('10','kosul','hizmet bölgesi sürelerini tamamlamadan','hizmet bölgesi değiştirerek atanmaz','(6) Subay ve astsubayların atandığı','atamaya tabi tutulmazlar.',[],'atama yönetmeliğindeki sebepler hariç'),
 ('10','kosul','subay kadrolarına','temayüz etmiş astsubay; değerlendirmede rütbe şartı yok','(7) İhtiyaç duyulması halinde subay','rütbe şartı aranmaz.',[],'liyakat esas'),
 ('11','sira_usul','ilk görev','branş ve ihtisasa göre kura','MADDE 11- (1) Öğrenimlerini','kura ile yapılır.',[],'kuradan muafiyeti JGK-SGK yönetmeliği belirler'),
 ('12','kosul','Personelin atamaları','kriterler: gelişim, kadro, hizmet süresi, terfi, branş, sağlık, puanlama, istek','MADDE 12- (1) Personelin atamaları','ğ) Asayiş, idari ve zaruri sebepler.',[],'asayiş-idari-zaruri sebepler de; eşin çalışması, çocuğun eğitimi YOK; sağlıkta yalnız hayati önemi haiz'),
 ('12','yasak','evlenmeden önceki','nüfus ilçesine (kendi/eşi) atanmaz; milyonu aşan ilçe hariç','(2) Personel, belediye sınırları','ilçelere atanmaz.',[],''),
 ('13','kosul','Hizmet bölgelerinin dereceleri','gelişmişlik, barınma, iklim, eğitim, asayiş, sağlık, özlük; ikinci iş YOK','MADDE 13- (1) Hizmet bölgelerinin dereceleri','kriterler dikkate alınarak belirlenir.',[],'sosyal-kültürel, günlük yaşam, istenilirlik, ulaştırma-haberleşme da; nüfus yoğunluğu YOK'),
 ('14','sure','Genel atamalar','Mayıs-Ekim arası (dahil); Bakanlık başka zaman da','(2) Genel atamalar, her yılın','zamanlarda da yapılabilir.',[],''),
 ('15','sure','Aynı yerdeki','göreve atanan: tebliğ gününü izleyen işgünü başlar','a) Aynı yerdeki görevlere','işe başlamak zorundadırlar.',[],'tebliğ günü DEĞİL'),
 ('15','sure','Başka yerdeki','göreve atanan: onbeş gün içinde hareket; yol süresini izleyen işgünü','b) Başka yerdeki görevlere','işe başlamak zorundadırlar.',[],''),
 ('15','makam','Savaş ve olağanüstü hallerde','Bakanlar Kurulu kısaltabilir','b) Başka yerdeki görevlere','Bakanlar Kurulu kararı ile kısaltılabilir.',[],''),
 ('15','sure','mutemetler','devir bir ayı geçemez; süre devirden sonra başlar','b) Hesaplarını, yerlerine','tarihinde başlar.',[],'sayman, mal sorumlusu, muhasebe yetkilisi'),
 ('15','sira_usul','yollukları','ödeme emri aranmadan derhal ödenir','(3) Yer değiştirme suretiyle','saymanlıklarca derhal ödenir.',[('57','sevk-refakatteki erbaş-erin yolluğunu görevlendiren makam peşin öder')],''),
 ('15','sure','amire ulaşmasından itibaren','en geç on günde tebliğ','(4) Atama emrinde aksi','ilgilisine tebliğ edilir.',[],''),
 ('15','kosul','izinli, raporlu, tutuklu','tebligata engel olmaz; ilişik gıyaben evrakla','(5) Atamaya tabi tutulan','ödenmeye başlanır.',[],'özlük hakları yeni birlikçe ödenir'),
 ('16','makam','geçici görevlendirmeler','Bakan; il valilerine devredebilir','Genel kolluk kuvvetleri arası geçici görevlendirmeler','il valilerine devredebilir.',[],'EGM, SGK, JGK arası her kademede'),
 ('16','makam','Aylık ve diğer mali haklar','kendi kurumunun bütçesinden','(2) Birinci fıkraya göre','bütçesinden karşılanır.',[],'özlük kendi kurumunda'),
 ('16','makam','Disiplin soruşturması','fiilen görevli olduğu kurumda; dosya kendi kurumuna','c) Disiplin soruşturması','disiplin amiri ve kurullarına gönderilir.',[],''),
 ('17','makam','eğitim planı','Jandarma-Sahil Güvenlik hazırlar, Bakanlık onaylar','(3) Personelin mesleki gelişimine','Bakanlık tarafından onaylanır.',[],''),
 # m.18-27 — ödev ve sorumluluklar
 ('18','kosul','sadakatle bağlı','Anayasa ve kanunlara; memuriyet yemini','MADDE 18- (1) Personel','hareket etmek zorundadır.',[],''),
 ('19','yasak','Tarafsızlık','siyasi partiye üye olamaz; ayrım, siyasi beyan yok','Tarafsızlık ve Devlete bağlılık','bu eylemlere katılamaz.',[('20','tarafsızlık davranış ilkelerinden de')],''),
 ('19','yasak','ayırım yapamaz','dil, ırk, cinsiyet, siyasi düşünce, felsefi inanç, din-mezhep; kıdem YOK','MADDE 19- (1) Personel siyasi','bu eylemlere katılamaz.',[],''),
 ('19','kosul','Devletin menfaatlerini','her durumda korumak mecburiyetinde','(2) Personel her durumda','bunlara yardım edemez.',[],'bölücü faaliyete, gruplaşmaya katılamaz'),
 ('19','yasak','kişi veya zümrenin','yararını veya zararını hedef tutamaz','MADDE 19- (1) Personel siyasi','davranışta bulunamaz;',[],''),
 ('20','kosul','itibar ve güvene','hizmet içindeki ve dışındaki davranışla gösterir','MADDE 20- (1) Personel, resmi','göstermek zorundadır.',[],''),
 ('20','kosul','ilkelerini esas alır','hukukun üstünlüğü, kamu yararı, tarafsızlık, katılımcılık, şeffaflık, hesap verebilirlik','a) Görev ve hizmetin yerine getirilmesinde','ilkelerini esas alır.',[],'hizmetin sonucuna odaklılık, sürekli gelişim de'),
 ('20','sira_usul','mesleki nezaket','astlar üstlerine, maiyet amirlerine nezaketle hitap','(3) Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı teşkilatlarında;','mesleki nezaket kurallarına göre hitap eder.',[],''),
 ('21','yasak','maiyetindeki personele','aykırı emir veremez; menfaat, hediye, borç alamaz','(3) Amir, maiyetindeki','borç alamaz.',[],'hakkaniyet ve adaletle davranır'),
 ('22','kosul','görevlerinin iyi ve doğru','amirlerine karşı sorumlu','MADDE 22- (1) Personel kanun','amirlerine karşı sorumludur.',[],''),
 ('23','kosul','Devlet malı','dikkat-itina; korur, hizmete hazır tutar','MADDE 23- (1) Personel, görevlerini','gerekli tedbirleri almak zorundadır.',[],''),
 ('23','kosul','idare zarara uğratılmışsa','personel rayiç bedel üzerinden öder','(2) Personelin kasıt','ödenmesi esastır.',[],'kasıt, kusur, ihmal, tedbirsizlik'),
 ('24','kosul','kamu hukukuna tabi görev','kurum aleyhine dava; personele değil','MADDE 24- (1) Kişiler kamu hukukuna','aleyhine dava açarlar.',[],''),
 ('24','kosul','zimmete geçirilmesi halinde','cezai takibat beklenmeden Hazine öder','Ancak, Devlet dairelerine tevdi','Hazine tarafından hak sahibine ödenir.',[],''),
 ('24','kosul','sorumlu personel','genel hükümlere göre rücu','Kurumun, genel hükümlere göre','rücu hakkı saklıdır.',[],''),
 ('24','kosul','Avrupa İnsan Hakları Mahkemesi','sorumlu personele rücu','(2) İşkence ya da zalimane','birinci fıkra hükmü uygulanır.',[],'işkence, kötü muamele tazminatı'),
 ('25','yasak','basına','illerde valiler ve Bakanın yetkili kıldığı görevli','MADDE 25- (1) Personel, kamu görevleri','görevli tarafından verilebilir.',[],'personel bilgi-demeç veremez'),
 ('25','yasak','demeç','personel veremez (basın, ajans, radyo-TV)','MADDE 25- (1) Personel, kamu görevleri','bilgi veya demeç veremez.',[],''),
 ('26','yasak','yetki verilen mahaller','dışına çıkaramaz; hususi işte kullanamaz','MADDE 26- (1) Personel, görevleri ile ilgili','güvenlik ve muhafazasından sorumludur.',[],'resmi belge, araç, gereç'),
 ('26','kosul','resmi belge, araç ve gereçleri','görev bitince iade; mirasçılara da şamil','(2) Personel görevleri icabı','mirasçılarına da şamildir.',[],''),
 # m.28-41 — haklar ve yasaklar
 ('28','kosul','aynen uygulanmasını','istemek hakkı','MADDE 28- (1) Personel, ilgili kanun','hakkına sahiptir.',[],''),
 ('29','kosul','görevine son','verilmez: kanunda yazılı haller dışında','MADDE 29- (1) Kanunlarda yazılı','elinden alınamaz.',[],'aylık ve hakları da alınamaz'),
 ('30','sure','emeklilik talep','Ocak-Şubat, Temmuz-Ağustos; kabul en geç bir ay','(2) Personel, emeklilik taleplerini','kabul edilebilir.',[],'diğer aylarda hizmet gereğine göre'),
 ('31','sure','çekilme','Ocak-Şubat, Temmuz-Ağustos; kabul en geç bir ay','(3) Personel çekilme taleplerini','kabul edilebilir.',[('11','kura çekilmesine ilişkin hususları JGK-SGK belirler'),('35','kasıtlı birlikte görevden çekilme yasak'),('55','çekilenin üniformayı çıkarma mecburiyeti')],'mecburi hizmet hükümleri saklı'),
 ('32','sira_usul','Müracaat ve şikâyetler','söz veya yazıyla, en yakın amirden silsileyle; şikâyet edilen atlanır','(2) Müracaat ve şikâyetler söz','atlanarak yapılır.',[],'en kısa zamanda ilgiliye bildirilir'),
 ('33','kosul','isnad','garaz-hakaret amaçlı: merkezde en büyük amir, illerde valiler dava ister','(1) Personel hakkındaki ihbar','Cumhuriyet savcılığından ister.',[],'sabit olmayan uydurma suç isnadı; kamu davası savcılıktan istenir'),
 ('35','yasak','Toplu eylem','kasıtlı birlikte çekilme, gelmeme, yavaşlatma yasak','Toplu eylem ve hareketlerde','bulunmaları yasaktır.',[],''),
 ('36','yasak','grev','karar, tertip, ilan, propaganda, katılma, destek yasak','Grev yasağı','teşvik edemez.',[],''),
 ('37','yasak','tacir veya esnaf','sayılmayı gerektiren faaliyet yasak; büro açamaz, vakıf üniversitesinde çalışamaz','MADDE 37- (1) Personel, 13/1/2011','vakıf yükseköğretim kurumlarında çalışamaz.',[],'kollektif ortak, komandite ortak olamaz'),
 ('37','istisna','kooperatif','yönetim-denetim kurulu üyeliği yasak dışı','(2) Personelin üyesi oldukları yapı','yasaklamanın dışındadır.',[],'yapı, kalkınma, tüketim kooperatifi; meslek kuruluşu; yardım sandığı'),
 ('37','sure','yasaklanan','faaliyeti eşi, reşit olmayan-mahcur çocuk yaparsa onbeş günde bildirir','(3) Eşleri, reşit olmayan','bildirmekle yükümlüdürler.',[],''),
 ('38','yasak','borç para','iş sahibinden istemek-almak yasak','MADDE 38- (1) Personelin doğrudan','almaları yasaktır.',[],''),
 ('38','yasak','Hediye alma','istemek yasak; menfaat amaçlı kabul yasak; kapsamı Etik Kurulu','Hediye alma, menfaat sağlama yasağı','çerçevesinde uygulama yapılır.',[('21','amir maiyetinden hediye kabul edemez')],'görev sırasında olmasa da'),
 ('39','yasak','denetimi altında','teşebbüsten doğrudan-aracıyla menfaat yasak','MADDE 39- (1) Personelin, denetimi','menfaat sağlaması yasaktır.',[],'her ne ad altında olursa olsun'),
 ('40','yasak','İkinci görev','657 kurumları, KİT, Devlet bankası; ödeme-yarar yok','İkinci görev yasağı','yarar sağlanamaz.',[],'hakem, bilirkişi, kurul-komisyon ücretleri saklı'),
 ('41','yasak','gizli bilgi','görevden ayrılsa da Bakanın yazılı izni olmadan açıklanamaz','(1) Gizli bilgi;','yazılı izni olmadıkça açıklayamaz.',[],''),
 ('41','tanim','Gizli bilgi;','kanunla ya da yetkili makamca gizli nitelendirilen','(1) Gizli bilgi;','nitelendirilen bilgidir.',[],''),
 # m.42-44 — nöbet ve izin
 ('42','sure','nöbet','yirmidört saati geçemez; amirin uygun gördüğü zaman başlar','(2) Nöbet, kurumlarda','yirmidört saati geçemez.',[],''),
 ('42','makam','nöbet sistemleri','kurumlarınca düzenlenir','MADDE 42- (1) Günün yirmidört','kurumlarınca düzenlenir.',[],''),
 ('42','istisna','hamile','doğumdan sonra iki yıl gece nöbeti yok','Ancak kadın memurlara','gece vardiyası görevi verilemez.',[('55','hamileliğini belgeleyen kadın personel sivil kıyafetle görev yapabilir')],'tabip raporunda belirtilmişse; hamilelik boyunca da'),
 ('42','istisna','Engelli memurlara','isteği dışında gece nöbeti verilemez','Engelli memurlara da','görevi verilemez.',[],''),
 ('42','sira_usul','Mazeret kalktığında','geçmiş nöbetlerden biri tutturulur','(3) Kendisine nöbet hizmeti','bir tanesi tutturulur.',[],'nöbet sonrakine devredilir'),
 ('42','sira_usul','Tatil ve bayram','nöbet hep aynı kişiye gelmez','(4) Tatil ve bayram','tedbirler alınır.',[],''),
 ('42','sira_usul','birden bire hastalanma','yetkili amir izniyle sonrakine devreder','(6) Nöbetçi personel','devir ve teslim edebilir.',[],'mahkemeye çağrılma, başka görev de'),
 ('42','kosul','nöbetin özelliğine','nöbet yerinden ayrılmaz, göreve hazır','(7) Görevlendirilen nöbetin','göreve hazır bulunur.',[],''),
 ('43','makam','izinden geri','çağırma: izin planlamasını onaylayan makam','(2) Görev ve hizmet ihtiyacının','geriye çağrılabilir.',[],''),
 ('43','sure','kısmen veya tamamen kullanamayan','izleyen yıl içinde','MADDE 43- (1) Yıllık izinlerin','izleyen yıl içinde verilebilir.',[],'esas: senesi içinde'),
 ('44','makam','İl ve ilçe jandarma komutanlıklarında','vali ve kaymakam verir','5) İl ve ilçe jandarma','vali ve kaymakamlar,',[],'yıllık ve mazeret izni'),
 ('44','makam','bölge komutanları için','konuşlu il valisi','4) Jandarma bölge komutanları','ilin valisi,',[],'SG bölge-grup komutanına da konuşlu il valisi'),
 ('44','makam','Jandarma Genel Komutanı için','Bakan','1) Jandarma Genel Komutanı için','Bakan,',[],'yardımcılarına Genel Komutan; Akademi Başkanına da Bakan'),
 ('44','makam','Diğer personel için','birinci amir','6) Diğer personel için','birinci amirler,',[],''),
 ('44','sira_usul','yüzer unsur','izin başlangıç-bitişi vali-kaymakama bildirilir','c) Sahil güvenlik bölge, grup ve yüzer','kaymakamlara bildirilir.',[],''),
 # m.45-50 — değerlendirme ve ödül
 ('45','sure','Değerlendirme','yılda en az bir kez','(4) Değerlendirme yılda','en az bir kez yapılır.',[('4','değerlendirme tanımı: başarı düzeyini ölçen işlemler'),('10','subay kadrosundaki astsubaya değerlendirmede rütbe şartı yok'),('16','geçici görevlinin değerlendirmesi kendi kurumunda')],''),
 ('45','kosul','Değerlendirme sonuçları','atama, gelişim, statü geçişi, terfi, kıdem, ödül; emeklilik DEĞİL','(3) Değerlendirme sonuçları','ödüllendirilmesinde dikkate alınır.',[],'görevlere seçim de'),
 ('45','makam','Değerlendirme sistemine','Bakanlık yönetmeliğiyle','(5) Değerlendirme sistemine','yönetmelik ile belirlenir.',[],''),
 ('45','tanim','liderlik yeteneği','görünüş, temsil, adalet, disiplin, meslek bilgisi, işbirliği, zeka, karar','(2) Değerlendirme personelin','kriterler esas alınarak yapılır.',[],'ölçütler'),
 ('46','tanim','ödüller','başarı, üstün başarı, takdir belgesi, rozet, bröve, madalya; aylık-plaket YOK','(4) Bu Yönetmelik kapsamında verilen ödüller','bröve ve madalyadır.',[],'şerit rozet; terfi ikramiyesi, yurt dışı görevi de YOK'),
 ('46','kosul','Ödül sistemi','disiplin cezalarından bağımsız','(3) Ödül sistemi','durum içinde değerlendirilir.',[],'emsalleriyle kıyaslama esas'),
 ('47','makam','görevlerini eksiksiz','yerine getirene: amiri takdir belgesi verir','MADDE 47- (1) Personel, görevlerini eksiksiz','takdir belgesi ile ödüllendirilir.',[],''),
 ('47','makam','başarı belgesi','merkezde Bakan, illerde valiler, ilçede kaymakamlar','(2) Görevli oldukları kurumlarda','başarı belgesi verilebilir.',[('46','ödül türleri listesi')],'tasarruf, kamu zararını önleme, gelir artışı katkısı'),
 ('47','sayi_oran','defa başarı belgesi','üç defa alana üstün başarı belgesi','Üç defa başarı belgesi','üstün başarı belgesi verilir.',[],'ÜÇ BAŞARI = BİR ÜSTÜN BAŞARI'),
 ('48','tanim','Şerit rozet','başarı, öğrenim, görev yeri temsilen','MADDE 48- (1) Personelin moralini','şerit rozetler verilir.',[('46','ödül türleri listesinde')],''),
 ('49','tanim','Bröve','ihtisas-yetenek kazandıran kurs mezununa','MADDE 49- (1) Personel arasından','bröve verilir.',[('46','ödül türleri listesinde')],''),
 ('50','makam','üstün cesaret ve feragat','Bakan verir','MADDE 50- (1) Kendisine tevdi','Bakan tarafından verilir.',[],'hayatını tehlikeye atarak görev'),
 ('50','makam','Madalyanın','esasları Jandarma ve Sahil Güvenlik ayrı yönetmelikle','Madalyanın hangi esas','yönetmeliklerle belirlenir.',[],''),
 # m.51-56 — görevden uzaklaştırma, soruşturma, kıyafet, özlük
 ('51','tanim','Görevden uzaklaştırma','ihtiyati tedbir; 657 usulü','MADDE 51- (1) Görevden uzaklaştırma','usul ve esaslara uyulur.',[('15', 'görevden uzaklaştırılmış olmak atama tebligatına engel değil'), ('52', 'görevden uzaklaştırmaya yetkililer: atama amiri, müfettiş, vali, kaymakam')],'ceza DEĞİL'),
 ('52','makam','Görevden uzaklaştırmaya yetkili','atama amiri, müfettiş, vali, kaymakam; jandarma komutanı, belediye DEĞİL','MADDE 52- (1) Görevden uzaklaştırmaya','ç) İlçelerde kaymakamlar.',[('51', 'm.51 metninde aynı liste tekrarlanır')],'Bakanlık müfettişleri'),
 ('52','sira_usul','uzaklaştırma tedbiri','personelin kurumuna derhal bildirilir','(2) Valiler ve kaymakamlar','kurumuna derhal bildirilir.',[('51','m.51 metninde aynı hüküm tekrarlanır')],'vali ve kaymakamın aldığı tedbir'),
 ('53','kosul','Disiplin işleri','özel kanun hükümleri','a) Disiplin işleri','göre yürütülür.',[],''),
 ('53','kosul','mülki görevlerinden doğan','suçlarda 4483 sayılı Kanun','b) Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı teşkilatları personelinin mülki','hükümlerine göre işlem yapılır.',[],''),
 ('53','kosul','Adli görevlerinden doğan suçlarda','5271 sayılı Ceza Muhakemesi Kanunu 161 beşinci fıkra','c) Adli görevlerinden doğan','fıkrası hükmü uygulanır.',[],''),
 ('53','kosul','askeri görev verildiği takdirde','bu görevden doğan suçlarda 353 sayılı Kanun; askeri mahkeme','ç) Jandarma hizmetleri ve sahil güvenlik','askeri mahkemede görülür.',[],''),
 ('53','kosul','kişisel suçlarında','genel hükümler','d) Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı teşkilatları personelinin kişisel','genel hükümlere göre işlem yapılır.',[],''),
 ('54','kosul','resmi üniforma giymesi','görevde zorunlu; istisnalar saklı','MADDE 54- (1) Personelin görev','giymesi zorunludur.',[],''),
 ('55','kosul','ilişiği kesildiği tarihten','üniformayı çıkarmaya mecbur','(3) Personel; emeklilik','çıkarmaya mecburdur.',[],'emeklilik, çekilme ya da başka nedenle'),
 ('55','istisna','sivil kıyafet','hamileliğini belgeleyen kadın personel','e) Resmi üniformalı olarak','görev yapabilir.',[],'yasak DEĞİL, izin'),
 ('55','yasak','eskimiş dahi olsa','personel dışındakilerce giyilemez, onlara verilemez','c) Resmi üniformalar eskimiş','bu kişilere verilemez.',[],''),
 ('55','kosul','kravat','sivil elbiseli çalışan; mülki amir izni hariç','d) Sivil elbise ile çalışanlar','görevde bulunmak zorundadırlar.',[],''),
 ('55','kosul','şapka, kep, bere','bina, araç, gemi dışında zorunlu','b) Resmi görevlilerin','giymesi zorunludur.',[],''),
 ('56','kosul','özlük hakları','saklıdır','MADDE 56- (1) Jandarma Genel Komutanlığı','özlük hakları saklıdır.',[('13','hizmet bölgesi derecesinde özlük haklarındaki farklılık dikkate alınır'),('15','gıyaben katılan personelin özlük hakları yeni birlikçe ödenir')],''),
 ('56','kosul','Asayiş Tazminatı','Jandarma ve Sahil Güvenlik kadrosundaki personel','(2) Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı kadrolarına','Asayiş Tazminatından yararlanır.',[],''),
 # m.57-64 — diğer
 ('57','makam','il sınırları dışına çıkan','yolluğu görevlendiren makam peşin öder','MADDE 57- (1) Hükümlü, tutuklu','peşin olarak ödenir.',[],'sevk-refakatteki erbaş ve er'),
 ('58','kosul','kazandan','beslenemeyen erbaş-ere tayın bedeli','MADDE 58- (1) Görevlerinin niteliği','kapsamında ödenir.',[],'5668 ve 2155 sayılı Kanunlar'),
 ('59','kosul','Sağlık yeteneği','Silahlı Kuvvetler, Jandarma ve Sahil Güvenlik Sağlık Yeteneği Yönetmeliği','MADDE 59- (1) Personelin sağlık','göre yürütülür.',[],''),
 ('60','sira_usul','Selamlama','astlar üstlerden evvel verir; her yerde, her zaman','(2) Selamlama her yerde','selamını alırlar.',[],'aynı rütbedekiler beklemeden selamlaşır'),
 ('61','makam','sosyal tesislerden yararlanmayı','Bakanlık-Milli Savunma protokolü','(2) Kimlik kartlarının','protokol ile belirlenir.',[],''),
 ('63','sure','yürürlüğe girer','yayımı tarihinde','MADDE 63- (1) Bu Yönetmelik','yürürlüğe girer.',[],''),
 ('64','makam','Yönetmelik hükümlerini','Bakanlar Kurulu yürütür','MADDE 64- (1) Bu Yönetmelik','Bakanlar Kurulu yürütür.',[('1', 'amaç: kanunların personel hükümlerinin uygulanması')],''),
]
yaz(22, 'Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı Personel Yönetmeliği', K)
