# Jandarma ve Sahil Güvenlik Personelinin Hizmet Esasları Yönetmeliği — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('2','istisna','işçiler kendi mevzuatına tabidir','işçiler Yönetmelik kapsamı dışında','görevli işçiler kendi','mevzuatına tabidir.',[],'askerlik yükümlüleri: eksik hususlarda diğer yükümlülerin mevzuatı'),
 ('3','sayi_oran',"24’üncü maddesine",'dayanak 2803 sayılı Kanun m.24 ve 2692 sayılı Kanun m.23','Bu Yönetmelik, 10/3/1983','dayanılarak hazırlanmıştır.',[],''),
 ('4','tanim','kuruluş yönünden bağlı olunan','Âmir; ayrıca âmir olarak yetkilendirilmiş diğer personel','a) Âmir: Kadro ve kuruluş','olan diğer personeli,',[],''),
 ('4','tanim','Rütbe veya kıdemce küçük','Ast (Üst: rütbe veya kıdemce büyük)','b) Ast: Rütbe veya kıdemce','küçük olan personeli,',[],''),
 ('4','tanim','astının ve üstünün hukukuna riayeti','Disiplin tanımı; mevzuata ve âmirlere mutlak itaat ile','g) Disiplin: Mevzuat hükümlerine','hukukuna riayeti,',[],''),
 ('4','tanim','söz, yazı ve sair surette','Emir tanımı; göreve ilişkin fiilin yapılması veya yapılmaması asta bildirilir','ğ) Emir: Göreve ilişkin','asta bildirilmesini,',[],''),
 ('4','tanim','yeterlik bakımından üstünlük sırasını','Kıdem (aynı nasıplılar arasında)','m) Kıdem: Belli bir rütbeye','üstünlük sırasını,',[],''),
 ('4','tanim','bekleme süresinin başlama tarihini','Nasıp (yeni rütbenin normal bekleme süresi)','u) Nasıp: İlk rütbeye','başlama tarihini,',[],''),
 ('4','tanim','duruşu ve dış görünüşünü','Kılık (Kıyafet = giyim ve kuşam)','n) Kılık: Personelin duruşu','ö) Kıyafet: Giyim ve kuşamı,',[],'KILIK DURUŞ, KIYAFET GİYİM'),
 ('4','tanim','komutası altındaki personeli','Maiyet (âmirin emir ve komutası altındakiler)','s) Maiyet: Âmirin emir','komutası altındaki personeli,',[],''),
 ('4','tanim','geçici olarak personelin kullanımına','Tahsis: belli bir görev için geçici kullanım (İstihkak: sarf yetkisi)','dd) Tahsis: Belli bir görevin','kullanımına verilmesini,',[],'istihkak = sarfına yetki verilen giyecek/teçhizatın cins ve miktarı'),
 ('4','tanim','Nizamiye/Lumbarağzı','giriş-çıkış kontrol ve emniyet tesisi; belirli sayıda kuvvet','ü) Nizamiye/Lumbarağzı: Karargâh','kuvvet ihtiva eden tesisi,',[],''),
 ('4','tanim','sekiz kademeli çavuşa kadar','uzman jandarma rütbe aralığı (3466 sayılı Kanun)','gg) Uzman jandarma: 28/5/1988','çavuşa kadar rütbeyi haiz şahısları,',[],'uzman erbaş: 3269; uzman onbaşı ve uzman çavuş'),
 ('4','tanim','erler ile işçiler hariç','Devlet memuru tanımı (rütbeliler, yedekler, erler dışında kalanlar)','f) Devlet memuru: Jandarma','işçiler hariç diğer personeli,',[],''),
 ('5','sira_usul','ant içerek göreve başlar','yetkili âmirlerin huzurunda; tören usulü yönerge ile','Personel, yetkili âmirlerin huzurunda','yönerge ile düzenlenir.',[],''),
 ('6','kosul','subay ve astsubayların astı','Uzman jandarma: diğer rütbeli personelin üstü','(3) Uzman jandarmalar, subay','diğer rütbeli personelin üstüdür.',[],''),
 ('6','kosul','emsal rütbedeki sözleşmeli erbaşların','Uzman erbaş onların üstü (subay, astsubay, uzman jandarmanın astı)','(4) Uzman erbaşlar, subay','emsal rütbedeki erbaşların üstüdür.',[],'yükümlü emsal erbaşların da üstü'),
 ('6','kosul','emsal rütbedeki uzman erbaşların astı','Sözleşmeli erbaş; yükümlü emsal erbaşların üstü','(5) Sözleşmeli erbaşlar, subay','emsal rütbedeki erbaşların üstüdür.',[],''),
 ('6','istisna','amir-maiyet ilişkisi vardır','Devlet memuru–rütbeli personel: astlık-üstlük yok','(6) Devlet memurları ile rütbeli','amir-maiyet ilişkisi vardır.',[('17','devlet memurları esas duruşa geçmez'),('18','devlet memurları selamlamadan muaf')],''),
 ('7','kosul','disiplinden taviz verilemez','Disiplin teşkilatın temelidir; hiçbir suretle','Disiplin, Jandarma Genel Komutanlığı','disiplinden taviz verilemez.',[],''),
 ('7','gorev_yetki','hep birlikte itaatsizlik veya mukavemet','halleri gören her üst emir ve komuta işini üzerine alır','(5) Herhangi bir karargâh','üzerine almak ile yükümlüdür.',[],'yükümlülük (yetki değil)'),
 ('7','kosul','öncelikle bilgi, yetenek','sevk ve idarede otorite; yüksek bir karakter ile sağlanır','(10) Sevk ve idarede otoritenin','sağlanması esastır.',[],''),
 ('8','gorev_yetki','kıyafetli olsun veya olmasın','âmirlerin usulüne uygun emirlerini tam, zamanında, değiştirmeden yerine getirir','resmî kıyafetli olsun veya olmasın','eksiksiz olarak yerine getirmekle',[],''),
 ('8','kosul','korku ile değil','görev sevgi ve üstün görev anlayışı ile icra edilir','(2) Görevini; korku ile değil','görev anlayışı ile icra eder.',[],''),
 ('8','yasak','âmirine mütalâada bulunmaz','ast, aldığı bir emirden dolayı; mırıldanmaz, doğru bulmadığını sezdirmez','(5) Aldığı bir emirden dolayı','hal ve harekette bulunmaz.',[],''),
 ('8','gorev_yetki','Âmirinin yokluğunda','âmirin yerini tutabilmek için onun görevini de öğrenir','Âmirinin yokluğunda','iyice öğrenmeye çalışır.',[],''),
 ('8','kosul','maiyete yüklenen görevleri yapar','Devlet memurları da astın görevlerini yapar','(14) Devlet memurları bu maddede','maiyete yüklenen görevleri yapar.',[],''),
 ('9','yasak','hususi bir menfaat','âmir maiyetinden böyle hiçbir talepte bulunmaz; gerektiğinde disiplin cezası verir','(4) Maiyetinden hususi bir menfaat','disiplin cezası verir.',[],''),
 ('9','yasak','mecbur kalmadıkça müdahalede bulunmaz','âmir; maiyetine görevini icra esnasında (âmirin görevleri)','(8) Maiyetine görevini icra esnasında','müdahalede bulunmaz.',[],''),
 ('9','kosul','nefsini sona bırakır','âmir; bir kolaylık çıkınca; zorlukta öne atılmak şerefli görev','(10) Maiyetinin katlandığı','şerefli bir görev kabul eder.',[],''),
 ('9','yasak','gerekçesiz takdir hakkı','âmir ödül veya ceza ile ilgili olarak kullanmaz','(11) Ödül veya ceza ile ilgili','hakkaniyetli davranır.',[],''),
 ('10','sira_usul','yazı ile yinelerse','emir yerine getirilir; sorumluluk emri verene; üst âmire bildirilir','(3) Ast emri; Anayasa ve mevzuat','bir üst âmirine bildirilir.',[],'mevzuata aykırı emir: önce yerine getirilmez, aykırılık emri verene bildirilir'),
 ('10','yasak','Konusu suç teşkil eden emir','hiçbir surette yerine getirilmez; yapan sorumluluktan kurtulamaz','(4) Konusu suç teşkil eden emir','sorumluluktan kurtulamaz.',[],''),
 ('10','makam','verilme takdiri','emrin yazılı, sözlü veya sair usulle verilmesi âmire aittir','(5) Emrin yazılı, sözlü','takdiri, âmire aittir.',[],''),
 ('10','kosul','kurum kimliği ile tanıtır','emir resmî veya sivil kıyafetli verilebilir; âmir gerektiğinde kendini','(6) Emir, resmî veya sivil','kurum kimliği ile tanıtır.',[('18','sivil üst kimlik kartını ibraz edince selam')],''),
 ('10','sira_usul','atlanan kademelere','acele halde silsile dışı emir; emri veren âmir bilgi verir','(7) Emirler, kural olarak','maiyet de âmirini haberdar eder.',[],'maiyet de kendi âmirini haberdar eder'),
 ('10','sira_usul','muhalif ikinci bir emir','ikinci emri veren âmire önceki emir bildirilir; ısrarda ikincisi yapılır','(8) Bir âmirin verdiği emir','en kısa zamanda bilgi verilir.',[],'ilk emri veren âmire bilgi verilir'),
 ('10','kosul','Emirde kararlılık esastır','verilen emir mecburi sebepler oluşmadıkça değiştirilemez veya yok sayılamaz','(11) Emirde kararlılık esastır','itibarsızlık yaratır.',[],''),
 ('10','kosul','emri yeni duruma uygun','ast sorumluluğu üzerine alarak değiştirerek yapabilir (âmirden yeni emir alınamıyorsa)','ast sorumluluğu üzerine alarak','getirilen âmire bilgi verilir.',[],'büyük tehlike/ağır zarar/bilinmeyen husus; ilk fırsatta bilgi'),
 ('10','sira_usul','nazik bir dille','üst âmir, emri iptal gereğini emri veren âmire izah eder','(14) Emri veren âmirin üst âmirleri','tatmin edici bir gerekçe sunar.',[],''),
 ('10','sira_usul','son kontrol yapılır','emri yerine getiren tarafından; sonra âmire bilgi verilir','Verilen emrin yerine getirilmesini müteakip','âmire bilgi verilir.',[],''),
 ('10','sira_usul','birleştirilerek verilir','birbiri ile bağlantılı emirler; işgücü israfını önlemek için','(18) Birbiri ile bağlantılı','birleştirilerek verilir.',[],''),
 ('11','yasak','toplu olarak söz veya yazı','aynı konuda toplu müracaat yasak; her biri ayrı ayrı','(2) Personelin, aynı konu ve şahısla','şikâyet hakkını kullanabilir.',[],''),
 ('11','ceza','yüzüne karşı kendisini şikâyet','âmirin; cezayı muciptir (dedikodu yapmak da)','(4) Âmirin yüzüne karşı','cezayı muciptir.',[],''),
 ('11','sira_usul','bizzat şikâyeti neticelendirirler','şikâyeti incelemeye yetkili âmirler; kararı şikâyetçiye tebliğ ederler','(3) Şikâyetleri incelemeye yetkili','şikâyetçiye tebliğ ederler.',[],''),
 ('11','kosul','Şikâyet ve Müracaatları Hakkında Yönetmelik','bu maddede hüküm bulunmayan hallerde uygulanır (8/5743 sayılı BKK)','(5) Bu maddede hüküm bulunmayan','Yönetmelik hükümleri uygulanır.',[],''),
 ('12','yasak','görevini vaktinde yapmıştır','bu gerekçeyle ödül dağıtmak, ödüllendirmede aşırıya kaçmaktır','Bu sebeple, “görevini yapmıştır','ödüllendirmede aşırıya kaçmaktır.',[],''),
 ('12','sira_usul','mesai arkadaşlarının huzurunda','ödüller mümkün olduğunca orada verilir; teşvik edici sözler','(6) Ödüller, mümkün olduğunca','teşvik edici sözler söylenir.',[],''),
 ('12','kosul','değerlendirme notundan bağımsız','ödül sistemi disiplin cezaları ile değerlendirme notundan bağımsız çalışır','(7) Ödül sistemi, disiplinle','durum içinde değerlendirilir.',[],''),
 ('12','yasak','daha büyük ödül tekliflerinde','başarı derecesine orantısız büyük ödül teklifi yapılmaz','(8) Başarının derecesi dikkate','tekliflerinde bulunulmaz.',[],''),
 ('12','makam','Ödül çeşitleri','Bakanlıkça yürürlüğe konulan yönetmelikle belirlenir','(9) Ödül çeşitleri, personelin','yönetmelikle belirlenir.',[],''),
 ('13','kosul','diğerlerine ibret olmasındadır','cezanın fayda ve tesiri; tam adaletle ve zamanında verilir','Cezanın, disiplinin tesisi bakımından','(2) Ceza tam bir adaletle ve zamanında verilmelidir.',[],''),
 ('13','kosul','7068 sayılı Genel Kolluk Disiplin','disiplin cezası gerektiren haller ve tatbik şekli bu Kanunda','(3) Disiplin cezası verilmesini','yazılı olduğu gibidir.',[],''),
 ('14','yasak','gönüllü olarak feragat','âmir, izin hakkından vazgeçmeye yönelik tavır, davranış ve imada bulunmaz','(3) Âmir, açıkça olmasa da','imada bulunmamalıdır.',[],''),
 ('14','sure','İzin yılı','her senenin ilk ayından itibaren başlar','(6) İzin yılı, her senenin','ona göre düzenlenir.',[],''),
 ('14','makam','kendi inisiyatiflerine','izinleri yetkili âmir kullandırır; daha büyük âmirler almaz','(4) İzinler yetkili âmir','inisiyatiflerine alınmamalıdır.',[],''),
 ('14','gorev_yetki','izinden çağrılmayı gerektirecek','izne giden, adresini ve iletişim araçlarını âmirine bildirir; ulaşılabilir kalır','(5) İzne giden her personel','ulaşılabilir kılmalıdır.',[],''),
 ('14','kosul','komuta yeteneği, beceri','izinlerin tam ve zamanında kullandırılması âmirin göstergesidir','İzinlerin tam ve zamanında kullandırılması','özgüvenlerinin bir göstergesidir.',[],''),
 ('15','istisna','tanıklık veya bilirkişilik dışında','adlî yargı makamlarına çağrılınca resmî kıyafet giyilmez; tutuklu/hükümlü de','(8) Rütbeli personel ve erler; tanıklık','resmî kıyafet giyemez.',[],'görevden uzaklaştırılanlar da giyemez'),
 ('15','yasak','sakız çiğnenmez, poşet taşınmaz','resmî kıyafetle; şapka çıkarılmaz, kol kola girilmez, eller cepte dolaşılmaz','b) Resmî kıyafet ile sakız','eller cepte dolaşılmaz.',[],''),
 ('15','istisna','nişan, evlilik ve devre yüzüğü','resmî kıyafetle bunlar dışında yüzük, bileklik ve kolye kullanılmaz','ç) Resmî kıyafet ile nişan','bileklik ve kolye kullanılmaz.',[],''),
 ('15','istisna','Hak sahibi olunmayan','şerit, rozet ve bröve takılmaz (mevzuata uymayanlar da)','Hak sahibi olunmayan veya','rozet ve bröveler takılmaz.',[],''),
 ('15','kosul','örgü başlık giyilmesi zorunludur','bina ve müştemilatı ile araç dışında şapka, kep, bere de','e) Bina ve müştemilatı','başlık giyilmesi zorunludur.',[],''),
 ('15','makam','şapkasız olarak dolaşılabilir','karargâh, birlik ve kurumlarda en büyük âmirin müsaade ettiği alanlarda','Karargâh, birlik ve kurumlarda, en büyük','şapkasız olarak dolaşılabilir.',[],''),
 ('15','kosul','Araç içinde resmî kıyafetli','yolculukta şapka çıkarılabilir; araç içinde birlik ve beraberlik esastır','f) Araç içinde resmî kıyafetli','birlik ve beraberlik esastır.',[],''),
 ('15','yasak','işaretler sökülse dahi','resmî kıyafet sivil kıyafete dönüştürülemez; resmî pantolon sivil gömlekle giyilemez','ı) Üzerindeki işaretler sökülse','giyeceklerle birlikte giyilemez.',[],''),
 ('15','kosul','göze görünmeyecek şekilde','rütbeli personel görev dışında sivil elbise ile tabancasını taşıyabilir','j) Rütbeli personel görev dışında','görünmeyecek şekilde taşıyabilir.',[],''),
 ('15','kosul','koyu renk ve sade desenlerde','resmî kıyafetle çantalar; yalnız sol elde taşınabilir','k) Resmi kıyafet ile sadece koyu','sol elde taşınabilir.',[],''),
 ('15','istisna','resmî kıyafet rengindeki başörtüleri','kadın rütbeli personel (yüzü kapatmayacak); bunun dışında sivil giysi giyemez','l) Kadın rütbeli personel yüzünü','benzeri kıyafetler giyemez.',[],''),
 ('15','kosul','hamileliğini belgelediği takdirde','kadın rütbeli personel sivil kıyafet ile görev yapabilir','m) Kadın rütbeli personel, hamileliğini','sivil kıyafet ile görev yapabilir.',[],''),
 ('15','kosul','ilişiği kesildiği tarihten','emeklilik, çekilme vb. ile; resmî kıyafetini çıkarmaya mecburdur','o) Rütbeli personel ve erler; emeklilik','çıkarmaya mecburdur.',[],'eskimiş resmî kıyafet başkasına verilmez'),
 ('15','yasak','favori, sakal ve bıyık','bırakılmaz (mevzuatta düzenlenen haller hariç); sadelik esastır','ö) El, yüz ve saç tuvaletlerinde','sakal ve bıyık bırakılmaz.',[],''),
 ('15','kosul','omuz hizasını geçmez','kadın rütbeli personel kısa saçlı ise; uzun saçlı ise toplar','Kadın rütbeli personel, uzun saçlı','omuz hizasını geçmez.',[],'erkek: saç şapka/bere içinden taşmaz'),
 ('15','kosul','istihbarata karşı koyma','kimlik kartı bu gibi istisnalar dışında her zaman üzerinde bulundurulur','(10) Kimlik kartı, kişinin','gösterilmesi zorunludur.',[],'yetkili makam isteyince gösterilmesi zorunlu'),
 ('15','sure','her sabah sakal','erkek personel sakal tıraşı her sabah; saç tıraşı gerekli zamanlarda','(6) Erkek personel her sabah','bitkin bir görüntü sergilemez.',[],''),
 ('15','kosul','Kılık ve Kıyafetine Dair Yönetmelik','Devlet memurlarının kılık kıyafeti bu Yönetmeliğe tabi (16/7/1982)','(12) Devlet memurları hakkında','Yönetmelik hükümleri uygulanır.',[],''),
 ('16','kosul','Devlet töresine göre','kamu kurum ve kuruluşlarının âmirlerine teamüllere göre hitap edilir','(2) Personel; kamu kurum','Devlet töresine göre hitap eder.',[],''),
 ('16','sira_usul','emir, broşür vb.','görgü ve nezaket ayrıntıları; her teşkilat ayrı ayrı hazırlar','Buna ilişkin ayrıntılar her teşkilatın','disiplin işlemi uygulanır.',[],'aykırı davranana disiplin işlemi'),
 ('17','kosul','otur veya rahat komutunu','âmir vermeden esas duruş bozulmaz; âmir gelince derhal ayağa kalkılır','(2) Âmir veya üst, astın','esas duruş bozulmaz.',[],''),
 ('17','kosul','yerinde dönüşle cephe','âmir yan tarafta ise; konuşurken baş çevrilmez, esas duruşa geçilir','(4) Âmir veya üst ile konuşurken','âmir veya üste çevrilir.',[],''),
 ('17','yasak','el ve kol sallanmaz','esas duruşta konuşmak gerekiyorsa; vücut bükülmez, sessiz kalınır','(5) Esas duruşta sessiz','vücut bükülmez.',[],''),
 ('17','istisna','esas duruşa geçmez','Devlet memurları; amirleri karşısında saygılı duruş zorunlu','(7) Devlet memurları esas duruşa','sergilemek zorundadır.',[('18','selamlamadan da muaf, saygılı duruş'),('6','astlık-üstlük yok, amir-maiyet var')],''),
 ('18','tanim','Küçüğün büyüğü selamlaması','saygının; büyüğün küçüğü sevginin; aynı seviye nezaket ve muhabbetin','Küçüğün büyüğü selamlaması','muhabbetin belirtisidir.',[],''),
 ('18','kosul','ayrılanların kalanları','selamlamada temel kural: astın üstünü, gelenlerin mevcut olanları selamlaması','Selamlamada temel kural;','ast selamlamayı bitiremez.',[],''),
 ('18','kosul','selamlamayı bitirmeden','üst veya âmir bitirmeden ast selamlamayı bitiremez','Selamlamada temel kural;','ast selamlamayı bitiremez.',[],''),
 ('18','kosul','Sivil kıyafetli olunması','sivil de olsa selam verilir (mani değil)','Sivil kıyafetli olunması','selam verilmesine mani değildir.',[],''),
 ('18','kosul','görmemek mazeret teşkil etmez','selamlama gecikmiş bile olsa yapılır','(5) Selamlama gecikmiş bile','mazeret teşkil etmez.',[],''),
 ('18','kosul','kimlik kartını ibraz ederek','sivil âmir veya üst; derhal esas duruşa geçilip selam verilir','Âmir veya üst sivil dahi olsa','gerekli saygı gösterilir.',[('10','emir veren âmir kurum kimliğiyle tanıtır')],''),
 ('18','kosul','başla takip yapılır','âmir veya üst selâmlanırken; selamlanan şahsın gözüne canlı bakılır','(7) Âmir veya üst selâmlanırken','canlı bir şekilde bakılır.',[],''),
 ('18','kosul','sağ el ile yapılır','elle selamlama; başta şapka, kayık kep, bere, çelik başlık varken','(8) Elle selamlama, başta','sağ el ile yapılır.',[],''),
 ('18','kosul','durup yol vermesi','merdiven ve dar geçit gibi yerlerde selamlama; astlar','Merdiven ve dar geçit','yol vermesi suretiyle olur.',[],''),
 ('18','istisna','eldiven ile selâmlama','tören birliklerindeki rütbeli personel ve erler hariç yapılmaz','(9) Tören birliklerinde bulunan','eldiven ile selâmlama yapılmaz.',[],''),
 ('18','kosul','cephe selamı verilir','Cumhurbaşkanına, sancağa, yabancı devlet başkanlarına ve sancaklarına, cenazeye','(10) Cumhurbaşkanına, sancağa','cephe selamı verilir.',[],'bayrak çekilir/indirilirken de cephe alınarak selamlanır'),
 ('18','kosul','açık yerde şapkalı','milli marş çalınırken saygı duruşu; kapalı yerlerde şapkasız','(11) Rütbeli personel ve erler, milli marş','saygı duruşunda bulunur.',[],'cephe marşın çalındığı yöne'),
 ('18','kosul','araç forsu veya flamasının','görülmesi halinde selamlama yapılır; özel araç kullanan üstlere de selam','(13) Resmî araçlardaki rütbeli','üstlere selam verilir.',[],''),
 ('18','istisna','Araç süren rütbeli','selamlama yapmaz; astın selamına araçta en kıdemli karşılık verir','Araç süren rütbeli personel','en kıdemli karşılık verir.',[],''),
 ('18','kosul','başı açık girilir','konferans salonu, gazino, kütüphane, yemekhane; karşılık beklenmeden içeridekiler selamlanır','(14) Konferans salonu, gazino','aynı kurallar geçerlidir.',[],'servis araçlarında da aynı'),
 ('18','kosul','Şehit na’şını taşıyan','hava nakil araçlarının iniş ve kalkışında hazır bulunanlarca selamlama','(15) Şehit na’şını taşıyan','hazır bulunanlarca selamlama yapılır.',[],''),
 ('18','istisna','selamlama ile ilgili hususlardan muaftır','Devlet memurları; amirlerine karşı saygılı duruşunu muhafaza eder','(16) Devlet memurları selamlama','muhafaza etmekle mükelleftir.',[('17','esas duruşa geçmez, saygılı duruş')],''),
 ('19','tanim','en büyük ve affedilmeyecek kusurdur','Korkaklık; cesaret ve şecaat vasfı','ç) Cesaret ve şecaat','namus ve onura leke getirir.',[],''),
 ('19','tanim','muntazam işleyen bir saat','İntizam severlik vasfı (görevi dakikası dakikasına)','j) İntizam severlik: Personel','adet haline getirmelidir.',[],''),
 ('19','tanim','kardeşten ileri olduğunu','İyi geçinmek; arkadaşın kabahatini örtbas etmek teşkilata fenalıktır','f) İyi geçinmek: Bütün mesai','her personel bilmelidir.',[],''),
 ('19','tanim','kendisini dinlemekte olduklarını','Sır saklamak; görev hususlarında hiç kimseye sır vermemek','ğ) Sır saklamak: Personel','doğruluktan ayrılmamalıdır.',[],''),
 ('19','tanim','gösterdiğinden dışarı çıkmamak','İtaat (yasak edilen şeyleri yapmamak)','b) İtaat: Mevzuat ile emirlerin','yasak edilen şeyleri yapmamaktır.',[],''),
 ('19','tanim','Başka milletten kolluk','Temsil ve tanıtım vasfı (iyi geçinmek, yüksek değeri tanıtmak)','k) Temsil ve tanıtım: Başka','mahiyetindeki görevidir.',[],''),
 ('19','tanim','bir vücut gibi çalışmaktır','Emel ve fikir birliği; genelin menfaati şahsi menfaatten üstün','h) Emel ve fikir birliği','takdir ederek sağlanır.',[],''),
 ('19','kosul','mesai saatleri dışında da','personel, teşkilatının bir personeli olduğu bilinciyle hareket eder','(2) Personel, resmî sıfatının','bilinciyle hareket eder.',[],''),
 ('20','gorev_yetki','hastalandığında durumunu âmirine','personel bildirmekle yükümlü; âmir de maiyetinin sağlığını yakinen takip eder','personel sağlığını korumakla','tedbirleri almakla yükümlüdür.',[],''),
 ('21','yasak','satamaz, kiralayamaz veya istifadesine','emanet devlet malı kimseye; kalkışanı duyan âmirine derhal haber verir','a) Devlet tarafından bedelsiz','âmirine derhal haber verir.',[],''),
 ('21','yasak','kendiliğinden ilâveler ve değişiklikler','kendisine verilen eşyanın şeklinde yapamaz','b) Kendisine verilen eşyanın','değişiklikler yapamaz.',[],''),
 ('22','makam','illerde valiler ve Bakanın','basına bilgi ancak onlar ve Bakanın yetkili kılacağı görevli verir','Bu konuda gerekli bilgi ancak illerde','görevli tarafından verilebilir.',[],''),
 ('22','yasak','topluca bildiri dağıtamaz','personel tek başına veya topluca; basına demeç veremez','Personel, tek başına veya topluca','yazı ve demeç veremez.',[],''),
 ('22','yasak','mesul müdürü, yazarı','personel hiçbir basın yayın organının, internet vasıtasının olamaz','(3) Personel, hiç bir basın','haber vericisi olamaz.',[],''),
 ('22','istisna','siyaset hariç olmak üzere','bilimsel, tarihi, iktisadi, içtimai, edebi makale ve kitap yazmak serbest','(5) Personel, siyaset hariç','bastırmakta serbesttir.',[],'siyaset hakkında yazı yazamaz'),
 ('22','kosul','ışığında yazılmıştır','resmî kaynaktan yararlanan eser; yazmadan evvel Komutanlıktan izin alınır','b) Yalnız mesleki makam','Sahil Güvenlik Komutanlığı belirler.',[],'kaydın konulup konulmayacağını Komutanlık belirler'),
 ('22','kosul','göreve mahsus kitaplardan','bunlardan yararlanan eser basılmadan evvel silsile ile incelettirilir; izin alınır','c) Yayımlanacak kitap veya makaleler','yayımlanması için izin alır.',[],''),
 ('23','makam','en kıdemli birlik komutanı','kışla komutanıdır (birden fazla birliğin aynı kışlada bulunduğu yer)','MADDE 23 - (1) Birden fazla','kurum âmiri kışla komutanıdır.',[],''),
 ('23','makam','kışla emniyet subayı','bir subay, yoksa tecrübeli bir astsubay görevlendirilir','Emniyet tedbirlerinin tespiti','kışla emniyet subayı olarak görevlendirilir.',[],''),
 ('23','makam','en kıdemli kışla komutanınca','aynı belediye mücavir alanında birden fazla kışla; planlar tek elden','(3) Aynı belediye mücavir','tek elden tespit ve takip edilir.',[],'JGK ve SGK için ayrı ayrı'),
 ('23','gorev_yetki','Paratonerlerin ölçüm ve bakımlarının','kışla komutanının görevi; yaptırılması ve kontrolünü sağlar','ı) Paratonerlerin ölçüm','kontrol edilmesini sağlar.',[],'içme suyu analizi, ilaçlama, hijyen denetimi de kışla komutanı'),
 ('23','gorev_yetki','Kışla gelişim planının','hazırlanmasını kışla komutanı sağlar','j) Kışla gelişim planının','hazırlanmasını sağlar.',[],''),
 ('24','sure','genel olarak 40 saattir','rütbeli personelin haftalık çalışma süresi (göreve çağrılmaya engel değil)','uzman jandarmaların haftalık çalışma','genel olarak 40 saattir.',[],''),
 ('24','makam','yirmi dört saatinde devamlılık','çalışma saat ve şekillerini birlik komutanları veya birim âmirleri belirler','(2) Günün yirmi dört saatinde','birim âmirlerince belirlenir.',[],''),
 ('24','kosul','nöbete ilişkin hükümler saklıdır','nöbetçi ve görevli olmayan rütbeli personel mesai bitiminde ayrılabilir','(3) Nöbetçi ve görevli olmayan','gündüz ve gece ayrılamaz.',[],'görev yerinden izinsiz ayrılma yok'),
 ('25','makam','günlük görev cetveline göre','kışlada kalanların yoklamasını nöbetçi heyeti alır','(3) Kışlada kalan rütbeli','görev cetveline göre alınır.',[],''),
 ('25','kosul','toplu takdim alınabilir','kılık, kıyafet, teçhizat kontrolü, müşterek emir tebliği için; âmir belirler','(2) Rütbeli personel ve erlerin kılık','esaslarına göre yürütülür.',[],''),
 ('25','makam','nöbetçi âmirinin emri','gereken hallerde onun emriyle de yoklama alınabilir','(4) Gereken hâllerde birlik','yoklama alınabilir.',[],'birlik komutanı, karargâh ve kurum âmirleri de'),
 ('26','tanim','nöbet görevi ihdas edilir','müşterek görevlerin belli bir sıra ve süreyle yapılması maksadıyla','belli bir sıra ve süreyle; personel tarafından','nöbet görevi ihdas edilir.',[],''),
 ('27','sayi_oran','en az üç kişiden','hazır kıt’a kuvveti; birliğin tamamına kadar; birlik komutanı belirler','(3) Hazır kıt’anın teşkil','uzman erbaş olabilir.',[],''),
 ('27','makam','uzman jandarma veya uzman erbaş','hazır kıt’a komutanı; birliğin büyüklüğüne bağlı (subay, astsubay da)','(3) Hazır kıt’anın teşkil','uzman erbaş olabilir.',[],''),
 ('27','makam','uyuyup uyumayacağı','hazır kıt’anın; çıkaran birlik komutanı emreder',"(2) Hazır kıt'a kendisine",'birlik komutanı tarafından emredilir.',[],'gece dahi tam teçhizatlı, silahlı hazır'),
 ('29','tanim','dayanıklı tüketim malları hariç','kantinlerin amacı; zaruri ihtiyaçlar daha ucuza ve kolay','dayanıklı tüketim malları hariç','kolaylıkla sağlanmasını temin maksadıyla',[],''),
 ('30','kosul','seyir istikametleri değiştirilmemek','servis araçlarından aileler ancak boş yer varsa; bu şartla','(2) Servis araçlarından, ancak','personelin aileleri de istifade edebilir.',[],'hasta/cenaze aracından da boş yerde yararlanır'),
 ('30','kosul','sivil moral ekipleri','savaşta ve olağanüstü hallerde harekât bölgesine nakil araçlarından yararlandırılır','(3) Savaşta ve olağanüstü','nakil araçlarından yararlandırılır.',[],''),
 ('30','kosul','hava araçlarından faydalanabilir','terörle mücadele bölgesinde yol güvenliği yoksa aileler de; boş yer','(4) Terörle mücadele harekâtı','hava araçlarından faydalanabilir.',[],''),
 ('30','kosul','en son gittiği yerden','tarifeli araç işlemeyen yere tayin; aile ve eşya resmî araçla','(7) Gündelik ve belirli tarifeli','ilgili komutanlıkça düzenlenir.',[],''),
 ('32','makam','en büyük mülki âmirine haber','birlik komutanları afet ve acil durumları bildirmekle sorumludur','MADDE 32 - (1) Birlik komutanları','haber vermekten sorumludurlar.',[],''),
 ('32','sira_usul','üstlerinden emir beklemeksizin','vali veya kaymakamın istediği yardımı birlik komutanı yapar; Komutanlığa haber','(2) Afet bölgelerinde veya civarında','Komutanlığına haber verirler.',[],''),
 ('32','kosul','Türkiye Afet Müdahale Planı','diğer afet işleri; Afet ve Acil Durum Müdahale Hizmetleri Yönetmeliği','(3) Afet ve acil durumlara ilişkin','Planı esaslarına göre yürütülür.',[],''),
 ('33','kosul','Binaların Yangından Korunması Hakkında Yönetmelik','yangın tedbirleri bu Yönetmelik ve ilgili Yönerge esaslarına göre','MADDE 33 - (1) Karargâh, birlik','Yönerge esaslarına göre yürütülür.',[],''),
 ('34','sure','onaylandığı tarihte yürürlüğe','Yönetmelik onay tarihinde yürürlüğe girer; Bakan yürütür','MADDE 34 - (1) Bu Yönetmelik onaylandığı','yürürlüğe girer.',[],''),
]
yaz(23, 'Jandarma ve Sahil Güvenlik Personelinin Hizmet Esasları Yönetmeliği', K)
