# Jandarma ve Sahil Güvenlik Personelinin Hizmet Esasları Yönetmeliği — kelime → cevap
# KURAL (başkan, 4 Eki 2026): SOL = soru KÖKÜNDE göreceğin ifade, SAĞ = doğru ŞIKTA arayacağın kelime.
# Sorulardan geriye doğru yazıldı (137 cevaplı soru + kitapçık kökleri); kanıt resmî metin.
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 # m.1-4 — amaç, kapsam, dayanak, tanımlar
 ('1','tanim','Yönetmeliğin amacı','görevde ve görev dışında uyulacak kurallar, vasıflar, görev icra tarzı','MADDE 1 - (1) Bu Yönetmeliğin amacı','icra tarzını belirlemektir.',[],''),
 ('2','tanim','kapsar','JGK, SGK, Akademi karargâh-birlik-kurum ve personeli; işçiler kendi mevzuatına','MADDE 2 - (1) Bu Yönetmelik, Jandarma','işçiler kendi mevzuatına tabidir.',[],'İçişleri merkez teşkilatının sivil memurları kapsam DIŞI'),
 ('2','kosul','askerlik yükümlüleri','eksik hususlarda diğer yükümlülerin mevzuatı','(2) Jandarma Genel Komutanlığı, Sahil Güvenlik','mevzuat hükümleri uygulanır.',[],'7179 sayılı Askeralma Kanununa tabi'),
 ('3','kosul','dayanılarak','2803 m.24 ve 2692 Sahil Güvenlik Komutanlığı Kanunu m.23','MADDE 3 - (1) Bu Yönetmelik, 10/3/1983','dayanılarak hazırlanmıştır.',[],''),
 ('4','tanim','kadro ve kuruluş yönünden','âmir','a) Âmir:','olan diğer personeli,',[],'âmir olarak yetkilendirilmiş diğer personel de'),
 ('4','tanim','Rütbe veya kıdemce büyük','üst olan kimse','ğğ) Üst:','ifade eder.',[],'kadro-kuruluş bağı şart değil'),
 ('4','tanim','Rütbe veya kıdemce küçük','ast olan personel','b) Ast:','küçük olan personeli,',[],''),
 ('4','tanim','emir ve komutası altındaki','maiyet','s) Maiyet:','komutası altındaki personeli,',[],'kadro-kuruluş yönünden bağlı olunan kimse ÂMİR'),
 ('4','tanim','Maiyet:','âmirin emir-komutası altındaki personel','s) Maiyet:','komutası altındaki personeli,',[],''),
 ('4','tanim','Makam:','âmirin temsil ettiği mevki','ş) Makam:','temsil ettiği mevkiyi,',[],''),
 ('4','tanim','Disiplin:','mevzuata ve âmire mutlak itaat; ast-üst hukukuna riayet','g) Disiplin:','hukukuna riayeti,',[],''),
 ('4','tanim','mutlak bir itaat','disiplin','g) Disiplin:','hukukuna riayeti,',[],'ast ve üstün hukukuna riayet'),
 ('4','tanim','sair surette asta','emir','ğ) Emir:','asta bildirilmesini,',[],'söz, yazı ve sair surette'),
 ('4','tanim','temsil ettiği mevki','makam','ş) Makam:','temsil ettiği mevkiyi,',[],''),
 ('4','tanim','amir tarafından verilen emirleri','görev','i) Görev:','verilen emirleri,',[],'mevzuat gereği yapılacak hususlar da'),
 ('4','tanim','emir komuta altında toplanan','birlik','e) Birlik:','taktik ve idari birimleri,',[],'taktik ve idari birimler'),
 ('4','tanim','duruşu ve dış görünüşü','kılık; kıyafet giyim-kuşam','n) Kılık:','ö) Kıyafet: Giyim ve kuşamı,',[],'KILIK DURUŞ, KIYAFET GİYİM'),
 ('4','tanim','aynı nasıplılar arasında','kıdem','m) Kıdem:','üstünlük sırasını,',[],''),
 ('4','tanim','normal bekleme süresinin başlama','nasıp','u) Nasıp:','başlama tarihini,',[],''),
 ('4','tanim','geçici olarak personelin kullanımına','tahsis','dd) Tahsis:','kullanımına verilmesini,',[],'sarf yetkisi verilen cins-miktar İSTİHKAK'),
 ('4','tanim','giriş ve çıkışlarının kontrol','nizamiye-lumbarağzı','ü) Nizamiye/Lumbarağzı:','kuvvet ihtiva eden tesisi,',[],''),
 ('4','tanim','sekiz kademeli çavuş','uzman jandarma','gg) Uzman jandarma:','rütbeyi haiz şahısları,',[],'3466 sayılı Kanun; uzman erbaş 3269'),
 ('4','tanim','teğmenden orgeneral','subay','çç) Subay:','yükümlü yedek subayları,',[],''),
 # m.5-7 — sadakat, hiyerarşi, disiplin
 ('5','kosul','her durumda','Devletin menfaatlerini korumak','MADDE 5 - (1) Personel, her durumda','herhangi bir faaliyette bulunamaz.',[],'bağımsızlığı ve bütünlüğü bozan faaliyette bulunamaz'),
 ('5','sira_usul','göreve başla','yetkili âmirlerin huzurunda ant içerek','(2) Personel, ettiği yemine','yönerge ile düzenlenir.',[('4','rütbe tanımı: ilk göreve başlamada kazanılan unvan')],'ant töreni yönergeyle'),
 ('6','kosul','Statüler arası','subay, astsubay, uzman jandarma, uzman erbaş, sözleşmeli erbaş, yükümlü erbaş','Statüler arası hiyerarşi','amir-maiyet ilişkisi vardır.',[],'üstten asta sıra; Astsubay sınavında soruldu'),
 ('6','kosul','Uzman jandarmalar','subay-astsubayın astı, diğer rütbelilerin üstü','(3) Uzman jandarmalar','diğer rütbeli personelin üstüdür.',[('24','haftalık çalışma 40 saat')],'uzman erbaşın üstü'),
 ('6','kosul','Subaylar,','diğer rütbeli personelin üstü','(1) Subaylar, diğer','personelin üstüdür.',[],''),
 ('6','kosul','rütbeli personelin üst','subay, astsubay, uzman jandarma, uzman erbaş, sözleşmeli erbaş','(1) Subaylar, diğer','emsal rütbedeki erbaşların üstüdür.',[],'üstten asta sıra'),
 ('6','istisna','Devlet memurları ile rütbeli','astlık-üstlük yok; amir-maiyet var','(6) Devlet memurları ile rütbeli','amir-maiyet ilişkisi vardır.',[],''),
 ('7','kosul','disiplinin ayrılmaz unsurları','görev, nöbet, selamlama, kılık-kıyafet; izin planlaması DEĞİL','(2) Personel görevini yerine getirirken','emirlere uymak zorundadır.',[],''),
 ('7','kosul','temelidir','JGK, SGK, Akademinin; hiçbir suretle taviz yok','Disiplin MADDE 7 - (1) Disiplin','disiplinden taviz verilemez.',[],''),
 ('7','kosul','tesis edilmeli','en zor zamanlarda bile uygulanacak şekilde','(7) Disiplin, en zor','tesis edilmelidir.',[],''),
 ('7','kosul','Sevk ve idarede otorite','bilgi, yetenek, yüksek karakter','(10) Sevk ve idarede','sağlanması esastır.',[],''),
 ('7','gorev_yetki','hep birlikte itaatsizlik','gören her üst emir-komutayı üzerine alır','(5) Herhangi bir karargâh','üzerine almak ile yükümlüdür.',[],'yükümlülük'),
 ('7','gorev_yetki','disipline aykırı','üst müdahale eder, emir verir','(4) Üst, disipline aykırı','emir vermeye yetkili ve sorumludur.',[],''),
 # m.8-9 — astın ve âmirin görevleri
 ('8','gorev_yetki','usulüne uygun emirlerini','tam, zamanında, değiştirmeden, eksiksiz; kendi yorumu YOK','MADDE 8 - (1) Ast, âmir ve üstlerine','bilgi vermekle yükümlüdür.',[],'resmî kıyafetli olsun olmasın'),
 ('8','kosul','icra eder','korku ile değil, sevgi ve üstün görev anlayışıyla','(2) Görevini; korku ile değil','tahammül kuvvetini sarf ederek yapar.',[],'mevzuata uygun her emri mutlak itaatle'),
 ('8','yasak','mütalâa','ast emirden dolayı mütalaa vermez, mırıldanmaz','(5) Aldığı bir emirden','hal ve harekette bulunmaz.',[],''),
 ('8','gorev_yetki','Âmirinin yokluğunda','onun görevini de öğrenir','(8) Amirlerine emirlere hazır','iyice öğrenmeye çalışır.',[],''),
 ('8','kosul','yüklenen görevleri','Devlet memurları maiyetin görevlerini yapar','(14) Devlet memurları bu maddede','maiyete yüklenen görevleri yapar.',[],''),
 ('9','gorev_yetki','Âmirin görevleri','yaptırır, yetiştirir, gözetir, adil davranır, örnek olur; itaat ASTIN','Âmirin görevleri','hakkaniyetli davranır.',[],'mütalaasız mutlak itaat, izni gerekçesiz reddetmek âmirin görevi DEĞİL'),
 ('9','kosul','Astlarına karşı','adil ve hakkaniyetli','(5) Astlarına karşı adil','gerekçe gösterilemez.',[],'hiçbir mazeret adaletten ayrılmaya gerekçe değil'),
 ('9','kosul','kolaylık','nefsini sona bırakır; zorlukta öne atılır','(10) Maiyetinin katlandığı','şerefli bir görev kabul eder.',[('29','kantin zaruri ihtiyaçları kolaylıkla sağlar')],''),
 ('9','yasak','Ödül veya ceza','gerekçesiz takdir hakkı kullanmaz; ölçülü, hakkaniyetli','(11) Ödül veya ceza','hakkaniyetli davranır.',[],''),
 ('9','yasak','müdahale','mecbur kalmadıkça yok','(8) Maiyetine görevini icra','müdahalede bulunmaz.',[('7','üst disipline aykırı her duruma müdahale eder'),('32','afet ve acil durum müdahale hizmetleri')],'âmir, görev icrasındaki maiyetine'),
 ('9','kosul','münasebet','görevde ciddi, görev dışında samimi-candan','(3) Görev esnasında, maiyeti','tavır ve davranışlarda bulunmaz.',[('8','ast âmirle münasebette nezaket kurallarına uyar'),('22','m.22 başlığı: basınla münasebet')],''),
 ('9','kosul','isimlerini','hususi vasıf, kişilik, mizaç da bilinir','Maiyetindeki personelin isimlerini','mizaçlarını ayrıntılarıyla bilir.',[],''),
 ('9','yasak','hususi bir menfaat','âmir maiyetinden talep etmez','(4) Maiyetinden hususi bir menfaat','disiplin cezası verir.',[],'gerektiğinde disiplin cezası verir'),
 # m.10 — emir
 ('10','tanim','düzenleyicisi','emir (tüm görevlerin düzenleyicisi)','Emir MADDE 10 - (1) Emir tüm görevlerin','düzenleyicisidir.',[],'Astsubay sınavında soruldu'),
 ('10','kosul','Emirlerin, göreve','göreve ilişkin ve mevzuata uygun olması şart','(2) Emirlerin, göreve','mevzuata uygun olması şarttır.',[],''),
 ('10','kosul','aykırı gör','yerine getirmez, emri verene bildirir','(3) Ast emri; Anayasa','emri verene bildirilir.',[('7','üst disipline aykırı gördüğü duruma müdahale eder')],''),
 ('10','sira_usul','yazı ile yinele','yapılır; sorumluluk verende; üst âmire bildirilir','Ancak, âmir emrinde ısrar','bir üst âmirine bildirilir.',[],'AYKIRI EMİR: BİLDİR; YAZILI ISRAR = YAP'),
 ('10','yasak','suç teşkil','hiçbir surette yapılmaz; yapan sorumlu','(4) Konusu suç teşkil eden','sorumluluktan kurtulamaz.',[],''),
 ('10','kosul','Emir, resmî veya sivil','her iki kıyafetle verilebilir; âmir kurum kimliğiyle tanıtır','(6) Emir, resmî veya sivil','kurum kimliği ile tanıtır.',[],'yalnız resmî kıyafetle DEĞİL; yazılı-sözlü takdiri âmirde'),
 ('10','sira_usul','silsile','acelede silsile dışı; atlanan kademelere bilgi verilir','(7) Emirler, kural olarak','maiyet de âmirini haberdar eder.',[('22','yayın izni silsile yoluyla istenir')],'emri alan maiyet de âmirini haberdar eder'),
 ('10','sira_usul','muhalif ikinci bir emir','önceki emir bildirilir; ısrarda büyük âmirinki yapılır','(8) Bir âmirin verdiği emir','en kısa zamanda bilgi verilir.',[],'ilk emri verene bilgi verilir'),
 ('10','kosul','anlaşılır','net olmalı','(9) Emir, net ve anlaşılır','yönlendirme sorumluluğu vardır.',[],'âmirin takip-kontrol sorumluluğu da var'),
 ('10','kosul','Emirde','kararlılık esas; mecbur kalmadıkça değiştirilmez','(11) Emirde kararlılık','itibarsızlık yaratır.',[('8','ast emirden dolayı mütalaa vermez')],''),
 ('10','kosul','büyük bir tehlikeye','ast sorumluluğu alıp emri değiştirerek yapar, sonra bildirir','(13) Emir yerine getirilirken','âmire bilgi verilir.',[],'âmirden yeni emir alınamıyorsa'),
 ('10','sira_usul','değiştirme veya iptal','üst âmir emri verene nazikçe izah eder','(14) Emri veren âmirin','tatmin edici bir gerekçe sunar.',[],''),
 ('10','sira_usul','yerine getirilmesini müteakip','yapan son kontrol eder, âmire bilgi','(16) Emri alan ast','âmire bilgi verilir.',[],''),
 ('10','sira_usul','Birbiri ile bağlantılı','birleştirilerek verilir','(18) Birbiri ile bağlantılı','birleştirilerek verilir.',[],''),
 ('10','kosul','yerine getiremeyecek durumda','zamanında ve gerekçesiyle âmire bildirir','(12) Emri alan ast','âmirin takdirindedir.',[],''),
 # m.11-14 — müracaat-şikâyet, ödül, ceza, izin
 ('11','yasak','aynı konu ve şahısla','toplu müracaat yasak; her biri ayrı şikâyet eder','(2) Personelin, aynı konu','şikâyet hakkını kullanabilir.',[],''),
 ('11','kosul','birden fazla personelin','her biri ayrı ayrı ya da yalnız başına','(2) Personelin, aynı konu','şikâyet hakkını kullanabilir.',[],''),
 ('11','tanim','resmi ve şahsi işlerinden','müracaat','(1) Personel, kurumlarıyla','dava açma hakkına sahiptir.',[],''),
 ('11','tanim','idari eylem ve işlemlerden','şikâyet ve dava açma','(1) Personel, kurumlarıyla','dava açma hakkına sahiptir.',[],''),
 ('11','ceza','yüzüne karşı','âmiri şikâyet etmek cezayı mucip','(4) Âmirin yüzüne karşı','cezayı muciptir.',[],'şikâyetçi olacağım diye dedikodu da'),
 ('11','yasak','Müracaat ve şikâyet','toplu müracaat yasak; her biri ayrı ayrı şikâyet eder','Müracaat ve şikâyetler MADDE 11','şikâyet hakkını kullanabilir.',[],''),
 ('11','ceza','cezayı mucip','âmirin yüzüne karşı şikâyet; şikâyet edeceğim dedikodusu','(4) Âmirin yüzüne karşı','cezayı muciptir.',[],''),
 ('11','kosul','hüküm bulunmayan','Devlet Memurlarının Şikâyet ve Müracaatları Yönetmeliği','(5) Bu maddede hüküm','Yönetmelik hükümleri uygulanır.',[],''),
 ('11','sira_usul','Şikâyetleri incelemeye yetkili','bizzat neticelendirir; üst karar gerekirse iletir','(3) Şikâyetleri incelemeye','şikâyetçiye tebliğ ederler.',[],''),
 ('12','tanim','Ödüllendirme','teşvik, moral, emsalleri arasında ayırt edip örnek kılmak','Ödül MADDE 12 - (1) Ödüllendirme','maksadı ile yapılır.',[],''),
 ('12','kosul','kıyaslanması','emsalleriyle esas; ödüllü sayısı aşırı olmaz','(4) Ödüllendirmede','ödülün değerini düşürür.',[],''),
 ('12','kosul','Ödül sistemi','disiplin cezaları ve değerlendirme notundan bağımsız','(7) Ödül sistemi','durum içinde değerlendirilir.',[],'ceza silme karşılığı ödül YOK'),
 ('12','yasak','aşırıya kaç','“görevini yapmıştır” diye ödül dağıtmak','(3) Personel kendisine','ödül karşılığı olarak yapılacağı hissinin oluşmasına neden olur.',[],''),
 ('12','sira_usul','Ödüller, mümkün olduğunca','mesai arkadaşlarının huzurunda','(6) Ödüller, mümkün','teşvik edici sözler söylenir.',[],''),
 ('12','yasak','daha büyük ödül','başarıya orantısız teklif yapılmaz','(8) Başarının derecesi','tekliflerinde bulunulmaz.',[],''),
 ('12','makam','Ödül çeşitleri','Bakanlık yönetmeliği','(9) Ödül çeşitleri','yönetmelikle belirlenir.',[],''),
 ('13','kosul','tatbik şekli','7068 sayılı Kanun','(3) Disiplin cezası verilmesini','yazılı olduğu gibidir.',[],''),
 ('13','kosul','fayda ve tesiri','diğerlerine ibret olması','Cezanın, disiplinin tesisi','diğerlerine ibret olmasındadır.',[],'uyarmak ve zarar vermekten ziyade'),
 ('13','kosul','Ceza tam bir','adaletle ve zamanında','(2) Ceza tam bir','zamanında verilmelidir.',[],''),
 ('14','tanim','İznin maksadı','dinlenme, güç toplama, şahsi ihtiyaç','İzin MADDE 14 - (1) İznin maksadı','şahsi ihtiyaçlarını görmesidir.',[],''),
 ('14','kosul','planlan','göreve ve personelin talep ettiği aylara göre önceden','(2) İzinler; göreve','planda belirtilen gün ve sürelere sadık kalınmalıdır.',[('30','servis araçları imkâna göre planlanır')],'tam ve zamanında kullandırmak âmirin yeteneğini gösterir'),
 ('14','yasak','izin hakkından','âmir feragate yönelik tavır-ima yapmaz','(3) Âmir, açıkça olmasa da','imada bulunmamalıdır.',[],''),
 ('14','makam','kullandırıl','yetkili âmir; büyük âmir kendi inisiyatifine almaz','(4) İzinler yetkili âmir','inisiyatiflerine alınmamalıdır.',[],''),
 ('14','sira_usul','İzne giden','adres ve iletişimini âmirine bildirir; ulaşılabilir kalır','(5) İzne giden her personel','ulaşılabilir kılmalıdır.',[],''),
 ('14','sure','İzin yılı','her senenin ilk ayından başlar','(6) İzin yılı','ona göre düzenlenir.',[],'göreve başlama ayı DEĞİL'),
 # m.15-18 — kılık-kıyafet, görgü, esas duruş, selamlama
 ('15','kosul','görev sırasında','resmî kıyafetli olması esas','(2) Rütbeli personel ve erlerin görev','resmî kıyafetli olması esastır.',[],'rütbeli personel ve erler'),
 ('15','makam','sivil kıyafet giyebileceği','yetkili makamlar görevin mahiyetine göre','(7) Rütbeli personel ve erlerin hangi','emirle düzenlenir.',[],''),
 ('15','yasak','resmî kıyafet giyemez','adli çağrıda (tanık-bilirkişi hariç), tutukluyken, uzaklaştırılmışken','(8) Rütbeli personel ve erler; tanıklık','resmî kıyafet giyemez.',[],'yıllık izinde giyilebilir'),
 ('15','kosul','pardösü ve yağmurluk','yaka kalkmaz, kuşak cebe girmez, daima bağlı','i) Resmî pardösü','daima bağlı durumda bulundurulur.',[],''),
 ('15','kosul','çanta','koyu renk, sade desen, sol elde','k) Resmi kıyafet ile sadece','sol elde taşınabilir.',[],''),
 ('15','kosul','Kimlik kartı','resmî-sivil her zaman üzerinde; güvenlik-İKK istisnası; istenince gösterilir','(10) Kimlik kartı','kimlik kartının gösterilmesi zorunludur.',[('18','sivil üst kimlik kartını ibraz edince selam verilir')],''),
 ('15','kosul','hamileliğini','kadın rütbeli sivil kıyafetle görev yapabilir','m) Kadın rütbeli personel, hamileliğini','sivil kıyafet ile görev yapabilir.',[],''),
 ('15','yasak','sakız','resmî kıyafetle sakız, poşet, kol kola, eller cepte yok','b) Resmî kıyafet ile sakız','tavır ve davranışlarda bulunulmaz.',[],'şapka çıkarılmaz'),
 ('15','istisna','yüzük, bileklik','nişan, evlilik, devre yüzüğü dışında yok','ç) Resmî kıyafet ile nişan','bileklik ve kolye kullanılmaz.',[],''),
 ('15','makam','şapkasız','en büyük âmirin izin verdiği alanda','e) Bina ve müştemilatı','şapkasız olarak dolaşılabilir.',[('18','kapalı yerde millî marşta şapkasız saygı duruşu')],'bina ve araç dışında başlık zorunlu'),
 ('15','kosul','Araç içinde','şapka çıkarılabilir; birlik-beraberlik esas','f) Araç içinde','birlik ve beraberlik esastır.',[],''),
 ('15','yasak','işaretler sökülse dahi','resmî kıyafet sivile dönüştürülmez','ı) Üzerindeki işaretler','birlikte giyilemez.',[],''),
 ('15','kosul','tabancalarını','görev dışında sivil elbiseyle görünmeden taşınabilir','j) Rütbeli personel görev dışında','görünmeyecek şekilde taşıyabilir.',[],''),
 ('15','istisna','başörtü','kadın rütbeli; yüzü kapatmayan, kıyafet renginde','l) Kadın rütbeli personel yüzünü','benzeri kıyafetler giyemez.',[],''),
 ('15','yasak','eskimiş','rütbeli ve er dışındakilere verilmez','n) Resmî kıyafetler eskimiş','kullanmalarına müsaade edilmez.',[],''),
 ('15','kosul','ilişiği kesil','resmî kıyafeti çıkarmaya mecbur','o) Rütbeli personel ve erler; emeklilik','çıkarmaya mecburdur.',[],''),
 ('15','yasak','favori, sakal ve bıyık','bırakılmaz (mevzuat istisnası hariç)','ö) El, yüz ve saç','sakal ve bıyık bırakılmaz.',[],'sadelik esas'),
 ('15','kosul','kısa saçlı','kadın: omuz hizasını geçmez; uzunsa toplanır','p) Erkek rütbeli personel','omuz hizasını geçmez.',[],'erkekte saç şapkadan taşmaz'),
 ('15','sure','her sabah','erkek sakal tıraşı; saç gerektiğinde','(6) Erkek personel her sabah','bitkin bir görüntü sergilemez.',[],''),
 ('15','kosul','Devlet memurları hakkında','Kamu Personeli Kılık ve Kıyafet Yönetmeliği','(12) Devlet memurları hakkında','Yönetmelik hükümleri uygulanır.',[],''),
 ('16','yasak','görgü ve nezaket kurallarına','aykırılıkta disiplin işlemi','Mesleki görgü ve nezaket MADDE 16','disiplin işlemi uygulanır.',[],'ayrıntılar emir-broşürle'),
 ('16','kosul','Devlet töresine','kamu âmirlerine teamül ve töreye göre hitap','(2) Personel; kamu kurum','Devlet töresine göre hitap eder.',[],''),
 ('17','kosul','Esas duruş,','ruhen-bedenen olgunluk, göreve hazırlık; her safhada aranır','Esas duruş MADDE 17 - (1) Esas duruş','her safhasında aranır.',[('18','sivil üste de derhal esas duruş ve selam')],''),
 ('17','kosul','esas duruş bozulmaz','âmir otur ya da rahat demeden','(2) Âmir veya üst','esas duruş bozulmaz.',[],'âmir gelince derhal ayağa kalkılır'),
 ('17','istisna','Devlet memurları esas duruş','geçmez; saygılı duruş zorunlu','(7) Devlet memurları esas','sergilemek zorundadır.',[],''),
 ('17','kosul','yan tarafta','yerinde dönüşle cephe âmire','(4) Âmir veya üst ile','âmir veya üste çevrilir.',[],'baş çevrilmez'),
 ('17','yasak','Konuşulması gerekiyorsa','el-kol sallanmaz, vücut bükülmez','(5) Esas duruşta sessiz','vücut bükülmez.',[],''),
 ('18','istisna','selamlama','araç süren selam vermez; sivil kıyafet, gecikme engel değil','Selamlama MADDE 18 - (1)','Selamlamanın yapılış tarzı',[('7','selamlama disiplinin ayrılmaz unsuru')],'görmemek mazeret değil; araçtaki astın selamına en kıdemli karşılık verir'),
 ('18','tanim','büyüğün küçüğü','sevgi; küçüğün büyüğü saygı','(1) Selam ve selamlama','muhabbetin belirtisidir.',[],'eşitlerin selamı nezaket'),
 ('18','sira_usul','Astlar, üstlerden','önce selam verir; üst bitirmeden ast bitiremez','(3) Astlar, üstlerden önce','ast selamlamayı bitiremez.',[],'aynı rütbedekiler beklemeden selamlaşır'),
 ('18','kosul','temel kural','astın üstünü, ayrılanın kalanı, gelenin mevcudu selamlaması','Selamlamada temel kural;','gelenlerin mevcut olanları selamlamasıdır.',[],''),
 ('18','kosul','Elle selamlama','başlık varken sağ elle','(8) Elle selamlama','sağ el ile yapılır.',[],''),
 ('18','istisna','Devlet memurları selamlama','muaf; saygılı duruş','(16) Devlet memurları selamlama','muhafaza etmekle mükelleftir.',[],''),
 ('18','kosul','milli marş','açıkta şapkalı, kapalıda şapkasız, cephe marşa','(11) Rütbeli personel ve erler, milli marş','saygı duruşunda bulunur.',[],''),
 ('18','kosul','cephe selamı','Cumhurbaşkanı, sancak, yabancı devlet başkanı, cenaze','(10) Cumhurbaşkanına','cephe selamı verilir.',[],'bayrak çekilir-indirilirken de cephe'),
 ('18','kosul','kimlik kartını ibraz','sivil üste derhal esas duruş ve selam','(5) Selamlama gecikmiş','gerekli saygı gösterilir.',[],''),
 ('18','sira_usul','Merdiven ve dar geçit','ast durup yol verir','Merdiven ve dar geçit','yol vermesi suretiyle olur.',[],''),
 ('18','istisna','eldiven','tören birlikleri dışında eldivenle selam yok','(9) Tören birliklerinde','eldiven ile selâmlama yapılmaz.',[],''),
 ('18','kosul','başı açık','konferans salonu, yemekhane; içeridekiler selamlanır','(14) Konferans salonu','aynı kurallar geçerlidir.',[],'servis aracında da'),
 ('18','kosul','Şehit na’şı','uçak iniş-kalkışında hazır bulunanlar selamlar','(15) Şehit na’şını','selamlama yapılır.',[],''),
 # m.19-22 — vasıflar, sağlık, devlet malı, basın
 ('19','tanim','en büyük ve affedilmeyecek','korkaklık','ç) Cesaret ve şecaat:','namus ve onura leke getirir.',[],''),
 ('19','tanim','ahlaki ve manevi vasıflar','itaat, sebat, cesaret, canını esirgememek, hazırlık, iyi geçinmek, ahlak, sır','(4) Her personelde bulunması','teşkilatların temsil ve tanıtım mahiyetindeki görevidir.',[('15','resmî kıyafet ahlaki ve manevi vasıfları hissettirir')],'yurt sevgisi, emel birliği, yardım, tavır, intizam, temsil de; tarafsız siyasi tavır YOK'),
 ('19','tanim','gösterdiğinden dışarı','itaat','b) İtaat:','yasak edilen şeyleri yapmamaktır.',[],'yasakları yapmamak'),
 ('19','tanim','İtaat:','mevzuat ve emrin dışına çıkmamak, yasakları yapmamak','b) İtaat:','yasak edilen şeyleri yapmamaktır.',[],''),
 ('19','tanim','İntizam severlik:','saat gibi dakikası dakikasına','j) İntizam severlik:','adet haline getirmelidir.',[],''),
 ('19','tanim','Temsil ve tanıtım:','yabancı kolluk-askerle iyi geçinip değerini tanıtmak','k) Temsil ve tanıtım:','mahiyetindeki görevidir.',[],''),
 ('19','tanim','bir vücut gibi','emel ve fikir birliği','h) Emel ve fikir birliği:','takdir ederek sağlanır.',[],'genel menfaat şahsi menfaatten üstün'),
 ('19','tanim','büyüğünün de küçüğünün','canını esirgememek','d) Canını esirgememek:','fedakârlıkla hareket etmektir.',[],''),
 ('19','tanim','pek yürekli','cesaret ve şecaat','ç) Cesaret ve şecaat:','pek yürekli olmaktır.',[],''),
 ('19','tanim','zorluk ve yokluklara','sebat ve mukavemet','c) Sebat ve mukavemet:','istenildiği gibi tamamlamaktır.',[],''),
 ('19','tanim','komutansız ve idarecisiz','göreve hazırlık','e) Göreve hazırlık:','arttırmaya çalışmaktır.',[],''),
 ('19','tanim','kardeşten ileri','iyi geçinmek','f) İyi geçinmek:','mertçe hareket etmektir.',[],'arkadaşın kabahatini örtbas etmek teşkilata fenalık'),
 ('19','tanim','kötü niyetlilerin','sır saklamak','ğ) Sır saklamak:','sır vermemelidir.',[],''),
 ('19','kosul','mesai saatleri dışında da','teşkilat personeli bilinciyle','(2) Personel, resmî sıfatının','bilinciyle hareket eder.',[],''),
 ('20','gorev_yetki','hastalandığında','âmirine bildirir; âmir sağlığı takip eder','Bu cihetle, personel sağlığını','tedbirleri almakla yükümlüdür.',[],''),
 ('21','yasak','bedelsiz ve emanet','satamaz, kiralayamaz; kalkışanı âmire haber verir','a) Devlet tarafından bedelsiz','âmirine derhal haber verir.',[],''),
 ('21','yasak','kendiliğinden ilâveler','eşyada değişiklik yapılamaz','b) Kendisine verilen eşyanın','değişiklikler yapamaz.',[],''),
 ('22','makam','basına','illerde valiler ve Bakanın yetkili kıldığı görevli verir','Basınla münasebet ve resmî yayın','görevli tarafından verilebilir.',[],'personel bildiri dağıtamaz, demeç veremez'),
 ('22','yasak','iç ve dış siyaset','yazı yazamaz; Hükümet ve meslek aleyhine tenkit yok','(4) Personel, gazete','yayın yapamaz.',[],''),
 ('22','istisna','siyaset hariç','bilimsel, tarihi, iktisadi, edebi yazı serbest','(5) Personel, siyaset hariç','bastırmakta serbesttir.',[],''),
 ('22','yasak','basın ve yayın organının','mesul müdür, yazar, muhabir olamaz','(3) Personel, hiç bir basın','haber vericisi olamaz.',[],''),
 ('22','kosul','resmî kaynak ve belgelerden','yazmadan önce JGK-SGK izni','b) Yalnız mesleki makam','Sahil Güvenlik Komutanlığı belirler.',[],''),
 ('22','kosul','göreve mahsus kitaplardan','basımdan önce silsileyle incelettirip izin','c) Yayımlanacak kitap','yayımlanması için izin alır.',[],''),
 ('22','yasak','kişisel bilgi veya belgeleri','yetkisizle paylaşamaz, basına veremez','(2) Personel, görevi gereği','iletişim kanallarına veremez.',[],''),
 ('22','kosul','kendi hesabına bastırarak','ismi olsun olmasın tamamen mesul','(6) Personel, kendi hesabına','tamamen mesuldür.',[],''),
 # m.23-27 — kışla, çalışma saatleri, yoklama, nöbet, hazır kıta
 ('23','makam','aynı kışla içinde','en kıdemli birlik komutanı, karargâh-kurum âmiri','Kışlalarda komutanlık MADDE 23','kurum âmiri kışla komutanıdır.',[],''),
 ('23','gorev_yetki','Kışla Komutanı','sınırlar, emniyet, yasak malzeme, giriş-çıkış, su analizi, ilaçlama, paratoner','(2) Kışla Komutanının görevleri','Kışla gelişim planının hazırlanmasını sağlar.',[],'hijyen denetimi, kantin geliri, gelişim planı da'),
 ('23','makam','kışla emniyet subayı','subay, yoksa tecrübeli astsubay','Emniyet tedbirlerinin tespiti','kışla emniyet subayı olarak görevlendirilir.',[],''),
 ('23','makam','belediye mücavir alanı','birden fazla kışlada planlar en kıdemli kışla komutanınca','(3) Aynı belediye mücavir','tek elden tespit ve takip edilir.',[],'JGK ve SGK için ayrı ayrı'),
 ('24','sure','haftalık çalışma','genel olarak 40 saat; göreve çağrılmaya engel değil','Çalışma saatleri MADDE 24','görev yerinden ayrılmamasına engel teşkil etmez.',[],'subay, astsubay, uzman jandarma'),
 ('24','kosul','40 saat','göreve çağrılmaya, ayrılmamaya engel değil','Çalışma saatleri MADDE 24','görev yerinden ayrılmamasına engel teşkil etmez.',[],'haftalık genel süre'),
 ('24','makam','yirmi dört saatinde devamlılık','birlik komutanı ya da birim âmiri belirler','(2) Günün yirmi dört','birim âmirlerince belirlenir.',[],''),
 ('24','kosul','eğitimin bitiminde','nöbetçi-görevli olmayan ayrılabilir; izinsiz ayrılma yok','(3) Nöbetçi ve görevli','gündüz ve gece ayrılamaz.',[],''),
 ('25','sira_usul','mesai başlangıcında','yoklama yapılır','Yoklamalar MADDE 25 - (1) Karargâh','yoklamaları yapılır.',[],''),
 ('25','sira_usul','toplu takdim','kılık, teçhizat, eğitim-disiplin tespiti, emir tebliği; âmir belirler','(2) Rütbeli personel ve erlerin kılık','esaslarına göre yürütülür.',[],''),
 ('25','sira_usul','Kışlada kalan','nöbetçi heyeti, görev cetveline göre yoklar','(3) Kışlada kalan','görev cetveline göre alınır.',[],''),
 ('25','kosul','Devlet memurları amirlerinin','emredilen tören, toplantı, yoklamalara katılır','(5) Devlet memurları amirlerinin','yoklamalara katılırlar.',[],''),
 ('26','sira_usul','nöbet görev','hakkaniyetli sıra, kayıt; yönetmelik-yönergeye göre','Nöbet görevleri MADDE 26','esaslarına göre yürütülür.',[],'müşterek görevleri sıra ve süreyle yürütmek için ihdas'),
 ('27','sayi_oran','kuvveti en az','üç kişiden birliğin tamamına kadar','(3) Hazır kıt’anın teşkil','birliğin tamamına kadar olabilir.',[],'zamanı ve kuvvetini birlik komutanı belirler; sabit on kişi YOK'),
 ('27','makam','uyuyup uyumayacağı','çıkaran birlik komutanı emreder','(2) Hazır kıt','birlik komutanı tarafından emredilir.',[],'gece dahi tam teçhizatlı, silahlı'),
 ('27','makam','Hazır kıt’a komutanı','birliğe göre subay, astsubay, uzman jandarma ya da uzman erbaş','Hazır kıt’a komutanı','uzman erbaş olabilir.',[],''),
 # m.28-35 — sosyal tesis, kantin, araçlar, tören, afet, yangın, son hükümler
 ('28','kosul','sosyal tesisler','esaslar ilgili Yönetmelikte','Vardiya yatakhaneleri, sosyal tesisler','Yönetmelik esaslarına göre belirlenir.',[],''),
 ('29','tanim','dayanıklı tüketim','kantin: zaruri ihtiyaç ucuz-kolay; dayanıklı mal hariç','Kantinler MADDE 29','Yönetmelik esaslarına göre belirlenir.',[],''),
 ('30','kosul','boş yer bulunduğu','aileler servis aracından yararlanır; istikamet değişmez','(2) Servis araçlarından','personel ve aileleri de yararlandırılır.',[],'hasta-cenaze aracından da'),
 ('30','kosul','sivil moral ekipleri','savaşta-OHAL’de nakil aracından yararlanır','(3) Savaşta ve olağanüstü','nakil araçlarından yararlandırılır.',[],''),
 ('30','kosul','hava araçlarından','terör bölgesinde aileler de boş yerde','(4) Terörle mücadele','hava araçlarından faydalanabilir.',[],''),
 ('30','kosul','umumi araçların en son','oradan görev yerine resmî araç','(7) Gündelik ve belirli','ilgili komutanlıkça düzenlenir.',[],''),
 ('31','kosul','Törenler','mevzuat ve teşkilat yönergeleri','Tören MADDE 31','yönergelere göre düzenlenir.',[('18','törenlerde bayrak geçidi ayakta selamlanır')],''),
 ('32','makam','afet ve acil durumları','birlik komutanı mahallin en büyük mülki âmirine bildirir','Afet ve acil durum müdahale hizmetleri','haber vermekten sorumludurlar.',[],''),
 ('32','sira_usul','yardımları','vali-kaymakam isterse emir beklemeden, gecikmeksizin','(2) Afet bölgelerinde','Komutanlığına haber verirler.',[('9','âmir maiyetine mümkün yardımları yapar'),('19','birbirine yardım vasfı')],'sonra sıralı amirlere bildirir'),
 ('32','kosul','acil durumlara ilişkin diğer','Afet Müdahale Yönetmeliği ve Türkiye Afet Müdahale Planı','(3) Afet ve acil durumlara','esaslarına göre yürütülür.',[],''),
 ('33','kosul','yangın','Binaların Yangından Korunması Yönetmeliği ve yönerge','Yangında yapılacak işler','Yönerge esaslarına göre yürütülür.',[('23','kışla komutanı yangından korunma planını tek elden yürütür')],''),
 ('34','sure','yürürlüğe girer','onaylandığı tarihte','Yürürlük MADDE 34','yürürlüğe girer.',[],''),
 ('35','makam','Yönetmelik hükümleri','Bakan yürütür','Yürütme MADDE 35','Bakan tarafından yürütülür.',[('11','şikâyette eksik hususta Devlet Memurları Şikâyet Yönetmeliği'),('15','Devlet memurlarına kılık-kıyafet yönetmeliği')],''),
]
yaz(23, 'Jandarma ve Sahil Güvenlik Personelinin Hizmet Esasları Yönetmeliği', K)
