# 6136 Ateşli Silahlar ve Bıçaklar ile Diğer Aletler Hakkında Kanun — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('2','istisna','armağan edilenlerin','resmî görevle yurt dışında; gümrük vergisiz yurda sokulur','B) Resmi görevle yurt dışına','ödenmeksizin)',[],'devlet/hükümet başkanı, genelkurmay başkanı, kuvvet komutanı armağanı; belgelenmeli'),
 ('2','istisna','tek bir silaha mahsus','dış temsilcilikte elçi, konsolos, subay, güvenlik memuru','C) Memuriyetleri devamınca','yurda sokulmasına izin verilir.',[],''),
 ('2','istisna','kıta ile gönderilen','kimlik kartındaki silah için yurda girişte izin aranmaz','Yurt dışına kıta ile','izin şartı aranmaz.',[],''),
 ('4','yasak','sustalı çakı','yapımı yasak alet (m.4)','Ülke içinde kama','yapımı yasaktır.',[],'kama, hançer, pala, kılıç, kasatura, süngü, topuz, muşta, boğma teli; meslek için İçişleri yönetmeliğiyle izin'),
 ('4','istisna','bu Kanun hükümlerine tabi değildir','yivsiz tüfek, spor silahı, meslek aletleri Kanuna tabi değil','Yalnız sporda kullanılan','tabi değildir.',[],''),
 ('4','kosul','ateşli yivli silahlar','avda-sporda bile m.7 ruhsatına tabi','Avda veya sporda kullanılan her nevi','ruhsata tabidir.',[],''),
 ('6','sure','beş yıl için geçerlidir','taşıma ve bulundurma ruhsatları; yenileme harcıyla','Bu Kanun kapsamına giren silahlar için verilen','beş yıl için geçerlidir.',[],''),
 ('6','sure','altı ay içerisinde ruhsatını yeniletmeyenlerin','ruhsat iptal; üçbin TL ödeyerek yeniden alınabilir (mülki amir)','Ruhsatların veriliş sebeplerinin','mülki amir yetkilidir.',[],'ruhsat sebebi kalkınca altı ayda bildirme yükümlülüğü'),
 ('6','istisna','süre kaydı aranmaz','Cumhurbaşkanı, bakanlar, TBMM üyeleri, komutanlar, gaziler, şehit yakını','Ancak, Cumhurbaşkanı, Başbakan','süre kaydı aranmaz.',[],'armağan silahlarda da süre kaydı yok'),
 ('6','kosul','mermiler için ayrıca ruhsat aranmaz','ruhsata bağlı silahın mermileri','Ruhsata bağlanmış silahlara ait','mermiler için de geçerlidir.',[],''),
 ('6','istisna','Ek 1 inci maddede sayılan','taşıma ruhsatı buralarda geçersiz; nereden verilmiş olursa olsun','Silah taşıma ruhsatları nereden','yerler dışında geçerlidir.',[],''),
 ('6','kosul','ayrı ayrı taşıma ruhsatı','birden fazla silahı olana, isteği halinde','Birden fazla silaha sahip','ayrı ayrı taşıma ruhsatı verilir.',[],''),
 ('7','kosul','mecburi hizmetini tamamlayarak istifa','emekli gibi silah taşıyabilir (subay, astsubay, uzman jandarma)','emekli subay, astsubay, uzman jandarma','emniyet hizmetleri sınıfı personeli,',[],''),
 ('7','sure','on yıl görev yapıp','sözleşmesi uzatılmayan/ayrılan uzman erbaş; emniyetten ayrılan da on yıl','emekli subay, astsubay, uzman jandarma','emniyet hizmetleri sınıfı personeli,',[],''),
 ('7','istisna','Devlet memurluğundan çıkarılanlar hariç','7068 disiplin cezasıyla çıkarılan emekli silah taşıyamaz','7068 sayılı Genel Kolluk','çıkarılanlar hariç olmak üzere;',[],'tart, ihraç, rütbe geri alma, ayırma işlemi de hariç'),
 ('7','kosul','Orman muhafaza memurları','orman bölge şefleri de; emekli olanlar taşıyabilir','h) Orman muhafaza','emekli olanlar.',[],'emekli vali, kaymakam, hâkim-savcı, emniyet, MİT, büyükelçi, infaz koruma de'),
 ('7','makam','valiler tarafından verilecek izin vesikasını','Cumhurbaşkanı yönetmeliğindeki esaslara göre; taşıma hakkı','5. Cumhurbaşkanınca çıkarılan yönetmelikte','izin vesikasını alanlar,',[],''),
 ('7','kosul','köy veya mahalle muhtarlığı','en az bir dönem yapmış olan taşıyabilir; terör irtibatı hariç','7. Yapılan soruşturma sonucu','bulundurabilirler.',[],'belediye başkanlığı da'),
 ('7','sayi_oran','en fazla bir adet silahın','6 ve 7 nci bentlerdeki kişilerin (korucu, muhtar) edinecekleri','Birinci fıkranın (1), (2), (3) ve (4)','en fazla bir adet silahın,',[],''),
 ('7','kosul','izin belgesi yerine geçer','Kuvvet/EGM/SGK/JGK kayıtlı emekli belgesi','Birinci fıkranın (4) numaralı bendinin (A)','izin belgesi yerine geçer.',[],''),
 ('8','makam','toplu silah aranması','Cumhurbaşkanı kararıyla valiler; halka taşıma izni de','Lüzum görülen mıntakalarda','yapılabilir.',[],''),
 ('9','yasak','muvakkaten de olsa başkalarına veremezler','ruhsatlı silah; ruhsatsıza satılamaz da','Ateşli silah taşımak müsaadesini','başkalarına veremezler.',[],''),
 ('9','kosul','intihar ve intihara teşebbüs','silahın ihmaliyle; vesika geri alınır, bir daha verilmez','Silah bulundurma ve taşıma ruhsatını haiz olan kimsenin','izni verilmez.',[],'silahla suç işlemek de'),
 ('9','kosul','İkinci kez silahı çalınan','yeni müracaatta tek silah izni','İkinci kez silahı çalınan','izni verilebilir.',[],'kaybeden de'),
 ('9','sure','Üçüncü kez silahı çalınan','vesika geri; beş yıl izin yok; sonra tek silah','Üçüncü kez silahı çalınan','izni verilmez.',[],'İKİNCİ KAYIP TEK SİLAH, ÜÇÜNCÜ KAYIP BEŞ YIL'),
 ('10','makam','tutanak karşılığı Milli Savunma','zoralımına karar verilen, ele geçirilen silah ve mermiler','Mahkemelerce zoralımına','Milli Savunma Bakanlığı emrine verilir.',[],'öncelik MSB, JGK, EGM, MİT, Gümrük Muhafaza; MKE aracılığıyla satış'),
 ('10','sayi_oran','bedellerinin yarısı','polisler zati tabancayı yarı bedelle; öncelik hakkı','Emniyet Genel Müdürlüğünce zati silah','öncelik hakkına sahiptirler.',[],''),
 ('11','kosul','üstte taşımaya cevaz vermez','antika silah izni; yalnız bulundurma ve nakil','Antika olan ateşli silahlarla bıçaklar için verilen izin','üstte taşımaya cevaz vermez.',[],'hatıra ve antika silaha bulundurma izni zorunlu'),
 ('11','istisna','kılıç, meç ve benzeri','görev nedeniyle verilen; izin belgesi aranmaz','Ancak, görevleri nedeniyle Devletçe','izin belgesi aranmaz.',[],''),
 ('11','kosul','izin vesikalarıyla birlikte satışı serbesttir','antika silah ve bıçaklar','Antika olan ateşli silahlarla bıçakların izin','satışı serbesttir.',[],''),
 ('11','tanim','artık imal edilmeyen','antika silah tanımı','Antika silah deyimi','ifade eder.',[],'hatıra silah: devlet başkanı/hükümet/genelkurmay hediyesi, İstiklal Savaşı silahları'),
 ('12','ceza','ülkeye sokar veya sokmaya kalkışır','silah/mermi; beş yıldan oniki yıla + beşyüz–beşbin gün APC','Her kim bu Kanunun kapsamına giren ateşli','adlî para cezasıyla cezalandırılır.',[],'imal, nakil, satış, bu amaçla bulundurma da'),
 ('12','ceza','daha çok kişinin birlikte','silahta sekiz yıldan onbeş yıla + bin–onbin gün','Birinci fıkrada yazılı suçları üçüncü fıkradaki hal dışında','adlî para cezasına hükmolunur.',[('14','bıçak suçunda iki kişi: ceza bir kat artar')],'örgüt faaliyetinde bir kat artırım'),
 ('12','ceza','susturuculu veya hedef noktalayıcı','cezalar yarı oranında artırılır; miktar vahimse de','Ateşli silahın tüfek veya seri','yarı oranında artırılarak hükmolunur.',[],'tam otomatik, dürbünlü, tüfek de'),
 ('12','ceza','Kurusıkı tabir edilen','dönüştürme = üretim; vahim değilse üçte birden yarısına indirim','Kurusıkı tabir edilen','yarısına kadar indirilir.',[],''),
 ('13','ceza','satın alan veya taşıyanlar','ruhsatsız silah; iki yıldan dört yıla + yüz–beşyüz gün','Bu Kanun hükümlerine aykırı olarak ateşli silahları','adlî para cezasına hükmolunur.',[],'vahim ya da nitelikli: beş yıldan sekiz yıla'),
 ('13','ceza','ev veya işyerinde bulundurulması','bir adet silah + mutat mermi: bir yıldan üç yıla','Bu Kanunun 12 nci maddesinin dördüncü fıkrasında sayılanlar dışındaki','adlî para cezasıdır.',[],''),
 ('13','ceza','takdir edilmemesi durumunda','pek az mermi: altı aya kadar hapis + otuz–beşyüz gün','takdir edilmemesi durumunda','adlî para cezasıdır.',[],''),
 ('13','ceza','Nakil izin belgesi almaksızın','onbin–yirmibeşbin TL idari para cezası; mülki idare amiri','Nakil izin belgesi almaksızın','idari para cezasına hükmolunur.',[],'ruhsatlandırma yükümlülüğüne aykırılıkta da aynı'),
 ('14','ceza','ikiyüz günden az olmamak','yasak bıçak imal/ithal/nakil; iki yıldan beş yıla hapis','Her kim, bu Kanun hükümlerine aykırı olarak 4 üncü','adlî para cezası ile cezalandırılır.',[],'azlıkta yarıya kadar indirim'),
 ('14','ceza','teşekkül kuranlar','bıçak suçunda beş yıldan on yıla + bin–onbin gün','Birinci fıkradaki eylemleri işlemek amacı ile teşekkül','adlî para cezasına hükmolunur.',[],''),
 ('15','ceza','yirmibeş günden az olmamak','yasak bıçak satma, alma, taşıma: altı aydan bir yıla','Bu Kanun hükümlerine aykırı olarak 4 üncü maddede yazılı olan bıçak veya diğer aletleri veya benzerlerini satanlar','adlî para cezasına hükmolunur.',[],'vahimse yarıdan bir katına artırım'),
 ('15','ceza','sırf saldırıda kullanmak amacıyla','üç aya kadar hapis ya da adlî para cezası','Bu Kanunun 4 üncü maddesinin üçüncü fıkrasında','cezalandırılır.',[],'izinli bıçak, yivsiz tüfek bile'),
 ('16','istisna','1918 Sayılı Kanun','Kaçakçılığın Men ve Takibi Kanunu bu suçlarda uygulanmaz','Bu Kanunun kapsamına giren suçlarda','uygulanmaz.',[],''),
 ('Geçici','sure','90 gün içinde','korucular silahı teslim ederse takibat yok; valiler harçsız ruhsat','mülki amirlerce gönüllü korucu','ruhsatı düzenlenebilir.',[],'geçici madde 9; devir, hibe, satış yasak'),
]
yaz(25, '6136 sayılı Ateşli Silahlar ve Bıçaklar ile Diğer Aletler Hakkında Kanun', K)
