# 6698 KVKK — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('3','tanim','özgür iradeyle açıklanan','açık rıza (tanım)','a) Açık rıza','özgür iradeyle açıklanan rızayı,',[],'belirli konu + bilgilendirme + özgür irade'),
 ('3','tanim','amaçlarını ve vasıtalarını belirleyen','veri sorumlusu','ı) Veri sorumlusu','gerçek veya tüzel kişiyi,',[('3','veri işleyen: sorumlunun yetkisiyle onun adına işleyen')],'kayıt sisteminin kurulmasından sorumlu'),
 ('3','tanim','onun adına kişisel verileri işleyen','veri işleyen','ğ) Veri işleyen','gerçek veya tüzel kişiyi,',[],''),
 ('3','tanim','başka verilerle eşleştirilerek dahi','anonim hâle getirme','b) Anonim hâle getirme','ilişkilendirilemeyecek hâle getirilmesini,',[],'kimlikle ilişkilendirilemez'),
 ('4','kosul','ilkelere uyulması zorunludur','dürüstlük, doğru-güncel, belirli-açık-meşru amaç, sınırlı-ölçülü, gerekli süre','(2) Kişisel verilerin işlenmesinde','süre kadar muhafaza edilme.',[],'beş genel ilke'),
 ('5','istisna','açık rızası aranmaksızın','kanun, fiili imkânsızlık, sözleşme, hukuki yükümlülük, alenileştirme, hak, meşru menfaat','(2) Aşağıdaki şartlardan','meşru menfaatleri için veri işlenmesinin zorunlu olması.',[],'yedi hal'),
 ('5','istisna','kendisi tarafından alenileştirilmiş olması','alenileştirilmiş veri: açık rıza aranmaz','d) İlgili kişinin kendisi','alenileştirilmiş olması.',[],''),
 ('5','istisna','meşru menfaatleri','açık rıza aranmaz; temel haklara zarar vermemek kaydıyla','f) İlgili kişinin temel hak','zorunlu olması.',[],'veri sorumlusunun meşru menfaati'),
 ('6','tanim','kılık ve kıyafeti','özel nitelikli kişisel veri','(1) Kişilerin ırkı','özel nitelikli kişisel veridir.',[],'ırk, etnik köken, siyasi düşünce, inanç, din, dernek-vakıf-sendika üyeliği, sağlık, cinsel hayat, ceza mahkûmiyeti'),
 ('6','tanim','biyometrik ve genetik','özel nitelikli kişisel veri','(1) Kişilerin ırkı','özel nitelikli kişisel veridir.',[],''),
 ('6','yasak','işlenmesi yasaktır','özel nitelikli veri; ancak sayılan hallerde mümkün','(3) (Değişik:2/3/2024-7499/33 md.) Özel nitelikli','işlenmesi yasaktır.',[],'açık rıza, kanun, fiili imkânsızlık, alenileştirme, hak, sağlık (sır saklayanlar), istihdam-sosyal güvenlik, vakıf-dernek üyeleri'),
 ('6','istisna','Sır saklama yükümlülüğü altında','sağlık verisi işlenebilir: koruyucu hekimlik, teşhis, tedavi','e) Sır saklama','amacıyla gerekli olması,',[],'sağlık hizmetlerinin planlanması, finansmanı da'),
 ('6','istisna','kâr amacı gütmeyen','vakıf, dernek: üyelerine yönelik özel veri işleyebilir','g) Siyasi, felsefi, dini veya sendikal','yönelik olması,',[],'üçüncü kişilere açıklanmamak kaydıyla'),
 ('6','makam','yeterli önlemlerin','Kurul belirler; özel nitelikli veri için','(4) Özel nitelikli','alınması şarttır.',[],''),
 ('7','kosul','sebeplerin ortadan kalkması','silinir, yok edilir veya anonim hâle getirilir','(1) Bu Kanun ve ilgili','anonim hâle getirilir.',[],'resen ya da ilgili kişinin talebiyle; veri sorumlusu'),
 ('28','istisna','konutta yaşayan aile fertleriyle','aile içi faaliyet; Kanun kapsamı dışında','konutta yaşayan aile','faaliyetler kapsamında işlenmesi.',[],'üçüncü kişiye verilmemek kaydıyla'),
 ('28','istisna','önleyici, koruyucu ve istihbari','Kanun uygulanmaz; kamu kurumlarının önleyici faaliyeti','ç) Kişisel verilerin millî savunmayı','istihbari faaliyetler kapsamında işlenmesi.',[],'millî savunma, güvenlik, kamu düzeni, ekonomik güvenlik'),
 ('28','istisna','talep etme hakkı hariç','kısmi istisnada tazminat hakkı kalır; aydınlatma, haklar, sicil uygulanmaz','(2) Bu Kanunun amacına','aşağıdaki hâllerde uygulanmaz:',[],'m.10, 11, 16'),
 ('28','istisna','disiplin soruşturma veya kovuşturması','denetleme, düzenleme, disiplin: aydınlatma ve haklar kısmen uygulanmaz','c) Kişisel veri işlemenin kanunun','kovuşturması için gerekli olması.',[],'suç önleme/soruşturma, alenileştirilmiş veri, bütçe-vergi de'),
 ('6', 'tanim', 'sendika üyeliği, sağlığı', 'özel nitelikli; ırk, etnik köken, siyasi düşünce, inanç, din, kılık-kıyafet', '(1) Kişilerin ırkı, etnik kökeni', 'özel nitelikli kişisel veridir.', [], 'eğitim durumu listede YOK'),
 ('6', 'tanim', 'ceza mahkûmiyeti ve güvenlik tedbirleriyle', 'özel nitelikli; sağlık, cinsel hayat, dernek-vakıf-sendika üyeliği, biyometrik, genetik', '(1) Kişilerin ırkı, etnik kökeni', 'özel nitelikli kişisel veridir.', [], ''),
 ('3', 'tanim', 'Kişisel verisi işlenen gerçek kişiyi', 'ilgili kişi tanımı', 'ç) İlgili kişi', 'işlenen gerçek kişiyi,', [], ''),
 ('3', 'tanim', 'belirlenebilir gerçek kişiye ilişkin', 'kişisel veri tanımı: her türlü bilgi; tüzel kişi YOK', 'd) Kişisel veri', 'her türlü bilgiyi,', [], ''),
 ('3', 'tanim', 'veri kayıt sisteminin parçası', 'kişisel verilerin işlenmesi tanımı: otomatik ya da otomatik olmayan yollarla', 'e) Kişisel verilerin işlenmesi', 'gerçekleştirilen her türlü işlemi,', [], ''),
 ('3', 'tanim', 'Kişisel Verileri Koruma Kurulunu', 'Kurul tanımı; Kurum = Kişisel Verileri Koruma Kurumunu', 'f) Kurul', 'Kişisel Verileri Koruma Kurumunu,', [], 'veri ihlali bildirimi tanımlarda YOK'),
 ('3', 'tanim', 'bilgilendirilmeye dayanan', 'açık rıza: belirli konu + bilgilendirme + özgür irade', 'a) Açık rıza', 'özgür iradeyle açıklanan rızayı,', [], ''),
 ('5', 'kosul', 'açık rızası olmaksızın işlenemez', 'kural; aşağıdaki şartlardan birinin varlığında rıza aranmaz (yedi hâl)', '(1) Kişisel veriler ilgili kişinin açık rızası', 'kişisel verilerinin işlenmesi mümkündür:', [], ''),
 ('5', 'istisna', 'sözleşmenin kurulması veya ifasıyla', 'taraflara ait verilerin işlenmesi gerekli ise rıza aranmaz', 'c) Bir sözleşmenin kurulması', 'işlenmesinin gerekli olması.', [], ''),
 ('5', 'istisna', 'Fiili imkânsızlık nedeniyle', 'rızasını açıklayamayan kişinin hayatı/beden bütünlüğü için zorunluysa rıza aranmaz', 'b) Fiili imkânsızlık nedeniyle rızasını', 'korunması için zorunlu olması.', [('6', 'özel nitelikli veride de fiili imkânsızlık istisnası var')], ''),
 ('6', 'tanim', 'sağlığı, cinsel hayatı', 'özel nitelikli kişisel veri: ırk, din, mezhep, kılık-kıyafet, biyometrik, genetik', '(1) Kişilerin ırkı', 'özel nitelikli kişisel veridir.', [], 'telefon, e-posta, doğum yeri özel nitelikli DEĞİL'),
 ('6', 'istisna', 'açık rızasının olması', 'özel nitelikli veri işleme hâllerinden ilki; toplam sekiz hâl', '(3) (Değişik:2/3/2024-7499/33 md.) Özel nitelikli', 'a) İlgili kişinin açık rızasının olması,', [], 'GENEL VERİ 7 HÂL, ÖZEL NİTELİKLİ 8 HÂL'),
 ('4', 'kosul', 'öngörülen usul ve esaslara', 'kişisel veriler ancak bu Kanun ve diğer kanunlardaki usulle işlenir', '(1) Kişisel veriler, ancak bu Kanunda', 'uygun olarak işlenebilir.', [], ''),
 ('4', 'kosul', 'Doğru ve gerektiğinde güncel', 'genel ilkeler: hukuk-dürüstlük, belirli-açık-meşru amaç, sınırlı-ölçülü, süreli muhafaza', '(2) Kişisel verilerin işlenmesinde aşağıdaki', 'süre kadar muhafaza edilme.', [], '2026 sınavında soruldu: süresiz muhafaza ilke DEĞİL'),
 ('28', 'istisna', 'aşağıdaki hâllerde uygulanmaz', 'tam istisna: aile içi faaliyet, resmi istatistik-anonim, sanat-bilim-ifade, istihbari, yargı', '(1) Bu Kanun hükümleri aşağıdaki', 'infaz mercileri tarafından işlenmesi.', [], ''),
 ('28', 'istisna', 'resmi istatistik ile anonim', 'araştırma, planlama, istatistik amaçlı işleme: Kanun uygulanmaz', 'b) Kişisel verilerin resmi istatistik', 'istatistik gibi amaçlarla işlenmesi.', [], ''),
 ('28', 'istisna', 'ifade özgürlüğü kapsamında', 'sanat, tarih, edebiyat, bilim amaçlı işleme; özel hayat ihlal edilmemeli', 'c) Kişisel verilerin millî savunmayı', 'ifade özgürlüğü kapsamında işlenmesi.', [], ''),
 ('7', 'kosul', 'hükümler saklıdır', 'silme/yok etme/anonimleştirmeye ilişkin diğer kanun hükümleri; usul yönetmelikle', '(2) Kişisel verilerin silinmesi, yok edilmesi veya anonim hâle getirilmesine ilişkin diğer', 'yönetmelikle düzenlenir.', [], ''),
 ('7', 'makam', 'usul ve esaslar yönetmelikle düzenlenir', 'kişisel verilerin silinmesi, yok edilmesi, anonim hâle getirilmesi', '(2) Kişisel verilerin silinmesi, yok edilmesi veya anonim hâle getirilmesine ilişkin diğer', 'yönetmelikle düzenlenir.', [], ''),
]
yaz(3, '6698 sayılı Kişisel Verilerin Korunması Kanunu', K)
