# 5326 Kabahatler Kanunu — kelime → cevap (kanıt aralıkları metindeki "..." kısaltmalarına girmeyecek şekilde seçildi)
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('2','tanim','öngördüğü haksızlık','kabahat (tanım)','(1) Kabahat deyiminden','haksızlık anlaşılır.',[],'karşılığında idarî yaptırım öngörülen haksızlık'),
 ('3','kosul','aksine hüküm bulunmaması halinde','kanun yolu hükümleri; genel hükümler para cezası gerektiren tüm fiillere','(1) Bu Kanunun; a)','uygulanır.',[],''),
 ('4','kosul','düzenleyici işlemleriyle de doldurulabilir','kabahat tanımının içeriği (suçta yasak)','(1) Hangi fiillerin','doldurulabilir.',[],'TCK m.2: suç ve ceza düzenleyici işlemle konulamaz'),
 ('4','kosul','ancak kanunla belirlenebilir','yaptırımın türü, süresi, miktarı','(2) Kabahat karşılığı','kanunla belirlenebilir.',[],''),
 ('5','kosul','derhal uygulama kuralı','yaptırım kararlarının yerine getirilmesinde (zaman bakımından)','Ancak, kabahatler karşılığında','derhal uygulama kuralı geçerlidir.',[],'TCK\'nın zaman kuralları kabahatte de uygulanır'),
 ('5','kosul','Neticenin oluştuğu zaman','dikkate alınmaz; davranış anı esas','(2) Kabahat, failin','dikkate alınmaz.',[],''),
 ('7','kosul','hukukî yükümlülüğün varlığı gereklidir','ihmali davranışla kabahat için','(1) Kabahat, icraî','yükümlülüğün varlığı gereklidir.',[],''),
 ('8','kosul','tüzel kişi hakkında da','organ veya temsilcinin kabahatinden idarî yaptırım uygulanabilir','(1) Organ veya temsilcilik','idarî yaptırım uygulanabilir.',[],''),
 ('8','kosul','iş sahibi kişi hakkında da','çalışanın kabahatinden işverene de yaptırım','Gerçek kişiye ait bir işte','idarî yaptırım uygulanabilir.',[],''),
 ('9','kosul','hem kasten hem de taksirle','kabahat işlenebilir; TCK\'da taksir açıkça yazılmalı','(1) Kabahatler, kanunda','taksirle işlenebilir.',[],''),
 ('11','istisna','onbeş yaşını doldurmamış','çocuğa idarî para cezası yok','(1) Fiili işlediği sırada','uygulanamaz.',[],''),
 ('11','istisna','Akıl hastalığı','idarî para cezası uygulanmaz','(2) Akıl hastalığı','uygulanmaz.',[],'algılama ya da yönlendirme yeteneği önemli derecede azalmış'),
 ('13','istisna','Kabahate teşebbüs','cezalandırılmaz; kanunda açık hüküm varsa TCK teşebbüs hükümleri','(1) Kabahate teşebbüs','kabahatler bakımından da uygulanır.',[],''),
 ('14','kosul','her biri hakkında, fail olarak','iştirakte herkes fail; idarî para cezası','(1) Kabahatin işlenişine','idarî para cezası verilir.',[],''),
 ('14','kosul','niteliği taşımayan kişi hakkında da','fail olarak idarî para cezası; TCK özgü suçun tersi','(2) Özel faillik','idarî para cezası verilir.',[],'TCK m.40: özgü suçta sıfatsız kişi fail olamaz'),
 ('15','kosul','en ağır idarî para cezası','bir fiille birden fazla kabahat','(1) Bir fiil ile birden fazla kabahatin','en ağır idarî para cezası verilir.',[],'başka idarî yaptırımlar varsa her biri uygulanır'),
 ('15','kosul','Kesintisiz fiille','karar verilinceye kadar tek fiil sayılır','Kesintisiz fiille','fiil tek sayılır.',[],'aynı kabahat birden fazla işlenirse her biri için ayrı ceza'),
 ('15','kosul','hem kabahat hem de suç','sadece suçtan yaptırım; uygulanamazsa kabahat','(3) Bir fiil hem kabahat','kabahat dolayısıyla yaptırım uygulanır.',[],''),
 ('16','tanim','idarî tedbirlerden ibarettir','idarî yaptırım türleri: para cezası ve idarî tedbirler','(1) Kabahatler karşılığında uygulanacak','diğer tedbirlerdir.',[],'tedbir: mülkiyetin kamuya geçirilmesi vb.'),
 ('17','tanim','maktu veya nispi','idarî para cezası türleri','(1) İdarî para cezası, maktu','maktu veya nispi olabilir.',[],''),
 ('17','makam','kendi bütçelerine gelir','SGK ve mahalli idare cezaları; savcılık-mahkeme cezaları Genel Bütçeye','Cumhuriyet başsavcılıkları ve mahkemeler','kendi bütçelerine gelir kaydedilir.',[],''),
 ('17','sure','dört eşit taksit','bir yıl içinde; ilk taksit peşin; ekonomik durum müsait değilse','Kişinin ekonomik durumunun','tamamı tahsil edilir.',[],'taksit aksarsa kalanın tamamı tahsil'),
 ('17','sure','tebliğinden itibaren bir ay içinde','ödeme süresi belirlenmemiş idari para cezası','Kanunlarında ödeme süresi','bir ay içinde ödenir.',[],''),
 ('17','sayi_oran','%25 oranında indirim','ödeme süresi içinde ödenirse','İdari para cezasının ödeme süresi içinde','başvurma hakkını etkilemez.',[],'ödeme, kanun yoluna başvuru hakkını kaldırmaz'),
 ('17','sayi_oran','yeniden değerleme oranında','her yıl artırılarak uygulanır','yeniden değerleme oranında','artırılarak uygulanır.',[],'nispi cezalar hariç'),
 ('18','kosul','aksi takdirde Devlete geçer','mülkiyeti kamuya geçirilen eşya; kanunda yazılıysa ilgili kuruma','(4) Eşyanın mülkiyeti','Devlete geçer.',[],'değerlendirilemezse imha'),
 ('18','kosul','şart değildir','mülkiyetin kamuya geçirilmesi için para cezası verilmiş olması gerekmez','(5) Eşyanın mülkiyetinin','şart değildir.',[],''),
 ('18','kosul','Kaim değerin','mülkiyetin kamuya geçirilmesine karar verilebilir','(6) Kaim değerin','karar verilebilir.',[],''),
 ('20','sure','Soruşturma zamanaşımı süresi','yüzbin+ beş, ellibin+ dört, az üç yıl','(2) Soruşturma zamanaşımı süresi','üç yıldır.',[],'dolarsa idarî para cezası verilemez'),
 ('20','sure','Nispî idarî para cezasını','zamanaşımı sekiz yıl','(3) Nispî','sekiz yıldır.',[],''),
 ('20','sure','takvim yılının son günü','trafik, askerlik vb. cezaları yıl sonuna kadar tebliğ edilmezse düşer','Ancak, 1111 Askerlik','verilmiş olanlar düşer.',[],'1111, 2839, 2918 ve sayılan kanunlar'),
 ('21','sure','Yerine getirme zamanaşımı süresi','ellibin+ yedi, yirmibin+ beş, onbin+ dört, az üç yıl','(2) Yerine getirme zamanaşımı süresi','üç yıldır.',[],'SORUŞTURMA 5-4-3 · YERİNE GETİRME 7-5-4-3'),
 ('21','sure','zamanaşımı süresi on yıldır','mülkiyetin kamuya geçirilmesinde yerine getirme','(3) Mülkiyetin kamuya geçirilmesine ilişkin zamanaşımı','on yıldır.',[],''),
 ('21','sure','takip eden takvim yılı başından','yerine getirme zamanaşımı başlangıcı; kesinleşme yılını izleyen','(4) Zamanaşımı süresi, kararın','işlemeye başlar.',[],''),
 ('22','makam','en üst amiri','idarî yaptırım yetkisi; kanunda açık hüküm yoksa','(2) Kanunda açık hüküm bulunmayan','yetkilidir.',[],''),
 ('23','makam','kendisi de idarî yaptırım kararı','Cumhuriyet savcısı, suç soruşturmasında kabahati öğrenirse','(2) Bir suç dolayısıyla','idarî yaptırım kararı verebilir.',[],'kuruma da bildirebilir'),
 ('24','makam','mahkeme tarafından idarî yaptırım kararı','kovuşturma konusu fiil kabahat çıkarsa','(1) Kovuşturma konusu','idarî yaptırım kararı verilir.',[],''),
 ('25','sira_usul','ispata yarayacak bütün deliller','idarî yaptırım tutanağı; kimlik-adres, fiil, tarih, görevlinin kimliği','(1) İdarî yaptırım kararına ilişkin tutanakta','açık bir şekilde yazılır.',[],'fiilin yeri ve zamanı da'),
 ('26','sure','beşinci günün sonunda','elektronik tebligat yapılmış sayılır','Elektronik ortamda yapılan tebligat','yapılmış sayılır.',[],'tebliğ 7201 Tebligat Kanununa göre'),
 ('27','sure','sulh ceza mahkemesine başvurulabilir','idarî para cezası ve mülkiyetin kamuya geçirilmesine karşı; onbeş gün','(1) İdarî para cezası ve mülkiyetin','kesinleşir.',[],'tebliğ ya da tefhimden itibaren; süresinde başvurulmazsa kesinleşir'),
 ('27','sure','en geç yedi gün içinde','mücbir sebep kalkınca başvuru','(2) Mücbir sebebin','başvuruda bulunulabilir',[],''),
 ('27','sira_usul','iki nüsha','başvuru dilekçesi','(3) Başvuru, bizzat','iki nüsha olarak verilir.',[],'bizzat, kanunî temsilci ya da avukat'),
 ('28','sure','mahkemeye cevap verir','ilgili kamu kurumu; dilekçenin tebliğinden onbeş gün','(3) İlgili kamu kurum','mahkemeye cevap verir',[],''),
 ('28','kosul','Onbeşbin Türk Lirası dahil','bu tutara kadar cezalarda başvuru kararı kesin','(10) Onbeşbin','kesindir.',[],''),
 ('29','sure','iki hafta içinde yapılır','mahkemenin son kararına itiraz (CMK)','(1) Mahkemenin verdiği','iki hafta içinde yapılır.',[],'dosya üzerinden incelenir'),
 ('30','kosul','başvurusundan vazgeçebilir','karar verilinceye kadar; bir daha aynı konuda başvurulamaz','(1) Kanun yoluna başvuran','başvuruda bulunulamaz.',[],'kurum da kararını geri alabilir'),
 ('32','ceza','verilen emre aykırı hareket eden','yüz Türk Lirası; emri veren makam karar verir','(1) Yetkili makamlar tarafından','karar verilir.',[],''),
 ('33','ceza','Dilencilik','elli TL; gelire el konur; mülkiyet mülkî amir/belediye encümeni','(1) Dilencilik yapan','belediye encümeni karar verir.',[('34','kumarda mülkiyete yalnız mülkî amir karar verir')],'ceza ve el koyma: kolluk ya da belediye zabıtası'),
 ('34','ceza','Kumar oynayan','bin TL; mülkiyet yalnız mülkî amir (zabıta yok)','(1) Kumar oynayan','mülkî amir karar verir.',[('33','dilencilikte belediye encümeni de karar verebilir')],'ceza ve el koyma: kolluk'),
 ('35','ceza','Sarhoş olarak','elli TL, kolluk; etkisi geçinceye kadar kontrol altında','(1) Sarhoş olarak','kontrol altında tutulur.',[],''),
 ('36','ceza','gürültüye neden olan','elli TL; ticarî işletmede bin–beşbin; kolluk ya da zabıta','(1) Başkalarının huzur','zabıta görevlileri karar verir.',[],''),
 ('37','ceza','başkalarını rahatsız eden','elli TL; kolluk ya da belediye zabıtası','(1) Mal veya hizmet satmak','zabıta görevlileri yetkilidir.',[],'mal ya da hizmet satmak için'),
 ('38','ceza','kaldırımları işgal eden','elli TL; yalnız belediye zabıtası','(1) Yetkili makamların açık','idarî para cezası verilir.',[],'inşaat malzemesi yığana yüz–beşyüz TL'),
 ('39','ceza','tütün mamulü tüketen','elli TL; kamu binası kapalı alanı; toplu taşımada da','(1) Kamu hizmet binalarının','idarî para cezası verilir',[],'birim amirinin yetkili kıldığı görevli verir'),
 ('40','ceza','bilgi vermekten kaçınan','elli TL; soran görevli verir','(1) Görevle bağlantılı','idarî para cezası verilir.',[],'kimlik ya da adres; gerçeğe aykırı beyan da'),
 ('40','sira_usul','kimliği belirlenemeyen kişi','tutulur; Cumhuriyet savcısı haberdar; gözaltı, gerekirse tutuklama','kimliği belirlenemeyen kişi tutularak','gerekirse tutuklanır.',[],''),
 ('41','makam','belediye sınırları dışında kolluk','çevre kirletme cezası; içinde belediye zabıtası','(7) Bu kabahatler dolayısıyla idarî para cezasına belediye','kolluk görevlileri karar verir.',[],''),
 ('41','istisna','derhal giderilmesi halinde','idarî para cezasına karar verilmeyebilir','(8) Bu kabahatler','karar verilmeyebilir.',[],'kirliliği kişi hemen temizlerse'),
 ('42','ceza','afiş ve ilân asan','yüz–üçbin TL; aynı içerik tek fiil','(1) Meydanlara/parklara','tek fiil sayılır.',[],'kolluk ya da belediye zabıtası'),
 ('42/A','ceza','112 Acil Çağrı Merkezini meşgul','il valileri; binbeşyüz TL','(1) 112 Acil','idari para cezası verilir.',[('42a','metinde aynı maddenin ikinci kaydı')],'bir yıl içinde tekrarı iki katı'),
 ('42/A','ceza','asılsız olduğunun','il valileri; onbeşbin TL; bir yılda tekrarı iki katı','(2) 112 Acil','idari para cezası verilir.',[('42a','metinde aynı maddenin ikinci kaydı')],'112 ihbarı; ekip tutanakla tespit eder'),
 ('43','ceza','görünür bir şekilde taşıyan','elli TL, kolluk; yasak olmayan silah, ruhsatsız','(1) Yetkili makamlardan ruhsat','idarî para cezası verilir.',[],'park, meydan, cadde, sokak'),
 ('43/A','ceza','iki katından az olamaz','tüzel kişiye idarî para cezası; menfaatin iki katından az olamaz','Ancak idari para cezası','iki katından az olamaz.',[],'organ/temsilcinin tüzel kişi yararına işlediği katalog suç; onbin TL–elli milyon TL; yargılayan mahkeme yetkili'),
 ('43/B','ceza','bildirim yükümlülüğü yerine getirilmediği','sahte para; bankaya Cumhuriyet savcısı bin–beşbin TL','bildirim yükümlülüğü yerine getirilmediği','idarî para cezası verilir.',[('43b','metinde aynı maddenin ikinci kaydı')],''),
 ('3', 'kosul', 'mülkiyetin kamuya geçirilmesi yaptırımını', 'Kanunun diğer genel hükümleri bu fiillerin tümüne uygulanır', 'b) Diğer genel hükümleri', 'uygulanır.', [], 'kanun yolu hükümleri: diğer kanunlarda aksine hüküm yoksa'),
 ('18', 'kosul', 'kanunda açık hüküm bulunan hallerde', 'mülkiyetin kamuya geçirilmesine ancak böyle karar verilir', '(1) Kabahatin konusunu oluşturan', 'karar verilebilir.', [], 'kaim değer için de olabilir; ayrıca para cezası şart değil'),
 ('20', 'kosul', 'aynı zamanda suç oluşturması', 'suça ilişkin dava zamanaşımı hükümleri uygulanır', '(5) Kabahati oluşturan fiilin', 'dava zamanaşımı hükümleri uygulanır.', [], ''),
 ('42', 'kosul', 'Aynı içerikteki afiş ve ilânlar', 'tek fiil sayılır', 'Aynı içerikteki afiş', 'tek fiil sayılır.', [], ''),
 ('41', 'ceza', 'özgü yerler dışına atan', 'evsel atık: idarî para cezası; derhal giderirse ceza verilmeyebilir', '(1) Evsel atık ve artıkları', 'idarî para cezası verilir', [], 'belediye sınırı içinde zabıta, dışında kolluk karar verir'),
 ('21', 'sure', 'Mülkiyetin kamuya geçirilmesine ilişkin', 'yerine getirme zamanaşımı on yıl', '(3) Mülkiyetin kamuya geçirilmesine', 'on yıldır.', [('18', 'mülkiyetin kamuya geçirilmesi kararı: kanunda açık hüküm şart'), ('27', 'idarî yaptırım kararına karşı başvuru yolu düzenlenir')], '2026 sınavında soruldu'),
 ('16', 'tanim', 'Kabahatler karşılığında uygulanacak', 'idarî para cezası ve idarî tedbir', '(1) Kabahatler karşılığında uygulanacak', 'idarî tedbirlerden ibarettir.', [], '2026 sınavında soruldu'),
]
yaz(6, '5326 sayılı Kabahatler Kanunu', K)
