# 2935 Olağanüstü Hal Kanunu — kelime → cevap
import sys, os; sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from ortak import yaz
K = [
 ('3','sure','altı ayı geçmemek üzere','olağanüstü hal ilanı; en çok altı ay; Cumhurbaşkanı, MGK görüşüyle','Yurdun bir veya birden fazla','olağanüstü hal ilan edebilir.',[],'sebepler: afet, salgın, ağır ekonomik bunalım (a); yaygın şiddet (b)'),
 ('3','sure','dört ayı geçmemek üzere','TBMM, Cumhurbaşkanının istemiyle uzatır','Olağanüstü hal kararı Resmi','olağanüstü hali kaldırabilir.',[],'İLAN ALTI, UZATMA DÖRT; Meclis süreyi değiştirebilir, kaldırabilir'),
 ('3','sira_usul','Türkiye Büyük Millet Meclisinin onayına','OHAL kararı RG\'de yayımlanır; tatildeyse Meclis derhal toplanır','Olağanüstü hal kararı Resmi','olağanüstü hali kaldırabilir.',[],''),
 ('3','makam','Milli Güvenlik Kurulunun görüşünü','ilan öncesi; şiddet (b) halinde uzatma-kaldırmada da','Cumhurbaşkanı, olağanüstü halin','Milli Güvenlik Kurulunun görüşünü alır.',[],''),
 ('3','sira_usul','Türkiye radyo ve televizyonuyla','OHAL kararının sebebi, bölgesi, süresi ilan edilir','Olağanüstü hal kararının hangi','diğer araçlarla ilan edilir.',[],''),
 ('9','gorev_yetki','öğrenime ara vermek','afet ve salgın OHAL tedbiri; öğrenci yurtlarını kapatma da','b) Resmi ve özel her derecedeki','süreli veya süresiz olarak kapatmak,',[],'m.9 tedbirleri şiddet OHAL\'inde de alınabilir'),
 ('9','gorev_yetki','yıllık izinlerini sınırlamak','OHAL hizmetinde görevli personel; afet-salgın tedbiri','d) Bölgede olağanüstü hal','sınırlamak veya kaldırmak,',[],''),
 ('9','gorev_yetki','Tehlike arz eden binaları yıkmak','afet/salgın tedbiri; sağlığa zararlı gıdayı imha','f) Tehlike arz eden','imha etmek,',[],''),
 ('11','gorev_yetki','Sokağa çıkmayı sınırlamak','şiddet OHAL\'inde ek tedbir; sokağa çıkma yasağı','a) Sokağa çıkmayı','yasaklamak,',[],'m.11: yalnız (b) bendi (şiddet) OHAL\'inde'),
 ('11','gorev_yetki','kimlik belirleyici belge taşıma mecburiyeti','şiddet OHAL\'i; bölge sakinleri ve bölgeye girenler','d) Olağanüstü hal ilan edilen bölge sakinleri','mecburiyeti koymak,',[],''),
 ('11','yasak','Ruhsatlı da olsa her nevi','şiddet OHAL\'inde nakli yasaklanabilir','i) Ruhsatlı da olsa','naklini yasaklamak,',[],'5442 m.11\'de vali de on beş gün için yasaklayabilir'),
 ('11','sure','işçi çıkartmalarını','üç ayı aşmamak üzere izne bağlama, erteleme','n) (Ek: 14/11/1984 - 3076/1 md.) İşçinin','izne bağlamak veya ertelemek,',[],''),
 ('11','sure','Dernek faaliyetlerini','her dernek için ayrı karar; üç ayı geçmemek üzere durdurma','o) (Ek: 14/11/1984 - 3076/1 md.) Dernek','durdurmak,',[],''),
 ('11','makam','Hükümetin müsaadesi tahtında','OHAL\'de sınır ötesi harekât; valinin talebi, Genelkurmay kanalı','p) (Ek: 25/7/1986','harekat planlayıp icra etmek.',[],'komşu ülkeyle mutabakat; 5442 m.11\'de "Cumhurbaşkanının müsaadesi"'),
 ('22','makam','bağlı oldukları bölge valisine','il valisi, kolluk yetmezse başvurur (şiddet OHAL\'i)','Olayları önleyemedikleri','il valisinin emrine girer.',[],'afet OHAL\'inde vali mevcut yetkileriyle yardım ister'),
 ('22','makam','il valisinin emrine girer','yardım üzerine gönderilen kolluk','Olayları önleyemedikleri','il valisinin emrine girer.',[],''),
 ('22','makam','en yakın askeri komutanlıktan','il valisi; ani olayda, bölge valisinin güçleri gelene kadar','İl valisi, ani ve olağanüstü','yardım gönderilmesini isteyebilir.',[],'bölge valisine ve İçişleri Bakanlığına bildirir'),
 ('23','gorev_yetki','doğruca ve duraksamadan hedefe ateş','teslim ol emrine uyulmaz, silahla karşılık, meşru müdafaa','Olağanüstü halin, bu Kanunun 3 üncü','hedefe ateş edebilirler.',[],'yalnız şiddet (b) OHAL\'inde'),
 ('23','sira_usul','tutuksuz yapılır','silah kullanan personelin soruşturması','Silah kullanan bütün personel','tutuksuz yapılır.',[],'İç Hizmet K. m.87 ve 1481 sayılı Kanun m.3 uygulanır'),
 ('2', 'kosul', 'para, mal ve çalışma yükümlülükleri', 'yalnız tabii afet, salgın, ağır ekonomik bunalım OHAL’inde', 'Bu Kanun; olağanüstü hal ilanına tabii afet', 'olağanüstü yönetim usullerine ilişkin hükümleri kapsar.', [], 'şiddet (b) OHAL’inde para-mal-çalışma yükümlülüğü YOK'),
 ('2', 'kosul', 'her türü için ayrı ayrı', 'temel hak sınırlaması, tedbirler, görevli yetkileri, yönetim usulleri', 'Bu Kanun; olağanüstü hal ilanına tabii afet', 'olağanüstü yönetim usullerine ilişkin hükümleri kapsar.', [], ''),
 ('2', 'kosul', 'kamu hizmeti görevlilerine ne gibi', 'yetkiler verileceği; durumlarında ne gibi değişiklikler yapılacağı', 'Bu Kanun; olağanüstü hal ilanına tabii afet', 'olağanüstü yönetim usullerine ilişkin hükümleri kapsar.', [], ''),
 ('2', 'kosul', 'olağanüstü yönetim usullerine', 'Kanun kapsamındaki son konu; OHAL dönemi idari yönetim usulleri', 'Bu Kanun; olağanüstü hal ilanına tabii afet', 'olağanüstü yönetim usullerine ilişkin hükümleri kapsar.', [], 'seçimlerin ertelenmesi, vergi muafiyeti kapsamda YOK'),
 ('1', 'tanim', 'Bu Kanunun amacı', 'OHAL ilanı, usulleri ve OHAL’de uygulanacak hükümleri belirlemek', 'Bu Kanunun amacı', 'uygulanacak hükümleri belirlemektir.', [], 'sebepler: (a) afet, salgın, ağır ekonomik bunalım; (b) yaygın şiddet, kamu düzeninin bozulması; dış tehdit, savaş, seferberlik YOK'),
 ('1', 'tanim', 'yaygın şiddet hareketlerine ait', 'OHAL sebebi (b): ciddi belirtiler ya da kamu düzeninin bozulması', 'b) Anayasa ile kurulan hür demokrasi', 'ciddi şekilde bozulması,', [('3', 'm.3 ilan usulü: Cumhurbaşkanı MGK görüşüyle altı ayı geçmemek üzere ilan eder')], ''),
 ('22', 'makam', 'emrindeki kolluk kuvvetleri ile', 'şiddet OHAL’inde vali önce bunlarla önler; yetmezse bölge valisi', 'b) İllerinde bu Kanunun 3 üncü maddesinin (b)', 'bölge valisine başvururlar.', [], ''),
 ('22', 'makam', 'bölge valisi ve İçişleri Bakanlığına', 'il valisi askeri yardım istediğini bildirir', 'İl valisi ayrıca bu durumu', 'İçişleri Bakanlığına bildirir.', [], ''),
 ('22', 'sure', 'gecikmeksizin yerine getirilir', 'il valisinin yardım istekleri; ilgililerce', 'İl valisinin yukarıda açıklanan istekleri', 'gecikmeksizin yerine getirilir.', [], ''),
 ('22', 'makam', 'il valilerince yerine getirilir', 'askeri yardımda bölge valisinin görev ve yetkileri (m.21 usulü)', 'İl valisinin askeri birliklerden yardım', 'il valilerince yerine getirilir.', [], ''),
 ('22', 'makam', 'mevcut kanunların kendilerine verdiği yetkileri', 'afet OHAL’inde (a) vali yardım istemini böyle yapar', 'a) İllerinde bu Kanunun 3 üncü maddesinin birinci fıkrasının (a)', 'yardım isteminde bulunurlar.', [], 'HEM a HEM b, FARKLI USUL'),
 ('3', 'sure', 'süreyi uzatabilir veya olağanüstü hali', 'TBMM; Cumhurbaşkanı istemiyle her defasında en çok dört ay', 'Meclis, olağanüstü hal süresini değiştirebilir.', 'olağanüstü hali kaldırabilir.', [], ''),
 ('3', 'makam', 'olağanüstü hal ilan edebilir', 'Cumhurbaşkanı ilan eder; Milli Güvenlik Kurulu görüşü alınır', 'Cumhurbaşkanı:1 a) Tabii afet', 'olağanüstü hal ilan edebilir.', [], '2026 sınavında soruldu; eskiden Bakanlar Kurulu'),
 ('11', 'gorev_yetki', 'toplantı ve gösteri yürüyüşlerini yasaklamak', 'şiddet OHAL’inde ek tedbir; ertelemek, izne bağlamak da mümkün', 'm) Kapalı ve açık yerlerde', 'gerekiyorsa dağıtmak,', [], 'afet OHAL’inde bu tedbir yok'),
 ('11', 'gorev_yetki', 'radyoaktif maddeler', 'bulundurma, hazırlama, yapma, nakli izne bağlanır ya da yasaklanır', 'j) Her türlü cephaneler', 'teslimini istemek veya toplatmak,', [], 'cephane, bomba, patlayıcı, zehir, boğucu gaz da'),
 ('11', 'gorev_yetki', 'ses ve görüntü bantlarını', 'her türlü yayımı denetlemek, kayıtlamak, yasaklamak (şiddet OHAL’i)', 'f) Söz, yazı, resmi, film', 'kayıtlamak veya yasaklamak,', [], ''),
 ('11', 'gorev_yetki', 'Gazete, dergi, broşür, kitap', 'yasaklamak veya izne bağlamak; yasaklanan matbuayı toplatmak', 'e) Gazete, dergi', 'matbuayı toplatmak,', [], 'seçimlerin ertelenmesi tedbirler arasında YOK'),
 ('11', 'makam', 'valinin talebi üzerine ilgili komutan', 'mahdut hedefli sınır ötesi harekât; Genelkurmay kanalı, Hükümet müsaadesi', 'valinin talebi üzerine ilgili komutan', 'harekat planlayıp icra etmek.', [], ''),
 ('9', 'gorev_yetki', 'salgın hastalıklar sebebiyle olağanüstü', 'afet-salgın tedbirleri: yerleşimi yasaklamak, boşaltmak, eğitime ara, elkoymak', 'Tabii afet ve tehlikeli salgın hastalıklar sebebiyle', 'başka yerlere nakletmek,', [], 'm.9 tedbirleri şiddet OHAL’inde de alınabilir'),
 ('23', 'gorev_yetki', 'silah kullanma yetkisini haizdirler', 'kolluk, özel kolluk, TSK; kanunlardaki silah kullanma şartlarından biri oluşunca', 'Olağanüstü hal ilanından sonra kolluk kuvvetleri', 'silah kullanma yetkisini haizdirler.', [], 'ön izin YOK'),
]
yaz(8, '2935 sayılı Olağanüstü Hal Kanunu', K)
