// OTOMATİK ÜRETİLDİ — `npm run diger:seed` ile yenile. ELLE DÜZENLEME.
// Diğer branşlar (Jandarma dışı 15) talim kanunları. blok='branş', id 68+. Çoklu branş bağı
// (_META.json.branslar). Bunlar KART İÇERMEZ (yalnız talim deneme soruları — Tatbikat'ta görünür).
import type { Law, LawBranch } from '@/db/schema';

export const SEED_LAWS_DIGER: Law[] = [
  { id: 68, blok: 'branş', ad: "5809 sayılı Elektronik Haberleşme Kanunu" },
  { id: 69, blok: 'branş', ad: "2920 sayılı Türk Sivil Havacılık Kanunu" },
  { id: 70, blok: 'branş', ad: "2629 sayılı Uçuş, Paraşüt, Denizaltı, Dalgıç ve Kurbağa Adam Hizmetleri Tazminat Kanunu" },
  { id: 71, blok: 'branş', ad: "657 sayılı Devlet Memurları Kanunu (Personel kapsamı: m.1, 3, 4, 5, 41, 99, 100, 101, 102, 103, 104, 105, 108, 137, 138, 139, 140, 141, 142, 143, 144, 145)" },
  { id: 72, blok: 'branş', ad: "926 SAYILI TÜRK SİLAHLI KUVVETLERİ PERSONEL KANUNU (MALİ HÜKÜMLER)" },
  { id: 73, blok: 'branş', ad: "3269 sayılı Uzman Erbaş Kanunu (Mali Hükümler kapsamı: m.10, m.12, m.16 mali hükümleri, m.17)" },
  { id: 74, blok: 'branş', ad: "3466 sayılı Uzman Jandarma Kanunu (Mali Hükümler - Dördüncü Bölüm)" },
  { id: 75, blok: 'branş', ad: "5510 SAYILI SOSYAL SİGORTALAR VE GENEL SAĞLIK SİGORTASI KANUNU" },
  { id: 76, blok: 'branş', ad: "7179 sayılı Askeralma Kanunu" },
  { id: 77, blok: 'branş', ad: "5018 SAYILI KAMU MALÎ YÖNETİMİ VE KONTROL KANUNU" },
  { id: 78, blok: 'branş', ad: "6085 sayılı Sayıştay Kanunu" },
  { id: 79, blok: 'branş', ad: "257 sayılı Er ve Erbaş Harçlıkları Kanunu" },
  { id: 80, blok: 'branş', ad: "488 SAYILI DAMGA VERGİSİ KANUNU" },
  { id: 81, blok: 'branş', ad: "2155 Sayılı Bazı Kamu Personeline Tayın Bedeli Verilmesi Hakkında Kanun" },
  { id: 82, blok: 'branş', ad: "2330 sayılı Nakdi Tazminat ve Aylık Bağlanması Hakkında Kanun" },
  { id: 83, blok: 'branş', ad: "3212 sayılı Silahlı Kuvvetler İhtiyaç Fazlası Mal ve Hizmetlerinin Satış, Hibe, Devir ve Elden Çıkarılması, Diğer Devletler Adına Yurt Dışı ve Yurt İçi Alımların Yapılması ve Eğitim Görecek Yabancı Personel Hakkında Kanun" },
  { id: 84, blok: 'branş', ad: "5668 sayılı Türk Silahlı Kuvvetleri, Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı Besleme Kanunu" },
  { id: 85, blok: 'branş', ad: "6191 sayılı Sözleşmeli Erbaş ve Er Kanunu (Madde 7 mali hükümleri + Ek Madde 2)" },
  { id: 86, blok: 'branş', ad: "6245 Sayılı Harcırah Kanunu" },
  { id: 87, blok: 'branş', ad: "4734 Sayılı Kamu İhale Kanunu" },
  { id: 88, blok: 'branş', ad: "4735 Sayılı Kamu İhale Sözleşmeleri Kanunu" },
  { id: 89, blok: 'branş', ad: "5543 sayılı İskân Kanunu" },
  { id: 90, blok: 'branş', ad: "2942 Sayılı Kamulaştırma Kanunu" },
  { id: 91, blok: 'branş', ad: "3194 sayılı İmar Kanunu" },
  { id: 92, blok: 'branş', ad: "3402 sayılı Kadastro Kanunu" },
  { id: 93, blok: 'branş', ad: "2565 sayılı Askeri Yasak Bölgeler ve Güvenlik Bölgeleri Kanunu" },
  { id: 94, blok: 'branş', ad: "4925 sayılı Karayolu Taşıma Kanunu" },
  { id: 95, blok: 'branş', ad: "5996 sayılı Veteriner Hizmetleri, Bitki Sağlığı, Gıda ve Yem Kanunu" },
  { id: 96, blok: 'branş', ad: "1219 Sayılı Tababet ve Şuabatı San'atlarının Tarzı İcrasına Dair Kanun" },
  { id: 97, blok: 'branş', ad: "ELEKTRONİK HABERLEŞME SEKTÖRÜNE İLİŞKİN YETKİLENDİRME YÖNETMELİĞİ" },
  { id: 98, blok: 'branş', ad: "Türk Silahlı Kuvvetleri, Millî İstihbarat Teşkilatı, Emniyet Genel Müdürlüğü, Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı Taşınır Mal Yönetmeliği (Bakanlar Kurulu Kararı 21/6/2010-2010/616, R.G. 25/7/2010-27652)" },
  { id: 99, blok: 'branş', ad: "MERKEZÎ YÖNETİM HARCAMA BELGELERİ YÖNETMELİĞİ" },
  { id: 100, blok: 'branş', ad: "Kamu Kurum ve Kuruluşları ile Gerçek ve Tüzel Kişilerin Elektronik Haberleşme Hizmeti İçinde Kodlu veya Kriptolu Haberleşme Yapma Usul ve Esasları Hakkında Yönetmelik" },
  { id: 101, blok: 'branş', ad: "Telsiz İşlemlerine İlişkin Usul ve Esaslar Hakkında Yönetmelik" },
  { id: 102, blok: 'branş', ad: "CUMHURBAŞKANLIĞININ 2019/12 SAYILI BİLGİ VE İLETİŞİM GÜVENLİĞİ TEDBİRLERİ GENELGESİ" },
  { id: 103, blok: 'branş', ad: "Türkiye Cumhuriyeti Cumhurbaşkanlığı Dijital Dönüşüm Ofisi Bilgi ve İletişim Güvenliği Rehberi" },
  { id: 104, blok: 'branş', ad: "Türk Silahlı Kuvvetleri, Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı Sağlık Yeteneği Yönetmeliği (BKK 2016/9431)" },
  { id: 105, blok: 'branş', ad: "Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı Kurum Kimlik Kartı Yönetmeliği" },
  { id: 106, blok: 'branş', ad: "Şehitlik Yönetmeliği" },
  { id: 107, blok: 'branş', ad: "Subay Sicil Yönetmeliği" },
  { id: 108, blok: 'branş', ad: "Astsubay Sicil Yönetmeliği" },
  { id: 109, blok: 'branş', ad: "Jandarma Kantin Yönetmeliği" },
  { id: 110, blok: 'branş', ad: "Jandarma Genel Komutanlığı Kıyafet Yönetmeliği" },
  { id: 111, blok: 'branş', ad: "Ordu Evleri, Askerî Gazinolar, Kışla Gazinoları ve Vardiya Yatakhaneleri ile Eğitim Merkezleri Yönetmeliği" },
  { id: 112, blok: 'branş', ad: "Jandarma Genel Komutanlığı Subay, Astsubay ve Uzman Jandarma Atama Yönetmeliği" },
  { id: 113, blok: 'branş', ad: "7567 Sayılı 2026 Yılı Merkezi Yönetim Bütçe Kanunu" },
  { id: 114, blok: 'branş', ad: "ER VE ERBAŞ HARÇLIKLARI YÖNETMELİĞİ" },
  { id: 115, blok: 'branş', ad: "Fazla veya Yersiz Ödemelerin Tahsiline İlişkin Usul ve Esaslar Hakkında Yönetmelik" },
  { id: 116, blok: 'branş', ad: "ÖN ÖDEME USUL VE ESASLARI HAKKINDA YÖNETMELİK (Cumhurbaşkanı Kararı 14/3/2025-9600, R.G. 15/3/2025-32842)" },
  { id: 117, blok: 'branş', ad: "İç Kontrol ve Ön Malî Kontrole İlişkin Usul ve Esaslar Yönetmeliği" },
  { id: 118, blok: 'branş', ad: "Kamu Zararlarının Tahsiline İlişkin Usul ve Esaslar Hakkında Yönetmelik" },
  { id: 119, blok: 'branş', ad: "KARAYOLU TAŞIMA YÖNETMELİĞİ" },
  { id: 120, blok: 'branş', ad: "Kamu İdarelerine Ait Taşınmazların Kaydına İlişkin Yönetmelik" },
  { id: 121, blok: 'branş', ad: "Kamu Konutları Yönetmeliği (BKK 16/7/1984-84/8345)" },
  { id: 122, blok: 'branş', ad: "Mal Alımı İhaleleri Uygulama Yönetmeliği" },
  { id: 123, blok: 'branş', ad: "Mal Alımları Denetim, Muayene ve Kabul İşlemlerine Dair Yönetmelik" },
  { id: 124, blok: 'branş', ad: "TÜRK SİLAHLI KUVVETLERİ, MİLLÎ İSTİHBARAT TEŞKİLATI, EMNİYET GENEL MÜDÜRLÜĞÜ, JANDARMA GENEL KOMUTANLIĞI VE SAHİL GÜVENLİK KOMUTANLIĞI TAŞINIR MAL YÖNETMELİĞİ" },
  { id: 125, blok: 'branş', ad: "YAPIM İŞLERİ İHALELERİ UYGULAMA YÖNETMELİĞİ" },
  { id: 126, blok: 'branş', ad: "Yapım İşleri Muayene ve Kabul Yönetmeliği" },
  { id: 127, blok: 'branş', ad: "Hazine Taşınmazlarının İdaresi Hakkında Yönetmelik" },
  { id: 128, blok: 'branş', ad: "Hekimlik Meslek Etiği Kuralları (Türk Tabipleri Birliği)" },
  { id: 129, blok: 'branş', ad: "Türk Silahlı Kuvvetleri, Jandarma Genel Komutanlığı ve Sahil Güvenlik Komutanlığı Besleme Kanunu Uygulama Yönetmeliği" },
  { id: 130, blok: 'branş', ad: "TÜRK SİLAHLI KUVVETLERİ BESLENME BEDELLERİNİN UYGULANMASINA DAİR YÖNETMELİK" },
  { id: 131, blok: 'branş', ad: "GIDA HİJYENİ YÖNETMELİĞİ" },
  { id: 132, blok: 'branş', ad: "KAZANDAN BESLEMESİ OLANAKSIZ OLAN JANDARMA GENEL KOMUTANLIĞI MENSUBU ERBAŞ/ERLERE ÖDENEN TAYIN BEDELİNİN KULLANIMINA İLİŞKİN YÖNETMELİK" },
  { id: 133, blok: 'branş', ad: "Ses ve Gaz Fişeği Atabilen Silahlar Hakkında Yönetmelik" },
  { id: 134, blok: 'branş', ad: "İlkyardım Yönetmeliği" },
  { id: 135, blok: 'branş', ad: "Yataklı Sağlık Tesislerinde Acil Servis Hizmetlerinin Uygulama Usul ve Esasları Hakkında Tebliğ" },
];

export const SEED_LAW_BRANCHES_DIGER: LawBranch[] = [
  { law_id: 68, branch_id: 2 },
  { law_id: 69, branch_id: 3 },
  { law_id: 70, branch_id: 3 },
  { law_id: 70, branch_id: 5 },
  { law_id: 71, branch_id: 4 },
  { law_id: 72, branch_id: 5 },
  { law_id: 72, branch_id: 4 },
  { law_id: 73, branch_id: 5 },
  { law_id: 73, branch_id: 4 },
  { law_id: 74, branch_id: 5 },
  { law_id: 74, branch_id: 4 },
  { law_id: 75, branch_id: 11 },
  { law_id: 75, branch_id: 5 },
  { law_id: 75, branch_id: 4 },
  { law_id: 75, branch_id: 10 },
  { law_id: 76, branch_id: 4 },
  { law_id: 77, branch_id: 8 },
  { law_id: 77, branch_id: 7 },
  { law_id: 77, branch_id: 5 },
  { law_id: 77, branch_id: 16 },
  { law_id: 77, branch_id: 15 },
  { law_id: 77, branch_id: 6 },
  { law_id: 78, branch_id: 5 },
  { law_id: 79, branch_id: 5 },
  { law_id: 80, branch_id: 5 },
  { law_id: 81, branch_id: 5 },
  { law_id: 82, branch_id: 11 },
  { law_id: 82, branch_id: 12 },
  { law_id: 82, branch_id: 5 },
  { law_id: 82, branch_id: 13 },
  { law_id: 82, branch_id: 10 },
  { law_id: 83, branch_id: 5 },
  { law_id: 84, branch_id: 8 },
  { law_id: 84, branch_id: 7 },
  { law_id: 84, branch_id: 5 },
  { law_id: 84, branch_id: 15 },
  { law_id: 85, branch_id: 5 },
  { law_id: 86, branch_id: 5 },
  { law_id: 87, branch_id: 8 },
  { law_id: 87, branch_id: 7 },
  { law_id: 87, branch_id: 16 },
  { law_id: 87, branch_id: 15 },
  { law_id: 87, branch_id: 6 },
  { law_id: 88, branch_id: 8 },
  { law_id: 88, branch_id: 7 },
  { law_id: 88, branch_id: 16 },
  { law_id: 88, branch_id: 15 },
  { law_id: 88, branch_id: 6 },
  { law_id: 89, branch_id: 6 },
  { law_id: 90, branch_id: 8 },
  { law_id: 90, branch_id: 7 },
  { law_id: 90, branch_id: 6 },
  { law_id: 91, branch_id: 6 },
  { law_id: 92, branch_id: 6 },
  { law_id: 93, branch_id: 6 },
  { law_id: 94, branch_id: 8 },
  { law_id: 94, branch_id: 7 },
  { law_id: 94, branch_id: 6 },
  { law_id: 95, branch_id: 11 },
  { law_id: 95, branch_id: 12 },
  { law_id: 95, branch_id: 13 },
  { law_id: 95, branch_id: 10 },
  { law_id: 95, branch_id: 15 },
  { law_id: 96, branch_id: 11 },
  { law_id: 96, branch_id: 12 },
  { law_id: 96, branch_id: 13 },
  { law_id: 96, branch_id: 10 },
  { law_id: 96, branch_id: 15 },
  { law_id: 97, branch_id: 2 },
  { law_id: 98, branch_id: 2 },
  { law_id: 99, branch_id: 8 },
  { law_id: 99, branch_id: 7 },
  { law_id: 99, branch_id: 5 },
  { law_id: 99, branch_id: 2 },
  { law_id: 99, branch_id: 13 },
  { law_id: 99, branch_id: 6 },
  { law_id: 100, branch_id: 2 },
  { law_id: 101, branch_id: 2 },
  { law_id: 102, branch_id: 2 },
  { law_id: 103, branch_id: 2 },
  { law_id: 104, branch_id: 3 },
  { law_id: 105, branch_id: 4 },
  { law_id: 106, branch_id: 8 },
  { law_id: 106, branch_id: 7 },
  { law_id: 106, branch_id: 4 },
  { law_id: 106, branch_id: 6 },
  { law_id: 107, branch_id: 4 },
  { law_id: 108, branch_id: 4 },
  { law_id: 109, branch_id: 5 },
  { law_id: 109, branch_id: 4 },
  { law_id: 110, branch_id: 4 },
  { law_id: 111, branch_id: 4 },
  { law_id: 112, branch_id: 4 },
  { law_id: 113, branch_id: 5 },
  { law_id: 114, branch_id: 5 },
  { law_id: 115, branch_id: 5 },
  { law_id: 116, branch_id: 8 },
  { law_id: 116, branch_id: 7 },
  { law_id: 116, branch_id: 5 },
  { law_id: 116, branch_id: 6 },
  { law_id: 117, branch_id: 5 },
  { law_id: 118, branch_id: 8 },
  { law_id: 118, branch_id: 7 },
  { law_id: 118, branch_id: 5 },
  { law_id: 118, branch_id: 6 },
  { law_id: 119, branch_id: 8 },
  { law_id: 119, branch_id: 7 },
  { law_id: 119, branch_id: 6 },
  { law_id: 120, branch_id: 8 },
  { law_id: 120, branch_id: 7 },
  { law_id: 120, branch_id: 6 },
  { law_id: 121, branch_id: 8 },
  { law_id: 121, branch_id: 7 },
  { law_id: 121, branch_id: 6 },
  { law_id: 122, branch_id: 8 },
  { law_id: 122, branch_id: 9 },
  { law_id: 122, branch_id: 11 },
  { law_id: 122, branch_id: 12 },
  { law_id: 122, branch_id: 7 },
  { law_id: 122, branch_id: 14 },
  { law_id: 122, branch_id: 16 },
  { law_id: 122, branch_id: 13 },
  { law_id: 122, branch_id: 10 },
  { law_id: 122, branch_id: 15 },
  { law_id: 122, branch_id: 6 },
  { law_id: 123, branch_id: 8 },
  { law_id: 123, branch_id: 9 },
  { law_id: 123, branch_id: 11 },
  { law_id: 123, branch_id: 12 },
  { law_id: 123, branch_id: 7 },
  { law_id: 123, branch_id: 14 },
  { law_id: 123, branch_id: 16 },
  { law_id: 123, branch_id: 13 },
  { law_id: 123, branch_id: 10 },
  { law_id: 123, branch_id: 15 },
  { law_id: 123, branch_id: 6 },
  { law_id: 124, branch_id: 8 },
  { law_id: 124, branch_id: 7 },
  { law_id: 124, branch_id: 6 },
  { law_id: 125, branch_id: 8 },
  { law_id: 125, branch_id: 7 },
  { law_id: 125, branch_id: 6 },
  { law_id: 126, branch_id: 8 },
  { law_id: 126, branch_id: 7 },
  { law_id: 126, branch_id: 13 },
  { law_id: 126, branch_id: 6 },
  { law_id: 127, branch_id: 8 },
  { law_id: 127, branch_id: 7 },
  { law_id: 127, branch_id: 6 },
  { law_id: 128, branch_id: 8 },
  { law_id: 128, branch_id: 11 },
  { law_id: 128, branch_id: 7 },
  { law_id: 128, branch_id: 10 },
  { law_id: 128, branch_id: 6 },
  { law_id: 129, branch_id: 8 },
  { law_id: 129, branch_id: 7 },
  { law_id: 130, branch_id: 8 },
  { law_id: 130, branch_id: 7 },
  { law_id: 131, branch_id: 8 },
  { law_id: 131, branch_id: 11 },
  { law_id: 131, branch_id: 12 },
  { law_id: 131, branch_id: 7 },
  { law_id: 131, branch_id: 14 },
  { law_id: 131, branch_id: 13 },
  { law_id: 131, branch_id: 10 },
  { law_id: 131, branch_id: 15 },
  { law_id: 132, branch_id: 8 },
  { law_id: 132, branch_id: 7 },
  { law_id: 132, branch_id: 13 },
  { law_id: 133, branch_id: 8 },
  { law_id: 134, branch_id: 11 },
  { law_id: 134, branch_id: 12 },
  { law_id: 134, branch_id: 13 },
  { law_id: 134, branch_id: 10 },
  { law_id: 134, branch_id: 15 },
  { law_id: 135, branch_id: 11 },
  { law_id: 135, branch_id: 10 },
];
